### ISSUE TITLE
GPL-licensed dependency : cftime

### ISSUE THREAD

**Issue by lcoulet** [Unidata/netcdf4-python#1000]
Hello,
I found in netCDF4 version 1.5.3 .

The library has a dependency towards a GPL-licensed library : cftime, which is GPL V3.

The GPL licenses are viral by nature and incompatible with the license chosen by NetCDF4.

The best solution IMO is to replace cftime by a more permissive OSS license.

**Comment by jswhit** [comment]
The GPL license in cftime was inherited from [calcalcs](http://meteora.ucsd.edu/~pierce/calcalcs/index.html).  Unless we switch to another algorithm for the calendar calculations we can't change the license.

**Comment by lcoulet** [comment]
That could be a problem. I think that GPL v3 is incompatible with other OSS licenses...

**Comment by jswhit** [comment]
If this is a problem for you, you could ask the author of calcalcs to change the license.
