### ISSUE TITLE
Problem after  python setup.py build

### ISSUE THREAD

**Issue by jczazueta** [Unidata/netcdf4-python#1005]
Hi,

I folow  the steps to install netcdf4-python  Version 1.5.3

Using Centos 7 with :
gcc (GCC) 8.2.0
CentOS SCL
Python 3.6.9

But we I do:

python setup.py build

Appears the following message:
/usr/bin/ld: skipping incompatible /usr/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/usr/bin/ld: skipping incompatible /usr/lib/libgcc_s.so.1 when searching for libgcc_s.so.1

May you help?
May it be a problem with gcc version ?

Best Regars
Juan C. Zazueta

**Comment by jczazueta** [comment]
Hi, 
I put here the output in context:
netCDF4/_netCDF4.c: In function ‘__pyx_pw_7netCDF4_8_netCDF4_8Variable_1__init__’:
netCDF4/_netCDF4.c:32142:22: warning: ‘__pyx_v_dimids’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       __pyx_v_ierr = nc_def_var(__pyx_v_self->_grpid, __pyx_v_varname, __pyx_v_xtype, __pyx_v_ndims, __pyx_v_dimids, (&__pyx_v_self->_varid));
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
netCDF4/_netCDF4.c:30747:8: note: ‘__pyx_v_dimids’ was declared here
   int *__pyx_v_dimids;
        ^~~~~~~~~~~~~~
gcc -pthread -shared -L/opt/rh/rh-python36/root/usr/lib64-Wl,-z,relro -Wl,-rpath,/opt/rh/rh-python36/root/usr/lib64 -Wl,--enable-new-dtags build/temp.linux-x86_64-3.6/netCDF4/_netCDF4.o -L/usr/lib -L/opt/rh/rh-python36/root/usr/lib64 -Wl,--enable-new-dtags,-R/usr/lib -lnetcdf -lhdf5_hl -lhdf5 -lpython3.6m -o build/lib.linux-x86_64-3.6/netCDF4/_netCDF4.cpython-36m-x86_64-linux-gnu.so
/usr/bin/ld: skipping incompatible /usr/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/usr/bin/ld: skipping incompatible /usr/lib/libgcc_s.so.1 when searching for libgcc_s.so.1

Regards
Juan C. Zazueta

**Comment by jswhit** [comment]
Sure looks like a problem with your gcc toolchain.

**Comment by jczazueta** [comment]
Hi,
How do i proceed, may I downgrade or upgrade the gcc compiler?

Regards

**Comment by jswhit2** [comment]
I don't know.  There are binary wheels that you can install - have you tried 'pip install'?

**Comment by jswhit** [comment]
Closing now since this appears to be an issue with the gcc toolchain , not netcdf4-python
