### ISSUE TITLE
Permission error when trying to reopen a file which already exists

### ISSUE THREAD

**Issue by jshholland** [Unidata/netcdf4-python#1015]
I'm using Python 3.8.2 on Linux, tested with python-netcdf4 versions 1.4.2 and 1.5.3. To reproduce:

```
$ python3
Python 3.8.2 (default, Jan  1 1970, 00:00:01)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from netCDF4 import Dataset
>>> d = Dataset('test.nc', 'w')
>>> d = Dataset('test.nc', 'w')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netCDF4/_netCDF4.pyx", line 2321, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1885, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'test.nc'
>>>
```
Oddly, if I restart the interpreter session (without removing the `test.nc` file) the first creation/truncation works fine without error, but the second always fails. Permissions/ownership on both the file and directory are fine.

I first noticed this when running in a Jupyter notebook but reproduced in vanilla Python.

**Comment by jshholland** [comment]
The problem goes away if I `.close()` the data set in between calls.

**Comment by jswhit** [comment]
I think this is expected behavior - you can't have the same file open for write access twice.

**Comment by jshholland** [comment]
That's what I thought - I almost pushed the "close and comment" button but wanted to wait for others to weigh in.

**Comment by jshholland** [comment]
Hi @GaunerReibi - see the below snippet for a working version of the original problem code.
```
Python 3.9.6 (default, Jun 28 2021, 08:57:49) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from netCDF4 import Dataset
>>> d = Dataset("test.nc", "w")
>>> d.close()
>>> d = Dataset("test.nc", "w")
>>>
```
