### ISSUE TITLE
TypeError: 'builtin_function_or_method' object is not subscriptable >>> 

### ISSUE THREAD

**Issue by annarhnna** [Unidata/netcdf4-python#1016]
for i in len [0,:,:]:                                                  
    t = variables[time][i,:,:]
    listtime.append[t]
    print(list(range(t)))

TypeError: 'builtin_function_or_method' object is not subscriptable
>>>

**Comment by jswhit** [comment]
The error is referring to you attempting to subscript the python builtin `len`.  Nothing to do with netcdf4-python.

**Comment by jswhit** [comment]
Closing since this appears to be a syntax error rather than a netcdf4-python issue....
