### ISSUE TITLE
"OSError: [Errno -101] NetCDF: HDF error:" But netCDF (and dependencies) are the only installed packages?

### ISSUE THREAD

**Issue by hockenden97** [Unidata/netcdf4-python#1017]
I'm using Python 3.7.6 on Windows, and I'm struggling to get a netcdf file to load at all, I just get this error message.  
"OSError: [Errno -101] NetCDF: HDF error:"
Some googling suggests that this error arises when different packages (ie rasterio) point to different versions of libnetcdf, so I've created a new environment in anaconda without those packages but I'm still having the same issues. I've never installed anything extra onto the base conda (i always run from environments) but I updated all the base packages in conda with "conda update --all" before I started.  

**Make a new environment**
conda create --name test_env python=3.7
activate test_env
**Load the packages within that environment**
conda install numpy cython cftime libcurl hdf5 hdf4
conda install netcdf4
**Run in python**
>>> from netCDF4 import Dataset
>>> fp = r'antarctica_ice_velocity_450m_v2.nc'
>>> data = Dataset(fp,'r',format='NETCDF4')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netCDF4\_netCDF4.pyx", line 2321, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4\_netCDF4.pyx", line 1885, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'antarctica_ice_velocity_450m_v2.nc'

Is there a way to fix this?

**Comment by jswhit** [comment]
Can you run `ncdump -h` on this file?

**Comment by hockenden97** [comment]
Yes, that returns
ncdump: antarctica_ice_velocity_450m_v2.nc: antarctica_ice_velocity_450m_v2.nc: NetCDF: HDF error

**Comment by jswhit** [comment]
Yes, probably the file is corrupted.

**Comment by hockenden97** [comment]
Okay thank you.
I've tried it again with a different file and it seems to work fine.
