### ISSUE TITLE
Which license does netcdf4-python use?

### ISSUE THREAD

**Issue by ecederstrand** [Unidata/netcdf4-python#1022]
I only see  "OSI Approved" in https://github.com/Unidata/netcdf4-python/blob/master/setup.py, but no mention of which exact license, and I can't finde a LICENSE file.

I found https://www.unidata.ucar.edu/software/netcdf/copyright.html which looks like a BSD 3-clause license to me, but I'm unsure if it applies to this software.

**Comment by ecederstrand** [comment]
Ok, I found https://github.com/Unidata/netcdf4-python/blob/master/COPYING but I'm unsure which exact license this is. Google doesn't return any exact matches on the text.

**Comment by shoyer** [comment]
This is a good question.

I think it's a variation of the MIT license, but it doesn't seem to be one of the standard ones: https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT

**Comment by ecederstrand** [comment]
@jswhit2 I see your name in the license text. Can you shed any light on this issue?

**Comment by ecederstrand** [comment]
@jswhit I see your name in the license text. Can you shed any light on this issue?

**Comment by jswhit2** [comment]
I actually don't remember where I got the text. I'm happy to change it to conform with the official MIT language.

**Comment by ecederstrand** [comment]
Thanks!
