### ISSUE TITLE
Method numpy.ndarray.tostring() is deprecated in favor of tobytes() in 1.9

### ISSUE THREAD

**Issue by AndrewUshakov** [Unidata/netcdf4-python#1023]
This deprecated (see at  accepted pull request https://github.com/numpy/numpy/pull/15867) method is used 6 times in the file  netCDF4/_netCDF4.pyx and may be somewhere else so each call to this method causes output of "DeprecationWarning: tostring() is deprecated. Use tobytes() instead." to stderrr.

**Comment by jameshiebert** [comment]
I'd like to +1 this issue. We have a repositories of modest length that use `netCDF4` and their test suites now come up with tens of thousands of warning messages!

`DeprecationWarning: tostring() is deprecated. Use tobytes() instead.`

Should be a pretty simple fix.

**Comment by AndrewUshakov** [comment]
Thank you!
