### ISSUE TITLE
Reading a variable from a truncated file returns a valid array without warning/error

### ISSUE THREAD

**Issue by mjroth** [Unidata/netcdf4-python#1030]
* Ubuntu 18.04
* Python 3.6.9
* netCDF4 1.3.1

I partially downloaded 29MB of a ~1.5GB netcdf file. 

Header:
```
<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_64BIT_OFFSET data model, file format NETCDF3):
    Conventions: CF-1.6
    history: 2020-07-23 13:47:36 GMT by grib_to_netcdf-2.16.0: /opt/ecmwf/eccodes/bin/grib_to_netcdf -S param -o /cache/data6/adaptor.mars.internal-1595511952.7642853-26666-35-db1c33da-6ca4-4848-97ee-db184dc2c23f.nc /cache/tmp/db1c33da-6ca4-4848-97ee-db184dc2c23f-adaptor.mars.internal-1595511952.7651062-26666-11-tmp.grib
    dimensions(sizes): longitude(1440), latitude(721), time(720)
    variables(dimensions): float32 longitude(longitude), float32 latitude(latitude), int32 time(time), int16 tcc(time,latitude,longitude)
    groups:
```

The file is severely truncated but still readable ---- netcdf is a robust file format. However, I expected that reading the `tcc` variable would result in an exception when attempting to grab data that is not there but netCDF4 simply fills in the "missing" values and returns a valid numpy array.

1. Is this expected behaviour?

2. Is there a way to verify that an existing file is not truncated?

**Comment by mjroth** [comment]
Some further background on the issue from a Java point-of-view:
[https://www.unidata.ucar.edu/mailing_lists/archives/netcdf-java/2016/msg00113.html](https://www.unidata.ucar.edu/mailing_lists/archives/netcdf-java/2016/msg00113.html)

**Comment by jswhit** [comment]
As is pointed out in that discussion this appears to be a design choice in the C library.  Seems like this issue should be raised at Unidata/netcdf-c.
