### ISSUE TITLE
Writing data colum-wise for 2D matrix data array

### ISSUE THREAD

**Issue by nestorkid** [Unidata/netcdf4-python#1034]
```python
model_grp = Dataset(str(save_path) , 'w', format='NETCDF3_CLASSIC')
model_grp.Title = "2-D earth model"

model_array = mat_vel_cdp.copy() #(1188,5968) matrix

cdp_ndim = no_cdp # size of the matrix column(5968)
time_ndim = no_vel  # size of the matrix row (1188)

cdp_dim = 6.25 * no_cdp
time_dim = float(s_time) * no_vel

"""Dimension (instead and cdp = ELevation while time = Distance)"""
model_grp.createDimension('Elevation', time_ndim)
model_grp.createDimension('Distance', cdp_ndim)

#variables
velocity = model_grp.createVariable('Velocity', 'f4', ('Elevation', 'Distance',))
velocity.Units = "m/s"
velocity.X_Limits_and_increment = 1000.000, float(cdp_ndim + 1000),  1.000
velocity.X_name = "CDP"
velocity.X_units = "" 
velocity.Z_Limits_and_increment = 0.000, float((float(s_time)) * no_vel), float(s_time)
velocity.Z_name = "Time"
velocity.Z_units = "ms"
velocity.V_name = "Velocity"
velocity.V_units = "m/s"

# Data
velocity[:,:] = model_array.transpose()

model_grp.close()
```
This code had been used severally to generate NetCDF files which surprisingly worked prior to a recent update of the NetCDF module on spyder 4. Due to the row-wise output of the data matrix written to the .nc file, the input matrix was transposed, else the data should be read column-wise
This current code is now giving ValueError: shape mismatch: objects cannot be broadcast to a single shape, as a result of the mismatch between velocity[:,:]  and model_array.transpose().
I wish to write (slice) the matrix column-wise or write-in the transpose while maintaining the dimensions and variable the way the code is. Slicing with velocity[:,:] = model_array[:,0] did not give the expected result. This was all done in python 3.7

Thanks in anticipation for any help.

**Comment by dopplershift** [comment]
Your example (with some filling in by me) works fine if I remove the call to `.transpose()`:
```python
from netCDF4 import Dataset
model_grp = Dataset('test.nc' , 'w', format='NETCDF3_CLASSIC')

model_array = np.empty((1188,5968), np.float32) #(1188,5968) matrix
cdp_ndim = 5968 # size of the matrix column(5968)
time_ndim = 1188  # size of the matrix row (1188)

model_grp.createDimension('Elevation', time_ndim)
model_grp.createDimension('Distance', cdp_ndim)

#variables
velocity = model_grp.createVariable('Velocity', 'f4', ('Elevation', 'Distance',))

# Data
velocity[:,:] = model_array

model_grp.close()
```

This makes sense because the variable is dimensioned on elevation, then distance. In this case that makes it `time_ndim` x `cdp_ndim`, or 1188x6968, the size of the original matrix, not the transpose.

**Comment by nestorkid** [comment]
Thanks for the reply.

That is the catch. Without the transpose, the code runs, however, when that data is viewed with ncdump it is observed the first line of the array is only a constant which is just the first row in the matrix array (model_array). This should not be as these are velocity values that increase along the elevation for a given distance.
 The challenge is then when the dimensions of the variable are swapped then the software that will read in the .nc file will not read it appropriately, which is strange. 
The way the code's dimensions and variables are defined is how it could be read by the designated software for its use. The challenge now is to either write the variable data (model_array) column-wise or in fit the transpose into the variable.

The other way out is to ensure that if velocity[:,:] = model_array is used then the .nc file will output the variable array column-wise. Is this possible. As using this velocity[:,:] = model_array is giving the wrong output when the .nc file is read.

**Comment by dopplershift** [comment]
So the way the code is currently structured, until proven otherwise, I think the problem is with your original `model_array`, so I'd double check that. It's easy enough to write it out to a file using [`np.savez`](https://numpy.org/doc/stable/reference/generated/numpy.savez.html) to then check what's in there outside of your script. It's my opinion that if you look at `model_array[0, :]` you're going to see a constant as well.

**Comment by nestorkid** [comment]
Yes if I look at model_array[0, :] I will see constants, which is a row-wise direction. However, I wish that the direction be model_array[:, 0] for reading-in and display that is column-wise. This was why the transpose was used to bring each column to become a row. Surprisingly all the while I was using the code with the transpose it gave the output as wanted and usable by the destination software. 

I have used the code in its current form about a year now until my python module requested that I install the NetCDF module because it was no longer recognizing any NetCDF module after which the code started failing.

**Comment by nestorkid** [comment]
model_array.txt

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
model_array.txt

Shared with Dropbox
 |

 |

 |



Hi,
This is the matrix array Used.
regards,Chisom    On Saturday, August 8, 2020, 10:58:59 PM GMT+1, Ryan May <notifications@github.com> wrote:  
 
 


So the way the code is currently structured, until proven otherwise, I think the problem is with your original model_array, so I'd double check that. It's easy enough to write it out to a file using np.savez to then check what's in there outside of your script. It's my opinion that if you look at model_array[0, :] you're going to see a constant as well.

**Comment by nestorkid** [comment]
I am attempting to share the matrix link on dropbox and maybe a sample of previous .nc files generated for an understanding of what I wish for. However, the matrix file is about 82GB and will not attach here.

**Comment by nestorkid** [comment]
netcdf NETcdf_vel_output_example {
dimensions:
        Elevation = 1183 ;
        Distance = 5901 ;
variables:
        float Velocity(Elevation, Distance) ;
                Velocity:Units = "m/s" ;
                Velocity:X_Limits_and_increment = 1000.f, 6900.f, 1.f ;
                Velocity:X_name = "CDP" ;
                Velocity:X_units = "" ;
                Velocity:Z_Limits_and_increment = 0.f, 9456.f, 8.f ;
                Velocity:Z_name = "Time" ;
                Velocity:Z_units = "ms" ;
                Velocity:V_name = "Velocity" ;
                Velocity:V_units = "m/s" ;

// global attributes:
                :Title = "2-D earth model" ;
                :Comment = "isovels output at Sat Aug  8 14:36:10 2020" ;
                :Model_file = "Pierce_Velocity_model/L6a-26_model_Vrms_arrays_100-150grid.nmo" ;
                :Source = "isovels " ;
data:
 Above is the output from the destination software my .nc file will be used in. If this format is not followed then the file will not yield the required output. 
The real question is that the transpose fitted into the netCDF data array before now; why is it not possible to store the data along the column-wise direction and not the row-wise direction? 
This challenge arose after the netCDF4 module stopped running in spyder and needed reinstallation in conda as a separate module. 
The input matrix follows this dimensioning and should be read along column if not the transpose would be needed if to be read along row.

**Comment by nestorkid** [comment]
![Model_array_matlib-plot](https://user-images.githubusercontent.com/47749913/89736665-f1680e00-da62-11ea-9fb2-d191041e3c32.png)
The above is a plot generated with the matrix prior to writing it out as a netCDF4 file. In the plot, the matplotlib.pyplot module reads the matrix column-wise which is what I wish the NetCDF4 write should do..

**Comment by nestorkid** [comment]
I have found a solution. The transposed matrix needed to be reshaped in the current dimension ensure it is read appropriately. using 
# Data
model_traspose = model_array.transpose()
velocity[:,:] = model_traspose.reshape(1188,5968)
