### ISSUE TITLE
Installation not finding numpy

### ISSUE THREAD

**Issue by afernandezody** [Unidata/netcdf4-python#1037]
Hello,
Maybe this is too basic but I'm getting the following error while installing:
```
$sudo python3 setup.py install
reading from setup.cfg...
using /opt/netcdf/bin/nc-config...
checking /opt/netcdf/include ...
hdf5 headers not found in /opt/netcdf/include
nc-config did provide path to HDF5 headers, search standard locations...checking /opt/hdf5/include ...
HDF5 library version: 1.10.6 headers found in /opt/hdf5/include
HDF5 library version: 1.10.6 found in /opt/hdf5
Traceback (most recent call last):
  File "setup.py", line 497, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
```
but I previously installed numpy:
```
$pip3 list
Package               Version
--------------------- --------------------
attrs                 19.3.0
...
numpy                 1.19.1
...
```
Thanks.

**Comment by ocefpaf** [comment]
Do you need to compile from source? Why not `pip install netcdf4`?

Also, your `pip3` may not be associated with our `python3` install. These things are hard to debug.
You can try:

```shell
python3 -m pip install --upgrade numpy
```

To ensure `numpy` will be installed on the `python3` location.

**Comment by afernandezody** [comment]
I was compiling from source as I do with netcdf-c & netcdf-fortran. I have no clue why compiling from source didn't work (maybe because of Ubuntu20.04 or maybe it's totally unrelated to the OS), but your shortcut worked so I'm closing the thread. Thanks.
