### ISSUE TITLE
RuntimeError: NetCDF: Can't open HDF5 attribute

### ISSUE THREAD

**Issue by jblarsen** [Unidata/netcdf4-python#1038]
When I run the script below with netCDF4 version 1.5.4 on Python 3.6.9 I get the following error in loop iteration 65533:

```
...
Loop iteration: 65531
Loop iteration: 65532
Loop iteration: 65533
Traceback (most recent call last):
  File "hdf_attribute_error.py", line 10, in <module>
    dataset.sync()
  File "netCDF4/_netCDF4.pyx", line 2551, in netCDF4._netCDF4.Dataset.sync
  File "netCDF4/_netCDF4.pyx", line 1928, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Can't open HDF5 attribute
```

Test script:

```
import netCDF4
  
dataset = netCDF4.Dataset("test.nc", "w")
dataset.createDimension("time", 10)
v = dataset.createVariable("time", "f8", ("time", ))
i = 1
while True:
    print('Loop iteration: %s' % i)
    v.test_attribute = 'test'
    dataset.sync()
    i += 1
dataset.close()
```

The error also occur if we substitute the second line in the loop with `v.setncattr("test_attribute" + str(i), 'test')`

Since 2^16 = 65536 it seems to me that this is likely caused by an overflow of a 2-byte integer somewhere.

```
netCDF4._netCDF4.getlibversion()
'4.6.3 of Jul 22 2020 23:13:57 $'
```

**Comment by akrherz** [comment]
I attempted to test on python 3.8 and Linux 64bit and did not reproduce this issue.  Which OS are you on and which HDF version?
```
netCDF4._netCDF4.getlibversion()
'4.7.4 of Jul 22 2020 20:57:05 $'
```

**Comment by jswhit** [comment]
Also unable to reproduce here with python 3.7.8 on macos x.  Must be an issue with the installed versions of netcdf-c and/or hdf5.

**Comment by jblarsen** [comment]
Thanks for the quick response. I am on Ubuntu 18.04 64 bit with Python 3.6. See netCDF lib version above.

I will try it out with more recent netcdf-c and hdf5 versions and post the result.
