### ISSUE TITLE
variable type difference between MFDataset and Dataset

### ISSUE THREAD

**Issue by nikhil003** [Unidata/netcdf4-python#1040]
I am using netcdf-python library version 1.5.3 with python 3.7.3 on a ubuntu os. While using `nc.MFDataset` and `nc.Dataset`, I have noticed difference in the variable type between the two different object. In the former case, I have found the variable type is `netCDF4._netCDF4._Variable` whereas in the latter case it is `netCDF4._netCDF4.Variable`. 

I am wondering whether this is intended behaviour. 

```python

from glob import glob
import netCDF4 as nc
filelist = glob('/home/gar305/Desktop/aplc/hsaf/2020/01/h14_202001*.nc')
filelist.sort()
datain = nc.MFDataset(filelist)
type(datain.variables['time'])

```
> netCDF4._netCDF4._Variable

```python
singleFile = nc.Dataset(filelist[0])
type(singleFile.variables['time'])
```
> netCDF4._netCDF4.Variable

Below, I have also put a screenshot of how I noticed this.
 
![Screenshot from 2020-09-02 17-39-14](https://user-images.githubusercontent.com/5336184/91951613-0bd09700-ed44-11ea-9cb8-79a8e80c8548.png)

**Comment by jswhit** [comment]
Yes that is the intended behavior.  `netCDF4._netCDF4._Variable` is an aggregation of the variables in the files you opened with `MFDataset`.

**Comment by nikhil003** [comment]
Thanks Jeff. I thought it was rather peculiar behavior as it fails when using `isinstance`. Closing this issue.
