### ISSUE TITLE
Netcdf could not able to read my .nc file

### ISSUE THREAD

**Issue by sandeepzone** [Unidata/netcdf4-python#1044]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue
* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
* a description of the issue with the steps needed to reproduce it

If you have a general question about the software, please view our [Suggested Support Process](https://www.unidata.ucar.edu/support/#process).

**Comment by ocefpaf** [comment]
This issue did not fill any of the required information is and impossible to be addresses b/c we don't have the debug information, steps needed to reproduce, and "my netcdf file" is far too broad for any attempt to check the error. We also don't have any error message!

Please fill the required information in the issue template and try to [create a SSCCE](http://sscce.org/) so we can properly debug this.
