### ISSUE TITLE
Why can't I use NC FORTRAN to read the NC file generated by NC Python in FORTRAN

### ISSUE THREAD

**Issue by jiangzhiwei2018** [Unidata/netcdf4-python#1045]
error message in fortran:

Segmentation fault (core dumped)

**Comment by ocefpaf** [comment]
This is the netcdf-c python wrapper. I guess you want to report this issue in the repository Fortran library. Also, there is not a lot to debug there. When reporting please provide more information for the developer to try to reproduce it.
