### ISSUE TITLE
Cannot get variable content

### ISSUE THREAD

**Issue by skoldobskiy** [Unidata/netcdf4-python#1047]
Hello!

I'm trying to read data from the NASA POES satellite (publicity available) and met some problems with reading the data.
[poes_m02_20170910_proc.nc.zip](https://github.com/Unidata/netcdf4-python/files/5469180/poes_m02_20170910_proc.nc.zip)
The file opens (I attached an example) and I'm able to read some variables.
At the same time, I cannot read other variables, getting 
`TypeError: object of type 'numpy.float64' has no len()`

There is how I'm trying to access the data:
```
from netCDF4 import Dataset
nc_f = "poes_m01_20170910_proc.nc"
nc_fid = Dataset(nc_f, 'r')
time = nc_fid.variables['time'][:] 
flux = nc_fid.variables['mep_ele_tel90_flux_e2'][:]
```
I get `time` without problems and cannot get `flux`.
And I cannot understand what is the reason for this problem.

Any help will be appreciated!

Software:
netCDF4 1.5.3
h5py 2.10.0
numpy 1.19.1
python 3.7.6
macOS Catalina

**Comment by jswhit** [comment]
I assume that you have a typo in the filename in your example code.  It should be either `nc_f="poes_m02_20170910_proc.nc"` or `nc_f= "poes_m01_20170101_proc.nc"`.  Either one works fine for me with
```
netcdf4-python version: 1.5.4
HDF5 lib version:       1.10.7
netcdf lib version:     4.7.4
numpy version           1.19.2
```

**Comment by skoldobskiy** [comment]
Thanks! So looks like there are some problems on my side.
