### ISSUE TITLE
New PyPi release?

### ISSUE THREAD

**Issue by kevinmickey** [Unidata/netcdf4-python#1050]
Thank you so much for this very useful package.

Would you consider creating a new PyPi release, based off the latest commit?

I use an automated toolchain that requires open source licenses from PyPi, so releasing the changes in #1046 would be very helpful.

Thanks again!

**Comment by jswhit** [comment]
PR #1051

**Comment by jswhit** [comment]
new wheels for linux and macosx at https://github.com/MacPython/netcdf4-python-wheels/releases/tag/v1.5.5rel
I will upload to pypi and merge PR #1051 as soon as @cgohlke has a chance to create windows wheels.

**Comment by jswhit** [comment]
New pypi release up, not windows wheels yet
