### ISSUE TITLE
Migrate from travis CI to github actions

### ISSUE THREAD

**Issue by jswhit** [Unidata/netcdf4-python#1053]
given the direction that travis is taking, and the fact that CI builds are taking longer and longer, we should migrate to github actions.   The [wheel-building repo](https://github.com/MacPython/netcdf4-python-wheels) also needs to move to github actions.

**Comment by ocefpaf** [comment]
I have some experience with this. Do you want me to give it a go or do you have plans on doing it?

**Comment by jswhit** [comment]
I have no plans to work on this - so I'm thankful you have stepped.

**Comment by jswhit** [comment]
For the wheel-building repo, [dipy-wheels](https://github.com/MacPython/dipy-wheels) has already done this and we should be able to copy what they've done.

**Comment by jswhit** [comment]
migration completed
