### ISSUE TITLE
Deprecation warning when calling a variable from a netCDF4 Dataset

### ISSUE THREAD

**Issue by jaistech-sp** [Unidata/netcdf4-python#1059]
Hi there, 
I am using python 3.8 with netCDF4 1.5.3, everything works fine but I would like you to notice that I get a deprecation warning when calling a variable from the netCDF4.

I copy pasted the command line used, you will see that the variable I am calling is 'time'
![imagen](https://user-images.githubusercontent.com/70139186/102910845-818b7a80-447b-11eb-9190-1e68f581bbd0.png)

This is just for generating awareness, I guess that netCDF4 is using .tostring() somewhere.

Thanks a lot!

**Comment by akrherz** [comment]
Please see the [changelog](https://github.com/Unidata/netcdf4-python/blob/0d006ee2b7360e250c40db3667e841bfd95650fd/Changelog#L23) for netcdf4 release 1.5.4
