### ISSUE TITLE
HDF error use NFS file system

### ISSUE THREAD

**Issue by wangrenz** [Unidata/netcdf4-python#1067]
Hi

My netcdf data mounted with NFS file system, while read its has this error
```
RuntimeError: NetCDF: HDF error
```
I do not know why.

Renzhi

**Comment by jswhit** [comment]
Neither do I. Need more information, preferably a stand-alone script with data to reproduce the problem.

**Comment by akrherz** [comment]
> NFS file system

You'll want to share which NFS version is at play here.  I've had similar issues and found the need to mount with `nfsvers=3` to sometimes get the troubles to go away.  `nfsvers=3` may not be an option though with your security posture, so then try other version / `tcp` until it magically works? :)

**Comment by wangrenz** [comment]
> > NFS file system
> 
> You'll want to share which NFS version is at play here. I've had similar issues and found the need to mount with `nfsvers=3` to sometimes get the troubles to go away. `nfsvers=3` may not be an option though with your security posture, so then try other version / `tcp` until it magically works? :)

this is a part of `df -Th` result .
```
Filesystem                         Type      Size  Used Avail Use% Mounted on
10.xx.x.xxx:/data                  nfs4      102T   23T   79T  23% /nas02
```
NFS version is 4.

if I copy netcdf file to local disk, its works, no error.
