### ISSUE TITLE
"from netCDF4 import Dateset'' has problem?

### ISSUE THREAD

**Issue by Zewen692** [Unidata/netcdf4-python#1068]
I use netCDF4 in latest version VS Code on Windows10, and run Python 3.6.8 with anaconda.
When I use netCDF4 to do something, the problem just appeared,  
PS D:\VSCode\python> & C:/tools/Anaconda3/python.exe d:/VSCode/python/RBSP.py
Traceback (most recent call last):
  File "d:/VSCode/python/RBSP.py", line 2, in <module>
    from netCDF4 import Dateset
ImportError: cannot import name 'Dateset' from 'netCDF4' (C:\tools\Anaconda3\lib\site-packages\netCDF4\__init__.py)

and the following is my program
import netCDF4 as cdf
from netCDF4 import Dateset
import numpy as np
import sys
import os

nc_obj=Dataset('D:\\data\\rbsp-a_wfr-spectral-matrix-diagonal-mergeds_emfisis-l2_20191013140000_20191014135059.cdf')
print(nc_obj)

why"from netCDF4 import Dateset'' has problem?

**Comment by ocefpaf** [comment]
Looks like a typo, it should be Dataset, not Dataset.

**Comment by Zewen692** [comment]
Thank you!

**Comment by ocefpaf** [comment]
Can you please close the issue?
