### ISSUE TITLE
ImportError: cannot import name '__pdoc__' from 'netCDF4._netCDF4'

### ISSUE THREAD

**Issue by AgilentGCMS** [Unidata/netcdf4-python#1075]
I recently upgraded my python from 3.8.2 to 3.8.7 using `port update outdated` on a mac running Catalina. After that I rebuilt netcdf and then netcdf4-python. Now, importing netCDF4 throws the following error:
```python
In [1]: from netCDF4 import Dataset
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-0a92aca04109> in <module>
----> 1 from netCDF4 import Dataset

<frozen zipimport> in load_module(self, fullname)

~/packages/macports/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netCDF4-1.5.3-py3.8-macosx-10.15-x86_64.egg/netCDF4/__init__.py in <module>
      3 from ._netCDF4 import *
      4 # Need explicit imports for names beginning with underscores
----> 5 from ._netCDF4 import __doc__, __pdoc__
      6 from ._netCDF4 import (__version__, __netcdf4libversion__, __hdf5libversion__,
      7                        __has_rename_grp__, __has_nc_inq_path__,

ImportError: cannot import name '__pdoc__' from 'netCDF4._netCDF4' (/Users/sbasu1/Library/Caches/Python-Eggs/netCDF4-1.5.3-py3.8-macosx-10.15-x86_64.egg-tmp/netCDF4/_netCDF4.cpython-38-darwin.so)
```
I've tried re-installing both netcdf and netCDF4, but I keep getting this error, and I don't understand why.

**Comment by AgilentGCMS** [comment]
Just tried updating to netCDF4-1.5.5.1, the latest version, but that throws the same error:
```python
Python 3.8.7 (default, Jan 18 2021, 19:47:51)
[Clang 11.0.3 (clang-1103.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from netCDF4 import Dataset
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/sbasu1/packages/macports/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netCDF4-1.5.5.1-py3.8-macosx-10.15-x86_64.egg/netCDF4/__init__.py", line 5, in <module>
ImportError: cannot import name '__pdoc__' from 'netCDF4._netCDF4' (/Users/sbasu1/Library/Caches/Python-Eggs/netCDF4-1.5.5.1-py3.8-macosx-10.15-x86_64.egg-tmp/netCDF4/_netCDF4.cpython-38-darwin.so)
```

**Comment by jswhit** [comment]
somehow you've got an updated `_netCDF4.so` (which no longer has the `__pdoc__` variable) and old version of `__init__.py` (which is trying to access that variable).

**Comment by AgilentGCMS** [comment]
Strange... I cleaned out all versions of netCDF4, both from my site-packages as well as ~/Library/Caches/Python-Eggs, and reinstalled, but I still get that error.

**Comment by AgilentGCMS** [comment]
(Posted the above in case it gives a clue as to why `__init__.py` is trying to read a symbol that's no longer in `_netCDF4.so`)

**Comment by jswhit** [comment]
Because there's still an old version of `__init__.py` (or `__init__.pyc`) that's lurking on your system somewhere and the python import system is picking that up instead of the new one. Try running `find ./ -name "netCDF4*" -print` from your home directory.

**Comment by AgilentGCMS** [comment]
So, I tried finding all instances of `*netCDF4*` in my home directory:
```bash
find ~ -name "*netCDF4*" -print 2>/dev/null
/Users/sbasu1/packages/macports/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netCDF4-1.5.5.1-py3.8-macosx-10.15-x86_64.egg
/Users/sbasu1/Downloads/sources/netCDF4-1.5.3.tar.gz
/Users/sbasu1/Downloads/sources/netCDF4-1.5.5.1.tar.gz
/Users/sbasu1/Downloads/sources/netCDF4-1.5.3
/Users/sbasu1/Downloads/sources/netCDF4-1.5.3/dist/netCDF4-1.5.3-py3.8-macosx-10.14-x86_64.egg
/Users/sbasu1/Downloads/sources/netCDF4-1.5.3/dist/netCDF4-1.5.3-py3.8-macosx-10.15-x86_64.egg
/Users/sbasu1/Downloads/sources/netCDF4-1.5.3/include/netCDF4.pxi
/Users/sbasu1/Downloads/sources/netCDF4-1.5.3/docs/netCDF4
/Users/sbasu1/Downloads/sources/netCDF4-1.5.3/netCDF4.egg-info
/Users/sbasu1/Downloads/sources/netCDF4-1.5.3/netCDF4
/Users/sbasu1/Downloads/sources/netCDF4-1.5.3/netCDF4/_netCDF4.c
/Users/sbasu1/Downloads/sources/netCDF4-1.5.3/netCDF4/_netCDF4.pyx
/Users/sbasu1/Downloads/sources/netCDF4-1.5.3/build/lib.macosx-10.15-x86_64-3.8/netCDF4
/Users/sbasu1/Downloads/sources/netCDF4-1.5.3/build/lib.macosx-10.15-x86_64-3.8/netCDF4/_netCDF4.cpython-38-darwin.so
/Users/sbasu1/Downloads/sources/netCDF4-1.5.3/build/temp.macosx-10.15-x86_64-3.8/netCDF4
/Users/sbasu1/Downloads/sources/netCDF4-1.5.3/build/temp.macosx-10.15-x86_64-3.8/netCDF4/_netCDF4.o
/Users/sbasu1/Downloads/sources/netCDF4-1.5.5.1
/Users/sbasu1/Downloads/sources/netCDF4-1.5.5.1/dist/netCDF4-1.5.5.1-py3.8-macosx-10.15-x86_64.egg
/Users/sbasu1/Downloads/sources/netCDF4-1.5.5.1/include/netCDF4.pxi
/Users/sbasu1/Downloads/sources/netCDF4-1.5.5.1/docs/netCDF4
/Users/sbasu1/Downloads/sources/netCDF4-1.5.5.1/netCDF4.egg-info
/Users/sbasu1/Downloads/sources/netCDF4-1.5.5.1/netCDF4
/Users/sbasu1/Downloads/sources/netCDF4-1.5.5.1/netCDF4/_netCDF4.c
/Users/sbasu1/Downloads/sources/netCDF4-1.5.5.1/netCDF4/_netCDF4.pyx
/Users/sbasu1/Downloads/sources/netCDF4-1.5.5.1/build/lib.macosx-10.15-x86_64-3.8/netCDF4
/Users/sbasu1/Downloads/sources/netCDF4-1.5.5.1/build/lib.macosx-10.15-x86_64-3.8/netCDF4/_netCDF4.cpython-38-darwin.so
/Users/sbasu1/Downloads/sources/netCDF4-1.5.5.1/build/temp.macosx-10.15-x86_64-3.8/netCDF4
/Users/sbasu1/Downloads/sources/netCDF4-1.5.5.1/build/temp.macosx-10.15-x86_64-3.8/netCDF4/_netCDF4.o
```
As you can see, except for the `Downloads/sources`, where I build things, the only other result is the newly built python egg, `/Users/sbasu1/packages/macports/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netCDF4-1.5.5.1-py3.8-macosx-10.15-x86_64.egg`. I checked that neither `Downloads` nor `sources` was in any environment variable like `PATH` or `PYTHONPATH` with `env | grep Downloads` and `env | grep sources`.

When I now try to import `netCDF4` from python, I get
```python
Python 3.8.7 (default, Jan 18 2021, 19:47:51)
[Clang 11.0.3 (clang-1103.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import netCDF4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/sbasu1/packages/macports/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netCDF4-1.5.5.1-py3.8-macosx-10.15-x86_64.egg/netCDF4/__init__.py", line 5, in <module>
ImportError: cannot import name '__pdoc__' from 'netCDF4._netCDF4' (/Users/sbasu1/Library/Caches/Python-Eggs/netCDF4-1.5.5.1-py3.8-macosx-10.15-x86_64.egg-tmp/netCDF4/_netCDF4.cpython-38-darwin.so)
>>>
```
i.e., the error is being thrown by the new `__init__.py`, about a missing symbol in `_netCDF4.cpython-38-darwin.so`, and as far as I'm concerned they were built and installed at the same time with `python3 setup.py install`. I know this is not a leftover from a previous install because I manually deleted all instances of netCDF4 from my python import folders.

**Comment by jswhit** [comment]
So `__init__.py` is trying to import `__pdoc__`, which does exist in 1.5.5.1 but not in the current master.  So you still must be picking up the `_netCDF4.so` that was built from the current master instead of the one from 1.5.5.1. Why not just install via conda or pip instead of trying to build multiple versions from source?

**Comment by AgilentGCMS** [comment]
But I never even downloaded the current master, let alone build it <puzzled>. So how could it be picking up that `_netCDF4.so`?

As to why I don't use `pip install`, it's mostly aesthetics. Since I already have a functioning netcdf installation, I'd like other language bindings (like python) to use that instead of some hidden netcdf library. I know it's not strictly necessary on my laptop, but I picked up the practice from having to build my own environment on computing clusters, where I **do** want my Fortran, C and python codes to all use the same netcdf, hdf5, szip etc. libraries.

**Comment by jswhit** [comment]
OK, then where did you get the 1.5.5.1 tarball that you built?

**Comment by jswhit** [comment]
the `__pdoc__` variable was removed on [Jan 19](https://github.com/Unidata/netcdf4-python/commit/e90e3a411737e696058a515d3bdf88979816ed58) in master.  There have been no releases since then.

**Comment by AgilentGCMS** [comment]
From pypi, specifically [this link](https://files.pythonhosted.org/packages/9f/e2/686d0d937f979e7ee0eb6bb4821448da6d2910789f4928c12b070f424b6a/netCDF4-1.5.5.1.tar.gz)

PyPI says that that file was uploaded on Dec 18, 2020.

**Comment by AgilentGCMS** [comment]
I just re-downloaded that file from pypi and checked that it's byte-identical to what I had downloaded earlier.

**Comment by jswhit** [comment]
OK, I'm stumped then since I just built and installed from that tarball and do not see that error.  You are not try to run from the install directory are you?

**Comment by AgilentGCMS** [comment]
No, I leave the install directory, go back to my home directory, and then import netCDF4 :-(
Let me build from the new tarball I just downloaded... shouldn't be any different, but still.

**Comment by AgilentGCMS** [comment]
At the beginning of this process,
```shell
$ find ~ -xdev -name "*netCDF4*" -print 2>/dev/null
/Users/sbasu1/Downloads/netCDF4-1.5.5.1.tar.gz
/Users/sbasu1/Downloads/sources/netCDF4-1.5.3.tar.gz
/Users/sbasu1/Downloads/sources/netCDF4-1.5.5.1.tar.gz
```
The two 1.5.5.1 tarballs are what I had downloaded earlier and what I downloaded just now. After building, and cd-ing out back into my home directory (no `.so` files there),
```python
Python 3.8.7 (default, Jan 18 2021, 19:47:51)
[Clang 11.0.3 (clang-1103.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import netCDF4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/sbasu1/packages/macports/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netCDF4-1.5.5.1-py3.8-macosx-10.15-x86_64.egg/netCDF4/__init__.py", line 5, in <module>
ImportError: cannot import name '__pdoc__' from 'netCDF4._netCDF4' (/Users/sbasu1/Library/Caches/Python-Eggs/netCDF4-1.5.5.1-py3.8-macosx-10.15-x86_64.egg-tmp/netCDF4/_netCDF4.cpython-38-darwin.so)
```
No dice. The python egg in question is definitely the one I built just now:
```shell
ls -l /Users/sbasu1/packages/macports/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netCDF4-1.5.5.1-py3.8-macosx-10.15-x86_64.egg
-rw-r--r-- 1 sbasu1 staff 476551 2021 Jan 29 15:00:03 /Users/sbasu1/packages/macports/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netCDF4-1.5.5.1-py3.8-macosx-10.15-x86_64.egg
```

**Comment by AgilentGCMS** [comment]
I just looked into the `.so` file for `pdoc`, and found
```shell
$ nm _netCDF4.cpython-38-darwin.so  | grep pdoc
00000000000d231f s ___pyx_k_pdoc
00000000000f2790 b ___pyx_n_s_pdoc
```
i.e., there are symbols that are close in name, but they're not called `__pdoc__`. Is that the issue? Although, I checked with an older installation of netCDF4 on a different computer, and the symbols are not called `__pdoc__` there either:
```shell
$ nm _netCDF4.cpython-37m-x86_64-linux-gnu.so  | grep pdoc
000000000014f1e4 r __pyx_k_pdoc
0000000000374550 b __pyx_n_s_pdoc
```
So now I'm stumped.

**Comment by AgilentGCMS** [comment]
I decided to fall back to `1.5.3`, re-downloaded it and built it, and even that is giving this error now!

**Comment by AgilentGCMS** [comment]
So, in a last ditch attempt I checked out the current master and built it, and now I get a different error:
```shell
Python 3.8.7 (default, Jan 18 2021, 19:47:51)
[Clang 11.0.3 (clang-1103.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import netCDF4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/sbasu1/packages/macports/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netCDF4-1.5.6-py3.8-macosx-10.15-x86_64.egg/netCDF4/__init__.py", line 6, in <module>
ImportError: cannot import name '__version__' from 'netCDF4._netCDF4' (/Users/sbasu1/Library/Caches/Python-Eggs/netCDF4-1.5.6-py3.8-macosx-10.15-x86_64.egg-tmp/netCDF4/_netCDF4.cpython-38-darwin.so)
```
Maybe this one will be easier to fix than `__pdoc__`?

I should say that all of this started since `port upgrade outdated` decided to update my python from 3.8.2 to 3.8.7. I got some errors trying to import `netCDF4` (I wish I had noted them down), so I thought I'd just rebuild it with the new python. Alas...

**Comment by jswhit** [comment]
Well that confirms there is something else wrong with your environment that is causing problems with python's import mechanism.  I would venture to guess this is going to be a problem with any module you try to import.

**Comment by AgilentGCMS** [comment]
That may be, but the problem only seems to show up for netCDF4. Trying to import a few other modules compiled from source into the same site-package folder,
```python
Python 3.8.7 (default, Jan 18 2021, 19:47:51)
[Clang 11.0.3 (clang-1103.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import osgeo
>>> import matplotlib
>>> import scipy
>>> import h5py
>>> from mpl_toolkits.basemap import Basemap
>>> import cartopy
>>> import cftime
>>> import tables
```
Using the modules is not a problem either:
```python
>>> import h5py
>>> with h5py.File('indonesia_sif_all.h5', 'r') as fid:
...     print(fid['asia/F_mean'][:10])
...
[[1.28879546]
 [1.35992736]
 [1.28416686]
 [1.12486216]
 [1.05215517]
 [0.88184766]
 [0.70012249]
 [0.71235292]
 [0.80188111]
 [0.81969875]]
```

**Comment by jswhit** [comment]
The only other thing I can suggest is to try it from a different directory.  Perhaps there is a stray netCDF4 directory in your home directory that is confusing the import logic.

**Comment by AgilentGCMS** [comment]
I've tried that, from several different directories :-(
I've even tried installing netCDF4 for python 3.7.9, and I am getting the same error for version 1.5.5.1.

**Comment by AgilentGCMS** [comment]
I've given up and pip installed netCDF4. That works for now, so I'll leave it as it is. Still leaves me a little bit dissatisfied because I've installed python-netCDF4 on dozens of machines (thank you Jeff!), and never had this problem.

**Comment by jswhit** [comment]
It's a weird one all right - never seen it before.  If you do every figure out what the problem was, please do post it here.
