### ISSUE TITLE
Slicing is incompatible with numpy arrays

### ISSUE THREAD

**Issue by akeeman** [Unidata/netcdf4-python#1079]
Slicing actions with index lists in two or more axis behaves differently when compared Numpy arrays.

### Rationale
The [documentation](https://unidata.github.io/netcdf4-python/#Variable) states:
> They [Variables, red.] are analogous to numpy array objects.

I could not find any further documentation about slicing, so therefore I guess the same slicing behaviour may be expected.

### Prerequisites
Python 3.8.5
netCDF4 1.5.5.1

### Example
Suppose I have a 3-by-3-by-3 matrix, which is the value of `netCDF4.Variable` `my_var`, and an equivalent `numpy.ndarray` `my_arr`, with the same data:
```python
      [[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],
       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],
       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])
```

Note that this data may be produced by:
```python
np.arange(3*3*3).reshape(3,3,3)
```

Then
```python
my_var[:, [0, 1], [0, 1]]
```
will result
```python
array([[ 0,  1,  3,  4],
       [ 9, 10, 12, 13],
       [18, 19, 21, 22]])
```
where 
```python
my_arr[:, [0, 1], [0, 1]]
```
results
```python
array([[ 0,  4],
       [ 9, 13],
       [18, 22]])
```

**Comment by jswhit** [comment]
Slicing a netCDF variable with a 1d boolean or index array behaves differently in netcdf4-python: see this [section](http://unidata.github.io/netcdf4-python/#writing-data-to-and-retrieving-data-from-a-netcdf-variable)  of the docs.

Specificially: "However, that there are some differences between NumPy and netCDF variable slicing rules. Slices behave as usual, being specified as a start:stop:step triplet. Using a scalar integer index i takes the ith element and reduces the rank of the output array by one. Boolean array and integer sequence indexing behaves differently for netCDF variables than for numpy arrays. Only 1-d boolean arrays and integer sequences are allowed, and these indices work independently along each dimension (similar to the way vector subscripts work in fortran)."

**Comment by akeeman** [comment]
@jswhit Ah, there it is. I missed that completely. It would be nice so reference this in de Variable API documentation, though.
Thanks for the clarification!
