### ISSUE TITLE
Numpy 1.20 DeprecationWarning

### ISSUE THREAD

**Issue by headtr1ck** [Unidata/netcdf4-python#1080]
Using numpy 1.20 raises a DeprecationWarnings concerning deprecated dtypes.

> DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
> Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

* the version of the software with which you are encountering an issue
  * netCDF4==1.5.5
  * numpy==1.20.0
* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
  * linux
  * python==3.9.1
* a description of the issue with the steps needed to reproduce it:
```
import netCDF4

with netCDF4.Dataset("test.nc", "w") as nc:
    nc.createDimension("x", 2)
    nc.createVariable("test", "short", ("x",))
    nc["test"][:] = [1, 2]
    print(nc["test"][:])
```

**Comment by akrherz** [comment]
see #1076, should be addressed in the next release.
