### ISSUE TITLE
Add examples to documentation for creating attributes that are "multiline" strings

### ISSUE THREAD

**Issue by BrendanMD** [Unidata/netcdf4-python#1082]
As it says on the can. I have tried joining with literal '/n', chr(10) and chr(2424) and cannot produce an attribute that displays properly in ncdump as a multiline string with NETCDF4_CLASSIC. I have tried for a couple hours. Please. Examples added to the docs for the various netcdf flavors would be greatly appreciated, especially when my top google search leads me here: (https://github.com/Unidata/netcdf4-python/blob/master/Changelog)
EDIT: It does work with '\n', but isn't that deprecated for netcdf4/netcdf4_classic ?

**Comment by jswhit** [comment]
This program

```python
from netCDF4 import Dataset
import os
nc = Dataset('test.nc','w',format='NETCDF4_CLASSIC')
nc.att = 'line 1'+os.linesep+'line 2'
#nc.att = 'line 1\nline2' # this works too
nc.close()
nc = Dataset('test.nc')
print(nc.att)
nc.close()
```

produces

```
line 1
line 2
```

and ncdump shows

```
netcdf test {

// global attributes:
		:att = "line 1\n",
			"line 2" ;
}
```

**Comment by jswhit** [comment]
> EDIT: It does work with '\n', but isn't that deprecated for netcdf4/netcdf4_classic ?

Not that I know of

**Comment by BrendanMD** [comment]
Thanks Jeff. I confused myself reading the second paragraph of [The Use of Strings](https://www.unidata.ucar.edu/software/netcdf/papers/nc4_conventions.html#Use_of_Strings_23472346293345447), which I now  *think* is saying that it is possible to use an array of variable length strings for an attribute and ncdump will display it properly.
