### ISSUE TITLE
netCDF4 versioning

### ISSUE THREAD

**Issue by mathause** [Unidata/netcdf4-python#1090]
What versioning system is netCDF4 following? It does not seem to be exactly semantic versioning but something like `1.major.minor[.patch]`. Is this correct? Or is it `major.minor.patch[.bugfix]`? Or something in between?

The background to this question is that xarray pins the oldest _minor_ version of a package it officially still supports. We currently pin version `1.5` - but if you don't follow semantic versioning we should probably pin version `1.5.4`.

**Comment by jswhit** [comment]
1.major.minor sounds about right.

**Comment by mathause** [comment]
Thanks!
