### ISSUE TITLE
Bad interaction of Variable with np.ma.filled(...)

### ISSUE THREAD

**Issue by 5tefan** [Unidata/netcdf4-python#1092]
If you put a netcdf Variable object into `np.ma.filled`, you get back an array that has dropped the mask and _not_ filled the formerly masked values with your specified fill value. In other words, the fill values leak through.

```
result = np.ma.filled(netcdf_variable_object, fill_value=np.nan)
```

This should be fixed since the statement above succeeds, but the intended operation has not been performed (and takes a careful eye to detect). Properly, this would probably be done as the following (note extra [:]) to read array first. 

```
result = np.ma.filled(netcdf_variable_object[:], fill_value=np.nan)
```

`np.ma.filled` is implemented in numpy here: https://github.com/numpy/numpy/blob/29d8d9339f077ed805d195cb852eac06d0be51ac/numpy/ma/core.py#L627-L636

For easy reference:

```
def filled(a, fill_value=None):
    """
    Return input as an array with masked data replaced by a fill value.
    If `a` is not a `MaskedArray`, `a` itself is returned.
    If `a` is a `MaskedArray` and `fill_value` is None, `fill_value` is set to
    ``a.fill_value``.
    Parameters
    ----------
    a : MaskedArray or array_like
        An input object.
    fill_value : array_like, optional.
        Can be scalar or non-scalar. If non-scalar, the
        resulting filled array should be broadcastable
        over input array. Default is None.
    Returns
    -------
    a : ndarray
        The filled array.
    See Also
    --------
    compressed
    Examples
    --------
    >>> x = np.ma.array(np.arange(9).reshape(3, 3), mask=[[1, 0, 0],
    ...                                                   [1, 0, 0],
    ...                                                   [0, 0, 0]])
    >>> x.filled()
    array([[999999,      1,      2],
           [999999,      4,      5],
           [     6,      7,      8]])
    >>> x.filled(fill_value=333)
    array([[333,   1,   2],
           [333,   4,   5],
           [  6,   7,   8]])
    >>> x.filled(fill_value=np.arange(3))
    array([[0, 1, 2],
           [0, 4, 5],
           [6, 7, 8]])
    """
    if hasattr(a, 'filled'):
        return a.filled(fill_value)

    elif isinstance(a, ndarray):
        # Should we check for contiguity ? and a.flags['CONTIGUOUS']:
        return a
    elif isinstance(a, dict):
        return np.array(a, 'O')
    else:
        return np.array(a)
```

Currently, the Variable object falls through to the `else`, and the `np.array()` reads from `Variable.__array__()` which returns masked array, and drops the mask.

A potential fix would be to add a filled member function to netcdf Variable that essentially performs `np.ma.filled()`?

**Comment by jswhit** [comment]
```np.ma.filled``` is intended to work on masked arrays, so I wouldn't expect passing it a `netCDF4.Variable` object would work.  As you suggest, slicing the `netCDF4.Variable` object to return a masked array is the way to do it.

**Comment by 5tefan** [comment]
Nominally, I agree and wouldn't expect passing a `nc.Variable` to work. Even if this did work, I wouldn't encourage people to use it. If Variable did get a `filled` member function, users should probably just call `filled` rather than pass the `nc.Variable` to `np.ma.filled`. This hypothetical `nc.Variable.filled(fill_value)` would probably just `return np.ma.filled(self[:], fill_value)` under the hood anyway, right? 

I anticipated this might be a "wontfix" type issue, but I was hoping to get some discussion on it.  I really want to highlight the consequences right now if you forget the `[:]`. The operation *appears* to have work, but really did not. Since it appears to work, you probably won't notice that you forgot the `[:]` until weird things happen later and you work backwards. This was a actual bug that I fixed today, which had been in our processing for possibly several years.

It would be nice if passing `nc.Variable` to `np.ma.filled` raised an exception, but I don't see a way to do that given the `np.ma.filled` fall through to `np.array()` and `nc.Variable` kind of duck typing as an array. I mean, `nc.Variable.filled` could raise an exception, but at that point, why not just do the filling?

**Comment by jswhit** [comment]
I understand where you are coming from, but have nothing useful to add.  Seems to me that this is a general issue with the `ma.filled` method - if you given any kind of python object it will return a numpy array if the object does not have a `filled` method.

**Comment by 5tefan** [comment]
That's a good point. I'll close this. I'm happy to try discussing it over at numpy if you think that's worthwhile. Thanks!
