### ISSUE TITLE
netcdf4 can not read group of hdf4 file

### ISSUE THREAD

**Issue by lwk1542** [Unidata/netcdf4-python#1093]
python3.7 and netcdf4 1.5.3，win10 OS.
I have an hdf4 file, and it has several groups. I want to read the group before reading the variables. But it is failed.
![QQ截图20210328203752](https://user-images.githubusercontent.com/16815156/112752421-7fe6cb00-9005-11eb-94e8-ce9fd6605062.png)

**Comment by jswhit** [comment]
The netcdf-c library can be built with hdf4 support that will allow it to read some hdf4 datasets that are compatible with the netcdf data model.  In general though, netcdf and hdf4 are two different dataset formats.

**Comment by jswhit** [comment]
netcdf uses HDF5 under the hood, but [HDF5 is completely different than HDF4](https://support.hdfgroup.org/products/hdf5_tools/h4toh5/h5h4-diff.html).
