### ISSUE TITLE
Tests exhibit odd filepath issue on Windows

### ISSUE THREAD

**Issue by bernd-wechner** [Unidata/netcdf4-python#1098]
Running the tests on Windows:

```
 python .\run_all.py
not running tst_unicode.py ...
not running tst_cdf5.py ...

netcdf4-python version: 1.5.6
HDF5 lib version:       1.10.6
netcdf lib version:     4.7.3
numpy version           1.19.4
cython version          0.29.22
.ncdump: C:UsersberndwAppDataLocalTemp1tmpvcr0sf95.nc: No such file or directory
..............................................................................................
----------------------------------------------------------------------
Ran 95 tests in 15.436s

OK
```

Notice that a) the tests pass but b) report an error acccessing `C:UsersberndwAppDataLocalTemp1tmpvcr0sf95.nc` which looks supisciously like  a Windoze path `C:\Users\berndw\AppData\Local\Temp\1tmpvcr0sf95.nc`  was not properly escaped in an FS agnostic means. 

If it's Python, OS agnostic filepath manipulations are easy enough (os.path) but I've not drilled down to see where it's generated (yet).

**Comment by jswhit** [comment]
the tests use the python builtin [tempfile.NamedTemporaryFile\(https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) to create temporary netcdf files.

**Comment by bernd-wechner** [comment]
Which test is it? I can't even find which test it is easily. Seems unlikely to me that `tempfile.NamedTemporaryFile` is buggy on Windows 10, and more likely the test does something odd with the name it gets.

**Comment by jswhit** [comment]
tst_atts.py

**Comment by jswhit** [comment]
tst_atts.py is passing the filename it gets from tempfile.NamedTemporaryFile to ncdump - it looks like ncdump is mangling the name and emitting the error.

**Comment by jswhit** [comment]
Can you check to see if PR #1101 fixes this (branch `issue1098`)?

**Comment by jswhit** [comment]
mergining PR #1101 and closing this issue now.  Please re-open if you find the test still fails on Windows.
