### ISSUE TITLE
DeprecationWarning: elementwise comparison failed; this will raise an error in the future.

### ISSUE THREAD

**Issue by bernd-wechner** [Unidata/netcdf4-python#1099]
A simple file read and assignment of a variable causes Python to report:

```
DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
```

It doesn't tell me where, but it's somewhere from within the netCDF4 library I'd say. The code to produce this is as simple as:

```lang-py
import netCDF4 

test_file = '20200904_142600.nc'

root = netCDF4.Dataset(test_file, "r", format="NETCDF4")

myvar = root['group1/group2/variable'][0][0]
```

`myvar` is populated fine by looks of it. But this warning is emitted.

**Comment by jswhit** [comment]
please tar up that test file and post it here (if it's small enough)

**Comment by jswhit** [comment]
what python and numpy versions?

**Comment by bernd-wechner** [comment]
Thanks kindly for the response.

From a bash window (but yes, on Windows 10):
```
$ python --version
Python 3.8.3
$ python -c "import numpy; print(numpy.__version__)"
1.19.4
```

re: data file, not ours, so will have to seek permission from owner first.

**Comment by jswhit** [comment]
question about your example - why are you using [0][0] to slice the variable?  Is it a 2D variable?  Is the warning emitted if you slice with [0,0]?

**Comment by bernd-wechner** [comment]
Apologies for the delay. It is in fact a 3D variable and I'm pulling one vector out. But indeed I tried the [0,0] syntax and the warning goes away. Thanks for that. And odd warning for that (which should be interchangeable syntax really).

**Comment by bernd-wechner** [comment]
I now have permission to share the file BTW if that's still helpful. But moving from [i][j] syntax to [i,j] syntax saw the warnings disappear anyhow.

**Comment by jswhit** [comment]
I would still like to know where the warning is coming from, so yes please share the file.

**Comment by bernd-wechner** [comment]
I'll get you a copy next week some time. Sorry, been distracted.It's at work and it's a weekend now ;-)

**Comment by jarethholt** [comment]
FWIW I've run into a similar error when loading files through xarray with the netCDF4 backend. I have a hunch that it's related to set_auto_maskandscale, as setting that to False silenced the error (again, at least for my files and through xarray).

**Comment by bernd-wechner** [comment]
My apologies, have been waylaid by illness. Alas it's too large to attach. So it can be downloaded here:

https://mega.nz/file/JXxkCDKb#qrqlIq04yJ2FdDxYbUx63H1jjCsOSX2q6CqV9v5X3c4

a link which may of course expire which is fine, it won't any time soon, but it means the largish data doesn't litter Github's database and issue here into perpetuity.

**Comment by jswhit2** [comment]
Thanks @bernd-wechner, I've got the file now.  I tried this 

```python
import netCDF4
test_file = '20200904_142600.nc'
root = netCDF4.Dataset(test_file, "r", format="NETCDF4")
myvar = root['Sonar/Beam_group1/equivalent_beam_angle'][0][0]
```

but I don't see the warning.  What group/variable generates the warning for you?

**Comment by jswhit** [comment]
OK found the right variable - it's a vlen.  I've updated the masking routine in PR #1106 to not try use the _FillValue to create a mask for vlens, since vlens don't have fill values anyway.

**Comment by jswhit** [comment]
close by PR #1106
