### ISSUE TITLE
AttributeError: module 'netCDF4' has no attribute 'Dataset'

### ISSUE THREAD

**Issue by somepayphone** [Unidata/netcdf4-python#1105]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue
* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
* a description of the issue with the steps needed to reproduce it
hello my netCDF4 is 1.5.6, the latest version i get by pip install netCDF4,but got error when tring to use netCDF4.Dataset, i am in a hurry so i really want to know how to deal it, does anyone know where the problem is or how to solve is? Thanks a lot!

If you have a general question about the software, please view our [Suggested Support Process](https://www.unidata.ucar.edu/support/#process).

**Comment by jswhit** [comment]
Need more info.  What happens at the python prompt if you run

```python
>>> import netCDF4
netCDF4.>>> netCDF4.Dataset
<class 'netCDF4._netCDF4.Dataset'>
>>>
```

**Comment by jswhit** [comment]
closing since OP hasn't responded to the request for more information.
