### ISSUE TITLE
problem during netCDF4 installation

### ISSUE THREAD

**Issue by Tapas104** [Unidata/netcdf4-python#1107]
I am not able to install netCDF4 and getting the following error... I have to install the module in Linux in a ssh server without internet

$ HDF5_DIR=/home/stud/tapasranjan/myhdf python3 setup.py install
reading from setup.cfg...
Package hdf5 was not found in the pkg-config search path.
Perhaps you should add the directory containing `hdf5.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hdf5' found
checking /home/stud/tapasranjan/myhdf/include ...
HDF5 library version: 1.12.0 headers found in /home/stud/tapasranjan/myhdf/include
HDF5 library version: 1.12.0 found in /home/stud/tapasranjan/myhdf

NETCDF4_DIR environment variable not set, checking standard locations.. 
checking /home/stud/tapasranjan ...
checking /usr/local ...
checking /sw ...
checking /opt ...
checking /opt/local ...
checking /usr ...
Traceback (most recent call last):
  File "setup.py", line 441, in <module>
    raise ValueError('did not find netCDF version 4 headers')
ValueError: did not find netCDF version 4 headers

**Comment by jswhit** [comment]
The error is pretty self-explanatory.  Do you have the hdf5 and netcdf c libraries installed?  If so, make sure the netcdf utility nc-config is in your PATH.
