### ISSUE TITLE
Windows version of python-netCDF4 produces OverflowError when dimension sizes become greater than 2**32-1 elements

### ISSUE THREAD

**Issue by kennybala97** [Unidata/netcdf4-python#1112]
Hi, I am experiencing a puzzling bug in the `netcdf4-python` library, specifically related when writing to variables that expand to a dimension size greater than `2**31-1` elements. This produces an `OverflowError` for me. However, as will be described below, this appears to be a windows-specific issue rather than a cross-platform issue. I have tried the same example on two different Linux machines(Fedora 34 and CentOS 7) and neither fail on me. I should also note that I tried the same example using both `pip` and `conda`, and the issue still persisted.

Any help is appreciated, thanks in advance!

# Setup

**OS:** 64-bit Windows 10 Enterprise, Build 16299
**Device:** Microsoft Surface Book 2
**C/C++ Compiler:** MSC v.1916 64 bit (AMD64)
**Python Version:** Python 3.8.8
**Package Manager:** 64-bit version of Anaconda3, build date of 2021.05
**python-netcdf4 version:** 1.5.3 when trying with `conda` and 1.5.6 when trying with `pip`

# Minimum Reproducible Example

```
import numpy as np
import netCDF4 as nc

test_file = nc.Dataset('size_testing.nc', mode = 'w', format = 'NETCDF4')

test_file.createDimension('Images', None)
test_file.createDimension('Buffers', None)
test_file.createDimension('Pixels', None)

# Can also try declaring a fixed dimension length such as 2**32, but the error will persist regardless

test_file.createVariable('image',
     np.dtype('u1'),
     ('Pixels',),
     fill_value=255
)
```
Once we do this, we can perform a quick test by typing `test_file.variables['image'][0:2**31-1] = 1`, which will succeed. However, instead trying `test_file.variables['image'][0:2**31] = 1` will fail with the following error.

```
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-16-04ce11d852f3> in <module>
----> 1 test_file.variables['image'][0:2**31] = 1

netCDF4\_netCDF4.pyx in netCDF4._netCDF4.Variable.__setitem__()

~\Anaconda3\lib\site-packages\netCDF4\utils.py in _StartCountStride(elem, shape, dimensions, grp, datashape, put, use_get_vars)
    429 
    430             start[...,i] = beg
--> 431             count[...,i] = n
    432             stride[...,i] = inc
    433             indices[...,i] = slice(None)

OverflowError: Python int too large to convert to C long
``` 

In order to rule out a generic issue in my setup, I tried to then declare a generic numpy array of size `2**32` as `temp = np.zeros((2**32,1)); temp[:] = 1`, which succeeds without issue. This seems to indicate the issue is specific to **python-netcdf4**.

**Comment by kennybala97** [comment]
As an additional point of info, I also uninstalled my Anaconda python distribution, reinstalled it and installed exclusively `conda install -c anaconda netcdf4` in order to rule out some conflict with a pre-existing library. The issue still persisted.

**Comment by jswhit** [comment]
Looks like conda provides both win-32 and win-64 packages - do you know which one was installed?

**Comment by kennybala97** [comment]
> 
> 
> Looks like conda provides both win-32 and win-64 packages - do you know which one was installed?

Hi @jswhit , I can check but I am not sure how. Given I have the 64 bit conda, and I installed the `netCDF4` package using `conda install -c anaconda netcdf4` , I think the package is likely the 64-bit version. Is there any command I can type in to give me explicit info on whether the package is 32 bit or 64 bit? At least when checking using `conda list`, I get :

```
# Name                    Version                   Build  Channel
------------------------------------------------------------------------------
netcdf4                   1.5.3            py38h012c1a0_0    anaconda
```

**Comment by jswhit** [comment]
@matthew-brett  I think you are right.  I've created a PR for this ( #1113 )

**Comment by jswhit** [comment]
After this is merged, I will create a 1.5.7 release next week.

**Comment by matthew-brett** [comment]
Thanks!

**Comment by kennybala97** [comment]
Thank you for your help and quick bug fixes @jswhit and @matthew-brett !

**Comment by ocefpaf** [comment]
> Looks like conda provides both win-32 and win-64 packages - do you know which one was installed?

conda-forge stopped building win-32 a few years ago. Any modern version is win-64.

**Comment by jswhit** [comment]
new windows wheels for 1.5.7 are up on pypi
