### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [Unidata/netcdf4-python#1114]
Problem
---------
On AArch64, ‘pip install netcdf4’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes more time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On AArch64, ‘pip install netcdf4’ should download the wheels from pypi

@jswhit, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by jswhit** [comment]
we already have aarch64 wheels on pypi (https://pypi.org/project/cftime/#files).  Don't know why pip is not using them.

**Comment by odidev** [comment]
@jswhit, I have raised PR: https://github.com/MacPython/netcdf4-python-wheels/pull/12. Can you please take a look on it? Thanks in advance.
