### ISSUE TITLE
Accessing a vlen variable with valid_range attribute fails

### ISSUE THREAD

**Issue by cyrilleponcelet** [Unidata/netcdf4-python#1115]
Platform windows (anaconda), netCDF4 = 1.5.6, python 3.7

Hi, 
When reading a vlen variable with a valid_range attribute set (or valid_min) an exception is raised 

```
  File "src\netCDF4\_netCDF4.pyx", line 4461, in netCDF4._netCDF4.Variable.__getitem__
  File "src\netCDF4\_netCDF4.pyx", line 4658, in netCDF4._netCDF4.Variable._toma
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
The only way to bypass this issue is to read value per value.

An example to reproduce the issue is given below

Please let me know if you need any other information. Thank you

```
import netCDF4 as nc
import tempfile as tmp
import numpy as np


def create_file_with_float_valid_range(file: str):
    """
    Create a netcdf file with one vlen variable and a valid_range attribute
    """
    with nc.Dataset(file, "w") as f:
        # create vlen type and name it
        x = f.createDimension("x", None)

        vlen_t_float = f.createVLType(np.float32, "my_type")
        vlvar_float = f.createVariable("values_float", vlen_t_float, ("x"))
        vlvar_float.valid_range = [np.float32(0), np.float32(5000)]

        count = 292
        # fill with arbitrary values
        data = np.empty(len(x), object)
        for n in range(count):
            # create array of variable len
            values = np.pi + np.arange(4)
            values[1] = np.nan
            vlvar_float[n] = values  # create fake data with pi values


def print_content_sample(file: str, var_name="var"):
    """
    read first and last values of vlen variable and print them
    """
    with nc.Dataset(file) as input:
        values = input[var_name]
        sample = values[:]
        last_index = len(sample) - 1
        print(f"file {file} : content_vlen = [{sample[0]} ...{sample[last_index]} ]")


if __name__ == "__main__":
    file = tmp.mktemp(suffix=".nc", prefix="temp_")
    create_file_with_float_valid_range(file)
    print_content_sample(file, var_name="values_float")

```

If you have a general question about the software, please view our [Suggested Support Process](https://www.unidata.ucar.edu/support/#process).

**Comment by jswhit** [comment]
Problem is that vlens are represented in python as object arrays containing numpy arrays.  You can't do normal numpy logical operations like `data > valid_max`  on such arrays, you have to loop over all the elements are do the comparison on each numpy array within the object array.  This can be done, but it may be quite slow.

**Comment by jswhit** [comment]
Also, what is valid_range supposed to do in the case of vlens?  if a 1-d array that is a represented by a single element of a vlen contains an out of range value, should that entire vlen element be masked, or should it contain a 1d data array with 
 only values masked that are out of range?

**Comment by jswhit** [comment]
Perhaps masked arrays should not be returned by default for vlens, since it's not obvious how to deal with missing or invalid values and there doesn't seem to be any official guidance in the netcdf users guide or the CF conventions.

**Comment by cyrilleponcelet** [comment]
I agree it cannot be optimum to loop over each array but I think that people expect to retrieve a 1d data array with only values masked out of range. 
I think people expects the same behaviour as regular arrays (scale_factor, add_offset, missing value, valid_range, valid_min and valid_max.) 
For information I did not create the file with vlen and valid_range, I just received it. 

I just tried to disable the auto_masking of variable with set_auto_mask(False) and it allows to bypass this issue.

Do you think it is correct to say that the api should apply validity range, and people can disable this with the auto_mask function if they want to improve vlen performances. ?

**Comment by cyrilleponcelet** [comment]
> 
> 
> Perhaps masked arrays should not be returned by default for vlens, since it's not obvious how to deal with missing or invalid values and there doesn't seem to be any official guidance in the netcdf users guide or the CF conventions.

Sorry I just saw your answer. See my comments above.

**Comment by jswhit** [comment]
I don't think your expectation necessarily conforms to netcdf policy for vlens.  There is some discussion of the use of missing_values and _FillValues for vlens at https://github.com/Unidata/netcdf-c/issues/1011.  The key point is that missing and/or fill values should have the base vlen type (they should be arrays themselves).

**Comment by jswhit** [comment]
Given the ambiguities of how missing_value/_FillValue/valid_range should be handled for vlens, I think this is best left to the user to implement.  PR #1115 disables auto-masking for vlens (it already is disabled for compounds for similar reasons).  With the change, auto-masking is only enabled for primitive data types and enum types.   scale_factor/add_offset packing still works for vlens though.

**Comment by jswhit** [comment]
PR #1120 merged

**Comment by cyrilleponcelet** [comment]
Many thanks for your answer and for the very interesting link about _FillValue.
