### ISSUE TITLE
Reading a truncated netCDF4 file from memory crashes the interpreter.

### ISSUE THREAD

**Issue by d70-t** [Unidata/netcdf4-python#1122]
When I try to read a truncated netCDF4-File from memory by running the following on macOS 11.3.1, Python 3.9.5:

```python
In [1]: import netCDF4

In [2]: netCDF4.__version__
Out[2]: '1.5.7'

In [3]: netCDF4.getlibversion()
Out[3]: '4.7.4 of Jun 21 2021 18:00:32 $'

In [4]: netCDF4.Dataset("test.nc", memory=b'\x89HDF\r\n\x1a\n')
Assertion failed: (udata != NULL), function NC4_extract_file_image, file nc4memcb.c, line 862.
fish: Job 1, 'ipython3' terminated by signal SIGABRT (Abort)
```

the interpreter crashes.

When I instead write the file out to disk:
```python
In [1]: f = open("test.nc", "wb")

In [2]: f.write(b'\x89HDF\r\n\x1a\n')
Out[2]: 8

In [3]: f.close()

In [4]: import netCDF4

In [5]: netCDF4.Dataset("test.nc")
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-5-652fc0e50f1f> in <module>
----> 1 netCDF4.Dataset("test.nc")

src/netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__()

src/netCDF4/_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()

OSError: [Errno -101] NetCDF: HDF error: b'test.nc'
```
I properly get an error.

I've got a bunch of files which I download from another server and would like to have only in memory. But as I don't know if the files are proper netCDF files, I need a way to try to open it. As the interpreter crashes, I can't catch the error. I would prefer if the variant reading from memory would also raise an error.

**Comment by dopplershift** [comment]
Given that the error is identified here:
> Assertion failed: (udata != NULL), function NC4_extract_file_image, file nc4memcb.c, line 862.

It's likely this is an issue with the netcdf-c library.

**Comment by jswhit** [comment]
Agreed - this is a netcdf-c problem so an issue should be opened there.  I would guess there is not a lot that can be done about it - if the file is corrupted it's probably inevitable that the library will try to address non-allocated memory.

**Comment by dopplershift** [comment]
Well, it's technically just failing an assertion, so it's a condition that's being checked for, just not returning an error. :wink:
