### ISSUE TITLE
Enum dicts have wrong values for large enums

### ISSUE THREAD

**Issue by habbit-baggins** [Unidata/netcdf4-python#1128]
* Found in: v 1.5.7 (latest release)
* Issue: the `enum_dict` member of an EnumType read from a file contains invalid values when the enum is large enough (more than 127 or 255 members)

When parsing an EnumType in an existing dataset, the `_read_enum` function uses a `char`-typed variable to call the NC function `nc_inq_enum_member`. This is used to build the name-to-value dict that is later returned by `enum_dict` in the generated EnumType:

https://github.com/Unidata/netcdf4-python/blob/d8b1cb11454f9beec674a29904c91f48db608c2c/src/netCDF4/_netCDF4.pyx#L5982
https://github.com/Unidata/netcdf4-python/blob/d8b1cb11454f9beec674a29904c91f48db608c2c/src/netCDF4/_netCDF4.pyx#L6004

For enum types with more than 255 values, this is incorrect and results in a (mostly) unusable `enum_dict`. Furthermore, the C function probably writes an integer of the "correct" size in the variable, so this is probably also a buffer overrun problem.

Instead, the expected behaviour would be to **use a CTypes/NumPy buffer of the right dtype**, which is also parsed by and available in the same `_read_enum` function.

Alternatively, it _might_ be possible to avoid this buffer creation by using a variable of type `intmax_t`, but the C function will likely leave most of that space untouched, so the actual dtype would still need to be considered when converting the read value to a Python int.

**Comment by jswhit** [comment]
Thanks for this report  @habbit-baggins.  Can you provide a simple python test script that triggers the problem so we can add it to the test suite?

**Comment by habbit-baggins** [comment]
Sure! Since the enum _writing_ part does seem to work, there is no need to upload a specific test file. The following code generates a test file containing an enum type with int16 values, and then tries to read it back. Changing this into Python unittest form to match your test suit should be just pretty straightforward, I think. 

The second assertion triggers for BITS values over 7 (included, actually, since the `char` variable used to read turns 128 into -128).

~~~ python
import netCDF4
import numpy as np
import tempfile

DT = np.int16
BITS = 8
STORED_VAL = DT(2**BITS)
VAL_MAP = {f'bits_{n}': DT(2**n) for n in range(1,BITS+1)}
VAL_MAP['invalid'] = 0

file = tempfile.NamedTemporaryFile(suffix='.nc', delete=False).name
print('File is:', file)

with netCDF4.Dataset(file, 'w') as nc:
	# The enum is created with dtype=int16, so it will allow BITS values up to 15
	et = nc.createEnumType(DT, 'etype', VAL_MAP)
	print(f'Writing ET with dtype={et.dtype} and values map={et.enum_dict}')
	ev = nc.createVariable('evar', et)
	# Succeeds because the created EnumType does keep the correct dict
	ev[...] = STORED_VAL

with netCDF4.Dataset(file, 'r') as nc:
	read_var = nc['evar']
	read_et = read_var.datatype
	# Will show a dict with bits_7=-128 and bits_N=0 for all N>=8
	print(f'Reading ET with dtype={read_et.dtype} and values map={read_et.enum_dict}')
	print(f'Read value={read_var[...]}')
	if read_var[...] != STORED_VAL:
		raise AssertionError("Read value does not match the original")
	if read_et.enum_dict != VAL_MAP:
		raise AssertionError("Read enum dict does not match the original")
~~~

**Comment by jswhit** [comment]
PR #1131 implements a fix - @habbit-baggins if this works for you I will merge.

**Comment by habbit-baggins** [comment]
Hi, I just built and tested it locally (Ubuntu 20.04, Python 3.8), and it seems to work with very large enums. Thanks a lot! 👍

**Comment by jswhit** [comment]
great, PR #1131  merged
