### ISSUE TITLE
setup.py not detecting parallel4 support

### ISSUE THREAD

**Issue by sjsmith757** [Unidata/netcdf4-python#1129]
Hi!

I have been having trouble getting netCDF4-python to recognize that my netcdf-c library is built with parallel support. nc-config --has-parallel(4) both return yes. As suggested in a previous issue, `$NETCDF4_DIR/include/netcdf_meta.h` includes `#define NC_HAS_PARALLEL4 1`, and running setup.py by itself (not installing) shows that check_api() returns has_parallel4_support=True. However, after importing netCDF4, `netCDF4.__has_parallel4_support__` returns False. I am also installing it just as a user ("pip install netcdf4 --user"), and wonder if my somewhat unique install conditions are part of the problem. I suspect maybe one of the environment variables is not set properly, but I'm unsure which ones netcdf4-python expects. 

I'm using:

netcdf4-python=1.5.7
mpi4py=3.0.3
numpy=1.19.5
cython=0.29.23
cftime=1.5.0
setuptools=47.1.0
hdf5=1.12
netcdf-c=4.7.4
gcc=9.3.0
mvapich=2.3.5
python=3.8.5
Red Hat Enterprise v8

Thanks for any help you can provide!

**Comment by jswhit** [comment]
Are you sure `pip install netcdf4 --user` isn't installing a pre-built wheel instead of building from source?  What happens if you run `python setup.py install --user` instead?

**Comment by sjsmith757** [comment]
Hi Jeff, thanks for the suggestion. It does seem to recognize that parallel support is enabled, however it results in a build failure:

/usr/bin/ld: netcdf/lib/libnetcdf.a(libdispatch_la-datt.o): relocation R_X86_64_PC32 against symbol `NC_check_id' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

I'm wondering if perhaps I didn't quite build my netcdf-c library correctly. I know that isn't necessarily a problem with netcdf-python, but I would be grateful for any direction if you have any ideas. I also know that now the title no longer matches the issue, so I can close this if necessary. Thanks!

**Comment by sjsmith757** [comment]
Turns out I had not built the netcdf-c libraries to enable shared libraries, it was able to build properly after rebuilding the netcdf libraries. Thanks so much!
