### ISSUE TITLE
Wheels for 3.10?

### ISSUE THREAD

**Issue by dopplershift** [Unidata/netcdf4-python#1136]
What would it take to get wheels for the current release up on PyPI? Just working through getting a Linux PyPI build for MetPy, and this is the first dependency in the way.

**Comment by jswhit** [comment]
working on new releases of cftime and netcdf4-python that will have 3.10  manylinux_2014 wheels

**Comment by jswhit** [comment]
v1.5.8 released with python 3.10 (and aarch64) wheels
