### ISSUE TITLE
TypeError: 'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by supershushu** [Unidata/netcdf4-python#1138]
Hi, when I use python 2.7 to pip install netcdf4, there is error:
 Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/gpfs/scratch1/nodespecific/int1/jinma/pip-install-_4R0L6/netcdf4/setup.py", line 419, in <module>
        _populate_hdf5_info(dirstosearch, inc_dirs, libs, lib_dirs)
      File "/gpfs/scratch1/nodespecific/int1/jinma/pip-install-_4R0L6/netcdf4/setup.py", line 364, in _populate_hdf5_info
        hdf5_version = get_hdf5_version(HDF5_incdir)
      File "/gpfs/scratch1/nodespecific/int1/jinma/pip-install-_4R0L6/netcdf4/setup.py", line 37, in get_hdf5_version
        hdf5_version = check_hdf5version(direc)
      File "/gpfs/scratch1/nodespecific/int1/jinma/pip-install-_4R0L6/netcdf4/setup.py", line 24, in check_hdf5version
        f = open(os.path.join(hdf5_includedir, 'H5public.h'), **open_kwargs)
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------

I have a solution but it needs to change the setup.py file.
just replace line 24 in setup.py to:
import io
 f = io.open(os.path.join(hdf5_includedir, 'H5public.h'), **open_kwargs)

But I am not sure if it works for python3. I am using python2.7 because of historical reasons of our projects.
thanks if you can help on this.

**Comment by jswhit** [comment]
python 2.7 is no longer supported in netcdf4-python.  You should upgrade to python 3, very few packages still support python 2.7 itself was sunsetted in Jan 2020 (https://www.python.org/doc/sunset-python-2/).  If you have to use python 2.7, try installing an older version of netcdf4-python (version 1.5.5.1 should work).

**Comment by supershushu** [comment]
Dear Sir, 

I totally agree with you that migration to python3 would better solution but our projects is large.
So, I tried to install old version 1.5.5.1 but it does not work either. Below is the information. Should I use a different HDF5 library ? 
thanks. 

Collecting netCDF4==1.5.5.1
  Using cached https://files.pythonhosted.org/packages/9f/e2/686d0d937f979e7ee0eb6bb4821448da6d2910789f4928c12b070f424b6a/netCDF4-1.5.5.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /sw/arch/Centos8/EB_production/2021/software/Python/2.7.18-GCCcore-10.3.0-bare/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/gpfs/scratch1/nodespecific/int3/jinma/pip-install-kW5GiG/netCDF4/setup.py'"'"'; __file__='"'"'/gpfs/scratch1/nodespecific/int3/jinma/pip-install-kW5GiG/netCDF4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /gpfs/scratch1/nodespecific/int3/jinma/pip-install-kW5GiG/netCDF4/
    Complete output (17 lines):
    reading from setup.cfg...
    checking /sw/arch/Centos8/EB_production/2021/software/HDF5/1.10.7-iimpi-2021a/include ...
    HDF5 library version: 1.10.7 headers found in /sw/arch/Centos8/EB_production/2021/software/HDF5/1.10.7-iimpi-2021a/include
    HDF5 library version: 1.10.7 found in /sw/arch/Centos8/EB_production/2021/software/HDF5/1.10.7-iimpi-2021a
    
    NETCDF4_DIR environment variable not set, checking standard locations..
    checking /home/jinma ...
    checking /usr/local ...
    checking /sw ...
    checking /opt ...
    checking /opt/local ...
    checking /usr ...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/gpfs/scratch1/nodespecific/int3/jinma/pip-install-kW5GiG/netCDF4/setup.py", line 427, in <module>
        raise ValueError('did not find netCDF version 4 headers')
    ValueError: did not find netCDF version 4 headers
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by supershushu** [comment]
Dear Sir,

thank you for the comment. I tried to use netcdf4 version==1.5.5.1 for python2.7, and it works.
