### ISSUE TITLE
Unexpected contiguous and chunking behaviour with createVariable() default arguments

### ISSUE THREAD

**Issue by wknoben** [Unidata/netcdf4-python#1141]
I noticed some unexpected behaviour when creating new datasets, resulting in contiguous or chunked data despite the arguments to `createVariable()` specifying not to do so. 

Some testing seems to suggest that default chunk size behavour is different for limited and unlimited dimensions (but not `None`), and that for limited dimensions the default chunk size is the size of the dimension. Intuitively I had not expected that default chunking behaviour is one large chunk that covers the entire limited dimension because this seems like it could be detrimental for the reading of larger files (which is the reason why I started looking into this in the first place). If this is in fact expected, then perhaps an update to the docs could be helpful (https://unidata.github.io/netcdf4-python/#Dataset.createVariable) to explicitly state what happens with `chunksizes=None`. I noticed also that the [link](http://www.hdfgroup.org/HDF5/doc/H5.user/Chunking.html) in the paragraph about `chunksizes` that should direct to further reading is broken.

Reproducible on both Windows:
- Python 3.8.8
- netCDF4 1.5.6
- libnetcdf 4.7.4

and Linux:
- Python 3.8.10
- netCDF4 1.5.4
- libnetcdf 4.7.4

#### MWE1: unlimited dimension only
```
import netCDF4 as nc4
with nc4.Dataset('unlimitedDim_defaultParameters.nc', 'w') as nc:
    nc.createDimension('unlimited', None);
    nc.createVariable('var','f8', 'unlimited', contiguous=False, chunksizes=None)
    print('shape, chunking = {}, {}'.format(nc['var'].shape, nc['var'].chunking()))
```
Result: chunked data:  `shape, chunking = (0,), [512]`

#### MWE2: limited dimension only
```
import netCDF4 as nc4
with nc4.Dataset('limitedDim_defaultParameters.nc', 'w') as nc:
    nc.createDimension('limited', 10);
    nc.createVariable('var','f8', 'limited', contiguous=False, chunksizes=None)
    print('shape, chunking = {}, {}'.format(nc['var'].shape, nc['var'].chunking()))
```
Result: contiguous data:  `shape, chunking = (10,), contiguous`

#### MWE3: unlimited and limited dimension
```
import netCDF4 as nc4
with nc4.Dataset('unlimitedDim_limitedDim_defaultParameters.nc', 'w') as nc:
    nc.createDimension('unlimited', None);
    nc.createDimension('limited', 10);
    nc.createVariable('var','f8', ('unlimited','limited'), contiguous=False, chunksizes=None)
    print('shape, chunking = {}, {}'.format(nc['var'].shape, nc['var'].chunking()))
```
Result: chunked data: `shape, chunking = (0, 10), [1, 10]`

#### MWE4: unlimited and limited dimension with multiple entries in unlimited dimension
```
import netCDF4 as nc4
import numpy as np
with nc4.Dataset('multipleUnlimitedDim_limitedDim_defaultParameters.nc', 'w') as nc:
    nc.createDimension('unlimited', None);
    nc.createDimension('limited', 10);
    nc.createVariable('var','f8', ('unlimited','limited'), contiguous=False, chunksizes=None)
    nc['var'][:] = np.random.rand(3,10)
    print('shape, chunking = {}, {}'.format(nc['var'].shape, nc['var'].chunking()))
```
Result: chunked data: `shape, chunking = (3, 10), [1, 10]`

**Comment by jswhit** [comment]
The default chunking is chosen by the C library.  I can't put my finger on where that is documented at the moment.

The broken link in the chunking docstring is fixed in PR #1142

**Comment by jswhit** [comment]
Chunking in netcdf-c lib is discussed here: https://www.unidata.ucar.edu/software/netcdf/documentation/NUG/netcdf_perf_chunking.html

**Comment by wknoben** [comment]
Thanks for taking a look and pointing me (and others) to the docs on this! Looks like I have some further reading to do.
