### ISSUE TITLE
AttributeError: NetCDF: Attribute not found

### ISSUE THREAD

**Issue by Gizem-9395** [Unidata/netcdf4-python#1143]
Hi, I'm very new to netCDf yet. I am trying to extract time series from netCDF file I have. I get the following error when I want to run my code. I am working with Jupyter 6.3.0 ve netCDF4 1.5.3. I couldn't understand what I did wrong. I would be glad if you help.
    3 times=data.variables['time'][:]
       4 units=data.variables['time'].units
----> 5 for key, value in data.iterrows():
       6 prints (key, value[0],value[1],value[2])
       7 time=value[0]

netCDF4\_netCDF4.pyx in netCDF4._netCDF4.Dataset.__getattr__()

netCDF4\_netCDF4.pyx in netCDF4._netCDF4.Dataset.getncattr()

netCDF4\_netCDF4.pyx in netCDF4._netCDF4._get_att()

netCDF4\_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()

AttributeError: NetCDF: Attribute not fou

**Comment by jswhit** [comment]
iterrows is a Pandas DataFrame method - the netCDF variable object doesn't have one.  Maybe you want something like this?

```python
from netCDF4 import Dataset
URL = 'https://podaac-opendap.jpl.nasa.gov/opendap/allData/modis/L3/aqua/11um/v2019.0/4km/daily/2017/365/AQUA_MODIS.20171231.L3m.DAY.NSST.sst.4km.nc'
nc = Dataset(URL)
for var in nc.variables:
    print(var, nc[var])
nc.close()
```
