### ISSUE TITLE
Dataset mode=a for non-existing file behaves differently than Python.open

### ISSUE THREAD

**Issue by zerothi** [Unidata/netcdf4-python#1144]
Versions:
```
sys.version_info(major=3, minor=9, micro=9, releaselevel='final', serial=0)
netCDF4: 1.5.7
```
Script to reproduce:
```python
import netCDF4 as nc

def run(func, *args, **kwargs):
    try:
        func(*args, **kwargs)
    except Exception as e:
        print(f"exception in: {func.__name__}")
        print(f"  > {e}")

def write_cdf(file, mode):
    out = nc.Dataset(file, mode)
    if "size" not in out.dimensions:
        dim = out.createDimension("size", 2)
    if "foo" in out.variables:
        var = out.createVariable("foo", 'f4', ("size",))
        var[:] = 2
    out.close()

def write_ascii(file, mode):
    open(file, mode).write("""hello world""")

# first write-will create files
run(write_ascii, "bug_ascii_w.txt", 'w')
run(write_cdf, "bug_ascii_w.nc", 'w')

# append to existing file
run(write_ascii, "bug_ascii_w.txt", 'a')
run(write_cdf, "bug_ascii_w.nc", 'a')

# append to non-existing file
run(write_ascii, "bug_ascii_a.txt", 'a')
run(write_cdf, "bug_ascii_a.nc", 'a')
```

When using regular Python, the `mode='a'` will create the file in case it is not there, see above script. I would expect a `Dataset` to behave the same.

The problem is that when one creates functions in API's that specifies the mode of a Dataset file one needs to ensure that the user adheres to these cases, or handle them internally. This is a needless pain in my opinion.

While I can see files that are created from a `mode='a'` still requires setting up dimensions etc. However, this is trivially handled by having an internal `_get_var` which checks for its existence.

Are there any reason for _not_ allowing mode=a to create the file if it does not exist?

**Comment by jswhit** [comment]
'a' stands for 'append mode', which implies there is something to append to.  Didn't realize python open created a file if one did not exist.  To implement this, one would have to first use os.path.exists to check for existence of the file, and if it doesn't exist use nc_create instead of nc_open.    However, the error message ```FileNotFoundError: [Errno 2] No such file or directory'``` is pretty clear, so just like your other issue I'm not quite sure this is necessary.

**Comment by zerothi** [comment]
I would argue that one would assume the same behaviour as the standard library.

I totally understand their differences, but it forces library devs to add boiler plate code which could easily be put into the netcdf code. Again since the standard libraries behaves like this I think it would be natural.

**Comment by jswhit** [comment]
Since this was relatively easy to implement, I went ahead and created a PR for it (PR #1146).  Would like to hear if others think this is a desirable change, or would cause problems with existing code that may be relying on the previous behavior.

**Comment by sadielbartholomew** [comment]
> Would like to hear if others think this is a desirable change, or would cause problems with existing code that may be relying on the previous behavior.

Hi @jswhit, on this note, @davidhassell and I make use of append mode for some features in the library [cfdm](https://github.com/NCAS-CMS/cfdm) and (after a brief discussion) whilst we wouldn't strictly class this change as desirable (we think there are arguments for either behaviour), we understand that consistency with the Python file management behaviour could be beneficial, and it certainly wouldn't cause problems for us downstream in cfdm for netcdf4-python to include this change. Thanks.

**Comment by jswhit** [comment]
PR #1146 merged, closing now...
