### ISSUE TITLE
createVariable does not accept `Dimension` objects as dimension specifications

### ISSUE THREAD

**Issue by zerothi** [Unidata/netcdf4-python#1145]
It would be nice if the following could be done, for completeness sake:
```python
import netCDF4 as nc

out = nc.Dataset("hello.nc", 'w')
dim = out.createDimension("size", 2)
foo = out.createVariable("foo", 'f4', ('size',))
bar = out.createVariable("bar", 'f4', (dim,))
```
The documentation is coherent with the implementation, but I think the above should be allowed.

**Comment by jswhit** [comment]
Not obvious to me that this is necessary, but if someone's willing to implement this I'll entertain a PR.

**Comment by jswhit** [comment]
This actually turned out to be pretty straightforward as well, so I created a draft PR #1147

**Comment by jswhit** [comment]
PR #1147 merged, closing now...
