### ISSUE TITLE
Preparing metadata (setup.py) ... error

### ISSUE THREAD

**Issue by CaffreyR** [Unidata/netcdf4-python#1157]
Version:macOS 12.1 Apple m1 pro python 3.9
I got this issue when I _pip install netCDF4_. I had already install hdf5 when I installed tensorflow for appleslicon. Thanks a lot.
<img width="579" alt="截屏2022-03-09 下午4 13 39" src="https://user-images.githubusercontent.com/84232793/157399906-a48d7146-bd90-4a80-8e5a-c55fe5d59d72.png">

**Comment by jswhit** [comment]
It's trying to build from source instead of installing a pre-built binary - what platform are you on?

To install from source, you need to have a C compiler installed, and the HDF5_DIR environment variable needs to point to the path where the HDF5 library was installed.  You also need to have the netcdf-c library installed.

**Comment by jswhit** [comment]
Sorry, I missed that you said you are using apple silicon.  We have a binary (universal2) for python 3.10 that should work on M1.  For some reason, pip is not using it -are you using python 3.10?  
We will soon be making a 1.6.0 release that should have M1 binaries for python 3.8,3.9 and 3.10.

**Comment by CaffreyR** [comment]
emm so I just have to create a env where python == 3.10 and pip install the netCDF4?

**Comment by CaffreyR** [comment]
> Sorry, I missed that you said you are using apple silicon. We have a binary (universal2) for python 3.10 that should work on M1. For some reason, pip is not using it -are you using python 3.10? We will soon be making a 1.6.0 release that should have M1 binaries for python 3.8,3.9 and 3.10.

emm so I just have to create a env where python == 3.10 and pip install the netCDF4?

**Comment by jswhit** [comment]
The 3.10 universal2 wheel is broken (see https://github.com/Unidata/netcdf4-python/issues/1148).  A workaround to build from source that uses homebrew to provide the C lib dependencies is described in that issue.

**Comment by jswhit** [comment]
You can also install via [conda](https://anaconda.org/conda-forge/netcdf4).

**Comment by jswhit** [comment]
I think the issues with cross-compiling the C libs are now fixed.  I've uploaded new arm64 wheels for version 1.5.8 to pypi. @CaffreyR - could you test and report back here whether they work?

**Comment by CaffreyR** [comment]
> I think the issues with cross-compiling the C libs are now fixed. I've uploaded new arm64 wheels for version 1.5.8 to pypi. @CaffreyR - could you test and report back here whether they work?
Actually, there are something wrong here. See although I successfully install netCDF4, I can't import it.
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/84232793/159426525-4a5d03e5-c995-468e-95ce-dca294723df4.png">

**Comment by CaffreyR** [comment]
And it seems it don't work on both python 3.9 and 3.10 @jswhit 
<img width="582" alt="image" src="https://user-images.githubusercontent.com/84232793/159428330-e1ac5f0e-888a-46e8-a573-73b0e19250cb.png">

**Comment by jswhit** [comment]
covered by issue #1158

**Comment by suchethu** [comment]
> Version:macOS 12.1 Apple m1 pro python 3.9 I got this issue when I _pip install netCDF4_. I had already install hdf5 when I installed tensorflow for appleslicon. Thanks a lot. <img alt="截屏2022-03-09 下午4 13 39" width="579" src="https://user-images.githubusercontent.com/84232793/157399906-a48d7146-bd90-4a80-8e5a-c55fe5d59d72.png">

**Comment by zouyim** [comment]
![image](https://user-images.githubusercontent.com/116799592/201269252-6c540be1-b792-48e6-9ec3-f0c0f4da73bb.png)

**Comment by KingMorisco** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/65326054/233801857-12995c09-43c5-4c4e-9c24-eb6fd38b3568.png)
i have the same problem , I need help

**Comment by MackenzieTheOne** [comment]
me three

**Comment by lonrencn** [comment]
+1

**Comment by resvisneto** [comment]
me forth
