### ISSUE TITLE
Create working universal2 and arm64 binary wheels for Applie M1 silicon

### ISSUE THREAD

**Issue by jswhit** [Unidata/netcdf4-python#1158]
see https://github.com/MacPython/netcdf4-python-wheels/issues/15

the current universal2 wheels don't work - see issue #1157 and issue #1148

**Comment by jswhit** [comment]
I have new arm64 wheels available on pypi - would appreciate if someone could test and report back here.

**Comment by CaffreyR** [comment]
![image](https://user-images.githubusercontent.com/84232793/159428515-2b818362-a3f9-4ead-bee3-f601dcb31d38.png)
![image](https://user-images.githubusercontent.com/84232793/159428528-6e10fcf5-7f9b-4371-a069-8712970ec2cf.png)
It seems that something wrong with the _import_

**Comment by jswhit** [comment]
OK, thanks for trying.  Seems as if there is still something wrong with the HDF5 cross-compilation.

**Comment by jswhit** [comment]
@CaffreyR I've got a new one for you to test (https://github.com/MacPython/netcdf4-python-wheels/releases/download/v1.5.8rel/netCDF4-1.5.8-cp310-cp310-macosx_11_0_arm64.whl).   It's not on pypi, so you have to download the wheel first and then install it with 

pip install netCDF4-1.5.8-cp310-cp310-macosx_11_0_arm64.whl  netCDF4

**Comment by CaffreyR** [comment]
<img width="568" alt="image" src="https://user-images.githubusercontent.com/84232793/159728689-8c307a12-391e-4964-bbcc-20c64afe1db5.png">
It seems that I can import it successfully with python 3.10! @jswhit

**Comment by CaffreyR** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/84232793/159730970-c7739930-6583-4fd7-ba6c-b73cc0a04c64.png">
I can load the file from NASA, it worked well now. @jswhit

**Comment by jswhit** [comment]
Thanks for checking @CaffreyR!  The 1.6.0 release on pypi will have working arm64 wheels for macosx.

**Comment by jaklan** [comment]
@jswhit If I ee correctly - `1.6.0` wasn't yet released, so it's impossible to install the package on M1-based MacBooks (with no manual steps).
