### ISSUE TITLE
Clipping the netcdf4 file to the polygon shapefile

### ISSUE THREAD

**Issue by d-saikrishna** [Unidata/netcdf4-python#1160]
Hello,

Currently the process to clip a netcdf4 file to a polygon is very lengthy. Given that the netcdf4 files are huge, the process often leads to Memory issues.

I have written a two-step function that does this on Python pretty quickly. Would love to contribute it as method to this package.

**Comment by jswhit** [comment]
netcdf4-python is really for basic IO functionality - may be more appropriate for a package like [shapely](https://github.com/shapely/shapely)
