### ISSUE TITLE
Unable to use URL approach to opening NetCDF file

### ISSUE THREAD

**Issue by christine-e-smit** [Unidata/netcdf4-python#1162]
**NetCDF4 version: 1.5.8
Environment: macOS Big Sur, anaconda python version 3.10.4**

I am trying to use some of the recent changes to the underlying NetCDF C libraries through python. Ultimately, I want to use this to open a zarr store from the NetCDF library, so I'm talking about the syntax outlined in this blog post: https://www.unidata.ucar.edu/blogs/developer/en/entry/overview-of-zarr-support-in

For now, I'm trying to use the URL-style access to open a locally stored NetCDF file and it's not working. 

### This works fine

```
from netCDF4 import Dataset
nc = Dataset("/not/a/real/path/file.nc")
```

So I know that my NetCDF file is fine.

### These don't work

```
from netCDF4 import Dataset
nc = Dataset("file://localhost/not/a/real/path/file.nc#mode=file")
```

and

```
from netCDF4 import Dataset
nc = Dataset("file:///not/a/real/path/file.nc#mode=file")
```

both give me the error

```
OSError: [Errno -101] NetCDF: HDF error
```

I looked at the python NetCDF4 documentation for the Dataset() function (https://unidata.github.io/netcdf4-python/#Dataset.__init__) and I'm not seeing any reference to passing in URLs, but I have see some references elsewhere to using this kind of syntax. So I think it should work? Please help.

Thank you.

**Comment by jswhit** [comment]
If it works in the C library, it should work in netcdf4-python.  I see the same error with netcdf-c 4.8.1 if I try to use the "file://path/to/file.nc#mode=file" URL, but I haven't tried it in a C program.

**Comment by jswhit** [comment]
Could be that the C lib was not built with `` --enable-nczarr ``?

**Comment by christine-e-smit** [comment]
I got the python library and the compile c libraries from anaconda python. I didn't compile the netcdf-c libraries myself. According to the ncdump executable I got from anaconda, the netcdf-c library I have is:

netcdf library version 4.8.1 of Aug 31 2021 00:10:05

So I'm using the same version as you. I'm not sure if there is some way to see what compile options were used building the package.

**Comment by jswhit** [comment]
I get the same error if I try to open a local file with a URL using a simple C program
```
#include <netcdf.h>
#include <stdio.h>
#include <stdlib.h>
void
check_err(const int stat, const int line, const char *file) {
    if (stat != NC_NOERR) {
        (void)fprintf(stderr,"line %d of %s: %s\n", line, file, nc_strerror(stat));
        fflush(stderr);
        exit(1);
    }
}
int
main()
{
    int ncid, ierr;
    ierr=nc_open("file:///Users/jwhitaker/oras5/grepv2_daily_20160328.nc#mode=file", 0, &ncid);
    check_err(ierr,__LINE__,__FILE__);
    ierr=nc_close(ncid);
}
~  
```

**Comment by christine-e-smit** [comment]
Okay. Does this mean that (a) the anaconda netcdf binaries do not have the new URL support or (b) the URL syntax is wrong? I'm guessing (a). If this is the case, then I guess I need to compile netcdf-c myself with the "--enable-nczarr" option?

**Comment by jswhit** [comment]
I think it's (b). The URL support should be enabled by defauit.

**Comment by DennisHeimbigner** [comment]
Using a file: url to access a netcdf-4 file using HDF5 will fail
because HDF5 does not support URL paths. Similarly for HDF4,
and pnetcdf. Netcdf-3 does not support it either, but since we
control that code, we could change it.
I could modify our HDF5 wrapping code to extract the path
from a "file:" url, but not sure there is any call for it.

**Comment by jswhit** [comment]
OK thanks @DennisHeimbigner.  @christine-e-smit the URL syntax is intended for use with nczarr or zarr,  not regular netcdf files.
