### ISSUE TITLE
Variable not pre-filled with default fill mode?

### ISSUE THREAD

**Issue by 0xa000** [Unidata/netcdf4-python#1165]
Likely just a confusion about the documentation: I'm trying to create a dummy dataset using netCDF4-python 1.5.8. My understanding of the default behavior is that a variable will be filled with the default fill value upon creation. But, instead it seems that filling only happens when the variable is first written to.

The code below produces a file of about 6 KB, where I would have expected 4 MB. Performing a single write to the variable (such as the commented line below) does create a file of the expected size.

```
with netCDF4.Dataset("test.nc", "w") as dataset:
    dim = dataset.createDimension("dim", 1024 * 1024)
    var = dataset.createVariable("var", "f4", ("dim",))
    # var[0] = 3.1415
```

The documentation of `createVariable()` reads: "The optional keyword `fill_value` can be used to override the default netCDF `_FillValue` (the value that the variable gets filled with before any data is written to it, defaults given in the dict `netCDF4.default_fillvals`)."

My confusion stems from the part "before any data is written to it". What is the intended behavior, filling upon creation, or upon first write?

**Comment by jswhit** [comment]
Seems to me the documentation is accurate.

```python
import netCDF4
with netCDF4.Dataset("test.nc", "w") as dataset:
    dim = dataset.createDimension("dim", 1024 * 1024)
    var = dataset.createVariable("var", "f4", ("dim",))
    var.set_auto_mask(False)
    print(var[0])
```

produces

```
9.96921e+36
```

**Comment by 0xa000** [comment]
Ah, yes, that could explain it. I made sure compression was turned off, but maybe HDF5 has more tricks up its sleeve. So the variable does get filled upon creation, but the file size does not reflect this. An obvious work-around would be to perform an arbitrary write for each variable so it gets expanded on disk.

Interestingly, even writing back the fill value will expand the variable. The following produces a file of ~4MB.
```
import netCDF4    
with netCDF4.Dataset("test.nc", "w") as dataset:
    dim = dataset.createDimension("dim", 1024 * 1024)
    var = dataset.createVariable("var", "f4", ("dim",))
    var.set_auto_mask(False)
    var[0] = var[0]
```

**Comment by 0xa000** [comment]
Ah, yes, that could explain it. I made sure compression was turned off, but maybe HDF5 has more tricks up its sleeve. So the variable does get filled upon creation, but the file size does not reflect this. An obvious work-around would be to perform an arbitrary write for each variable so it gets expanded on disk.

Interestingly, even writing back the fill value will expand the variable. The following produces a file of ~4MB.
```
import netCDF4    
with netCDF4.Dataset("test.nc", "w") as dataset:
    dim = dataset.createDimension("dim", 1024 * 1024)
    var = dataset.createVariable("var", "f4", ("dim",))
    var.set_auto_mask(False)
    var[0] = var[0]
```
