### ISSUE TITLE
Write netCDF4 Dataset object directly to netCDF file

### ISSUE THREAD

**Issue by piratepheasant** [Unidata/netcdf4-python#1167]
I obtain a netCDF4 Dataset object using erddap-python:

from erddapClient import ERDDAP_Griddap
remote = ERDDAP_Griddap('https://www.ncei.noaa.gov/erddap','NCOM_amseas_latest2d')
nc = remote.ncDataset

I have been unable to determine if there is a way to turn this (or any netCDF4 Dataset object) into a netCDF file without having to go through the process of making a new netCDF file, e.g.,

from netCDF4 import Dataset
ncfile = Dataset('new.nc',mode='w',format='NETCDF3_CLASSIC')

and then add all of the dimensions, variables, etc. from the netCDF4 Dataset object, nc, to the newly created file.

I am using Python 3.7 on Mac OS 12.3.1.

Thanks so much for your help.
-Sunni

**Comment by ocefpaf** [comment]
This is beyond the scope of netcdf4-python. It is a question for erddap-python. I don't know how that library works but if you use `erddapy` you will can use the `.to_xarray()` method and then use xarray's `to_netcdf`. See https://ioos.github.io/erddapy/01a-griddap-output.html and https://docs.xarray.dev/en/latest/generated/xarray.Dataset.to_netcdf.html
