### ISSUE TITLE
Python 3.7 wheels for v1.6.0 on MacOS and Windows?

### ISSUE THREAD

**Issue by horizon-blue** [Unidata/netcdf4-python#1174]
Hi there,

It looks like the v1.6.0 version of `netcdf4` package on [PyPI](https://pypi.org/project/netCDF4/#files) only contains wheels for Linux distributions on Python 3.7. As a result, `pip install netcdf4` will fall back to building the source distribution on MacOS and Linux, which fails unless one has HDF5 dependency configured.

Since the release note doesn't mention anything about dropping Python 3.7 support, I'm wondering if there's any plan to add Python 3.7 wheels for MacOS and Windows in the future?

**Comment by jswhit** [comment]
I could add python 3.7 wheels for macos x, but the windows wheels are contributed by [Christoph Gohlke](https://www.lfd.uci.edu/~gohlke/pythonlibs/#netcdf4).

**Comment by jswhit** [comment]
x86_64 macosx wheels for python 3.6 and 3.7 now available on pypi.

**Comment by jswhit** [comment]
maybe I wasn't clear before, but windows wheels are out of my control.  I don't have the ability to create them, so I rely on contributions from others (primarily @cgohlke)

**Comment by horizon-blue** [comment]
Ah, I see, thanks for the clarification. Regardless, it's great that we get MacOS support.

We have a library that depends on netCDF4 indirectly and we will pin netCDF4 to 1.5.8 for Python 3.7 Windows users for now. Feel free to close the issue if you think this is no longer relevant :)
