### ISSUE TITLE
The files libzstd.lib, libblosc.lib, libbz2.lib are missing.

### ISSUE THREAD

**Issue by mbstoner53** [Unidata/netcdf4-python#1176]
I installed netcdf4 version 1.6.0 through using anaconda.  I am on a windows 10 laptop.  I also installed nco version 5.1.0.

When I run nco commands such as ncks or ncecat I get warning messages.  

I have a python script that calls these functions using subprocess.  This function is how my program calls nco commands.

```
# Run command line program as a subprocess and print the output from it.
#
# command: Command string to run.
def do_command(command): 

    ret = subprocess.run(command, capture_output=True)
    print( "\ncommand = "+ret.args )
    print( "return code = ", ret.returncode )
    print( "stdout:" )
    print( ret.stdout.decode("unicode_escape") )
    
    return ret.returncode
```

Here is a short clip of the output.

> ncecat: WARNING nc_cdc_lst_bld() reports nco_inq_filter_avail() did not find Zstandard filter (with HDF5 filter ID = 32015) as an HDF5 shared library filter. This is probably fixable because this filter is supported by all default installations of netCDF version 4.9.0 or higher. HINT: If you build netCDF from source, please be sure it was configured with the following options: "--enable-nczarr" and "--with-plugin-dir=${HDF5_PLUGIN_PATH}". The latter is especially important in netCDF 4.9.0. Also, please be sure the library for the missing filter (e.g., libzstd.a, libblosc.a, libbz2.a) is in an automatically searched directory, e.g., $LD_LIBRARY_PATH or /usr/lib.
> INFO: NCO stub function for nc_inq_filter_avail() reports an inquiry on filter availability of HDF5 filter ID = 32001. Stub function employed because libnetcdf.a does not contain nc_inq_filter_avail(). Please rebuild NCO against netCDF library version 4.9.0 (released ~20220601) or later to support the capability to find and call filters besides DEFLATE, Shuffle, and Fletcher32.

I get the same message if I call nco functions myself on the command line.  I looked in the lib folder in my environment and sure enough, there are no files "libzstd.lib", "libblosc.lib", or "libbz2.lib"

My application now only uses zlib, but I would like to be able to add the more advanced data compression features as options.  I would think version 1.6.0 would automatically install the netCDF library version 4.9.0, but it looks like it didn't.  Where can I find the missing library items?  Sorry if this is simple but I'm new to working with netCDF4 and working by myself.

**Comment by ocefpaf** [comment]
This is most likely unrelated to netcdf4-python. Please open an issue upstream in the `nco` feedstock at https://github.com/conda-forge/nco-feedstock/issues

Be sure to add the required debug info when opening an issue to help us reproduce it.

**Comment by mbstoner53** [comment]
Sorry.  I'm a newbie and I probably posted the wrong place.  This likely isn't a bug but simply a missing feature with the Anaconda auto-install.  Anaconda is installing netCDF 4.8.1 C libraries with netcdf4-python 1.6.0.  I could install 4.9.0 C libraries manually in the virtual environment in a way Anaconda likes, but its beyond me at the moment.  Since this is for reporting bugs I'll ask for help somewhere more appropriate.  You can just close this, unless you have something to add.
