### ISSUE TITLE
Segmentation fault | Reading a ~20 GB file

### ISSUE THREAD

**Issue by raj-magesh** [Unidata/netcdf4-python#1178]
I can't systematically reproduce this segmentation fault, but several times (~80% of trials), my Python interpreter crashes here, where `path` is the path to a large ~20 GB netCDF-4 file created with `xarray`. 

```python
assembly = netCDF4.Dataset(path, "r", format="NETCDF4")
```

It has a single large variable with 2 dimensions, a few global attributes, and ~300 coordinates along one of the dimensions.

Version: 1.6.0
Environment: Python 3.10, Linux (CentOS)

I'm not sure what information I can provide to debug this. I could try to see whether this occurs with smaller files so you could easily reproduce it, but I was wondering if others had reported this behavior or if it's already known.

**Comment by jswhit** [comment]
Have not seen this. Without having access to the file, I don't think there's much we can do
