### ISSUE TITLE
A selfish request for a new release after 2.6.0

### ISSUE THREAD

**Issue by hmaarrfk** [Unidata/netcdf4-python#1188]
This is a selfish request for a new release that would included the addition made in https://github.com/Unidata/netcdf4-python/pull/1183

Thank you for your consideration.

**Comment by jswhit** [comment]
v1.6.1rel release branch created (PR #1189)

**Comment by hmaarrfk** [comment]
Thank you!

**Comment by jswhit** [comment]
release created - closing now

**Comment by hmaarrfk** [comment]
Exciting! thank you!
