### ISSUE TITLE
what to do when a variable is sliced with an all False Boolean index array?

### ISSUE THREAD

**Issue by jswhit** [Unidata/netcdf4-python#1200]
Current behavior:
1) for a 1D variable an empty array is returned
2) for multi-dim variables an opaque exception is raised.
3) for numpy arrays, an empty array is always returned

Two potential solutions:
1) PR #1197:  always return an exception with a more informative error message
2) PR #1198:  always silently return an empty array (as numpy does)

Which one do you prefer?

**Comment by jswhit** [comment]
@dopplershift @shoyer any thoughts on this?

**Comment by shoyer** [comment]
Returning the size zero array like NumPy feels like the right thing to do

**Comment by dopplershift** [comment]
I agree, my lean was towards mirroring NumPy behavior.

**Comment by jswhit** [comment]
thanks - that's my thought as well.  I will merge PR #1198 next week if we have no dissenting opinions by then.
