### ISSUE TITLE
DEP: distutils is deprecated

### ISSUE THREAD

**Issue by snowman2** [Unidata/netcdf4-python#1206]
https://github.com/Unidata/netcdf4-python/blob/8f7a365555013dcbb002462215665ca424b71957/setup.py#L6

https://www.python.org/dev/peps/pep-0632/

**Comment by ocefpaf** [comment]
I'm pretty sure that can be removed if we implement #1207

**Comment by ocefpaf** [comment]
While we can use the vendored `Distribution` class from `setuptools`, this is used in:

https://github.com/Unidata/netcdf4-python/blob/8f7a365555013dcbb002462215665ca424b71957/setup.py#L526-L534

and that works only for numpy, querying the package is, in a way, still broken without `hdf5`, etc.
Ideally we should factor all that out of the `setup.py`.
