### ISSUE TITLE
pyproject.toml file?

### ISSUE THREAD

**Issue by snowman2** [Unidata/netcdf4-python#1207]
I saw this recently:
```
DEPRECATION: netcdf4 is being installed using the legacy 'setup.py install' method, because the '--no-binary' option was enabled for it and this currently disables local wheel building for projects that don't have a 'pyproject.toml' file. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/11451
```
Is there interest in adding a simple pyproject.toml file?
https://github.com/pyproj4/pyproj/blob/main/pyproject.toml

**Comment by ocefpaf** [comment]
> Is there interest in adding a simple pyproject.toml file?

We could really use one! Even with just the bare bones pep518numpy and cython build deps. Do you plan on working on that or should I?

**Comment by snowman2** [comment]
> Do you plan on working on that or should I?

Feel free to go ahead :rocket:
