### ISSUE TITLE
addition of pyproject.toml broke mpi parallel builds

### ISSUE THREAD

**Issue by jswhit** [Unidata/netcdf4-python#1211]
PR #1208 added pyproject.toml and removed the deprecated build_requires.  However, since mpi4py.get_include is used when building with MPI parallel support, and mpi4py cannot be included in pyproject.toml (since it has no wheels on pypi), this broke the mpi tests.  As a workaround, PR #1210 adds  --no-build-isolation to the pip install so that mpi4py can be imported by setup.py.

**Comment by ocefpaf** [comment]
Ouch! Sorry for not catching that. I'm not sure if there is a better solution, it seems that h5py does the same.
