### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: b'F:\\\xe5\x88\x9b\xe5\xbb\xba\xe6\x96\x87\xe4\xbb\xb6\\\\new.nc'

### ISSUE THREAD

**Issue by yqhhhh612** [Unidata/netcdf4-python#1220]
To report a non-security related issue, please provide:

Software: pycharm educational 2021, netCDF4 1.4.0
Computer system and compile: windows10, python3.9.6

When run scripts as follow:
'''
from netCDF4 import Dataset
import numpy as np
savepath = r'F:\创建文件\\'
nc_data = Dataset(savepath+'new.nc','w',format='NETCDF4')
x = np.arange(0,10,1)
a = np.zeros((10,10))
nc_data.createDimension('x',10)
nc_data.createVariable('data',np.float32,('x','x'))
nc_data.variables['data'][:] = a
nc_data.close()
'''
It's seems that error reporting when file path is not in English. Although it is no longer wrong after being changed to English, I hope it will be more flexible

**Comment by jswhit** [comment]
possibly related to https://github.com/Unidata/netcdf4-python/issues/997

**Comment by jswhit** [comment]
PR #1221 fixes the printing of the filename in the error message.  @yqhhhh612 can you confirm that upgrading netcdf4-python fixes the problem?  (you can use `pip install --upgrade netCDF4`)

**Comment by yqhhhh612** [comment]
I upgraded the netCDF4 version and the problem persists. The file path still cannot appear in Chinese or it will report an error.
