### ISSUE TITLE
pip install netcdf4=1.6.2 has netcdf-c=4.9.0 and not 4.9.1

### ISSUE THREAD

**Issue by nlenssen2013** [Unidata/netcdf4-python#1236]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue

Having issues creating string variable with string length greater than 1.
Issue seems to have been addressed in 4.9.1 version via ticket: https://github.com/Unidata/netcdf-c/pull/2467

Can't 

* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)

python version 3.8.0

* a description of the issue with the steps needed to reproduce it

If you have a general question about the software, please view our [Suggested Support Process](https://www.unidata.ucar.edu/support/#process).

**Comment by jswhit** [comment]
the 1.6.2 wheels were created before netcdf-c 4.9.1 was release.  The next netcdf4-python release will use 4.9.1.  I can create a new release fairly soon (next couple of weeks)

**Comment by nlenssen2013** [comment]
@jswhit got it, thanks

**Comment by jswhit** [comment]
1.6.3 is released - new wheels use netcdf-c 4.9.1
