### ISSUE TITLE
Two NetCDF format files, how to draw in the same coordinate system

### ISSUE THREAD

**Issue by wangshuaicumt** [Unidata/netcdf4-python#1238]
Two NetCDF format files, how to draw in the same coordinate system?

**Comment by jswhit** [comment]
huh?

**Comment by wangshuaicumt** [comment]
> huh?

Yeah, for example, I have two grd files, the format is NetCDF, I want to merge the two files

**Comment by jswhit** [comment]
https://docs.xarray.dev/en/latest/user-guide/io.html#combining-multiple-files (using xarray)

**Comment by wangshuaicumt** [comment]
> https://docs.xarray.dev/en/latest/user-guide/io.html#combining-multiple-files（使用xarray）
> 
> （xarray在引擎盖下使用netcdf4-python）

Year, thanks, I will try.

**Comment by davidhassell** [comment]
Hi - just to highlight `cf-python`, another option that uses netcdf4-python under the hood: https://ncas-cms.github.io/cf-python/tutorial.html#reading-field-constructs-from-datasets

**Comment by wangshuaicumt** [comment]
> https://ncas-cms.github.io/cf-python/tutorial.html#reading-field-constructs-from-datasets

Thanks, I merge the data, but I can draw a picture.

**Comment by wangshuaicumt** [comment]
> Glad it's useful! The cf-plot package is designed to plot cf-python fields: The gallery has lots of plotting cf-python field examples: http://ajheaps.github.io/cf-plot/gallery.html

<xarray.DataArray 'z' (lat: 4420, lon: 5060)>
[22365200 values with dtype=float32]
Coordinates:
  * lon      (lon) float64 88.22 88.22 88.22 88.22 ... 91.73 91.73 91.73 91.73
  * lat      (lat) float64 43.59 43.59 43.59 43.59 ... 45.43 45.43 45.43 45.43
Attributes:
    long_name:     z
    actual_range:  [-536.39135742  304.35101318]

<xarray.DataArray 'z' (lat: 1180, lon: 1910)>
[2253800 values with dtype=float32]
Coordinates:
  * lon      (lon) float64 116.2 116.2 116.2 116.2 ... 117.2 117.2 117.2 117.2
  * lat      (lat) float64 35.48 35.48 35.48 35.48 ... 35.97 35.97 35.97 35.97
Attributes:
    long_name:     z
    actual_range:  [-153.15245056  136.86753845]

This is the information I read from the original file

**Comment by wangshuaicumt** [comment]
> Glad it's useful! The cf-plot package is designed to plot cf-python fields: The gallery has lots of plotting cf-python field examples: http://ajheaps.github.io/cf-plot/gallery.html

This is the data information after my splicing, but I can not get the correct picture.

**Comment by wangshuaicumt** [comment]
> Ah - you used the wrong link in your [comment](https://github.com/Unidata/netcdf4-python/issues/1238#issuecomment-1455852651) :) I can hlpe with cf-python, but not with xarray issues, sorry.

Thanks, I am installing the cf library now

**Comment by wangshuaicumt** [comment]
> Ah - you used the wrong link in your [comment](https://github.com/Unidata/netcdf4-python/issues/1238#issuecomment-1455852651) :) I can hlpe with cf-python, but not with xarray issues, sorry.

I installed cf, but I can't realize splicing.
