### ISSUE TITLE
documentation of setting coordinates

### ISSUE THREAD

**Issue by jmccreight** [Unidata/netcdf4-python#1243]
It appears that the way to set a coordinate variable, e.g.
`data_var.coordinates = "y_coord x_coord"`
is not really documented in netcdf4. it would be helpful to add that to the docuementation.

**Comment by jswhit** [comment]
the coordinates attribute is a CF convention, so it doesn't seem to me that it should be part of the netcdf4-python docs.  If it's not clear how to set an attribute from the docs, then that should definitely be fixed - but it seems fairly well covered [here](http://unidata.github.io/netcdf4-python/#attributes-in-a-netcdf-file).

**Comment by jmccreight** [comment]
I'm just suggesting a simple reminder that coordinates are done by attributes, not a general explanation. I'd have remembered this more quickly if, say,
```
temp.coordinates = "longitudes latitudes times"
````
were inserted in the existing examples. The word coordinate(s) only appears 7(4) times in the documentation, it'd be helpful and quick to spot if it were added to this example.

**Comment by jmccreight** [comment]
feel free to close if you disagree
