### ISSUE TITLE
Incorrect value for `isopen` when using MFDataset

### ISSUE THREAD

**Issue by nikhil003** [Unidata/netcdf4-python#1244]
I noticed that when one uses `MFDataset`, the response of `isopen` method is incorrect. Looking in the source code, it appears that the method for `MFDataset` hasn't been defined, so it uses method defined on `Dataset` object.

```python
import netCDF4 as nc

fin = nc.MFDataset(
    ['./IDY25006.APS3.wind.10m.2019121112.009.surface.nc',
     './IDY25006.APS3.wind.10m.2019121112.010.surface.nc',])

print("Is file open: ", fin.isopen())
fin.close()
```

> Is file open:  False

Below is a sample implementation which can rectify this situation. Here, I have assumed that `MFDataset` can only be deemed open when all the underlying files are open.

```python
class MFDataset(nc.MFDataset):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def isopen(self):
        return all(map(lambda dset: dset.isopen(), self._cdf))

fin = MFDataset(
    ['./IDY25006.APS3.wind.10m.2019121112.009.surface.nc',
     './IDY25006.APS3.wind.10m.2019121112.010.surface.nc',])

print("Is file open: ", fin.isopen())

fin.close()
```
> Is file open:  True

[IDY25006.APS3.wind.10m.2019121112.0.zip](https://github.com/Unidata/netcdf4-python/files/11280079/IDY25006.APS3.wind.10m.2019121112.0.zip)

**Comment by jswhit** [comment]
thanks, that looks great.   Could you create a PR?
