### ISSUE TITLE
netCDF import not working

### ISSUE THREAD

**Issue by sbeale007** [Unidata/netcdf4-python#1248]
Hello,

I am trying to import netCDF4 on python but it is giving me an error like this:

ImportError: dlopen(/anaconda3/lib/python3.10/site-packages/netCDF4/_netCDF4.cpython-310-darwin.so, 2): Library not loaded: @loader_path/libzip.5.5.dylib
  Referenced from: /anaconda3/lib/python3.10/site-packages/netCDF4/.dylibs/libnetcdf.19.dylib
  Reason: no suitable image found.  Did find:
	/anaconda3/lib/python3.10/site-packages/netCDF4/.dylibs/libzip.5.5.dylib: cannot load 'libzip.5.5.dylib' (load command 0x80000034 is unknown)
	/anaconda3/lib/python3.10/site-packages/netCDF4/.dylibs/libzip.5.5.dylib: cannot load 'libzip.5.5.dylib' (load command 0x80000034 is unknown)

I have python 3.10 and used pip install netcdf4. This is my first time using netcdf so I am not familiar with any problems. Any suggestions would be very helpful. Thank you!

**Comment by dopplershift** [comment]
If you're using anaconda, you're likely to have much more success installing netcdf4 using conda. I'd try to fix by:
1. `pip uninstall netcdf4`
2. `conda install netcdf4`

**Comment by sbeale007** [comment]
I tried that and it worked! thank you very much
