### ISSUE TITLE
ModuleNotFoundError: No module named 'netCDF4._netCDF4'

### ISSUE THREAD

**Issue by SuthonFurI** [Unidata/netcdf4-python#1249]
Im trying to visualize a .nc file but this error appears.

```
from netCDF4 import Dataset
import numpy as np

data=Dataset(r'C:\Users\Admin\OneDrive\Documentos\python\download.nc','r')
print(data)
```
and as a response i get

> Traceback (most recent call last):
>   File "c:\Users\Admin\OneDrive\Documentos\python\extract.py", line 1, in <module>
>     from netCDF4 import Dataset
>   File "c:\Users\Admin\OneDrive\Documentos\python\netCDF4\__init__.py", line 3, in <module>
>     from ._netCDF4 import *
> ModuleNotFoundError: No module named 'netCDF4._netCDF4'

Does someone know why this might be?  ive already pip install netCDF4.

**Comment by jswhit** [comment]
Either your 'pip install netCDF4' did not succeed, or you are trying to import from a different python environment than you 'pip installed' in.
