### ISSUE TITLE
QUESTION: Writing large netCDF4 files using multiprocessing

### ISSUE THREAD

**Issue by Joueswant** [Unidata/netcdf4-python#1250]
Hi!

I am trying to store large data arrays (global files weighting ~ 150GB) in a single netCDF4. I do it from 36 regional files (kind of merging them).

The processes is the following:

1. Function generating the global files in write mode with dims, vars and metadata. New files are closed
2. Calling a multiprocessing.Pool where every worker loads the file in 'r+' mode and fills it from data from 1 of each 36 regionales files asynchronously 

The point is that multiprocessing is not working as expected and only 1 region out of 36 is filled at a time.

Is this an expected behaviour? How can I run multiprocessing to fill the file asynchronously?

Thanks a lot!

Python 3.9.9
netCDF4 1.6.0

**Comment by jswhit** [comment]
should work, as long as you are opening and writing to a different file on each sub-process.

**Comment by Joueswant** [comment]
Thanks a lot @jswhit, my goal is to write in the same file on each subprocess, is there a way to do so?
Thanks!

**Comment by jswhit** [comment]
No - but you could have each worker process write its results to its own  file, and have the main program merge them after all workers are finished.

Alternately, you could use the MPI interface to write to the same file from different MPI tasks (http://unidata.github.io/netcdf4-python/#parallel-io).

**Comment by Joueswant** [comment]
Thanks a lot @jswhit! I will double check the mpi4py module, I believe it matches my needs!
Best!
