### ISSUE TITLE
Cannot import name '__version__' from netCDF4._netCDF4

### ISSUE THREAD

**Issue by AgilentGCMS** [Unidata/netcdf4-python#1261]
I recently installed python 3.11.3 and then netcdf 4.9.2 (from source) on a linux machine. On top of that, I installed python-netcdf4 1.6.3 from source as well. Now, when I try to import netCDF4, I get this weird error that harkens back to [this issue](https://github.com/Unidata/netcdf4-python/issues/1075#issuecomment-770030129). That issue never got resolved, I gave up and did a `pip install` instead.
```
$ python3
Python 3.11.3 (main, May 31 2023, 20:11:46) [GCC Intel(R) C++ gcc 8.5 mode] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import netCDF4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nobackup/sbasu1/packages/python/3.11.3/lib/python3.11/site-packages/netCDF4-1.6.3-py3.11-linux-x86_64.egg/netCDF4/__init__.py", line 6, in <module>
ImportError: cannot import name '__version__' from 'netCDF4._netCDF4' (/home1/sbasu1/.cache/Python-Eggs/netCDF4-1.6.3-py3.11-linux-x86_64.egg-tmp/netCDF4/_netCDF4.cpython-311-x86_64-linux-gnu.so)
```
Now that this issue has reappeared, I would really like to solve it instead of giving up again.

**Comment by jswhit** [comment]
When you installed netcdf4-python from source did you use pip?  (if not, I would recommend doing that - the 'python setup.py install' method is deprecated)

**Comment by AgilentGCMS** [comment]
I did not, and when I did `pip install .` from the source tree, the resulting netCDF4 module did not give me the error I reported. So that's resolved, thanks!
