### ISSUE TITLE
Question about packaging plugins

### ISSUE THREAD

**Issue by opoplawski** [Unidata/netcdf4-python#1263]
I'm the packager for netcdf4-python in Fedora, and I have a question about dealing with netcdf plugins.  If I define NETCDF_PLUGIN_DIR=%{_libdir}/hdf5/plugin which is where the netcdf package installs the plugins, the netcdf4-python package copies these into the python package - which seems to me to be unnecessary duplication.  If I don't set this at build time though, will netcdf4-python still be able to make use of the plugins?   Thanks.

**Comment by jswhit** [comment]
yes, it will find them if you set the HDF5_PLUGIN_PATH env var at runtime.

**Comment by opoplawski** [comment]
Okay, thank.  I'll leave NETCDF_PLUGIN_DIR undefined then.
