### ISSUE TITLE
Support modifying datatype to an EnumTupe

### ISSUE THREAD

**Issue by bzah** [Unidata/netcdf4-python#1274]
netCDF4 version: 1.6.4
python version: 3.10

I have a variable which has a type u1 and represent a flag.
I would like to add a meaning to this flag variable by transforming its datatype into an EnumType.
Ideally, I would like to be able to modify the datatype the same way it can be changed from say, u1 to u2.

```py
"""[MRE] [feature request] Modify datatype to put a `nc.EnumType`."""

import netCDF4 as nc

# In real life, this dataset already exists with its variables
ds = nc.Dataset("./example.nc", "w")
ds.createDimension("time", 2)
my_var = ds.createVariable("my_var", "u1", "time")
my_var[:] = [1, 0]

# -- Now I want to add meaning to my_var
my_enum = ds.createEnumType("u1","my_enum",{"a":0, "b":1})
my_var.datatype = my_enum 
# --> error 
# TypeError: illegal data type for attribute b'datatype',
# must be one of dict_keys(['S1', 'i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f4', 'f8']), got O                                                                                                                   
```

Would this be possible ?

As a workaround, I could try to create a second variable properly typed by the enum and then copy the data and attributes of the first variable.
But then I can't delete the first variable with netCDF4, right ?

**Comment by jswhit** [comment]
This is not currently possible, nor do I see how it could be implemented since the netcdf-c API does not allow for deleting variables.

**Comment by bzah** [comment]
I understand, thanks.
