### ISSUE TITLE
Running into Attribute not found error when using underscore

### ISSUE THREAD

**Issue by odyvesp** [Unidata/netcdf4-python#1275]
Hello,
My app is using netCDF4 to read the header of a WRF output file. The error occurs when reading one the attributes defined with a name containing an underscore. The snippet reads:

```
import netCDF4 as nc
...
        self.dataset = nc.Dataset(out_file)
        self.tempus.start_date = self.dataset.START_DATE
        self.tempus.e_we = self.dataset.WEST-EAST_GRID_DIMENSION 
```
This reads the start date without any problem but it crashes when it tries to read WEST-EAST_GRID_DIMENSION with AttributeError: NetCDF: Attribute not found. Further details include:

```
File "src/netCDF4/_netCDF4/pyx", line 3120, in netCDF4._netCDF4.Dataset.__getattr__
File "src/netCDF4/_netCDF4/pyx", line 3065, in netCDF4._netCDF4.Dataset.getncattr
File "src/netCDF4/_netCDF4/pyx", line 1530, in netCDF4._netCDF4.__get_att
File "src/netCDF4/_netCDF4/pyx", line 2014, in netCDF4._netCDF4._ensure_nc_success
```
I've run into this issue a few times and it always happens when the name uses an underscore.
The O/S is Ubuntu 22 and python is the preinstalled version (3.10). 
Thanks.

**Comment by DennisHeimbigner** [comment]
If the file being read is an HDF5 file or netcdf-4 file, can you make it accessible to us?

**Comment by odyvesp** [comment]
I could make it public in an AWS S3 bucket. Would that work for you or do you have any suggestions? [Maybe renaming the file so that I can upload it to Github]

**Comment by akrherz** [comment]
The minus sign is special in python and most programming languages, so you need to use a helper.
```diff
- self.tempus.e_we = self.dataset.WEST-EAST_GRID_DIMENSION
+ self.tempus.e_we = self.dataset.getncattr("WEST-EAST_GRID_DIMENSION")
```

**Comment by odyvesp** [comment]
Thanks! (Don't know why I assumed that the issue was with the underscore, not the minus sign)
