### ISSUE TITLE
Wheel for Windows/Python 3.12

### ISSUE THREAD

**Issue by AndrewUshakov** [Unidata/netcdf4-python#1282]
Could you please build wheel for  Windows/Python 3.12 and deploy it to the pypi.org?

Thank you in advance.

**Comment by jswhit** [comment]
working on this - currently being help up by https://github.com/MacPython/netcdf4-python-wheels/issues/23

**Comment by jswhit** [comment]
3.12 wheels now available with 1.6.5 release on pypi
