### ISSUE TITLE
new in v1.6.5 "Package hdf5 was not found in the pkg-config search path"

### ISSUE THREAD

**Issue by craigstanton** [Unidata/netcdf4-python#1293]
I can't install v1.6.5 but 1.6.4 still works fine.

> python3 -m pip install netCDF4

` Collecting netCDF4
#8 9.445   Downloading netCDF4-1.6.5.tar.gz (764 kB)
#8 9.457      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 765.0/765.0 kB 77.6 MB/s eta 0:00:00
#8 9.502   Installing build dependencies: started
#8 14.74   Installing build dependencies: finished with status 'done'
#8 14.74   Getting requirements to build wheel: started
#8 14.88   Getting requirements to build wheel: finished with status 'error'
#8 14.89   error: subprocess-exited-with-error
#8 14.89   
#8 14.89   × Getting requirements to build wheel did not run successfully.
#8 14.89   │ exit code: 1
#8 14.89   ╰─> [37 lines of output]
#8 14.89       Package hdf5 was not found in the pkg-config search path.
#8 14.89       Perhaps you should add the directory containing `hdf5.pc'
#8 14.89       to the PKG_CONFIG_PATH environment variable
#8 14.89       No package 'hdf5' found
#8 14.89       reading from setup.cfg...
#8 14.89       
#8 14.89           HDF5_DIR environment variable not set, checking some standard locations ..
#8 14.89       checking /root/include ...
#8 14.89       hdf5 headers not found in /root/include
#8 14.89       checking /usr/local/include ...
#8 14.89       hdf5 headers not found in /usr/local/include
#8 14.89       checking /sw/include ...
#8 14.89       hdf5 headers not found in /sw/include
#8 14.89       checking /opt/include ...
#8 14.89       hdf5 headers not found in /opt/include
#8 14.89       checking /opt/local/include ...
#8 14.89       hdf5 headers not found in /opt/local/include
#8 14.89       checking /opt/homebrew/include ...
#8 14.89       hdf5 headers not found in /opt/homebrew/include
#8 14.89       checking /usr/include ...
#8 14.89       hdf5 headers not found in /usr/include
#8 14.89       Traceback (most recent call last):
#8 14.89         File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#8 14.89           main()
#8 14.89         File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#8 14.89           json_out['return_val'] = hook(**hook_input['kwargs'])
#8 14.89         File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
#8 14.89           return hook(config_settings)
#8 14.89         File "/tmp/pip-build-env-fdmlvosp/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
#8 14.89           return self._get_build_requires(config_settings, requirements=['wheel'])
#8 14.89         File "/tmp/pip-build-env-fdmlvosp/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
#8 14.89           self.run_setup()
#8 14.89         File "/tmp/pip-build-env-fdmlvosp/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
#8 14.89           exec(code, locals())
#8 14.89         File "<string>", line 457, in <module>
#8 14.89         File "<string>", line 398, in _populate_hdf5_info
#8 14.89       ValueError: did not find HDF5 headers
#8 14.89       [end of output]
#8 14.89   
#8 14.89   note: This error originates from a subprocess, and is likely not a problem with pip.
#8 14.89 error: subprocess-exited-with-error`

**Comment by jswhit** [comment]
Python 3.7 wheels are no longer supported - you'll have to keep using 1.6.4 or upgrade python to get 1.6.5.
