### ISSUE TITLE
ValueError using netCDF4 v1.6.5 with Python 3.9 and numpy v1.20.3

### ISSUE THREAD

**Issue by lidemjan** [Unidata/netcdf4-python#1294]
Hello,

I am facing a problem using netCDF4 v1.6.5 with Python 3.9 and numpy v1.20.3.
I installed netCDF4 using pip install on Anaconda Prompt. 
I work on Windows and use Spyder Anaconda3 to run my scripts.

I obtain the following error :
  File "****", line 11, in <module>
    from netCDF4 import Dataset

  File "C:\ProgramData\Anaconda3\lib\site-packages\netCDF4\__init__.py", line 31, in <module>
    from ._netCDF4 import *

  File "src\\netCDF4\\_netCDF4.pyx", line 1, in init netCDF4._netCDF4

ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 232 from C header, got 216 from PyObject

Maybe a specific version of numpy should be used in order to avoid this error ?

Thanks in advance for your help.

Libuse

**Comment by ocefpaf** [comment]
This is an incompatibility between numpy and the other binaries that are built with it. It is hard to debug without your conda environment issue but this is not a problem with netCDF4-python. It is most likely a problem with your installation.
