### ISSUE TITLE
Add static type hints

### ISSUE THREAD

**Issue by headtr1ck** [Unidata/netcdf4-python#1298]
Since static typing has come a long way in python, it would be nice if you could add static type hints to netCDF4.

There has already been some work done here: https://github.com/python/typeshed/issues/9545

If you think that this support should be carried out externally (like in the linked typeshed issue), feel free to close this issue.

**Comment by jswhit** [comment]
there was some work done on this (https://github.com/Unidata/netcdf4-python/pull/1279), but the OP closed the pull request.

**Comment by RandallPittmanOrSt** [comment]
Hey, @headtr1ck, @jswhit, @Woefie, high five on getting the type stubs into 1.7.2! (ref #1279, #1302, and #1349)! Thanks especially to Lars and Michael for your initial work and Jeff and Michael for your meticulous reviews of my PR. It's been a pleasure to work with you on this.
