### ISSUE TITLE
Indexing a vlen variable produces inconsistent results

### ISSUE THREAD

**Issue by 5tefan** [Unidata/netcdf4-python#1306]
## Summary

Indexing a vlen variable produces inconsistent results:

```python
import netCDF4 as nc
import numpy as np

nc_out = nc.Dataset("ex.nc", "w", diskless=True, persist=False)
t = nc_out.createDimension("t", None)
v = nc_out.createVariable("s", str, ("t",))

v[0] = "aaa"
v[1] = "bbb"
v[2] = "ccc"
v[3] = "ddd"

print("1. ", v[:])
print("2. ", v[np.arange(4)])
print("3. ", v[np.array([0, 1, 2])])
print("4. ", v[np.array([0, 3, 2])])
```

Produces the following output:

```
1.  ['aaa' 'bbb' 'ccc' 'ddd']
2.  ['aaa' 'bbb' 'ccc' 'ddd']
3.  ['aaa' 'bbb' 'ccc']
4.  [array('aaa', dtype=object) array('ddd', dtype=object)
 array('ccc', dtype=object)]
```

The result of number 4 is surprising and seems to be a bug. Items 1, 2, and 3 show expected behavior. The issue occurs when indexing out of order.

## Versions

1. MacOS Ventura 13.6.3 Intel based
1. Reproduced with Python v3.10.13 and 3.8.10.
2. netcdf4 Python versions 1.6.5 and 1.5.7

**Comment by jswhit** [comment]
closed by PR #1309
