### ISSUE TITLE
wheels not published to pypi, aarch64 missing

### ISSUE THREAD

**Issue by jswhit** [Unidata/netcdf4-python#1328]
Not sure why the wheels were not published to pypi (see https://github.com/Unidata/netcdf4-python/actions/runs/9506104839/workflow).

aarch64 is commented out in the workflow - can this be enabled? (we have been providing aarch64 wheels with multibuild)

@ocefpaf

**Comment by ocefpaf** [comment]
I commented it out during testing iteration, b/c it was super slow, and forgot to put is back. Trying it now in https://github.com/Unidata/netcdf4-python/pull/1333

**Comment by ocefpaf** [comment]
Regarding the wheels, someone with PyPI admin access must set the token up. Or maybe you may want to try a new way for this with https://docs.pypi.org/trusted-publishers/. Apologies that I forgot to mentioned that before.

BTW, if you choose the former, the process should be similar to what happened in cftime. We need to create the PYPI token, and then add it as a GH secret in this repo, with the same names [used here](https://github.com/Unidata/netcdf4-python/blob/1bae39c0ecfb80410c88202d9e38bdcdebd87a63/.github/workflows/cibuildwheel.yml#L194).

**Comment by dopplershift** [comment]
Would wholly recommend using the trusted publisher stuff. Was easy to set up and have had no issues on MetPy.

**Comment by ocefpaf** [comment]
> Would wholly recommend using the trusted publisher stuff. Was easy to set up and have had no issues on MetPy.

It is safer too BTW.
