### ISSUE TITLE
netcdf4-1.7.0.tar.gz on PyPI is missing source files

### ISSUE THREAD

**Issue by cgohlke** [Unidata/netcdf4-python#1329]
The latest source distribution on PyPI, [`netcdf4-1.7.0.tar.gz`](https://pypi.org/project/netCDF4/1.7.0/#files), is missing some source code files:

- `include/netcdf-compat.h`
- `include/parallel_support_imports.pxi.in`
- `include/no_parallel_support_imports.pxi.in`
- `external/nc_complex/*`

**Comment by ocefpaf** [comment]
Indeed. Please see https://github.com/Unidata/netcdf4-python/issues/1331#issuecomment-2167315084.

**Comment by aaraney** [comment]
I don't think the missing files in `include` are related to #1331. These just need to be added to the `MANIFEST.in` file.

```
include/netcdf-compat.h
include/parallel_support_imports.pxi.in
include/no_parallel_support_imports.pxi.in
```

**Comment by ocefpaf** [comment]
Indeed, those 3 are not part of the `nc_complex`. I'll address those tomorrow morning.

**Comment by aaraney** [comment]
@ocefpaf, no worries! I just opened https://github.com/Unidata/netcdf4-python/pull/1336 to add them!

**Comment by mgorny** [comment]
Thanks. I can confirm that 1.7.1 looks good.
