### ISSUE TITLE
PIP install decode in a Python 3.8.7 venv - netcdf4-1.7.1 results in subprocess-exited-with-error (ValueError: did not find HDF5 headers)

### ISSUE THREAD

**Issue by Cladge** [Unidata/netcdf4-python#1341]
* Software versions:
    * netcdf4-1.7.1
* Environmental information:
    * Windows 11
    * Python 3.8.7 (venv)
    * pip 24.0 (venv)
    * pip-tools 7.4.1 (venv)
    * setuptools 49.2.1 (venv)
* Description of the issue:
    1. Use Python 3.8.7 to create a fresh Python 3.8.7 venv (virtual environment).
    2. Activate the venv.
    3. Upgrade pip (venv):
    ```shell
    (venv) $ python -m pip install --upgrade pip
    ``` 
    4. Install pip-tools (venv):
    ```shell
    (venv) $ pip install pip-tools
    ``` 
    5. Install decode (venv):
    ```shell
    (venv) $ pip install decode
    ``` 
    6. Tries to install build dependencies using netcdf4-1.7.1.tar.gz but exits with errors:
        * "error: subprocess-exited-with-error"
        * "ValueError: did not find HDF5 headers"
    7. See: [pip-install-decode-error.txt](https://github.com/user-attachments/files/15917922/pip-install-decode-error.txt) for the complete output log.

**Comment by ocefpaf** [comment]
You will have to provide the dependencies, hdf5 and netcdf-c, plus a compiler to build it from source. Or you will need to upgrade to Python 3.9 b/c there are no wheels for Python 3.8. I don't recall why we did not build wheels for 3.8, probably some incompatibility with numpy, but I can check tomorrow. Regardless, upgrading to Python>3.8 is probably easier.

**Comment by Cladge** [comment]
Thanks @ocefpaf.
Actually, I think the issue might lie with the decode library. I looked at it again on [pypi - decode](https://pypi.org/project/decode) and they only support Python >= 3.9! So, yes, you are correct - upgrading to Python>3.8 is probably easier!

**Comment by ocefpaf** [comment]
Great! Closing this one as solved then. Please reopen if you disagree.
