### ISSUE TITLE
NetCdf4==1.7.1 Mac Arm ImportError: symbol not found in flat namespace '_H5get_libversion'

### ISSUE THREAD

**Issue by lukegehring99** [Unidata/netcdf4-python#1345]
I created a new conda environment with netcdf4 version 1.7.1 and am getting the following error when trying to use netcdf4:

```
File ~/anaconda3/envs/weather2/lib/python3.10/site-packages/netCDF4/__init__.py:3
      1 # init for netCDF4. package
      2 # Docstring comes from extension module _netCDF4.
----> 3 from ._netCDF4 import *
      4 # Need explicit imports for names beginning with underscores
      5 from ._netCDF4 import __doc__

ImportError: dlopen(/Users/luke/anaconda3/envs/weather2/lib/python3.10/site-packages/netCDF4/_netCDF4.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_H5get_libversion'
```

This error is from a conda environment running python 3.10 on a Mac M2 chip. 

[This issue](https://github.com/Unidata/netcdf4-python/issues/1148) had the same error listed, but cloning the repo and building locally did not resolve the issue. 

NetCdf4 version 1.6.5 does not produce this error.

**Comment by ocefpaf** [comment]
@lukegehring99 are you using the conda package or the one from PyPI? It seems you are installing it in an anaconda distribution and that can ve quite troublesome! Please start a fresh env and try:

```
conda create --name TEST netcdf4  # add here more packages that you may need for this task
conda activate TEST
# try to import it
```

**Comment by lukegehring99** [comment]
Yes, I was using PyPI to install netcdf4. Installing using conda resolved the issue for me. Thanks @ocefpaf for the help!

For anyone else that runs into this issue: I had to add the `conda-forge` channel to conda to get version 1.7.1
```
conda config --append channels conda-forge
```
