### ISSUE TITLE
Expose nc_rc_set

### ISSUE THREAD

**Issue by magnusuMET** [Unidata/netcdf4-python#1347]
* python-netcdf 1.6.5-2
* netcdf 4.9.2
* Arch Linux, python 3.12.3
* Can't call `nc_rc_set` to set custom configuration

In newer versions of `netCDF` one is required to explicitly set a path to e.g. `.netrc`, see https://github.com/Unidata/netcdf-c/issues/1966. I can't seem to find a way to call this function from python as this function is not exposed.

**Comment by jswhit** [comment]
PR #1347 exposes `nc_rc_set` (via `rc_set`) and `nc_rc_get` (via `rc_get`).

For some reason, `rc_get` triggers a segfault (crashing the interpreter) if you ask for a non-existent key.

**Comment by jswhit** [comment]
@magnusuMET would you be able to test PR #1348 to see if it resolves your issue?

**Comment by magnusuMET** [comment]
As far as I can tell this sets the key appropriately. I am seeing an issue where the key is not used by netcdf-c, but I think that is an unrelated issue

**Comment by jswhit** [comment]
closed by PR #1348
