### ISSUE TITLE
Rebuild the Windows wheel?

### ISSUE THREAD

**Issue by njzjz** [Unidata/netcdf4-python#1358]
We [found](https://github.com/materialsproject/pymatgen/pull/3894#issuecomment-2271088209) there is an import issue in netcdf4-python on the Windows platform due to https://github.com/adang1345/delvewheel/issues/51. This bug was [fixed](https://github.com/adang1345/delvewheel/commit/79b08910ad90ae4fc12bd37496abf744f374e870) in delvewheel 1.7.4, but we still need a new Windows wheel from netcdf4 to fix this error.

**Comment by jswhit** [comment]
[Done](https://pypi.org/project/netCDF4/#files)
