### ISSUE TITLE
Wrong type hint for `createEnumType`

### ISSUE THREAD

**Issue by headtr1ck** [Unidata/netcdf4-python#1378]
It seems that `createEnumType` is wrongly typed as:
```python
def createEnumType(
    self,
    datatype: np.dtype[np.integer] | type[np.integer] | type[int],
    datatype_name: str,
    enum_dict: Mapping[str, int | np.integer],
) -> EnumType: ...
```
But e.g. `datatype="u1"` is also supported.

* the version of the software with which you are encountering an issue: netCDF4==1.7.2
* environmental information (i.e. Operating System, compiler info, java version, python version, etc.): Win10 / python 3.12
* a description of the issue with the steps needed to reproduce it:
downstream issue:
https://github.com/pydata/xarray/issues/9624

problematic lines (roughly):
```python
with nc4.Dataset(tmp_file, mode="w") as nc:
    nc.createEnumType("u1", "cloud_type", {"clear": 0, "cloudy": 1})
```

**Comment by jswhit** [comment]
so what's the suggested fix?

**Comment by jswhit** [comment]
@RandallPittmanOrSt

**Comment by RandallPittmanOrSt** [comment]
Good catch. I think the most expedient fix is to just add `str` to the union for `datatype` and rely on the runtime (`_def_enum()` ) to ensure that it's an integer type. So the signature is just 

```python
def createEnumType(
    self,
    datatype: np.dtype[np.integer] | type[np.integer] | type[int] | str,
    datatype_name: str,
    enum_dict: Mapping[str, int | np.integer],
) -> EnumType: ...
```

Looks like we got this right on `EnumType.__init__()` so it was an oversight here.

I don't think adding a `Literal` would be helpful here (especially based on our discussion [here](https://github.com/Unidata/netcdf4-python/pull/1349#discussion_r1807935057))
