### ISSUE TITLE
Please add option to disable setting runtime_library_dirs

### ISSUE THREAD

**Issue by dopplershift** [Unidata/netcdf4-python#138]
_From [or...@cora.nwra.com](https://code.google.com/u/112866468608817563417/) on September 12, 2012 15:45:44_

In the processes of packaging netcdf4-python for Fedora, it was necessary to remove setting runtime_library_dirs as setting the rpath in forbidden in Fedora:

--- netCDF4-1.0/setup.py.norpath        2012-05-12 08:04:26.000000000 -0600
+++ netCDF4-1.0/setup.py        2012-05-23 16:38:16.376417441 -0600
@@ -163,7 +163,7 @@ NETCDF4_DIR environment variable not set
         lib_dirs.append(szip_libdir)
         inc_dirs.append(szip_incdir)

-extensions = [Extension("netCDF4",["netCDF4.c"],libraries=libs,library_dirs=lib_dirs,include_dirs=inc_dirs,runtime_library_dirs=lib_dirs)]
+extensions = [Extension("netCDF4",["netCDF4.c"],libraries=libs,library_dirs=lib_dirs,include_dirs=inc_dirs)]

 setup(name = "netCDF4",
   version = "1.0",

It would be helpful if there was an option to disable this, or perhaps just not set it if lib_dirs consists of /usr/lib, /usr/lib64 only.

_Original issue: http://code.google.com/p/netcdf4-python/issues/detail?id=138_

**Comment by opoplawski** [comment]
I don't see any evidence that this was fixed.  We still need to remove runtime_library_dirs in Fedora or we get:
```
+ /usr/lib/rpm/check-rpaths
*******************************************************************************
*
* WARNING: 'check-rpaths' detected a broken RPATH OR RUNPATH and will cause
*          'rpmbuild' to fail. To ignore these errors, you can set the
*          '$QA_RPATHS' environment variable which is a bitmask allowing the
*          values below. The current value of QA_RPATHS is 0x0000.
*
*    0x0001 ... standard RPATHs (e.g. /usr/lib); such RPATHs are a minor
*               issue but are introducing redundant searchpaths without
*               providing a benefit. They can also cause errors in multilib
*               environments.
*    0x0002 ... invalid RPATHs; these are RPATHs which are neither absolute
*               nor relative filenames and can therefore be a SECURITY risk
*    0x0004 ... insecure RPATHs; these are relative RPATHs which are a
*               SECURITY risk
*    0x0008 ... the special '$ORIGIN' RPATHs are appearing after other
*               RPATHs; this is just a minor issue but usually unwanted
*    0x0010 ... the RPATH is empty; there is no reason for such RPATHs
*               and they cause unneeded work while loading libraries
*    0x0020 ... an RPATH references '..' of an absolute path; this will break
*               the functionality when the path before '..' is a symlink
*          
*
* Examples:
* - to ignore standard and empty RPATHs, execute 'rpmbuild' like
*   $ QA_RPATHS=$(( 0x0001|0x0010 )) rpmbuild my-package.src.rpm
* - to check existing files, set $RPM_BUILD_ROOT and execute check-rpaths like
*   $ RPM_BUILD_ROOT=<top-dir> /usr/lib/rpm/check-rpaths
*  
*******************************************************************************
ERROR   0001: file '/usr/lib64/python3.11/site-packages/netCDF4/_netCDF4.cpython-311-s390x-linux-gnu.so' contains a standard runpath '/usr/lib64' in [/usr/lib64]
```
