### ISSUE TITLE
Access to the metadata without reading the whole netCDF file

### ISSUE THREAD

**Issue by dopplershift** [Unidata/netcdf4-python#162]
_From [k.hosseinizad](https://code.google.com/u/k.hosseinizad/) on February 19, 2013 07:11:45_

What steps will reproduce the problem? 1. reading the netCDF file What version of the product are you using? On what operating system? version: 0.9.9   linux Please provide any additional information below. I create some netCDF4 files, each 2GB or so. When I want to access to the data, I do not want to load the whole file in my memory. I just want to access to some parts of the file (like metadata) and then choose those groups that I need. Is there anyway to do so? This makes the whole procedure much faster and more feasible.

Thank you very much in advance for your time and kind attention to my request.

Best,
Kasra

_Original issue: http://code.google.com/p/netcdf4-python/issues/detail?id=162_

**Comment by AndyLuckert** [comment]
Could you please describe how you exactly access the metadata, please?
