### ISSUE TITLE
Dataset.renameVariable method doesn't appear to work properly

### ISSUE THREAD

**Issue by dopplershift** [Unidata/netcdf4-python#17]
_From [Michael.Cayanan@gmail.com](https://code.google.com/u/Michael.Cayanan@gmail.com/) on May 18, 2009 10:34:16_

What steps will reproduce the problem? 1. root = Dataset('a netcdf file', 'r+')
2. root.renameVariable('old name', 'new name') 3. What is the expected output? What do you see instead? I expected the statement in (2) to rename the variable in the netcdf file.
Instead I get an error:

Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "netCDF4.pyx", line 1172, in netCDF4.Dataset.renameVariable
(netCDF4.c:5213)
RuntimeError: NetCDF4: Operation not allowed in data mode What version of the product are you using? On what operating system? I'm using version 0.8 of the product on a Mac OS X 10.4.11 operating system. Please provide any additional information below. I made sure the netcdf file I was opening had its permission settings set
to read/write. I also tried using the 'a' flag instead of the 'r+' flag to
open the data file.

_Original issue: http://code.google.com/p/netcdf4-python/issues/detail?id=17_

**Comment by lovecanmovemountain** [comment]
Thanks for this answer Jeff I encounter the same error message and your comment helped me to fix it.
Babette
