### ISSUE TITLE
sudo python first time before creating files

### ISSUE THREAD

**Issue by dopplershift** [Unidata/netcdf4-python#208]
_From [john.m.m...@gmail.com](https://code.google.com/u/102853524899024036242/) on November 19, 2013 07:47:35_

What steps will reproduce the problem? 1.  If I try the following for the first time:
temp = Dataset('/home/somename/temp.nc','w')
I get a permission denied.
2.  If I try again in a sudoed interpreter it works
3.  Now I can create files normally in not sudoed interpreter What is the expected output? What do you see instead? if I try again using format='NETCDF4' I have to repeat What version of the product are you using? On what operating system? Debian 7, Python 2.7.3

_Original issue: http://code.google.com/p/netcdf4-python/issues/detail?id=208_

**Comment by nicolaisi** [comment]
How did you solve this, seems like I'm bumping into the same problem
