### ISSUE TITLE
Leap seconds not handled

### ISSUE THREAD

**Issue by neothemachine** [Unidata/netcdf4-python#280]
```python
import netcdftime
tunits = 'seconds since 1970-01-01 00:00:00'
calendar = 'gregorian'

dleap = netcdftime.datetime(2012,6,30,23,59,60)
print netcdftime.date2num(dleap, tunits, calendar)
# 1341100800.0

d2 = netcdftime.datetime(2012,7,1,0,0,0)
print netcdftime.date2num(d2, tunits, calendar)
# 1341100800.0

print netcdftime.num2date(1341100800.0, tunits, calendar)
# datetime.datetime(2012, 7, 1, 0, 0)

import datetime
def unix(dt):
    return (dt - datetime(1970, 1, 1)).total_seconds()
print unix(datetime.datetime(2012,7,1,0,0,0))
# 1341100800.0
```

Clearly `(2012,6,30,23,59,60)` and `(2012,7,1,0,0,0)` should lead to different results. To me it looks like leap seconds are not handled at all.

Is this a fundamental problem of the definition of the units attribute (as the documentation doesn't state what happens to leap seconds) or is it an implementation problem? It looks like it's doing the same as unix time where a leap second timestamp is ambiguous: 1341100800 can refer to the leap second or the second after it. But that is not really a nice property to have for scientific data. Right?

EDIT: See e.g. http://cdf.gsfc.nasa.gov/html/leapseconds_requirements.html and http://cdf.gsfc.nasa.gov/html/leapseconds.html

**Comment by jswhit** [comment]
I think that unless python datetime supports leap seconds, supporting it in netcdf4-python is not feasible.  Closing
