### ISSUE TITLE
netCDF4 is installed but not possible to import it

### ISSUE THREAD

**Issue by kasra-hosseini** [Unidata/netcdf4-python#286]
Hi,

I have installed netCDF4 by using:
pip install netCDF4
and it seems that it went through.

However, when I want to import it:
----> 1 import netCDF4

ImportError: /usr/lib/x86_64-linux-gnu/libk5crypto.so.3: symbol krb5int_buf_len, version krb5support_0_MIT not defined in file libkrb5support.so.0 with link time reference

Any suggestions?

Thanks in advance for your time.

All best,
Kasra

**Comment by birdage** [comment]
check that you have the hdf5 binaries installed...
