### ISSUE TITLE
VLEN string write out 

### ISSUE THREAD

**Issue by nberg14** [Unidata/netcdf4-python#324]
I have struggled with simply outputting an array of strings using this module.  Below is a sample script of what I would like to accomplish.  I have tried to cast the elements to be numpy objects, but the error message persists.  Could you provide guidance on how to modify this code and successfully write out strings into netCDF files?

Many thanks in advance.

>>> import netCDF4
>>> import numpy as np

>>> time_stamps = np.array(['2001-01-01', '2001-01-02', '2001-01-03'], 'S10')

>>> fileout = netCDF4.Dataset('./tmp_str.nc', 'w')
>>> fileout.createDimension('time', 4)
>>> strvar = filename_out.createVariable('strvar', str, 'time')
>>> strvar[:] = time_stamps
>>> fileout.close()

TypeError: only numpy object arrays can be assigned to VLEN str var slices

**Comment by shoyer** [comment]
If you have access to a newer version of netCDF4, this example will work (well, with a few typos fixed). On your current version, try:

```python
import netCDF4
import numpy as np

time_stamps = np.array(['2001-01-01', '2001-01-02', '2001-01-03'], dtype=object)

fileout = netCDF4.Dataset('./tmp_str.nc', 'w')
fileout.createDimension('time', 3)
strvar = fileout.createVariable('strvar', str, 'time')
strvar[:] = time_stamps
fileout.close()
```

**Comment by nberg14** [comment]
That works!  Sorry about the typos...was coding off the cuff there.  I'll look into updating my netCDF4 version as well.  Thanks so much.
