### ISSUE TITLE
indexing very very slow since  v1.1.2

### ISSUE THREAD

**Issue by s-hahn** [Unidata/netcdf4-python#325]
In the changelog it has been mentioned that

* indexing netCDF variables with integer sequences and boolean arrays now
behave the same way (integer sequences are converted to boolean arrays
internally). Addresses issue #300. 

I've tested indexing the same data with v1.1.1 and v1.1.2 (about 220000 elements) with very scattered int indices (e.g. 2000, 2300, 10002, 100000, .. overall 150 indices) and the performance difference is really shocking.

**Comment by jswhit** [comment]
Would you mind posting a code snippet with timing results?

**Comment by s-hahn** [comment]
This test shows that v1.1.1 is faster about 130 times. 

np.unique is actually only needed for v1.1.2, which requires sorted indicies without duplicates.

netCDF4 version: 1.1.2
write function took 4704.421 ms
read function took 12191.375 ms

netCDF4 version: 1.1.1
write function took 5326.627 ms
read function took 89.266 ms

```python
import time
import netCDF4
import numpy as np

def timing(f):
    """
    Wrapper for function run-time.
    """
    def wrap(*args):
        time1 = time.time()
        ret = f(*args)
        time2 = time.time()
        print('%s function took %0.3f ms' %
              (f.func_name, (time2 - time1) * 1000.0))
        return ret
    return wrap


@timing
def write(fn, var1):
    with netCDF4.Dataset(fn, mode='w') as nc:
        nc.createDimension('dim1')
        nc_var1 = nc.createVariable('var1', var1.dtype,
                                    dimensions=('dim1'))
        nc_var1[:] = var1


@timing
def read(fn, s):
    subset = np.unique((np.random.randint(0, s, 2000)))
    with netCDF4.Dataset(fn, mode='r') as nc:
        x = nc.variables['var1'][subset]
    return x

print("netCDF4 version: {:}".format(netCDF4.__version__))
fn = 'test.nc'
var1 = np.arange(500000)
write(fn, var1)
read(fn, var1.size)
```

**Comment by jswhit** [comment]
The slowness comes from the block of code in netCDF4_utils.py (around line 246) that tries to convert the indices to a slice object.  If that code is bypassed, there is no difference in speed between 1.1.1 and 1.1.2.

**Comment by jswhit** [comment]
Pull request #326 fixes this by not trying to convert boolean indices to slices except for the very simplest case (all elements in the range are True).

**Comment by jswhit** [comment]
@shoyer , I like your solution much better.
