### ISSUE TITLE
workaround for IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by wingkitlee** [Unidata/netcdf4-python#328]
Hi,

I have some old code that reads a= nc.Variables['something][0] for scalar variables. I believe it was due to inconsistency and was fixed in recent version. Now the same code gives

IndexError: invalid index to scalar variable.

So just curious how to read the scalar variables now? by nc.Variables['something'].getValue() ? Thanks

**Comment by shoyer** [comment]
`nc.Variables['something'][...]` and `nc.Variables['something'][()]` both work (these also work for indexing scalar variables with numpy).
