### ISSUE TITLE
Build failure on Ubuntu 14.10

### ISSUE THREAD

**Issue by timburgess** [Unidata/netcdf4-python#329]
I am getting a build failure on Ubuntu 14.10. I have built the library before from source but that was on prior Ubuntu versions. For the record:

Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
[GCC 4.9.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.9.1'
>>> import Cython
>>> Cython.__version__
'0.20.1'

I have netCDF4 4.3.2 and HDF5 built and installed to /usr/local

I have pulled the repo and checked out the 1.3.1 tag:
git clone git@github.com:Unidata/netcdf4-python.git
 cd netcdf4-python
 git tag -l
 git checkout v1.1.3rel

In the repo, I copy setup.cfg.template to setup.cfg and I have tried both uncommenting the <code>ncconfig</code> line and then the <code>netCDF4_dir</code> and <code>HDF5_dir</code>, setting both to /usr/local

The error I get is:
python setup.py build
reading from setup.cfg...
using netcdf library version 4.3.2
using Cython to compile netCDF4.pyx...
netcdf lib has group rename capability
netcdf lib has nc_inq_path function
netcdf lib has nc_inq_format_extended function
running build
running build_py
running build_ext
building 'netCDF4' extension
creating build/temp.linux-x86_64-2.7
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/include -I/usr/local/include -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c netCDF4.c -o build/temp.linux-x86_64-2.7/netCDF4.o
x86_64-linux-gnu-gcc: error: netCDF4.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 4

Doing a <code>git status</code>, I see that <code>netCDF4.c</code> has been deleted (??) and that <code>constants.pyx</code> has been modified.

**Comment by jswhit** [comment]
netCDF4.c is still there.  Notice "using Cython to compile netCDF4.pyx...".  The build attempted to re-create netCDF4.c from netCDF4.pyx, and apparently failed (producing an empty netCDF4.c).  Try running "cython netCDF4.pyx" on the command line and see what happens (there should be some sort of error message).

**Comment by timburgess** [comment]
Thanks Jeff. I built Cython 0.22 on the same Ubuntu machine and afterwards, <code>sudo python setup.py install</code> worked fine. I had 0.20.1 installed prior so something odd resolved by Cython upgrade.
