### ISSUE TITLE
Cannot create String variable with fill_value=False: HDF error

### ISSUE THREAD

**Issue by jdemaria** [Unidata/netcdf4-python#331]
Hi,

This simple code is broken using the latest versions of netCDF4-python (1.1.3), Python (2.7.9), numpy (1.9.1), netcdf-c (4.3.2) and hdf5 (1.8.14), on Debian GNU/Linux 5.0 x86_64:

d = nc.Dataset('bug_str.nc', 'w')
d.createVariable('var', np.str, (), fill_value=False)
d.close()

and the code works if I remove the fill_value arg
It works also if I use a previous version of the tools: netCDF4-python (1.0.5), numpy (1.6.1), and I don't know for other tools; it was also compiled on a 32 bits system.

Thanks in advance,

Julien

**Comment by jswhit** [comment]
See issue #333 (scalar vlen variables are not supported)

**Comment by jswhit** [comment]
This is actually not related to issue #333 (which is fixed by pull request #335).

**Comment by jswhit** [comment]
fill values are not supported for vlen or compound variables anyway.  In branch issue333 (pull request #335) I made fill_value=False a no-op for vlen and compound variables.  Setting the fill_value will still raise an error for vlen and compound.

**Comment by jswhit** [comment]
pull request #335 has been merged, so closing now...
