### ISSUE TITLE
Is it possible to make a copy of a netCDF variable without opening a new file?

### ISSUE THREAD

**Issue by qAp** [Unidata/netcdf4-python#332]
Hi,
Is there a way to make a copy of a netCDF4.Variable without having to open a new netCDF file for writing or appending?   

I only know how to do this by creating a new file:
http://nbviewer.ipython.org/gist/qAp/212122b92a881ef30216/Copying%20netCDF%20file%20variables.ipynb

I want to change the variable and use the changed variable for, say, plotting, so it does not need to be saved to disk.

**Comment by shoyer** [comment]
In memory variables aren't really within the scope of this package, which focuses on the details of reading files from disk. You should check out [Iris](http://scitools.org.uk/iris/) or [xray](http://xray.readthedocs.org) (my project) for in memory models of netCDF variables. Iris even has some nice integrated plotting routines (haven't gotten around to that for xray yet).

**Comment by qAp** [comment]
k, thanks
