### ISSUE TITLE
Bug in strings reading: only first character available

### ISSUE THREAD

**Issue by jdemaria** [Unidata/netcdf4-python#333]
Hi,

This simple code is broken using the latest versions of netCDF4-python (1.1.3), Python (2.7.9), numpy (1.9.1), netcdf-c (4.3.2) and hdf5 (1.8.14), on Debian GNU/Linux 5.0 x86_64.

import netCDF4 as nc
d = nc.Dataset('sample.nc', 'w')
teststring = d.createVariable('teststring', str)
teststring[()] = "yyyymmdd_hhmmss"
d.close()
d = nc.Dataset('sample.nc')
teststring = d.variables['teststring']
print "teststring value:"+teststring[:]
d.close()

Thanks in advance,
Julien

**Comment by jswhit** [comment]
scalar vlen variables are not supported.  We should either fix this or raise an error message.

You can use this workaround:

    x = d.createDimension('x',0)
    teststring = d.createVariable('teststring', str, 'x')
    teststring[0] = "yyyymmdd_hhmmss"

Just curious though - what is the use case for a scalar vlen string variable?  Why not just make it a Dataset attribute?

**Comment by jswhit** [comment]
pull request #335 forbids creation of scalar vlen vars (so your example will raise an error)
I'm investigation if scalar vlens are allowed in the C lib.

**Comment by jswhit** [comment]
Disregard my previous comment - I just noticed from ncdump that the data is written to the file correctly.  It must be a problem with reading vlen scalar variables.

**Comment by jswhit** [comment]
OK - got it sorted now.  Was a bug in reading the scalar vlen string.  Pull request #335 is now modified to fix the bug instead of disallowing scalar vlens.  Your example now works with branch issue333.

**Comment by jswhit** [comment]
pull request #335 has been merged, so closing now...
