### ISSUE TITLE
Reordering of 2D data dimensions when writing to file

### ISSUE THREAD

**Issue by thorsant** [Unidata/netcdf4-python#337]
I am creating a NC file using netCDF4 in python. The file is quite simple and includes variables of 1 and 2 dimensions (1st dim=num_shots, 2nd dim=num_records). But the problem is that when I read out the file, the dimensions of the 2D variables are interchanged, i.e. instead of coming out as data of dimension (num_shots, num_records), they come out as dimension (num_records, num_shots), while all 1D data comes out as (num_shots, ), as expected.

```python
root = nc.Dataset(filename, 'w', format='NETCDF4')
dimensions = ('num_shots', 'num_records')

root.createDimension(dimensions[0], None)
root.createDimension(dimensions[1], None)

for field in fields:
        field_def = ...<defintion of field, how many dimensions etc...>
        if field_def[0] == 1: # how many dimensions in this variable
            chunk_size = (200, )
        else:
            chunk_size = (200, 1)

        dim = tuple(dimensions[:field_def[0]])
        var = root.createVariable(field, field_def[3], dimensions=dim,
                                fill_value=0,   chunksizes=chunk_size)
```

When data is read from the file the 2D data is transposed, while the 1D data is kept unchanged. I am using netcdf4 version 1.1.1

**Comment by jswhit** [comment]
Your example does not actually write any data.  Could you post a complete example that we can run?

**Comment by thorsant** [comment]
The code is quite complex and not easy to give you all, but I can code an example which shows the problem. This is how the file is defined, I'll come up with an example which shows how the data is written

**Comment by thorsant** [comment]
Here is an example. But as this example will show you, the dimensions are correct when using the python implementation of netCDF4 for reading, but when I use the matlab implementation, netcdf (http://www.unidata.ucar.edu/software/netcdf/old_docs/docs_4_0_1/) the ordering of the dimensions for the 2D variables are opposite. When I use an nc file browser, e.g. ncBrowse, the dimensions are right, i.e. the same way as I read/write in python. When I generate files in matlab and later read them in matlab, things are correct (but when I open the matlab generated files in ncBrowse, the dimensions are opposite).

So, is it the Matlab implementation which is faulty? If I understand correctly both the pyhton and Matlab interface is based on the unidata C library? Is there a difference between netCDF 4.0.1 and 4.1-4.3?

A clue might be this (from the matlab netcdf.defVar documentation):
This function corresponds to the "nc_def_var" function in the netCDF
library C API, but because MATLAB uses FORTRAN-style ordering, the
the fastest-varying dimension comes first and the slowest comes
last. Any unlimited dimension is therefore last in the list of
dimension IDs. This ordering is the reverse of that found in the C
API.

But in my case both dimensions are unlimited. Then maybe I have to change the way I read/write in either Matlab and Python, to make the files from both languages compatible

```python
import netCDF4 as nc
import numpy as np
import os


def create_file(filename, field_defs, chunk_size, fill_value):

    root = nc.Dataset(filename, 'w', format='NETCDF4')

    dimensions = ('num_records', 'num_est')
    root.createDimension(dimensions[0], None)
    root.createDimension(dimensions[1], None)

    for field in field_defs.keys():
        print field
        field_def = field_defs[field]
        if field_def[0] == 1:
            _chunk_size = (chunk_size, )
        else:
            _chunk_size = (chunk_size, 1)

        dim = tuple(dimensions[:field_def[0]])
        var = root.createVariable(field, field_def[3], dimensions=dim,
                                fill_value=fill_value, chunksizes=_chunk_size)

        var.setncattr('standard_name', field)
        var.setncattr('long_name', field_def[2])
        var.setncattr('unit', field_def[1])
        var.setncattr('scale', field_def[4])
    root.close()

def open_file(filename, mode):
    return nc.Dataset(filename, mode)

def write_data(root, start, **kwargs):
    if root is None:
        raise AttributeError('Handler must be opened before any interaction can be done')

    # Get name of dimension which is the increasing one
    num_rec_dim = 'num_records'

    for field in kwargs.keys():
        value = kwargs[field]

        if value is None:
            continue

        # Get the nc variable for this field
        var = root.variables[field]

        # Find index of increasing dimension
        ix = var.dimensions.index(num_rec_dim)
        ndim = len(var.dimensions)

        if ix == 0:
            if ndim == 1:
                if value.ndim == 1:
                    var[start:(start+value.shape[0])] = value
                else:
                    raise ValueError('')
            else:
                dim1 = root.dimensions[var.dimensions[1]]
                if dim1.isunlimited() and value.ndim == 1:
                    var[start:(start+value.shape[0]), 0] = value
                elif dim1.isunlimited():
                    start_dim1 = len(dim1)
                    var[start:(start+value.shape[0]), start_dim1:(start_dim1+value.shape[1])] = value
                elif value.ndim == 2:
                    var[start:(start+value.shape[0]), 0:value.shape[1]] = value
                else:
                    raise ValueError('Incompatible dimensions for field ''%s'', input: %s file: %s '
                                                 % (field, value.shape, var.dimensions))
        else:
            var[:, start:start+value.shape[1]] = value

def read_data(filename, field):
    pass

if __name__ == '__main__':

    field_def = {'field1': (1, '', 'blablabla', np.uint8, 1),
                'field2': (1, '', 'blablabla', np.uint32, 1),
                'field3': (2, 'm', 'blablabla', np.uint16, 1e5)}
    chunk_size = 200
    fill_value = 0

    filename = 'test_dim_art.nc'

    create_file(filename, field_def, chunk_size, fill_value)

    root = open_file(filename, 'r+')

    data1 = np.random.random_integers(0, high=7, size=(234, ))
    data1 = data1.astype(np.uint8)

    data3 = np.random.random_integers(0, high=15000, size=(234, 2))
    data3 = data3.astype(np.uint16)

    write_data(root, 0, field1=data1, field3=data3)

    print 'After writing'
    for field in root.variables:
        var = root.variables[field]
        if var.ndim == 1:
            print 'Size %s (%d, )' % (field, var.shape[0])
        else:
            print 'Size %s (%d, %d)' % (field, var.shape[0], var.shape[1])

    root.close()

    root = open_file(filename, 'r')
    print 'After reading'
    for field in root.variables:
        var = root.variables[field]
        if var.ndim == 1:
            print 'Size %s (%d, )' % (field, var.shape[0])
        else:
            print 'Size %s (%d, %d)' % (field, var.shape[0], var.shape[1])
    root.close()
```
MatlabCode
```MATLAB
nc = netcdf.open('test_dim_art.nc');
[name, xtype, dimids] = netcdf.inqVar(nc, netcdf.inqVarID(nc, 'field3'));
netcdf.inqDim(nc, dimids(1))
netcdf.inqDim(nc, dimids(2))
```
Show 'num_est', 'num_records'.

**Comment by zerothi** [comment]
Matlab is fortran based (which swaps dimensions for obvious reasons)
whereas python is c-based.
column major vs. row major
They are both "correct" implementations, the behaviour is as expected.

2015-02-18 13:08 GMT+01:00 thorsant <notifications@github.com>:

> Here is an example. But as this example will show you, the dimensions are
> correct when using the python implementation of netCDF4 for reading, but
> when I use the matlab implementation, netcdf (
> http://www.unidata.ucar.edu/software/netcdf/old_docs/docs_4_0_1/) the
> ordering of the dimensions for the 2D variables are opposite. When I use an
> nc file browser, e.g. ncBrowse, the dimensions are right, i.e. the same way
> as I read/write in python. When I generate files in matlab and later read
> them in matlab, things are correct (but when I open the matlab generated
> files in ncBrowse, the dimensions are opposite).
>
> So, is it the Matlab implementation which is faulty? If I understand
> correctly both the pyhton and Matlab interface is based on the unidata C
> library? Is there a difference between netCDF 4.0.1 and 4.1-4.3?
>
> A clue might be this (from the matlab netcdf.defVar documentation):
> This function corresponds to the "nc_def_var" function in the netCDF
> library C API, but because MATLAB uses FORTRAN-style ordering, the
> the fastest-varying dimension comes first and the slowest comes
> last. Any unlimited dimension is therefore last in the list of
> dimension IDs. This ordering is the reverse of that found in the C
> API.
>
> But in my case both dimensions are unlimited. Then maybe I have to change
> the way I read/write in either Matlab and Python, to make the files from
> both languages compatible
>
> import netCDF4 as ncimport numpy as npimport os
>
> def create_file(filename, field_defs, chunk_size, fill_value):
>
>     root = nc.Dataset(filename, 'w', format='NETCDF4')
>
>     dimensions = ('num_records', 'num_est')
>     root.createDimension(dimensions[0], None)
>     root.createDimension(dimensions[1], None)
>
>     for field in field_defs.keys():
>         print field
>         field_def = field_defs[field]
>         if field_def[0] == 1:
>             _chunk_size = (chunk_size, )
>         else:
>             _chunk_size = (chunk_size, 1)
>
>         dim = tuple(dimensions[:field_def[0]])
>         var = root.createVariable(field, field_def[3], dimensions=dim,
>                                 fill_value=fill_value, chunksizes=_chunk_size)
>
>         var.setncattr('standard_name', field)
>         var.setncattr('long_name', field_def[2])
>         var.setncattr('unit', field_def[1])
>         var.setncattr('scale', field_def[4])
>     root.close()
> def open_file(filename, mode):
>     return nc.Dataset(filename, mode)
> def write_data(root, start, **kwargs):
>     if root is None:
>         raise AttributeError('Handler must be opened before any interaction can be done')
>
>     # Get name of dimension which is the increasing one
>     num_rec_dim = 'num_records'
>
>     for field in kwargs.keys():
>         value = kwargs[field]
>
>         if value is None:
>             continue
>
>         # Get the nc variable for this field
>         var = root.variables[field]
>
>         # Find index of increasing dimension
>         ix = var.dimensions.index(num_rec_dim)
>         ndim = len(var.dimensions)
>
>         if ix == 0:
>             if ndim == 1:
>                 if value.ndim == 1:
>                     var[start:(start+value.shape[0])] = value
>                 else:
>                     raise ValueError('')
>             else:
>                 dim1 = root.dimensions[var.dimensions[1]]
>                 if dim1.isunlimited() and value.ndim == 1:
>                     var[start:(start+value.shape[0]), 0] = value
>                 elif dim1.isunlimited():
>                     start_dim1 = len(dim1)
>                     var[start:(start+value.shape[0]), start_dim1:(start_dim1+value.shape[1])] = value
>                 elif value.ndim == 2:
>                     var[start:(start+value.shape[0]), 0:value.shape[1]] = value
>                 else:
>                     raise ValueError('Incompatible dimensions for field ''%s'', input: %s file: %s '
>                                                  % (field, value.shape, var.dimensions))
>         else:
>             var[:, start:start+value.shape[1]] = value
> def read_data(filename, field):
>     pass
> if __name__ == '__main__':
>
>     field_def = {'field1': (1, '', 'blablabla', np.uint8, 1),
>                 'field2': (1, '', 'blablabla', np.uint32, 1),
>                 'field3': (2, 'm', 'blablabla', np.uint16, 1e5)}
>     chunk_size = 200
>     fill_value = 0
>
>     filename = 'test_dim_art.nc'
>
>     create_file(filename, field_def, chunk_size, fill_value)
>
>     root = open_file(filename, 'r+')
>
>     data1 = np.random.random_integers(0, high=7, size=(234, ))
>     data1 = data1.astype(np.uint8)
>
>     data3 = np.random.random_integers(0, high=15000, size=(234, 2))
>     data3 = data3.astype(np.uint16)
>
>     write_data(root, 0, field1=data1, field3=data3)
>
>     print 'After writing'
>     for field in root.variables:
>         var = root.variables[field]
>         if var.ndim == 1:
>             print 'Size %s (%d, )' % (field, var.shape[0])
>         else:
>             print 'Size %s (%d, %d)' % (field, var.shape[0], var.shape[1])
>
>     root.close()
>
>     root = open_file(filename, 'r')
>     print 'After reading'
>     for field in root.variables:
>         var = root.variables[field]
>         if var.ndim == 1:
>             print 'Size %s (%d, )' % (field, var.shape[0])
>         else:
>             print 'Size %s (%d, %d)' % (field, var.shape[0], var.shape[1])
>     root.close()
>
> MatlabCode
>
> nc = netcdf.open('test_dim_art.nc');
> [name, xtype, dimids] = netcdf.inqVar(nc, netcdf.inqVarID(nc, 'field3'));
> netcdf.inqDim(nc, dimids(1))
> netcdf.inqDim(nc, dimids(2))
>
> Show 'num_est', 'num_records'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unidata/netcdf4-python/issues/337#issuecomment-74854150>
> .
>



-- 
Kind regards Nick

**Comment by thorsant** [comment]
But then one would have to be aware of what kind of system generated the file when reading the data, or have some idea about dimension order and reorder the data after reading it from the file. Having to transpose data after reading when data sets are large is not very efficient.

Anyone has any tips on how to implement this to make it smooth and efficient; I have files that are to be shared between Python and MATLAB and I want to keep a matrix the same shape in both systems without having to transpose matrices.

**Comment by mdecker** [comment]
This is why NetCDF stores metadata with your variables.
This will allow you to find the correct dimensions and their order without having to guess. Transposing the data or just adapting your loops to fit the variable shape should not be a big deal.

**Comment by zerothi** [comment]
Well, to handle the data most efficiently you would still need to handle
them transposed (numpy can do this with views, so it is practically free).

If I operate on matrix A(M,N) I would in fortran do A(M,N) whereas in
python I would do A(N,M). It depends on the situation and the importance,
nevertheless this is going to have to be the programmers choice.
And if you want the "same" data representation you need to swap the axis
when traversing the c->fortran barrier.
Now for linear algebra this is of course important to know what is row vs.
column major order.

It seems that you are doing python the "fortran" way:
var[:, start:start+value.shape[1]] = value
whereas you should swap the dimensions, to get C efficiency (of course this
is dependent how the data representation really is, but...)
Choose your dimensions according to the underlying programming layer.


2015-02-18 13:26 GMT+01:00 thorsant <notifications@github.com>:

> But then one would have to be aware of what kind of system generated the
> file when reading the data, or have some idea about dimension order and
> reorder the data after reading it from the file. Having to transpose data
> after reading when data sets are large is not very efficient.
>
> Anyone has any tips on how to implement this to make it smooth and
> efficient; I have files that are to be shared between Python and MATLAB and
> I want to keep a matrix the same shape in both systems without having to
> transpose matrices.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unidata/netcdf4-python/issues/337#issuecomment-74856087>
> .
>



-- 
Kind regards Nick

**Comment by thorsant** [comment]
Thanks for the tips.

We wrote the MATLAB code first and thus stuck with the matrix
dimensions/shape from this implementation, thats why we are doing it this
way. Other parts of the code assumes certain shape of the data for
calculations, linear algebra and such. It could be an idea to reorder the
dimensions in python since it is more efficient as you say.

Thanks again for the help and the discussion.
