### ISSUE TITLE
MFDataset: cannot access part of the variable

### ISSUE THREAD

**Issue by doncristobal** [Unidata/netcdf4-python#339]
I read two netCDF subsetted files (to my knowledge, netCDF3) from the web, one with longitudes -1..0 and one with longitudes 0..1. (The subset service does not seem to be able to send me this data in one file.) Then, I use MFDataset to combine them into one, by aggregating over the longitude dimension.
After aggregating, I can successfully print the shape of the lats/lons (dimension) variable from the aggregated dataset (which correctly shows the larger i.e. aggregated shape and lat/lons). 
However, I can only access my data variable (e.g. 'Total_cloud_cover_entire_atmosphere') partly: namely, I can only access the part of the variable referring to the first dataset. If I try to access part of the variable belonging to the second dataset, I get an IndexError:
```
  File "netCDF4.pyx", line 3015, in netCDF4.Variable.__getitem__ (netCDF4.c:41549)
  File "netCDF4.pyx", line 3653, in netCDF4.Variable._get (netCDF4.c:49443)
IndexError
```
The underlying model (GFS) encodes longitude -1 as 359. Maybe this is part of the problem, because it leads to the combined sequence lons: [ 359.   359.5    0.     0.5    1. ] ?

```
import urllib, sys, numpy as np
from netCDF4 import Dataset, MFDataset

FILENAME_DATASET_1 = "localGFSTCC.ncdf"
FILENAME_DATASET_2 = "localGFSTCC2.ncdf"

varNames = "Total_cloud_cover_entire_atmosphere"
# I have so far not been able to retrieve longitudes -1 .. +1. It just retrieves 0..+1.
# Main catalog page:  http://nomads.ncdc.noaa.gov/thredds/ncss/grid/gfs-004/201501/20150115/gfs_4_20150115_1200_006.grb2/dataset.html
urlBB1 = "http://nomads.ncdc.noaa.gov/thredds/ncss/grid/gfs-004/201501/20150115/gfs_4_20150115_1200_006.grb2?north=40.0&" \
        "south=38.0&west=359.0&east=360.0&var=%s" % varNames
urlBB2 = "http://nomads.ncdc.noaa.gov/thredds/ncss/grid/gfs-004/201501/20150115/gfs_4_20150115_1200_006.grb2?north=40.0&" \
        "south=38.0&west=0.0&east=1.0&var=%s" % varNames

testfile = urllib.URLopener()
testfile.retrieve (urlBB1, FILENAME_DATASET_1)
testfile.retrieve (urlBB2, FILENAME_DATASET_2)
data1 = Dataset (FILENAME_DATASET_1)
print "  File 1: lats: %s\nlons: %s" % (data1.variables["lat"][:], data1.variables["lon"][:],)
data2 = Dataset (FILENAME_DATASET_2)
print "  File 2: lats: %s\nlons: %s" % (data2.variables["lat"][:], data2.variables["lon"][:],)
print "Aggregating two files..."
combinedData = MFDataset ((FILENAME_DATASET_1, FILENAME_DATASET_2), check = True, aggdim = "lon")
# The following three statements works correctly, i.e. show aggregated data.
print "  Combined lats: %s\nlons: %s" % (combinedData.variables["lat"][:], combinedData.variables["lon"][:],)
print "  combinedData shape: %s" % (combinedData.variables["Total_cloud_cover_entire_atmosphere"].shape,)
# Accessing the part of the MFDataset which comes from dataset 1 works:
print "  Access 1:\n%s" % combinedData.variables["Total_cloud_cover_entire_atmosphere"] [0, 0:2, 0:2]
# Accessing the part of the MFDataset which comes from dataset 2 fails:
sys.stdout.flush()
print "  Access 2:\n %s" % combinedData.variables["Total_cloud_cover_entire_atmosphere"] [0, 2:3, 2:3]
# This also fails
print "  Access 3:\n %s" % combinedData.variables["Total_cloud_cover_entire_atmosphere"] [:, :, :]
```
Output:
```
  File 1: lats: [ 40.   39.5  39.   38.5  38. ]
lons: [ 359.   359.5]
  File 2: lats: [ 40.   39.5  39.   38.5  38. ]
lons: [ 0.   0.5  1. ]
Aggregating two files...
  Combined lats: [ 40.   39.5  39.   38.5  38. ]
lons: [ 359.   359.5    0.     0.5    1. ]
  combinedData shape: (1, 5, 5)
  Access 1:
[[13.0 0.0]
 [0.0 0.0]]
Traceback (most recent call last):
  File "~/testMFDatasets.py", line 44, in <module>
    print "  Access 2:\n %s" % combinedData.variables["Total_cloud_cover_entire_atmosphere"] [0, 2:3, 2:3]
  File "netCDF4.pyx", line 3015, in netCDF4.Variable.__getitem__ (netCDF4.c:41549)
  File "netCDF4.pyx", line 3653, in netCDF4.Variable._get (netCDF4.c:49443)
IndexError
```

**Comment by jswhit** [comment]
From the MFDataset docs:

aggdim - The name of the dimension to aggregate over (must be the leftmost dimension of each of the variables to be aggregated). If None (default), aggregate over the unlimited dimension.

longitude is the rightmost dimension, not the leftmost.

Don't know for sure this is the cause of your error, but it does seem that what you're doing probably should not work.  MFDataset only handles the very simplest kinds of aggregations.

**Comment by jswhit** [comment]
Pretty simple to do it manually though

    from netCDF4 import Dataset
    import numpy as np
    FILENAME_DATASET_1 = "localGFSTCC.ncdf"
    FILENAME_DATASET_2 = "localGFSTCC2.ncdf"
    varname = "Total_cloud_cover_entire_atmosphere"
    nc1 = Dataset (FILENAME_DATASET_1)
    nc2 = Dataset (FILENAME_DATASET_2)
    lats = nc1.variables['lat'][:]
    lons1 = nc1.variables['lon'][:]
    lons1 = np.where(lons1>180,lons1-360,lons1)
    lons2 = nc2.variables['lon'][:]
    lons2 = np.where(lons2>180,lons2-360,lons2)
    data1 = nc1.variables[varname][:]
    data2 = nc2.variables[varname][:]
    lons = np.concatenate((lons1,lons2))
    data = np.concatenate((data1,data2),axis=-1)

**Comment by doncristobal** [comment]
Jeff,
thanks for your answer. At the time of writing the code, I probably took the fact that MFDataset threw no exception and also seemed to concatenate my longitudes successfully, as an indication that aggregating by longitude was (despite the documentation) a valid way to go. But you're right, the documentation says otherwise. Maybe an error could be thrown if MFDataset tries to aggregate along a non-valid dimension.
Thanks for your example code also, I have implemented a workaround along these lines.
Chris
