### ISSUE TITLE
Install failed - netCDF4 v1.1.4

### ISSUE THREAD

**Issue by duytrung** [Unidata/netcdf4-python#340]
I installed the package and was not successful. Could you please, provide the package in Python Wheel standard. Thanks!
Here is the log:
```
<code>

c:\PYX>pip install -U netCDF4
Collecting netCDF4 from https://pypi.python.org/packages/source/n/netCDF4/netCDF4-1.1.4.tar.gz#md5=0
c9d6c2f625e20855282bc0d5bf12a8c
  Using cached netCDF4-1.1.4.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\myexpe~1\appdata\local\temp\pip-build-qomxw5\netCDF4\setup.py", line 187, in <m
odule>
        retcode =  subprocess.call([ncconfig,'--libs'],stdout=subprocess.PIPE)
      File "C:\Pyx\lib\subprocess.py", line 522, in call
        return Popen(*popenargs, **kwargs).wait()
      File "C:\Pyx\lib\subprocess.py", line 710, in __init__
        errread, errwrite)
      File "C:\Pyx\lib\subprocess.py", line 958, in _execute_child
        startupinfo)
    WindowsError: [Error 2] The system cannot find the file specified
    Complete output from command python setup.py egg_info:
    reading from setup.cfg...

    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "c:\users\myexpe~1\appdata\local\temp\pip-build-qomxw5\netCDF4\setup.py", line 187, in <m
odule>

        retcode =  subprocess.call([ncconfig,'--libs'],stdout=subprocess.PIPE)

      File "C:\Pyx\lib\subprocess.py", line 522, in call

        return Popen(*popenargs, **kwargs).wait()

      File "C:\Pyx\lib\subprocess.py", line 710, in __init__

        errread, errwrite)

      File "C:\Pyx\lib\subprocess.py", line 958, in _execute_child

        startupinfo)

    WindowsError: [Error 2] The system cannot find the file specified

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in c:\users\myexpe~1\appdata\local\t
emp\pip-build-qomxw5\netCDF4

</code>
```
Regards

**Comment by matteobachetti** [comment]
Hi, same exact problem here. On Travis CI, working until yesterday, with Python versions 2.7, 3.3 and 3.4. Looks like a typo, `ncconfig` should not be `nc-config` instead?
```
  Downloading netCDF4-1.1.4.tar.gz (630kB)
    100% |################################| 630kB 381kB/s 
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-TzVjFV/netCDF4/setup.py", line 187, in <module>
        retcode =  subprocess.call([ncconfig,'--libs'],stdout=subprocess.PIPE)
      File "/home/travis/miniconda/lib/python2.7/subprocess.py", line 522, in call
        return Popen(*popenargs, **kwargs).wait()
      File "/home/travis/miniconda/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/home/travis/miniconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
    Complete output from command python setup.py egg_info:
    reading from setup.cfg...

```

**Comment by jswhit** [comment]
On Windows, you should probably install the binary installer (there's a link on the pypi page)

**Comment by jswhit** [comment]
Link to binary installers:

http://www.lfd.uci.edu/~gohlke/pythonlibs/#netcdf4

**Comment by matteobachetti** [comment]
May it be related to the NetCDF version? On my Mac, where things install correctly, I have 4.3.2, while on the Travis machine 4.1.1 is installed.

**Comment by jswhit** [comment]
4.1.1 is pretty old, but it should work.

**Comment by swails** [comment]
FWIW, I'm seeing the same problem as @matteobachetti.  Travis all of a sudden just stopped working, not sure why.

The problem here is that `nc-config` isn't found when `subprocess.Popen` tries to run it.  The error message (which is the same as what I'm getting) seems to suggest that `ncconfig` is set to an empty string instead of the full path to `nc-config`.  Not sure where this is coming from and why it only happens on Travis.

Rolling back to 1.1.3 solves my problem, but I'd rather that not be my permanent solution.

**Comment by swails** [comment]
Is there some `setup.cfg` file that is uploaded to the `pip`-installable package?  I'm not seeing what's changed between 1.1.3 and 1.1.4 that would be breaking things...

**Comment by swails** [comment]
OK, I figured it out.  I'll issue a PR shortly to fix it.

In the meantime, @matteobachetti -- install `netcdf-bin` in addition to `libnetcdf-dev` in your `.travis.yml` script.

**Comment by jswhit** [comment]
Uploaded version 1.1.4.1 to pypi.  Same as 1.1.4, but without nc_config=True in setup.cfg.

**Comment by jswhit** [comment]
BTW thanks for tracking down the problem @swails

**Comment by matteobachetti** [comment]
Thanks a lot @swails for the solution, and @jswhit for the quick upload.
