### ISSUE TITLE
version 1.1.4 does no longer honor the environment variables HDF5_INCDIR and HDF5_LIBDIR

### ISSUE THREAD

**Issue by toelke** [Unidata/netcdf4-python#341]
With version 1.1.3 I can install netcdf4-python in debian by doing

    export HDF5_LIBDIR=/usr/lib/x86_64-linux-gnu/hdf5/serial/
    export HDF5_INCDIR=/usr/include/hdf5/serial/
    pip install netcdf4-python

with version 1.1.4 the following error appears:

    Downloading/unpacking netcdf4
      Running setup.py (path:/tmp/pip-build-0vwxtdh8/netcdf4/setup.py) egg_info for package netcdf4
        using nc-config ...
        using netcdf library version b'4.1.3'
        
    Requirement already satisfied (use --upgrade to upgrade): numpy>=1.3 in /usr/lib/python3/dist-packages (from netcdf4)
    Installing collected packages: netcdf4
      Running setup.py install for netcdf4
        using nc-config ...
        using netcdf library version b'4.1.3'
        building 'netCDF4' extension
        x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.4m -c netCDF4.c -o build/temp.linux-x86_64-3.4/netCDF4.o
        netCDF4.c:237:22: fatal error: H5public.h: No such file or directory
         #include "H5public.h"
                              ^
        compilation terminated.
        error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
        Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-0vwxtdh8/netcdf4/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ekxn2ogs-record/install-record.txt --single-version-externally-managed --compile:
        reading from setup.cfg...
    
    using nc-config ...
    
    using netcdf library version b'4.1.3'
    
    running install
    
    running build
    
    running build_py
    
    creating build
    
    creating build/lib.linux-x86_64-3.4
    
    copying netCDF4_utils.py -> build/lib.linux-x86_64-3.4
    
    creating build/lib.linux-x86_64-3.4/netcdftime
    
    copying netcdftime/netcdftime.py -> build/lib.linux-x86_64-3.4/netcdftime
    
    copying netcdftime/__init__.py -> build/lib.linux-x86_64-3.4/netcdftime
    
    running build_ext
    
    building 'netCDF4' extension
    
    creating build/temp.linux-x86_64-3.4
    
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.4m -c netCDF4.c -o build/temp.linux-x86_64-3.4/netCDF4.o
    
    netCDF4.c:237:22: fatal error: H5public.h: No such file or directory
    
     #include "H5public.h"
    
                          ^
    
    compilation terminated.
    
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
    Cleaning up...
    Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-0vwxtdh8/netcdf4/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ekxn2ogs-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-0vwxtdh8/netcdf4
    Storing debug log for failure in /root/.pip/pip.log

**Comment by jswhit** [comment]
It's using nc-config by default.  You can change that by editing setup.cfg.

**Comment by toelke** [comment]
On debian/amd64, nc-config does not return the correct path for libhdf5:

    $ nc-config --includedir
    /usr/include
    $ ls /usr/include/H5public.h
    ls: cannot access /usr/include/H5public.h: No such file or directory
    $ ls /usr/include/hdf5/serial/H5public.h
    /usr/include/hdf5/serial/H5public.h

Since the needed paths

    export HDF5_LIBDIR=/usr/lib/x86_64-linux-gnu/hdf5/serial/
    export HDF5_INCDIR=/usr/include/hdf5/serial/

are non-overlapping, even setting HDF5_DIR is not enough.

**Comment by toelke** [comment]
So I guess "WONTFIX"?

**Comment by mdecker** [comment]
Has anything changed between 1.1.4 and 1.1.6 in this regard? I managed to compile on debian testing today using the LIBDIR and INCDIR variables described above.
Is there any interest in patching the setup script so that the new debian default paths will be checked automatically? I'm willing to take a look if no other obvious facts speak against including them...

**Comment by shoyer** [comment]
@mdecker perhaps it would be better to fix `nc-config`? Just an idea...

**Comment by toelke** [comment]
The problem is that nc-config is not the right tool to ask about hdf. I have not yet tried 1.1.6, I will do so later today or tomorrow.

**Comment by jswhit** [comment]
Alternatively, you can create your own version of setup.cfg that has the correct paths for debian.

**Comment by mdecker** [comment]
Sure, I could do that. I just thought it might be nicer to enable easy installation for as many people as possible. If nobody is interested in this then I won't waste my time on it.

**Comment by toelke** [comment]
Since I roll out the installation via puppet, I very much like the option of using pip.

Uninstalling nc-config is a reasonable work-around for me. If it is installed, no version > 1.1.3 is installable as the paths from nc-config override the ones from the environment.

**Comment by jswhit** [comment]
What the lib and include paths that setup.py should search on Debian for HDF5 and netCDF?

**Comment by toelke** [comment]
On amd64 it's

    /usr/lib/x86_64-linux-gnu/hdf5/serial/
    /usr/include/hdf5/serial/

for hdf5 and

    /usr/lib/
    /usr/include/

for netCDF.

**Comment by jswhit** [comment]
It should already be finding the netCDF libs and include files.  The HDF5 paths are problematic, since setup.py is assuming the paths are of the form $INCDIR/include and $LIBDIR/lib.  The following should work in 1.1.6 (and probably with earlier versions):

mv setup.cfg setup.cfg.save
export USE_NCCONFIG=0
export HDF5_LIBDIR=/usr/lib/x86_64-linux-gnu/hdf5/serial
export HDF5_INCDIR=/usr/include/hdf5/serial
export NETCDF4_DIR=/usr
python setup.py build
python setup.py install

Note that you have to move setup.cfg out of the way to use the env vars to specify the paths.

Alternatively, replace the default setup.cfg with

[options]
use_ncconfig=False
[directories]
netCDF4_dir=/usr
HDF5_libdir=/usr/lib/x86_64-linux-gnu/hdf5/serial
HDF5_incdir=/usr/include/hdf5/serial
python setup.py build
python setup.py install

The default install using nc-config should work though, if netcdf was compiled with the same HDF5 library and include paths.  I'd be curious to know what nc-config --libs and nc-config --includedir report.  If they don't report the correct paths, then I'd say that's a netcdf packaging bug.

**Comment by jswhit** [comment]
Correction:  You don't have to move setup.cfg out of the way with version 1.1.6 to use env vars, setting USE_NCCONFIG=0 is enough.

**Comment by toelke** [comment]
USE_NCCONFIG=0 is not honored using pip (I tried it with 1.1.5 and 1.1.6)

**Comment by jswhit** [comment]
You're right.  Fixed in pull request #373

**Comment by jswhit** [comment]
Merging pull request #373.  Will release 1.1.7 tomorrow - if this does not fix it for you, please report back here.

**Comment by toelke** [comment]
1.1.7 does not compile at all: #375

**Comment by jswhit** [comment]
FIxed now, try again.

**Comment by toelke** [comment]
Yes, 1.1.7.1 works. Thank you for the way you handled this problem!
