### ISSUE TITLE
Inconsistency in num2date -> date2num

### ISSUE THREAD

**Issue by akleeman** [Unidata/netcdf4-python#344]
This seems suspicious:

```
In [2]: units = 'hours since 2013-12-12T12:00:00'

In [3]: nc4.date2num(nc4.num2date(1., units), units)
Out[3]: 0.9999999962747097

In [4]: nc4.__version__ 
Out[4]: '1.1.4'
```

Is this expected?  I've been looking for a bug in date2num but can't find anything.

**Comment by jhamman** [comment]
@akleeman - I believe this is a known precision issue that comes from storing seconds as a `float` in `netcdftime`.  @jswhit and I discussed this a bit in #321/#322.

**Comment by jswhit** [comment]
That's right - the date2num and num2date calculations have a precision of 1 second.

**Comment by akleeman** [comment]
Would it be worth using the approach in the coards package?

```
In [3]: units = 'hours since 2013-12-12T12:00:00'
In [4]: coards.to_udunits(coards.from_udunits(1., units), units)
Out[4]: 1.0
```

It only works for Gregorian calendars, but does roundtrip appropriately.

**Comment by jswhit** [comment]
pull request #348 rounds the results of date2num consistent with the 1 second accuracy in the calculation.  This should improve the accuracy of the round trip calculation.

**Comment by jswhit** [comment]
Pretty sure this does not solve the problem - perfect round trip accuracy with floating point arithmetic is really not possible.  Best just to be aware of the limitations.

**Comment by jswhit** [comment]
Added a test to make sure that roundtrip accuracy is within what is expected given 1 second accuracy (pull request #350)

**Comment by jswhit** [comment]
Pull request #351 fixes (for some cases) by using python datetime (which has microsecond accuracy) whenever possible.

**Comment by jswhit** [comment]
pull request #351 merged, closing...
