### ISSUE TITLE
differences between netcdf4-python and Scientific.IO.NetCDF

### ISSUE THREAD

**Issue by jswhit** [Unidata/netcdf4-python#345]
Got this email today (see below).  Posting it here in case others would like to respond.

Hi Jeffrey,

I am helping the Debian GIS Team to transition to the latest NetCDF C
library which has had the fortran and C++ interfaces split out since we
last packaged it.

As part of that effort we were also planning to package the
netcdf-python package. However, the maintainer of the PythonScientific
package has asked what advantages netcdf-python has over python-netcdf
(Scientific). This is normal practise in Debian to make sure that when
we package software, the users are getting what they need, and there is
no needless duplication and confusion.

You can see Konrad's answer about the reason he maintains python-netcdf
below, and the whole thread here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=778417

A reply direct to me is fine, but it would be better if you could reply
publicly to all of the email addresses below (except me, because I am
subscribed to both the bug email, and debian-devel*).

This would be really useful and help us decide if packaging one or
other, or both of the python interfaces to NetCDF was a good idea.

Many thanks for all the work you do on netcdf-python anyway. I am
monitoring the issues list on Github, and I can see there is an active
community of users.

Regards,

Ross Gammon

-------- Forwarded Message --------
Subject: RE:Bug#778417: ITP: netcdf-python -- python interface to the
netCDF4 (network Common Data Form) library
Resent-Date: Thu, 19 Feb 2015 20:51:09 +0000 (UTC)
Resent-From: debian-devel@lists.debian.org
Date: Thu, 19 Feb 2015 21:33:01 +0100
From: Konrad Hinsen <research@khinsen.fastmail.net>
To: PICCA Frederic-Emmanuel <frederic-emmanuel.picca@synchrotron-soleil.fr>
CC: Ross Gammon <rossgammon@mail.dk>, 778417@bugs.debian.org
<778417@bugs.debian.org>, debian-devel@lists.debian.org
<debian-devel@lists.debian.org>

Hi everyone,

PICCA Frederic-Emmanuel writes:
 > @Konrad do you think that this netcdf implementation from scientific
python could be replace by this
 > netcdf4-python implementation ? Should we get rid of your
implentation and use this one instead (to be clear)

The main problem with Python-netCDF interfaces is that no two of them
have compatible API even for the most basic operations. Whenever some
Python package depends on netCDF, it depends on one of the various
Python-netCDF interfaces, and wouldn't work with the other ones.

To make it worse, even if your goal is only to provide a single Python
interface for new developments, not caring about compatibility, the
features of the various Python interfaces are sufficiently different
to make a choice very difficult.

The unique feature of my own netCDF interface, and the reason why
I keep maintaining it, is the C-level API for other Python modules.
Each of the other interfaces has such unique features as well.

Konrad.
--
---------------------------------------------------------------------
Konrad Hinsen
Centre de Biophysique Moléculaire, CNRS Orléans
Synchrotron Soleil - Division Expériences
Saint Aubin - BP 48
91192 Gif sur Yvette Cedex, France
Tel. +33-1 69 35 97 15
E-Mail: research AT khinsen DOT fastmail DOT net
http://dirac.cnrs-orleans.fr/~hinsen/
ORCID: http://orcid.org/0000-0003-0330-9428
Twitter: @khinsen
---------------------------------------------------------------------

**Comment by zerothi** [comment]
In my experience many of the features are quite similar.

However, netcdf4-python has the advantage of full CDF4 capabilities.
Konrads excellent package allows reading a NetCDF4 format in "CLASSIC"
format, it also allows writing the CDF3 and CDF3-64 bit files. But it does
not allow writing the full NetCDF4 format (I do not know if he has just
implemented it, but last time I checked, 2.9.3, he hadn't).

Other than that I see few differences in usage, for my small projects I
have created a tiny wrapper to read variables dependent on 3 different
netcdf packages. A tiny wrapper can also be made for creating variables and
this is where they differ the most. But once a variable is opened as an
instance, retrieving its values through index slices is the same (refrain
from using obscure slices).

If the target is to add netcdf4 functionality to the masses through
packages, then netcdf4-python is a must as ScientificPython does not add
netcdf4 API. However, Konrad does have a point in that ScientificPython is
still heavily used and thus many packages might require it, in that regard
netcdf4-python is still in its infancy.
So maintaining both could be a vial solution, albeit confusing for the user.

Hope it helps :)

2015-02-23 21:01 GMT+00:00 Jeff Whitaker <notifications@github.com>:

> Got this email today (see below). Posting it here in case others would
> like to respond.
>
> Hi Jeffrey,
>
> I am helping the Debian GIS Team to transition to the latest NetCDF C
> library which has had the fortran and C++ interfaces split out since we
> last packaged it.
>
> As part of that effort we were also planning to package the
> netcdf-python package. However, the maintainer of the PythonScientific
> package has asked what advantages netcdf-python has over python-netcdf
> (Scientific). This is normal practise in Debian to make sure that when
> we package software, the users are getting what they need, and there is
> no needless duplication and confusion.
>
> You can see Konrad's answer about the reason he maintains python-netcdf
> below, and the whole thread here:
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=778417
>
> A reply direct to me is fine, but it would be better if you could reply
> publicly to all of the email addresses below (except me, because I am
> subscribed to both the bug email, and debian-devel*).
>
> This would be really useful and help us decide if packaging one or
> other, or both of the python interfaces to NetCDF was a good idea.
>
> Many thanks for all the work you do on netcdf-python anyway. I am
> monitoring the issues list on Github, and I can see there is an active
> community of users.
>
> Regards,
>
> Ross Gammon
>
> -------- Forwarded Message --------
> Subject: RE:Bug#778417: ITP: netcdf-python -- python interface to the
> netCDF4 (network Common Data Form) library
> Resent-Date: Thu, 19 Feb 2015 20:51:09 +0000 (UTC)
> Resent-From: debian-devel@lists.debian.org
> Date: Thu, 19 Feb 2015 21:33:01 +0100
> From: Konrad Hinsen research@khinsen.fastmail.net
> To: PICCA Frederic-Emmanuel frederic-emmanuel.picca@synchrotron-soleil.fr
> CC: Ross Gammon rossgammon@mail.dk, 778417@bugs.debian.org
> 778417@bugs.debian.org, debian-devel@lists.debian.org
> debian-devel@lists.debian.org
>
> Hi everyone,
>
> PICCA Frederic-Emmanuel writes:
>
> @Konrad <https://github.com/Konrad> do you think that this netcdf
> implementation from scientific
> python could be replace by this
> netcdf4-python implementation ? Should we get rid of your
> implentation and use this one instead (to be clear)
>
> The main problem with Python-netCDF interfaces is that no two of them
> have compatible API even for the most basic operations. Whenever some
> Python package depends on netCDF, it depends on one of the various
> Python-netCDF interfaces, and wouldn't work with the other ones.
>
> To make it worse, even if your goal is only to provide a single Python
> interface for new developments, not caring about compatibility, the
> features of the various Python interfaces are sufficiently different
> to make a choice very difficult.
>
> The unique feature of my own netCDF interface, and the reason why
> I keep maintaining it, is the C-level API for other Python modules.
> Each of the other interfaces has such unique features as well.
> Konrad.
> ------------------------------
>
> Konrad Hinsen
> Centre de Biophysique Moléculaire, CNRS Orléans
> Synchrotron Soleil - Division Expériences
> Saint Aubin - BP 48
> 91192 Gif sur Yvette Cedex, France
> Tel. +33-1 69 35 97 15
> E-Mail: research AT khinsen DOT fastmail DOT net
> http://dirac.cnrs-orleans.fr/~hinsen/
> ORCID: http://orcid.org/0000-0003-0330-9428
> Twitter: @khinsen <https://github.com/khinsen>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unidata/netcdf4-python/issues/345>.
>



-- 
Kind regards Nick

**Comment by jswhit** [comment]
Thanks.  Would you mind posting that on the Debian list?  Here's the link to the thread

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=778417

**Comment by zerothi** [comment]
Done :)

2015-02-24 3:42 GMT+00:00 Jeff Whitaker <notifications@github.com>:

> Thanks. Would you mind posting that on the Debian list? Here's the link to
> the thread
>
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=778417
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unidata/netcdf4-python/issues/345#issuecomment-75694459>
> .
>



-- 
Kind regards Nick

**Comment by khinsen** [comment]
The netCDF interface in ScientificPython has not support for the functionality specific to netCDF4, for two reasons: (1) I don't need it and (2) I want to maintain compatibility with netCDF3, which is (or at least used to be a while ago) much less problematic to install than netCDF4 with its enormous dependency (HDF5).

I cannot dedicate much energy to netCDF support because I am migrating my own software to a direct use of HDF5. I continue to support netCDF merely for keeping my legacy software usable. I'd be happy to abandon my netCDF interface in the long run and use netcdf4-python for my legacy code. However, the last time I checked, this didn't look like a viable option.

For the pure Python interface, I could probably replace Scientific.IO.NetCDF by a thin wrapper on top of netcdf4-python. But for the C interface, I do not see a solution. I have application code (the Molecular Modelling Toolkit, http://dirac.cnrs-orleans.fr/MMTK/) that accesses a single opened netCDF file both from Python code and from C extension modules. To make this work portably, supporting shared libraries on all platforms, the C API calls must pass through the C extension module that is linked to the netCDF library. Last time I checked, netcdf4-python did not support this. Is there perhaps a different solution for this scenario?

**Comment by zerothi** [comment]
2015-02-24 9:26 GMT+00:00 khinsen <notifications@github.com>:

> The netCDF interface in ScientificPython has not support for the
> functionality specific to netCDF4, for two reasons: (1) I don't need it and
> (2) I want to maintain compatibility with netCDF3, which is (or at least
> used to be a while ago) much less problematic to install than netCDF4 with
> its enormous dependency (HDF5).
>
In case anybody is looking, I have attached an install script which
installs zlib, hdf5 and netcdf4-c/f. With very little changes it can be
used for parallel io as well. It is targeted a specific scientific software
package, yet the installation works. It fixes the runtime library dirs so
as not to confuse the user.

> I cannot dedicate much energy to netCDF support because I am migrating my
> own software to a direct use of HDF5. I continue to support netCDF merely
> for keeping my legacy software usable. I'd be happy to abandon my netCDF
> interface in the long run and use netcdf4-python for my legacy code.
> However, the last time I checked, this didn't look like a viable option.
>

For the pure Python interface, I could probably replace
> Scientific.IO.NetCDF by a thin wrapper on top of netcdf4-python. But for
> the C interface, I do not see a solution. I have application code (the
> Molecular Modelling Toolkit, http://dirac.cnrs-orleans.fr/MMTK/) that
> accesses a single opened netCDF file both from Python code and from C
> extension modules. To make this work portably, supporting shared libraries
> on all platforms, the C API calls must pass through the C extension module
> that is linked to the netCDF library. Last time I checked, netcdf4-python
> did not support this. Is there perhaps a different solution for this
> scenario?
>
I agree that the difference in API is not so straightforwardly fixed :(

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unidata/netcdf4-python/issues/345#issuecomment-75723937>
> .
>



-- 
Kind regards Nick

**Comment by khinsen** [comment]
I don't see any attached install script (does GitHub allow attachments???), but I am not interested in it anyway unless it deals with all of the following situations:
 - Linux, MacOS, and Windows
 - multiple Python installations
 - incomplete existing installations of any dependencies
 - existing installations of dependencies in incompatible versions
 - users without administrator rights

For many years, netCDF installation problems were the most frequent subject of support e-mails for my software packages. Recently Linux distributions that modify Python in some way have taken the lead, but netCDF-related problems have not diminished.

**Comment by zerothi** [comment]
Probably it does not (as I can see it in my sequence of mails, so I did not
forget it).
* It lets the user select an install directory, could be local (if no admin
rights)
* the installation will not look for already installed libraries (it will
link against those installed)
* It deals with both 32 and 64 bit library locations
* It only installs netcdf4-c/f no python, it was merely if people had an
interest.

I here post it in its completeness:
#!/bin/bash

# VERY BASIC installation script of required libraries
# for installing these packages:
#   zlib-1.2.8
#   hdf5-1.8.12
#   netcdf-4.3.2
#   netcdf-fortran-4.4.1

# If you have downloaded other versions edit these version strings
z_v=1.2.8
h_v=1.8.12
nc_v=4.3.2
nf_v=4.4.1

# Install path, change accordingly
# You can change this variable to control the installation path
# If you want the installation path to be a "packages" folder in
# your home directory, change to this:
# ID=$HOME/packages
ID=/opt

# First we check that the user have downloaded the files
function file_exists {
    if [ ! -e $(pwd)/$1 ]; then
echo "I could not find file $1..."
echo "Please download the file and place it in this folder:"
echo " $(pwd)"
exit 1
    fi
}

file_exists zlib-${z_v}.tar.gz
file_exists hdf5-${h_v}.tar.gz
file_exists netcdf-${nc_v}.tar.gz
file_exists netcdf-fortran-${nf_v}.tar.gz
unset file_exists

#################
# Install z-lib #
#################
tar xfz zlib-${z_v}.tar.gz
cd zlib-${z_v}
./configure --prefix $ID/zlib/${z_v}
make
make test 2>&1 | tee zlib.test
make install
mv zlib.test $ID/zlib/${z_v}/
cd ../
rm -rf zlib-${z_v}
echo "Completed installing zlib"
[ -d $ID/zlib/${z_v}/lib64 ] && zlib_lib=lib64 || zlib_lib=lib

################
# Install hdf5 #
################
tar xfz hdf5-${h_v}.tar.gz
cd hdf5-${h_v}
mkdir build ; cd build
../configure --prefix=$ID/hdf5/${h_v} \
--enable-shared --enable-static \
--enable-fortran --with-zlib=$ID/zlib/${z_v} \
LDFLAGS="-L$ID/zlib/${z_v}/$zlib_lib -Wl,-rpath=$ID/zlib/${z_v}/$zlib_lib"
make
make check-s 2>&1 | tee hdf5.test
make install
mv hdf5.test $ID/hdf5/${h_v}/
cd ../../
rm -rf hdf5-${h_v}
echo "Completed installing hdf5"
[ -d $ID/hdf5/${h_v}/lib64 ] && hdf5_lib=lib64 || hdf5_lib=lib

####################
# Install NetCDF-C #
####################
tar xfz netcdf-${nc_v}.tar.gz
cd netcdf-${nc_v}
mkdir build ; cd build
../configure --prefix=$ID/netcdf/${nc_v} \
--enable-shared --enable-static \
--enable-netcdf-4 --disable-dap \
CPPFLAGS="-I$ID/hdf5/${h_v}/include -I$ID/zlib/${z_v}/include" \
LDFLAGS="-L$ID/hdf5/${h_v}/$hdf5_lib -Wl,-rpath=$ID/hdf5/${h_v}/$hdf5_lib \
-L$ID/zlib/${z_v}/$zlib_lib -Wl,-rpath=$ID/zlib/${z_v}/$zlib_lib"
make
make install
cd ../../
rm -rf netcdf-${nc_v}
echo "Completed installing C NetCDF library"
[ -d $ID/netcdf/${nc_v}/lib64 ] && cdf_lib=lib64 || cdf_lib=lib

##########################
# Install NetCDF-Fortran #
##########################
tar xfz netcdf-fortran-${nf_v}.tar.gz
cd netcdf-fortran-${nf_v}
mkdir build ; cd build
../configure CPPFLAGS="-DgFortran -I$ID/zlib/${z_v}/include \
-I$ID/hdf5/${h_v}/include -I$ID/netcdf/${nc_v}/include" \
LIBS="-L$ID/zlib/${z_v}/$zlib_lib -Wl,-rpath=$ID/zlib/${z_v}/$zlib_lib \
-L$ID/hdf5/${h_v}/$hdf5_lib -Wl,-rpath=$ID/hdf5/${h_v}/$hdf5_lib \
-L$ID/netcdf/${nc_v}/$cdf_lib -Wl,-rpath=$ID/netcdf/${nc_v}/$cdf_lib \
-lnetcdf -lhdf5hl_fortran -lhdf5_fortran -lhdf5_hl -lhdf5 -lz" \
--prefix=$ID/netcdf/${nc_v} --enable-static --enable-shared
make
make check 2>&1 | tee check.serial
make install
mv check.serial $ID/netcdf/${nc_v}/
cd ../../
rm -rf netcdf-fortran-${nf_v}
echo "Completed installing Fortran NetCDF library"

##########################
# Completed installation #
##########################

echo ""
echo ""
echo "##########################"
echo "# Completed installation #"
echo "#   of NetCDF package    #"
echo "#  and its dependencies  #"
echo "##########################"
echo ""
echo ""



2015-02-24 14:55 GMT+00:00 khinsen <notifications@github.com>:

> I don't see any attached install script (does GitHub allow
> attachments???), but I am not interested in it anyway unless it deals with
> all of the following situations:
>
>    - Linux, MacOS, and Windows
>    - multiple Python installations
>    - incomplete existing installations of any dependencies
>    - existing installations of dependencies in incompatible versions
>    - users without administrator rights
>
> For many years, netCDF installation problems were the most frequent
> subject of support e-mails for my software packages. Recently Linux
> distributions that modify Python in some way have taken the lead, but
> netCDF-related problems have not diminished.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unidata/netcdf4-python/issues/345#issuecomment-75770899>
> .
>



-- 
Kind regards Nick
