### ISSUE TITLE
read/write big endian ints.

### ISSUE THREAD

**Issue by akleeman** [Unidata/netcdf4-python#346]
It appears that writing/reading of big endian ints is not consistent.  (Also possible I'm doing something incorrectly!)

```
        # create a big endian variable
        xs = np.arange(10, dtype='>i4')
        nc = nc4.Dataset('./test.nc', mode='w')
        nc.createDimension('x', size=xs.size)
        nc.createVariable('x', xs.dtype, ('x'),
                          endian='big')
        nc.variables['x'][:] = ds['x'].values
        nc.close()

        actual = nc4.Dataset('./test.nc')
        print xs
        print nc.variables['x'][:]
        print actual.variables['x'][:]
```

```
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[        0  16777216  33554432  50331648  67108864  83886080 100663296
 117440512 134217728 150994944]
```

**Comment by shoyer** [comment]
@akleeman I think your use of `ds['x'].values` should be `xs`, yes?

**Comment by akleeman** [comment]
@shoyer good catch, your example is correct.

**Comment by jswhit** [comment]
tentative fix in pull request #347

**Comment by jswhit** [comment]
merging pull request #347, closing...

**Comment by sjschneider** [comment]
I'm not sure if I'm experiencing a regression or if my data files are prepared improperly, but there was a change between Release 1.1.4 and 1.1.5 that I think is attributed to the endianess issue here.


I prepared my data file, [dxqclddp2.199306.h5 (dropbox)](https://www.dropbox.com/s/xfrv91eb4b19ai0/dxqclddp2.199306.h5.zip?dl=0), from a [SDS file (dropbox)](https://www.dropbox.com/s/qaoprkg6yle82ru/dxqclddp2.199306.sds.zip?dl=0), converted on an Amazon EC2 Ubuntu image to the HDF5 format, using the [h4toh5](http://www.hdfgroup.org/ftp/HDF5/tools/h4toh5/src/unpacked/doc/h4toh5lib_RM.html#Tools-h4toh5) utility.  [Panoply](http://www.giss.nasa.gov/tools/panoply/) reads both these files without a problem.  The short script is shown below with the output running on release v1.1.4 and v1.1.5 of netCDF4.

```python
# running on Mac OS X
import numpy as np
from netCDF4 import Dataset
fh = Dataset('dxqclddp2.199306.h5')
print(fh.variables['Data-Set-2'])
print(fh.variables['Data-Set-2'][:])
fh.close()
```

## Release v1.1.4 (correct)
```
<class 'netCDF4.Variable'>
int16 Data-Set-2(phony_dim_0, phony_dim_1)
    coordsys: 720X360 grid
    valid_max: 4455
    valid_min: -10
    long_name: file=/data6/model11.9306/dxqclddp2.9306.sds
    units: *10
    format: integer*2, missing value -10
    HDF4_OBJECT_TYPE: SDS
    HDF4_OBJECT_NAME: Data-Set-2
    HDF4_REF_NUM: 2
unlimited dimensions: 
current shape = (360, 720)
filling off

[[2239 2239 2239 ..., 2039 2040 2323]
 [2482 2482 2482 ..., 2267 2267 2454]
 [2397 2397 2397 ..., 2441 2441 2397]
 ..., 
 [ -10  -10  -10 ...,  -10  -10  -10]
 [ -10  -10  -10 ...,  -10  -10  -10]
 [ -10  -10  -10 ...,  -10  -10  -10]]
```

## Release v1.1.5 (incorrect)
```
<class 'netCDF4.Variable'>
>i2 Data-Set-2(phony_dim_0, phony_dim_1)
    coordsys: 720X360 grid
    valid_max: 4455
    valid_min: -10
    long_name: file=/data6/model11.9306/dxqclddp2.9306.sds
    units: *10
    format: integer*2, missing value -10
    HDF4_OBJECT_TYPE: SDS
    HDF4_OBJECT_NAME: Data-Set-2
    HDF4_REF_NUM: 2
unlimited dimensions: 
current shape = (360, 720)
filling off

[[-16632 -16632 -16632 ...,  -2297  -2041   4873]
 [-19959 -19959 -19959 ...,  -9464  -9464 -27127]
 [ 23817  23817  23817 ..., -30455 -30455  23817]
 ..., 
 [ -2305  -2305  -2305 ...,  -2305  -2305  -2305]
 [ -2305  -2305  -2305 ...,  -2305  -2305  -2305]
 [ -2305  -2305  -2305 ...,  -2305  -2305  -2305]]
```

**Comment by jswhit** [comment]
re-opening this issue

**Comment by jswhit** [comment]
The data is marked as big-endian in the hdf5 file.  When read in on a little endian machine, the data is automatically returned in an array of dtype '>i2' (big-endian short integer) in version 1.1.5.  This was not happening in version 1.1.4 (the data was being returned in a native-endian array, which in your case is little).    This was a bug, which was fixed by pull request #347. Are you sure the data in the file is actually big endian?  It seems that your 'correct' result is only obtained if you assume the data in the file is little endian.

**Comment by sjschneider** [comment]
Thanks for your help.  It's not clear to me where the big-endian marking is coming from, perhaps from the source sds file or during the conversion.  Either way, the data is only read correctly when it is interpreted as little endian.  Is there a way I can force the netcdf4 package to read the data in as little endian so that I can use the latest release?  Otherwise, can I change the marking on the files to be little endian?

**Comment by jswhit** [comment]
You can't tell netcdf4-python to over-ride the endian-ness designation in the file.  You can just byteswap the array that is returned though - using the numpy array byteswap method.  Or, you rewrite the data with the correct endian flag.
