### ISSUE TITLE
Question about data change in reading data from netCDF file

### ISSUE THREAD

**Issue by XingZheng** [Unidata/netcdf4-python#352]
When I tried to read the data from a netcdf file with netcdf4-python. I found the data my code read is different from the data stored in that file.
My code is just like,

netcdffile = Dataset(filename,'r')
print netcdffile.variables['UGDRNOFF'][:]
Then the list python outputs is [4.828756E-13, 3.5546802E-19, 7.904436E-12], 
while the original list should be [3.714428E-14, 2.734369E-20, 6.0803353E-13]. So what causes the difference between the output result and the input data? How can I solve this problem to keep the data python reads as they were in the netCDF file?

Thanks for your help!

**Comment by shoyer** [comment]
Your data has a `scale_factor` defined. Set `var.set_auto_maskandscale(False)` to turn off automatic decoding of the scale factor (though usually you *do* want the scale factor to be automatically removed when reading data from disk). See here for more details:
http://unidata.github.io/netcdf4-python/netCDF4.Variable-class.html

**Comment by XingZheng** [comment]
No, I tried your solution. But it didn't work...

**Comment by shoyer** [comment]
In that case, you'll need to share either your code or your data :)

**Comment by XingZheng** [comment]
https://drive.google.com/file/d/0BwoGp3c8wYxjQkpWWkRCR0c1TGs/view?usp=sharing
https://drive.google.com/file/d/0BwoGp3c8wYxja0RQWXgyU1pERkU/view?usp=sharing

Here are my data and code. Wish you could help me figure out the problem. Thank you so much! I really appreciate it.

**Comment by shoyer** [comment]
You probably also need to use `set_auto_maskandscale(False)` when writing your data.

**Comment by shoyer** [comment]
When I look at your dataset, I see exactly the output you said you expect:
```
In [1]: import netCDF4

In [2]: f = netCDF4.Dataset('/Users/shoyer/Downloads/2015021301.LDASOUT_DOMAIN1.nc')

In [3]: v = f.variables['UGDRNOFF']

In [4]: v[:]
Out[4]:
array([[[  3.71442785e-14,   3.71442785e-14,   3.71442785e-14, ...,
          -9.99999994e+32,  -9.99999994e+32,  -9.99999994e+32],
        [  3.71442785e-14,   3.71442785e-14,   3.71442785e-14, ...,
          -9.99999994e+32,  -9.99999994e+32,  -9.99999994e+32],
        [  3.71442785e-14,   3.71442785e-14,   3.71442785e-14, ...,
          -9.99999994e+32,  -9.99999994e+32,  -9.99999994e+32],
        ...,
        [  6.08033535e-13,   6.08033535e-13,   6.08033535e-13, ...,
           3.71442785e-14,   3.71442785e-14,   3.71442785e-14],
        [  6.08033535e-13,   6.08033535e-13,   6.08033535e-13, ...,
           3.71442785e-14,   3.71442785e-14,   3.71442785e-14],
        [  6.08033535e-13,   6.08033535e-13,   6.08033535e-13, ...,
           3.71442785e-14,   3.71442785e-14,   3.71442785e-14]]], dtype=float32)
```

Not sure exactly what the issue is.

**Comment by XingZheng** [comment]
OK, I see where my problem is. I have a file list to read into the same netCDF file. But the way I organize the file is not exactly follow the time order. So for the first time step, I just read the data of other time instead of the start time. 
Stupid mistake...
Thanks for your help! I really appreciate it!
