### ISSUE TITLE
Regression in ability to roundtrip some netcdftime.datetime objects through date2num

### ISSUE THREAD

**Issue by shoyer** [Unidata/netcdf4-python#355]
In v1.1.4, this date roundtrips successfully through date2num:
```
In [1]: import netCDF4 as nc4

In [2]: import datetime

In [4]: num = nc4.date2num(datetime.datetime(2001, 4, 1, 1), 'days since 0001-01-01', calendar='noleap')

In [5]: nc4.num2date(num, 'days since 0001-01-01', calendar='noleap')
Out[5]: 2001-04-01 01:00:00
```

In v1.1.5, this is no longer the case:
```
(Pdb) nc4.num2date(num, 'days since 0001-01-01', calendar='noleap')
2001-04-01 00:59:59
```

To state the obvious, we need more regression tests for `netcdftime` :). I'll also see if I can get xray setup to test against the master branch of netcdf4-python so we can hopefully identify these issues earlier.

**Comment by jswhit** [comment]
Now that we have greater accuracy, the date is represented as 2001-04-01 00:59:59 and 999986 microseconds.  So the roundtrip calculation is 14 microseconds off!

**Comment by shoyer** [comment]
OK, fair enough! I'll make that an approximate equality test.
