### ISSUE TITLE
date2num no longer returns timezone naive datetimes

### ISSUE THREAD

**Issue by shoyer** [Unidata/netcdf4-python#357]
This is not exactly a bug, *per se*, but is a change that broke backwards compatibility and that was not announced in the release notes.

date2num (in v1.1.5) now returns dates with a UTC timezone:
```
(Pdb) nc4.num2date(0, units, calendar)
datetime.datetime(2000, 1, 1, 0, 0, tzinfo=tzutc())
```

Unfortunately, UTC datetime objects cannot be compared with timezone naive datetimes:
```
(Pdb) datetime.datetime(2000, 1, 1, 0, 0, tzinfo=dateutil.tz.tzutc()) == datetime.datetime(2000, 1, 1, 0, 0)
*** TypeError: can't compare offset-naive and offset-aware datetimes
```

Hence, old code which relied on prior behavior (including xray prior to https://github.com/xray/xray/pull/355) will be broken.

In my opinion, it is probably more appropriate to return timezone-naive datetime objects, which are a bit more convenient, rather than the technically more correct UTC timezones.

**Comment by jswhit** [comment]
Pull request #360 modifies the units date parser so that it returns datetime instances without any time zone info.  Not totally comfortable with this, since I wonder if some people are relying on having time zone info in the units string.

**Comment by jswhit** [comment]
Added time zone offset to basedate calculated by units date parser. I'm OK with this change now, since the datetime instances returned for calendars and dates not covered by python datetime were always timezone naive.  Now it's more consistent - the datetime instances returned by num2date are now always timezone naive.

**Comment by jswhit** [comment]
@shoyer  could you run branch issue357 through the xray tests?  If it passes, then I'll merge.

**Comment by shoyer** [comment]
Things aren't quite working yet, but I think that's mostly my fault. I'll take a more detailed look soon.

**Comment by shoyer** [comment]
@jswhit Yes, everyone passes now. Your efforts here are greatly appreciated!

**Comment by jswhit** [comment]
OK great. I'll merge the pull request now.

**Comment by shoyer** [comment]
For reference, the last listed build here is now testing xray against netCDF4-python master: https://travis-ci.org/xray/xray

I'll try to keep an eye on it and let you know if something breaks.
