### ISSUE TITLE
Question about changing dimension to unlimited

### ISSUE THREAD

**Issue by matilton** [Unidata/netcdf4-python#361]
Hello, is there a way to change a fixed dimension to unlimited after a netCDF file has been created?

I'm trying to aggregate many small time-series netCDF4 files into a larger file. (I want an actual file, not just the ability to read the aggregated dataset.) The easiest way to start is simply by copying the first file into the new file that will become the aggregated file. However, the time dimension is fixed, and it needs to be unlimited to append subsequent files. Is there a way to change this? I suspect I have to recreate the file, but I wanted to check. Thanks for any help.

**Comment by jswhit** [comment]
No, a dimension cannot be changed to unlimited.  You can however, concatenate files along a given dimension using the NCO tools, even if the dimensions are not unlimited

http://nco.sourceforge.net/nco.html#Concatenation

**Comment by matilton** [comment]
Thank you very much, Jeff. I will look into those tools. Meg
