### ISSUE TITLE
netcdftime: make calendar keyword case insensitive 

### ISSUE THREAD

**Issue by jhamman** [Unidata/netcdf4-python#362]
Some netCDF files have time calendar attributes with non-standard formatting.  For example, at least one global climate model I am aware of using a calendar attribute of `NOLEAP`.

Would it be acceptable to add a `calendar.lower()` line in [netcdftime.py#L646](https://github.com/Unidata/netcdf4-python/blob/master/netcdftime/netcdftime.py#L646)?  This would essentially make the calendar keyword case insensitive?

CC @emaroon.

**Comment by jswhit** [comment]
Sounds reasonable.  Care to make a pull request?

**Comment by jswhit** [comment]
I think

    calendar = calendar.lower()

should be added to date2num and num2date in utils.pyx as well.

**Comment by jhamman** [comment]
ed2d378 should take care of `num2date` and `date2num`.

**Comment by jswhit** [comment]
Thanks!

**Comment by jhamman** [comment]
Thank you!.
