### ISSUE TITLE
Version 1.0.7 import issue

### ISSUE THREAD

**Issue by bmayerornl** [Unidata/netcdf4-python#366]
Version 1.0.7 was installed over 1.0.6
First time trying to load module fails with "cannot import name _tostr", issue the same load command again and it works.
-----
-bash-4.2$ ~/python_3.2.3/bin/python3
Python 3.2.3 (default, May  1 2012, 10:57:41) 
[GCC 4.3.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from netCDF4 import Dataset
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netCDF4.pyx", line 790, in init netCDF4 (netCDF4.c:51074)
ImportError: cannot import name _tostr
>>> from netCDF4 import Dataset
>>> dir(Dataset)
['__class__', '__delattr__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__unicode__', '_enddef', '_grpid', '_isopen', '_redef', 'close', 'cmptypes', 'createCompoundType', 'createDimension', 'createGroup', 'createVLType', 'createVariable', 'delncattr', 'dimensions', 'file_format', 'filepath', 'getncattr', 'groups', 'maskanscale', 'ncattrs', 'parent', 'path', 'renameAttribute', 'renameDimension', 'renameGroup', 'renameVariable', 'set_fill_off', 'set_fill_on', 'setncattr', 'setncatts', 'sync', 'variables', 'vltypes']
>>>

**Comment by jswhit** [comment]
No idea.  If problems persist, I'd suggest upgrading to 1.1.5.

**Comment by bmayerornl** [comment]
Went around problem with new Python and modules install.
