### ISSUE TITLE
Error building netcdf4-python

### ISSUE THREAD

**Issue by KrisHammerberg** [Unidata/netcdf4-python#376]
Hi, 
I've get the following when attempting to build:
I have built also built netCDF4 from source and installed it to a custom directory, but I've included that in the setup.cfg file (as well as set the NETCDF4 environmental variable). It doesn't appear to like my /libnetcdf.a file.

reading from setup.cfg...
using nc-config ...
unable to detect netcdf library versionrunning build
running build_py
running build_ext
building 'netCDF4' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/home/WRF/LIBRARIES//netcdf/include -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c netCDF4.c -o build/temp.linux-x86_64-2.7/netCDF4.o
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from netCDF4.c:250:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
netCDF4.c: In function ‘__pyx_f_7netCDF4__find_cmptype’:
netCDF4.c:67616:34: warning: ‘__pyx_v_xtype’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             return PyInt_FromLong((long) value);
                                  ^
netCDF4.c:56264:11: note: ‘__pyx_v_xtype’ was declared here
   nc_type __pyx_v_xtype;
           ^
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/netCDF4.o -L/home/khammerb/WRF/LIBRARIES//netcdf/lib -Wl,-R/home/WRF/LIBRARIES//netcdf/lib -lnetcdf -lm -o build/lib.linux-x86_64-2.7/netCDF4.so
/usr/bin/ld: /home/WRF/LIBRARIES//netcdf/lib/libnetcdf.a(libdispatch_la-error.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/home/WRF/LIBRARIES//netcdf/lib/libnetcdf.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by KrisHammerberg** [comment]
So this seems to be a problem with shared vs. static libraries. I built netCDF from source to work with WRF and likely didn't include the --enable-shared flag. I guess I need to rebuild it and hope it doesn't unravel my install of WRF... *cringe*

**Comment by jswhit** [comment]
You could also recompile the static library, but included the -fPIC compiler flag.

**Comment by KrisHammerberg** [comment]
I opted to build netCDF again into the more typical /usr/local location with the --enabled-shared flag. This has allowed me to install netcdf-python and hopefully hasn't broken anything else, but for the purposes of this issue, I declare it closed.
