### ISSUE TITLE
nc4tonc3 -h fails due to indentation errors

### ISSUE THREAD

**Issue by RossGammon** [Unidata/netcdf4-python#378]
Hi,
In the Debian GIS Team we are trying to package netcdf4-python. During testing I discovered that running nc4tonc3 -h fails because Tabs have been used in one place instead of spaces.
A pull Request is on it's way.
Regards,
Ross

**Comment by jswhit** [comment]
Thanks!  I just ran the python reindent.py utility on all the *py and *pyx files and fixed quite a few more of these (pull request #380).
