### ISSUE TITLE
Bug when add_offset is used without scale_factor

### ISSUE THREAD

**Issue by davidhassell** [Unidata/netcdf4-python#381]
Hi, 

I think that the in-place addition for adding an ```add_offset``` in the absence of a ```scale_factor```  should be replaced with a not-in-place one. I.e (line 3158 in netCDF4.pyx):
```
elif hasattr(self, 'add_offset') and self.add_offset != 0.0:
    data += self.add_offset
```
should become something like:
```
elif hasattr(self, 'add_offset') and self.add_offset != 0.0:
    data = data + self.add_offset
```

This change ensures that the returned numby array is the correct dtype, in the case that the original data is, for example, of type ```short```.

Do you think that that's right?

Many thanks and all the best,

David Hassell

**Comment by dopplershift** [comment]
Given that we're already doing magic to apply scale/offset, it seems only fair that we do it correctly. :)

**Comment by jswhit** [comment]
I agree we should do it correctly - but it's not obvious to me why in-place addition does not work here.  Are you expecting a short array to be returned?  This will not be the case, since the "magic" Ryan refers to means that a float array (with scale_factor and add_offset applied) will be returned.  If you want the raw short data returned, you need to explicitly turn the magic off (with the set_auto_maskandscale variable method).

**Comment by dopplershift** [comment]
I think that's precisely the point--if you use in place operations, results will be converted back to short, which can quite often produce odd results. This is especially the case if you have packed short data and expect using float scale/offset returns proper floating point. The current code won't do this.

**Comment by jswhit** [comment]
Are you sure?

   import numpy as np
   add_offset = np.array(1, np.int16)
   data = np.ones(10, np.float32)
   data += add_offset
   print data.dtype
   print data

gives

   float32
   [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]

**Comment by jswhit** [comment]
Never mind - I see I've got it backwards.  add_offset is float and data is short, in which case data is still short with an in-place addition.

**Comment by dopplershift** [comment]
Bingo.

**Comment by jswhit** [comment]
pull request #382

**Comment by davidhassell** [comment]
Hi,

You've been busy whilst I've been having a relaxing evening! Ryan summed it up perfectly. Thanks for your time and help.

All the best,

David
