### ISSUE TITLE
Runtime detection of indexing semantics

### ISSUE THREAD

**Issue by rhattersley** [Unidata/netcdf4-python#385]
netCDF4 and numpy differ in how they treat tuple/array indexing arguments:
```python
>>> type(v)
<type 'netCDF4.Variable'>
>>> v.shape
(240, 37, 49)
>>> v[(0, 1), (0, 2, 3)].shape
(2, 3, 49)
>>> np.array(v)[(0, 1), (0, 2, 3)].shape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 
```

It's something of a long shot, but ... given an object that supports indexing, how can I determine at runtime which of these two styles it supports?

I like to avoid `isinstance(v, netCDF4.Variable)`, or probing the behaviour with something like `v[(0, 1), (0, 2, 3), 0]` as it could have a relatively large cost.

**Comment by jswhit** [comment]
hasattr(v,'_varid') ?

**Comment by shoyer** [comment]
The best I've come up with is using isinstance checks. Which actually seems to work OK, for the most part. I've found most stores support neither type of fancy indexing with multiple arrays, unless they are just proxying indexing on to a library like netCDF4 or numpy.

The other option is coming is up with some sort of convention for how to mark "orthogonally" indexed arrays such as some special attribute.

**Comment by rhattersley** [comment]
> The best I've come up with is using isinstance checks.

That's what I'm inclined to use, unless ...

> The other option is coming is up with some sort of convention for how to mark "orthogonally" indexed arrays

... this gets some traction. But that would need to involve other libraries. Does xray support one (or both?) of these indexing styles?

**Comment by dopplershift** [comment]
Couldn't we just standardize on what numpy itself supports?

```python
import numpy as np
a = np.zeros((240,37,49))
print a[np.array([0,1])[:,None], np.array([0,2,3])].shape
```
prints `(2,3,49)` for me. Essentially, instead of tuples, you need to pass in arrays that can broadcast against each other.

**Comment by jswhit** [comment]
Or just

    print a[(0,1),:,:][:,[0,2,3]].shape

This works for netcdf variables too, but it is probably a lot slower since it reads more data.

    import numpy as np
    from netCDF4 import Dataset
    a = np.zeros((240,37,49))
    print a[(0,1),:,:][:,[0,2,3]].shape
    nc = Dataset('test.nc','w')
    xd = nc.createDimension('x',240)
    yd = nc.createDimension('y',37)
    zd = nc.createDimension('z',49)
    v = nc.createVariable('v',np.float,('x','y','z'))
    print v[(0,1),:,:][:,[0,2,3]].shape
    nc.close()

**Comment by jswhit** [comment]
Pull request #386 allows Ryan's example to work on both numpy arrays and netcdf variables, so that

    import numpy as np
    from netCDF4 import Dataset
    n1 = 240; n2 = 37; n3 = 49
    a = np.arange(n1*n2*n3).reshape((n1,n2,n3))
    aa = a[np.array([0,1])[:,None], np.array([0,2,3])]
    print aa.shape
    nc = Dataset('test.nc','w')
    xd = nc.createDimension('x',n1)
    yd = nc.createDimension('y',n2)
    zd = nc.createDimension('z',n3)
    v = nc.createVariable('v',np.float,('x','y','z'))
    v[:] = a
    vv = v[np.array([0,1])[:,None], np.array([0,2,3])]
    print vv.shape
    print np.abs(vv-aa).max()

gives 

    (2, 3, 49)
   (2, 3, 49)
   0.0

@rhattersley, does that help?

**Comment by shoyer** [comment]
@rhattersley Yes, both xray and pandas do orthogonal indexing like netCDF4, Iris and Biggus.

The problem with standardizing on what NumPy supports is that NumPy made a decision that makes sense (sort of) for NumPy arrays, but that doesn't make sense for systems that use labeled arrays. I would actually love to see a custom indexer for numpy (like `.loc` in pandas) which does orthogonal indexing. Right, that can be difficult to do efficiently in some cases.

**Comment by dopplershift** [comment]
I'm mainly talking about standardizing within NetCDF. I think here, it's entirely appropriate to match the ndarray interface/behavior whenever possible.

**Comment by jswhit** [comment]
Pull request #386 makes a small step in this direction by at least allowing for multi-dimensional index arrays when they produce the same result in numpy as orthogonal indexing with 1-d arrays.

**Comment by shoyer** [comment]
Even if we can exactly copy NumPy indexing exactly in this case, I'm still not sure that's a good idea. It suggests to users that numpy's broadcasting indexing is how netCDF4 works, which is a little misleading.

**Comment by jswhit** [comment]
I agree that there is not much to gain by allowing multi-dimensonal indices in those special cases when they behave the same as in numpy, given the potential for confusion.

**Comment by jswhit** [comment]
One could create a numpy-like object (as a sub-class of ndarray) that has the same indexing behavior as netcd4-python (and xray, iris, Biggus).    Don't know whether that would help @rhattersley or not.

**Comment by shoyer** [comment]
@jswhit Indeed, I wrote something like that already for xray:
https://github.com/xray/xray/blob/0d164d848401209971ded33aea2880c1fdc892cb/xray/core/variable.py#L128

As you'll notice in the comments, @rhattersley wrote something very similar in biggus.

**Comment by jswhit** [comment]
Nice!  Would there be any benefit to having netcdf4-python return those objects instead of numpy arrays?  That way you could  perform the same slicing operations on the returned array object as the original netcdf variable. I imagine that could cause all kinds of issues in downstream code though.

**Comment by shoyer** [comment]
I think it is a useful thing to have on reference for library writers, and we could consider including it as an option on netCDF4 variables (like mask and scale), but we shouldn't make it the default. There is a lot of value in returning standard objects.

**Comment by rhattersley** [comment]
Thanks for all the comments - much appreciated!

For the short-term, I'm happy to stick with isinstance. In the longer term it would still be nice if objects had some standard way to state that they provide orthogonal indexing. I'd happily implement such a thing in Iris & Biggus. Perhaps @shoyer's "special attribute" suggestion? (There's also the question of *where* to have this discussion - sorry for littering the netcdf4-python issue tracker! :wink: Perhaps a PEP??)

**Comment by jswhit** [comment]
A special attribute sounds like a reasonable idea to me (and here is as good a place as any to discuss it).  How about "__orthogonal_indexing__"?

Has anyone ever approached the numpy developers about supporting orthogonal indexing, at least as an option?

**Comment by shoyer** [comment]
`getattr(array, '__orthogonal_indexing__', False)` for runtime indexing checks seems about as good as we're going to get.

@jswhit I think the numpy developers would be quite open to the idea if it's implemented as separate indexer attribute (maybe `array.ix_[...]`?). Numpy already has some work arounds, namely the [`np.ix_`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ix_.html) function, but frankly it's a lot more awkward and not as fully featured as a real indexer (e.g., you can't mix arrays with slices). My guess is that the idea of multiple indexers simply never occurred to anyone as an option. Someone should raise the issue on the numpy-discussion list :).

**Comment by jswhit** [comment]
pull request #387 adds ``Variable.__orthogonal_indexing__=True``

**Comment by rhattersley** [comment]
> Someone should raise the issue on the numpy-discussion list :).

http://mail.scipy.org/pipermail/numpy-discussion/2015-April/072587.html

**Comment by jswhit** [comment]
Uh oh - that was the first post on April 1

**Comment by rhattersley** [comment]
> Uh oh - that was the first post on April 1

Good! That stops someone else from having the first post as nonsense instead. (Bah! Humbug! etc.)

**Comment by rhattersley** [comment]
> (Bah! Humbug! etc.)

Cultural disclaimer ... we don't really do the whole April fools day thing in the UK very much. :wink:
