### ISSUE TITLE
v1.1.7 > 100 MB ?

### ISSUE THREAD

**Issue by zerothi** [Unidata/netcdf4-python#395]
I have just tried downloading 1.1.7 from the release page.

It chips it at 120 MB. All previous releases are below 1MB.   
The reason is the examples/data directory with 13 netcdf files.  
Is it really necessary to have 132 MB of nc files lying in the tar?

I think not.

**Comment by jswhit** [comment]
the tarball on pypi is 599kb

(see https://pypi.python.org/pypi/netCDF4?)

If you clone the entire github repo, it is close to 120mb.  That's apparently what you get on the github releases page.

**Comment by jswhit** [comment]
I just added a .gitattributes file that tells github to exclude examples/data from the releases tarball.  It should be about 700kb for 1.1.8.

**Comment by zerothi** [comment]
:+1: 
Ok, I am just used to following this site. 

Might I suggest to create a new repo with netcdf4-python-tests and have that as a sub-repo for netcdf4-python?
That would limit the repo size when forking, cloning, and the tests can always be tracked :)

**Comment by zerothi** [comment]
Oh... I have actually just created a PR for that exact thing. You can close it if you want? :)
