### ISSUE TITLE
is there a function to flatten a dataset?

### ISSUE THREAD

**Issue by mtpain** [Unidata/netcdf4-python#397]
In the NCO [`ncks`](http://nco.sourceforge.net/nco.html#ncks-netCDF-Kitchen-Sink) there's a way to [flatten groups](http://nco.sourceforge.net/nco.html#Flattening-Groups). Now it wouldn't be too much to do manually, but is there a built-in method for doing this with NetCDF4-python?

**Comment by jswhit** [comment]
There is nothing currently, although I suppose it would not be too hard to write a utility function to to this.  I forsee problems with name collisions - for example, if two different groups have identically named variables.

**Comment by mtpain** [comment]
Ok, yes I could see that. I don't see any obvious documentation on how ncks handles this. How do you think name collisions could be handled? Maybe append group name on a name collision?

**Comment by jswhit** [comment]
What is the use case you're thinking of?

**Comment by mtpain** [comment]
I'm working on running hydrological models interchangeably with NetCDF as the reference data format. I want to take advantage of groups to encode the structure of a particular input or output scheme used by a particular model. However I also want to write generic checkers to see if the right variables are available to use the data as inputs to a different model, and then a similarly generic transformer to re-write the data specific for a particular model. So I was thinking of that generic piece as using a flattening routine to give a list of all variables and use each variable's CF `standard_names` to do the checking and mapping.

Does that make sense? 

It really isn't too much for my use case to just join a few lists by recursing through each group. Or perhaps there is a python built-in that would work?

**Comment by jswhit** [comment]
It's pretty easy to iterate through all the groups in a dataset - see the 'walktree' generator in the tutorial at http://unidata.github.io/netcdf4-python/.  Could you use a generator like that to check all the variables, instead of 'flattening' the dataset?

**Comment by mtpain** [comment]
Yes, that may even be more suitable for this use case. Thanks!
