### ISSUE TITLE
Group specific dimensions

### ISSUE THREAD

**Issue by shoyer** [Unidata/netcdf4-python#398]
I don't actually have a use case for this (currently), but reading the netCDF docs suggest that it is possible to create dimensions associated with particular groups on a netCDF4 file:
https://www.unidata.ucar.edu/software/netcdf/docs/netcdf/Data-Model.html

From the perspective of the HDF5 file format, sub-group specific dimensions (or rather *dimension scales*) are very natural, and some users find this to be very useful. It would be nice to support this in the Python API.

xref https://github.com/xray/xray/issues/66

**Comment by zerothi** [comment]
I do not quite follow the issue? 
As I understand, it is whether dimensions can exist/be created in sub-groups of a netcdf4 file?

I use dimensions with same same names in different groups, and use netcdf4-python to read that data, without problems, or am I missing something? Isn't it inherently in the python API?
I also use netcdf4-python to create a netcdf4 file with different sub-group dimensions.

I tried to read the xref, but could not figure out what was meant.

Disclaimer, I may completely misunderstand the issue! ;)

**Comment by shoyer** [comment]
You're right, this is actually already supported by netCDF4-python. Oops!

(I missed that Group is a subclass of Dataset.)

**Comment by zerothi** [comment]
:+1:
