### ISSUE TITLE
num2date fails to process certain time units

### ISSUE THREAD

**Issue by benjwadams** [Unidata/netcdf4-python#402]
I noticed that the `num2date` function only parses certain types of units in the dates.

Units such as 'second' or 'minutes' are allowed, but 'sec' or 'mins' failed, despite both forms being valid UDUNITS time units, as far I am aware. 
Looked in the NetCDF users guide and didn't really see much in the way of suggestions for how dates should be formatted.  Obviously not all NetCDF files follow CF conventions, but CF does mention that 

> "The acceptable units for time are listed in the udunits.dat file. The most commonly used of these strings (and their abbreviations) includes day (d) , hour (hr, h) , minute (min) and second (sec, s) . Plural forms are also acceptable ..."

Source: http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#time-coordinate

So in short, I'm wondering why a snippet like this shouldn't work
    
    import netCDF4
    import numpy as np
    # fails!
    times = netCDF4.num2date(np.arange(10), 'secs since 2014-01-01Z')

Substituting 'seconds' or 'second' for 'secs', this will work.  But I'm wondering why not not the abbreviated form as all forms appear to be valid udunits time units.

Running this, we get `UnboundLocalError: local variable 'tsecs' referenced before assignment`  suggesting an inexhaustive match for unit patterns.

Indeed, we see this here:
https://github.com/Unidata/netcdf4-python/blob/master/netcdftime/netcdftime.py#L791-L802

I understand this package no longer comes bundled with udunits support by default, but this could be fairly easily fixed by introducing a couple more forms for the units used and placing and `else` clause raising `ValueError` or similar at the end of the `elif`s if the unit was not found.

**Comment by jswhit** [comment]
Honestly, I never even thought about allowing for abbreviations in the units definition.  As you say, should be easy to fix though.  Seems like 's since' should also be allowed.

**Comment by jswhit** [comment]
see pull request #403

**Comment by jswhit** [comment]
merged pull request #403, closing now...
