### ISSUE TITLE
year out of range ValueError in dateparse

### ISSUE THREAD

**Issue by bekozi** [Unidata/netcdf4-python#407]
Hi. I am getting an error in ``date2num/dateparse`` that starts in version 1.1.5 (I think - couldn't test 1.1.5 directly due to build issues) and is still present in 1.1.7. I am using libnetcdf v4.3.3.1.

```sh
======================================================================
ERROR: test_dateparse (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_date2num.py", line 16, in test_dateparse
    netCDF4.date2num(time_values, units, calendar=calendar)
  File "utils.pyx", line 120, in netCDF4.date2num (netCDF4.c:4096)
  File "utils.pyx", line 21, in netCDF4._dateparse (netCDF4.c:3034)
ValueError: year is out of range

----------------------------------------------------------------------
```

I put together a test case: https://gist.github.com/bekozi/fdc47cb936d34ced362a. It could be user error, but the test case seems pretty straightforward.

**Comment by shoyer** [comment]
I'm pretty sure the problem is that the year 0 is not defined for the standard calendar:
http://en.wikipedia.org/wiki/0_%28year%29

**Comment by bekozi** [comment]
Yup, that is the issue. I was allowed to misbehave in previous versions. Thanks!
