### ISSUE TITLE
Consider moving netcdf4.so into own package?

### ISSUE THREAD

**Issue by matthew-brett** [Unidata/netcdf4-python#408]
I am trying to set up a repository to do automated builds of OSX wheels:

https://github.com/MacPython/netcdf4-python-wheels

This is not yet working, because the tools that I am using (and wrote) can't easily work on compiled libraries that are not in their own package directory.  So, I can't easily work on `netCDF4.so` which is being installed straight into `site-packages` without an enclosing `netCDF4` folder.

Have you considered moving `netCDF4` into its own package?

I mean, something like `netCDF4/__init__.py` with `from ._netcdf4.so import *` or similar?  Maybe with a `site-packages/netcdf4_utils.py` doing `from netcdf4.utils import *`?

**Comment by jswhit** [comment]
how about a pull request?

**Comment by matthew-brett** [comment]
How about https://github.com/Unidata/netcdf4-python/pull/409 ?

**Comment by jswhit** [comment]
pull request #409 merged, closing now.
