### ISSUE TITLE
masked arrays and set_auto_maskandscale

### ISSUE THREAD

**Issue by ocehugo** [Unidata/netcdf4-python#410]
I imagine that there is support for numpy masked arrays directly from netcdf4-python right!?

  https://code.google.com/p/netcdf4-python/issues/detail?id=173

This point to a yes, but the current behaviour is not as described in this older issue.

I'm reading a variable with a _FillValue attribute, but Dataset class ignore this completely and returns me an array with the _FillValues inside the ndarray.

I would expect that if the netcdf variable has the attribute _FillValue, the returned array from dataset.variables[var] would be a numpy.ma array.

I'm also unable to use the ```set_auto_maskandscale``` method. setting this True/False doesn't change the output array when working with the dataset object. I suspect that this is only used for writing!?

snippet:
```
In [5]: A.variables['temp'].set_auto_maskandscale(True)

In [6]: A.variables['temp'][0,22,...]
Out[6]:
array([[ 13.42983441,  13.42936089,  13.43977819, ...,  10.05841723,
         10.05841723,  10.05841723],
       [ 13.43030792,  13.43835765,  13.45587766, ...,  10.05841723,
         10.05841723,  10.05841723],
       [ 13.44806468,  13.43456954,  13.46724198, ...,  10.05841723,
         10.05841723,  10.05841723],
       ...,
       [ 17.15023114,  17.08157166,  17.02711759, ...,  10.05841723,
         10.05841723,  10.05841723],
       [ 10.05841723,  10.05841723,  10.05841723, ...,  10.05841723,
         10.05841723,  10.05841723],
       [ 10.05841723,  10.05841723,  10.05841723, ...,  10.05841723,
         10.05841723,  10.05841723]])

In [7]: A.variables['temp'].set_auto_maskandscale(False)

In [8]: A.variables['temp'][0,22,...]
Out[8]:
array([[ 13.42983441,  13.42936089,  13.43977819, ...,  10.05841723,
         10.05841723,  10.05841723],
       [ 13.43030792,  13.43835765,  13.45587766, ...,  10.05841723,
         10.05841723,  10.05841723],
       [ 13.44806468,  13.43456954,  13.46724198, ...,  10.05841723,
         10.05841723,  10.05841723],
       ...,
       [ 17.15023114,  17.08157166,  17.02711759, ...,  10.05841723,
         10.05841723,  10.05841723],
       [ 10.05841723,  10.05841723,  10.05841723, ...,  10.05841723,
         10.05841723,  10.05841723],
       [ 10.05841723,  10.05841723,  10.05841723, ...,  10.05841723,
         10.05841723,  10.05841723]])
```

 The 10.0584 was supposed to be masked since its the FillValue.

any tips how to read 'temp' as a masked array? Any support to assign masked values directly to nan when setting the masked array!?

I would like to avoid searching the fillvalue, creating a masked array from it and assigning a new value to each variable...

**Comment by mdecker** [comment]
So you are trying to mask a float/double? To me this looks like a rounding problem. Have you verified that the _FillValue and the data you want to mask are actually 100% bit-identical? Except if you abbreviated the number in your explanation it can clearly not work.

**Comment by ocehugo** [comment]
mdecker,
yes the problem in the example above was a rounding problem. I was trying to force by editing the FillValue attribute... but nevermind, I found the problem. 

My fillvalue attribute was changing when packing some netcdf3 files and I was losing the masking information...I note that when looking in ncview. The problem was that since my ncview colorbar has a white color, and my field had a lot of missing values, I didn't noted that the fields were not masked but instead was being plotted as real values.

Indeed this was the case since a lot of points were missing and my colorbar was scrambled centered around the supposed missing value (to my bad luck towards white).
