### ISSUE TITLE
data attribute on variable instance?

### ISSUE THREAD

**Issue by brorfred** [Unidata/netcdf4-python#413]
It seems like netcdf-python is missing the data attribute on variable instances? This would be great to have, both as a interface call that can handle scalars and arrays, and to make it more backward compatible with scipy.io.netcdf_file.

**Comment by jswhit** [comment]
How would ``v.data`` be any different than ``v`` itself?  Would ``v.data`` be a numpy array with all the data in the netcdf variable?  Or would it be lazily evaluated to a numpy array when you slice it?  If it's the latter, then it's no different the the netcdf Variable object itself (``v``).  The former would be dangerous, since accessing the ``data`` attribute could easily fill up available memory.

**Comment by jswhit** [comment]
BTW - the netcdf4-python was designed to be mostly backwards compatible with Konrad Hinsen's Scientific.IO.NetCDF module, as was pupnyere (scipy.io.netcdf_file).  I don't think Scientific.IO.NetCDF variable instances have a ``data`` attribute.

**Comment by brorfred** [comment]
The main benefit with v.data is that scalars are handled transparently. At least scipy.io.netcdf_file raises an error when a scalar variable is accessed via v[:]  since the data type can't be indexed. This means that you need to access array data via slicing and scalar data via v.getValue(), which is quite messy for beginners or exploratory scripts. My assumption is that scipy.io.netcdf_file solves this by using a conditional statement in v.data, that calls the respective access methods depending on datatype.  This approach also provide an interface that can handle cases where scalar data are both coded with a scalar data type and as a one-element array.

**Comment by shoyer** [comment]
@brorfred The cross-compatible way to access scalar/non-scalar variables as arrays is to use either: `np.asarray(v)` or `v[...]`. It's probably worth calling this out more explicitly in the documentation -- there's no good reason to use `getValue()`. I'm pretty sure `v[:]` also works (or worked) for scalar arrays with netCDF4-Python at one point, but that should probably be considered a bug.

**Comment by brorfred** [comment]
Hm, I tried a dataset with a scalar value (a gridfile for ROMS). It seems like you are right that scipy.io.netcd_file doesn't allow slicing a scalar while netCDF4-python does: 

In [43]: from scipy.io import netcdf_file
In [44]: nc = netcdf_file("coral_grd.nc")
In [45]: nc.variables['el'][:]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-45-71b55d1ccfc1> in <module>()
----> 1 nc.variables['el'][:]

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/io/netcdf.pyc in __getitem__(self, index)
    917 
    918     def __getitem__(self, index):
--> 919         return self.data[index]
    920 
    921     def __setitem__(self, index, data):

IndexError: too many indices for array

In [46]: nc.variables['el'].data
Out[46]: array(3873600.8003949076)


from netCDF4 import Dataset
In [47]: nc = Dataset("coral_grd.nc")
In [48]: nc.variables['el'][:]
Out[48]: 3873600.8003949076

np.asarray doesn't work for either package:

In [54]: nc = netcdf_file("coral_grd.nc")
In [55]: asarray(nc.variables['el'])
Out[55]: array(<scipy.io.netcdf.netcdf_variable object at 0x1130468d0>, dtype=object)

In [56]: nc = Dataset("coral_grd.nc")
In [57]: asarray(nc.variables['el'])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-57-29a550443e92> in <module>()
----> 1 asarray(nc.variables['el'])

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/numeric.pyc in asarray(a, dtype, order)
    460 
    461     """
--> 462     return array(a, dtype, copy=False, order=order)
    463 
    464 def asanyarray(a, dtype=None, order=None):

ValueError: object __array__ method not producing an array

Ellipses works for both:

In [61]: nc.variables['el'][...]
Out[61]: array(3873600.8003949076)
In [62]: nc = Dataset("coral_grd.nc")
In [63]: nc.variables['el'][...]
Out[63]: 3873600.8003949076

So  ellipses is a cross-compatible way to read data, which is great! It's not the most common way though,  at least at least for me. I agree that this could be stressed more explicitly as the preferred way if slicing isn't needed. One netCDF4-python iPython notebook seems to use slicing to read a scalar: http://nbviewer.ipython.org/github/Unidata/netcdf4-python/blob/master/examples/reading_netCDF.ipynb.

There might be a reason to add v.data for some extra compatibility with scipy.io.netcdf_file. Maybe just an @property decorated method that calls  np.asarray(self)?

**Comment by shoyer** [comment]
Interesting. It looks like there is a bug for netCDF4-python with `__array__` with scalar variables.... and apparently nobody ever bothered to add that method to `scipy.io.netcdf`.

Adding `v.data` to netCDF4-python does have some appeal, but ultimately I don't think it's a good idea. The difference is that in scipy, `v.data` is typically a memory-mapped numpy array to the values. In contrast, it's generally not possible to memory map the data from a netCDF4 variable.

**Comment by dopplershift** [comment]
+1 on making np.asarray() work

**Comment by jswhit** [comment]
v[...] returns a numpy scalar, not a scalar array.  That's why np.asarray(v[...]) doesn't work.

**Comment by dopplershift** [comment]
Isn't the problem that `np.asarray(v)` doesn't work for a variable that contains a scalar? To me that's different from `np.asarray(v[...])` being broken.

**Comment by jswhit** [comment]
`__array__` does this:
    
    def __array__(self)
            return self[...]

For a scalar variable, self[...] returns a numpy scalar, not a numpy scalar array.

**Comment by shoyer** [comment]
I'm pretty sure the fixed version of `__array__` would just be:
```python
def __array__(self):
    return np.asarray(self[...])
```

**Comment by jswhit** [comment]
Yep, that should do it.

**Comment by shoyer** [comment]
There's also a case for making `v[...]` always return a numpy array, even if it 0d.

**Comment by jswhit** [comment]
numpy scalars and scalar arrays are extremely annoying.

**Comment by jswhit** [comment]
I added this to pull request #414 

    @@ -3239,9 +3239,9 @@ rename a L{Variable} attribute named C{oldname} to C{newname}."""
             if hasattr(data,'shape'):
                 data = data[tuple(squeeze)]
             if hasattr(data,'ndim') and self.ndim == 0:
    -            # Make sure a numpy scalar is returned instead of a 1-d array of
    +            # Make sure a numpy scalar array is returned instead of a 1-d array of
                 # length 1.
    -            if data.ndim != 0: data = data[0]
    +            if data.ndim != 0: data = numpy.asarray(data[0])

Now `v[...]` returns a scalar array (instead of just a scalar) when `v` is a scalar variable.
