### ISSUE TITLE
Cannot add datetime.deltatime to phony datetime object

### ISSUE THREAD

**Issue by pagecp** [Unidata/netcdf4-python#416]
Hi everyone,

I am quite new using netcdf4-python, and I would like to know if it is possible add support to + and - operations for phony datetime objects?
If not, can a workaround be described in the doc?

Best regards,

Christian

**Comment by jswhit** [comment]
I presume you are converting numeric netcdf time variables into datetime objects?  You could just do the time arithmetic in numeric time units, then convert to a datetime object.  The intent of the 'phony' datetime object was to be able to return the calendar date information in a consistent way, even for calendars not supported by the python datetime module.  I never intended to support all of the functionality of the 'real' python datetime object.

**Comment by pagecp** [comment]
Yes, indeed, this is what I do. In fact I just solve the problem this afternoon by converting to time values, adding the delta time I want, then converting back. It works flawlessly! But maybe it could be a good addition to the library to add this functionality. Best regards
