### ISSUE TITLE
Subclassing netcdf4 classes / private attributes

### ISSUE THREAD

**Issue by cpaulik** [Unidata/netcdf4-python#419]
Hi,

I'm currently trying to write a few classes that make creation/handling of netCDF files according to the [CFConventions](http://cfconventions.org/) easier. My first thought was to inherit from the existing netCDF4 classes. Unfortunately this does not really work since I can not use any attributes in the subclasses except the ones on the `_private_atts` list. 

Would you consider e.g. making available all attributes starting and ending with `__` as python level attributes?

**Comment by jswhit** [comment]
Sorry, but I don't really understand what the problem is.  Can you provide an example?  Just playing around in the interpreter I did:

    >>> from netCDF4 import Dataset
    >>> class Dataset2(Dataset):
    ...     pass
    ...
    >>> ds = Dataset2('file.nc','w')
    >>> ds
    <class '__main__.Dataset2'>
    root group (NETCDF4 data model, file format HDF5):
        dimensions(sizes):
        variables(dimensions):
        groups:
    >>> ds.path
    '/'
    >>> v = ds.createVariable('x',float)
    >>> v._grpid
    65536
    >>> v.mask
    True

**Comment by cpaulik** [comment]
In the subclass I would need a few attributes that I can use to store things on a python level which should not be written to the netCDF file as global attributes. 

e.g. `own_var` could be some variable related to the CFConventions.

```python
In [1]: from netCDF4 import Dataset

In [2]: class Dataset2(Dataset):
   ...:     def __init__(self, filename, own_var, **kwargs):
   ...:         self.__own_var__ = own_var
   ...:         super(Dataset2, self).__init__(filename, **kwargs)
   ...:         

In [3]: ds = Dataset2('file.nc', 'var', mode='w')
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-4c31e4d7cc88> in <module>()
----> 1 ds = Dataset2('file.nc', 'var', mode='w')

<ipython-input-2-d977a14eba80> in __init__(self, filename, own_var, **kwargs)
      1 class Dataset2(Dataset):
      2     def __init__(self, filename, own_var, **kwargs):
----> 3         self.__own_var__ = own_var
      4         super(Dataset2, self).__init__(filename, **kwargs)
      5 

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__setattr__ (netCDF4/_netCDF4.c:15187)()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.setncattr (netCDF4/_netCDF4.c:14352)()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4._set_att (netCDF4/_netCDF4.c:4839)()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4._get_format (netCDF4/_netCDF4.c:4563)()

RuntimeError: NetCDF: Not a valid ID
```

I hope this makes it clearer.

**Comment by jswhit** [comment]
Just use self.__dict__, like this

    from netCDF4 import Dataset
    class Dataset2(Dataset):
         def __init__(self, filename, own_var, **kwargs):
             self.__dict__['__own_var__'] = own_var
         super(Dataset2, self).__init__(filename, **kwargs)
    ds = Dataset2('file.nc', 'var', mode='w')
    print ds.__own_var__

**Comment by cpaulik** [comment]
The issue with the `__dict__` solution is that this leads to somewhat strange behavior, and is very unwieldy to work with:

```python

In [1]: from netCDF4 import Dataset

In [2]: class Dataset2(Dataset):
    def __init__(self, filename, own_var, **kwargs):
        super(Dataset2, self).__init__(filename, **kwargs)
        self.__dict__['__own_var__'] = own_var
   ...:         

In [3]: ds = Dataset2('file.nc', 'var', mode='w')

In [4]: ds.__own_var__
Out[4]: 'var'

In [5]: ds.__own_var__ = 'variable'

In [6]: ds.__own_var__
Out[6]: 'var'

```
 Now `__own_var__` is both written to the netCDF file and also a python level attribute. But they have different values.

But, thinking about it I might not subclass them anyway since it would make it difficult to support different netCDF libraries if ever necessary. 

Also changing this behavior in any way could break code of people using netCDF attributes like `__attribute__`. Although I doubt that would be a lot of people.

Sorry for the noise and thanks for taking a look.

**Comment by jswhit** [comment]
You have to use __dict__ consistently for python level attributes. As long as they are all private attributes (not to be set by client code) I don't see a problem.  That's the way I do it in MFDataset (which is a subclass).  I guess I don't really understand what you are trying to do - do you want users to be able to set arbitrary python level attributes?

**Comment by cpaulik** [comment]
The solution you suggested works fine for my needs, just that it is not very "pretty", but I see now that that is probably unavoidable in the backend if the user facing API should be beautiful for setting attributes.

**Comment by shoyer** [comment]
you probably know this already, but generally speaking it's a far better pattern to use composition rather than subclassing from third party libraries.

**Comment by cpaulik** [comment]
@shoyer Thanks. That's what I've done in the past. Looking back I don't know what benefit I thought subclassing would bring.
