### ISSUE TITLE
len() on empty variable fails.

### ISSUE THREAD

**Issue by brorfred** [Unidata/netcdf4-python#420]
I get an error when trying to use len() on an empty variable, instead of an expected 0. 

The file I'm working with is: http://brorfred.org/argo/6901860_meta.nc 

I started with
```python
from netCDF4 import Dataset
nc = Dataset("6901860_meta.nc")
var = nc.variables['LAUNCH_QC']
```
The variable seems to be empty:
```python
print var
<type 'netCDF4.Variable'>
|S1 LAUNCH_QC()
    long_name: Quality on launch date, time and location
    conventions: Argo reference table 2
    _FillValue:  
unlimited dimensions: 
current shape = ()
filling off
```
len() give an error that I didn't expect:
```python
len(var)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-217-8e90ee0af111> in <module>()
----> 1 len(var)

netCDF4.pyx in netCDF4.Variable.__len__ (netCDF4.c:49854)()

IndexError: tuple index out of range
```

**Comment by jswhit** [comment]
I agree, that's not a very useful error.  Pull request #421 changes that error to "TypeError: len() of unsized object".  That's the same error you get when you do len() on a scalar numpy array.

**Comment by jswhit** [comment]
merge pull request #421.  len() still gives an error on a scalar variable (as it should), but the error is now more informative.
