### ISSUE TITLE
Any way to copy the dimension information of a Dataset or even the data?

### ISSUE THREAD

**Issue by ChaoYue** [Unidata/netcdf4-python#422]
I don't know whether this could be a generally interesting user case. For me sometimes, I just need to do some mathematical manipulation of the data, like detrending using scipy. After that I would like to write the data back to a new netCDF file. In this case, I have to create a new netCDF file, basically I would need to re-create all relevant dimensions and the variables having a single dimension (this is what I mean by "basic information" in the title) in the newly created file. I find this could be a bit tedious. Would it be nice if we have something like copy the original data into a new Dataset object, and allow the user just replace some variables in the new data set and write it out? I don't know whether this could be technically challenging, or there is some other reason not to have this (e.g., this would be the code "dirty"). This is something from my personal experience that could be nice, and depending on how complex it is, I can potentially contribute some time to.

**Comment by jswhit** [comment]
It's fairly straightforward to iterate over all the dimensions and variables in a Dataset using the ``dimensions`` and ``variables`` dicts.  See the ``_nc3tonc4`` function in netCDF4/utils.py as an example.  You could use that as a template for a function to create a copy of an existing Dataset object (as long as it is uses the old NETCDF3 data model - if it uses the new NETCDF4 data model it could be substantially more complicated).

**Comment by shoyer** [comment]
A nice way to handle this is to use objects for your data analysis that maintain the netcdf data model. So you might be interested in checking out [xray](http://xray.readthedocs.org/) (my project) or [iris](http://scitools.org.uk/iris/).

**Comment by jswhit** [comment]
@shoyer makes a good point - that is probably the way to go.

**Comment by ChaoYue** [comment]
@jswhit @shoyer :Thank you both for responses. Yes, _nc3tonc4 is something I am looking for. It should be sufficient for my purpose as now I am mainly working with netCDF3. Originally I mean maybe most users need something like this -- probably they're not aware of such code. But as not too many people ask this, looks like this is not bothering them. 
I will definitely take a look at xray -- in fact, I am have something similar (but very very simple) in my own function pool.
