### ISSUE TITLE
dimension of size one dropped on slicing

### ISSUE THREAD

**Issue by marqh** [Unidata/netcdf4-python#423]
hello netcdf4-python folks

I have prepared a test to illustrate a problem I am having when retrieving subsets of a variable.

The request to the netCDF variable has 3 dimensions requested, two of them are size one.  The result I get back has the correct values but the wrong shape, hence the test fails.
https://github.com/Unidata/netcdf4-python/compare/master...marqh:scalarIndex?expand=1

Do you agree that the behaviour illustrated by me test is the expected behaviour?
Is this a bug? A feature I do not understand?

many thanks
mark

**Comment by jswhit** [comment]
SIngleton dimensions in the returned numpy array are 'squeezed' out.  Many (most?)  times this is what people want - for example if you read one time level from a 3d variable with dims ``('t','y','x')`` most people expect an ``('x','y')`` array to be returned.  In your case, you're reading 9 time levels at a single ``x,y`` point and you get a 1d array with 9 time values back - which would be what I would expect.   I suppose there could be use cases when this is wrong behavior.    Perhaps you could tell us about your use case?

**Comment by jswhit** [comment]
The behavior in your example is also consistent with numpy:

    >>> from numpy import *
   >>> a = ones((10,10,10))
   >>> a[0:9,5,4].shape
   (9,)
   >>>

**Comment by marqh** [comment]
in the code I have provided in my test, I actually get back an array of:
(9, 1)
so one of the size one dimensions has been dropped and the other has not, which is different from the behaviour illustrated from numpy

I am hoping to preserve my size one dimensions in this case.  
It sounds like you're expectation is that I would not get back any size 1 dimensions

Is your expectation that you would be consistent with numpy?
Is there a syntax I can use to support my case?

thank you
mark

**Comment by marqh** [comment]
So, I think that the case I want to support is:

```
import numpy as np
a = np.ones((10,10,10))
keys = ((0, 1, 2, 3, 4, 5, 6, 7, 8), slice(5, 6, None), slice(4, 5, None))
a[keys].shape == (9, 1, 1)
```
which this library already supports, using the ```slice``` syntax

I have been confused by the lack of dropped dimensions, so, in test.tst_slicing:
```
    def test_retain_single_dims(self):
        f = Dataset(self.file, 'r')
        v = f.variables['data']
        keys = ((0, 1, 2, 3, 4, 5, 6, 7, 8), (5,6,7), (4,))
        shape = (9, 3, 1)
        data = v[keys]
        assert_equal(data.shape, shape)
```

is currently a valid test, no singleton trailing dimension is dropped. 

if there are two trailing dimensions of size one, one of them is dropped

**Comment by jswhit** [comment]
from netCDF4 import Dataset
    import numpy as np
    f = Dataset('test.nc','w')
    x = f.createDimension('x',10)
    y = f.createDimension('y',10)
    t = f.createDimension('t',None)
    v = f.createVariable('v',np.float,('t','y','x'))
    v[:] = np.ones((10,10,10),np.float)
    f.close()
    f = Dataset('test.nc')
    print v[0:9,5,4].shape
    print v[((0, 1, 2, 3, 4, 5, 6, 7, 8), (5,), (4,))].shape
    print v[((0, 1, 2, 3, 4, 5, 6, 7, 8), slice(5, 6, None), \
       slice(4, 5, None))].shape
    print v[((0, 1, 2, 3, 4, 5, 6, 7, 8), 5, 4,)].shape
    f.close()

gives

   (9,)
   (9, 1, 1)
   (9, 1, 1)
   (9,)

So, if you want to retain the singleton dims, slice with tuples or slice objects

**Comment by jswhit** [comment]
Expanding the previous example to include numpy's behavior:

```
from netCDF4 import Dataset
import numpy as np
f = Dataset('test.nc','w')
x = f.createDimension('x',10)
y = f.createDimension('y',10)
t = f.createDimension('t',None)
v = f.createVariable('v',np.float,('t','y','x'))
a = np.ones((10,10,10),np.float)
v[:] = a
f.close()
f = Dataset('test.nc')
print v[0:9,5,4].shape
print v[((0, 1, 2, 3, 4, 5, 6, 7, 8), (5,), (4,))].shape
print v[((0, 1, 2, 3, 4, 5, 6, 7, 8), slice(5, 6, None), \
       slice(4, 5, None))].shape
print v[((0, 1, 2, 3, 4, 5, 6, 7, 8), 5, 4,)].shape
print
print a[0:9,5,4].shape
print a[((0, 1, 2, 3, 4, 5, 6, 7, 8), (5,), (4,))].shape
print a[((0, 1, 2, 3, 4, 5, 6, 7, 8), slice(5, 6, None), \
       slice(4, 5, None))].shape
print a[((0, 1, 2, 3, 4, 5, 6, 7, 8), 5, 4,)].shape
f.close()
```

shows that for the case of a single element tuple slice (or single element array slice) netcdf4-python returns the singleton dimension and numpy does not.  

```
(9,)
(9, 1, 1)
(9, 1, 1)
(9,)

(9,)
(9,)
(9, 1, 1)
(9,)
```

Pull request #425 fixes this.

**Comment by shoyer** [comment]
> if there are two trailing dimensions of size one, one of them is dropped

The behavior here is an example of NumPy's slightly insane fancy indexing behavior, so I *would not* copy it in netCDF4.

RE: @jswhit's example... not entirely sure what's going on here, but it's still not behavior we want to emulate. NumPy is certainly *not* dropping all singleton dimensions -- that would be too consistent! netCDF4 is already doing the consistent thing with a single array indexer:
```
In [30]: a[:, [4], 0].shape
Out[30]: (10, 1)

In [31]: v[:, [4], 0].shape
Out[31]: (10, 1)
```

**Comment by jswhit** [comment]
@shoyer - I agree this behavior is weird and unexpected.  Pull request #425 should not be merged.

**Comment by rhattersley** [comment]
> not entirely sure what's going on here, but it's still not behavior we want to emulate

:+1:

Since #387 netCDF4 has declared its indexing behaviour as orthogonal, not "fancy", so it shouldn't be emulating the weird and wonderful behaviour of fancy indexing. Orthogonal indexing seems to be as simple as:
- Indexing with a scalar should always drop the dimension.
- Indexing with anything else should always keep the dimension.

**Comment by jswhit** [comment]
Agreed - anything else is a bug.   Given that, does the "Lazy nc index" issue imply a bug in netcdf4-python?

**Comment by rhattersley** [comment]
> does the "Lazy nc index" issue imply a bug in netcdf4-python?

Yes, and it looks like [@marqh's branch](https://github.com/Unidata/netcdf4-python/compare/master...marqh:scalarIndex?expand=1) captures that in a nice, simple test case.

**Comment by jswhit** [comment]
That test passes with github master.  It's a good one to have though - I'll add it.
