### ISSUE TITLE
netcdf4-python does not build out of the box on a Debian (pip or from github master)

### ISSUE THREAD

**Issue by jmp75** [Unidata/netcdf4-python#430]
Hi,

I have I think all the prerequisites packages to build from source, including hdf5:
```
pkg-config --cflags hdf5
## -I/usr/include/hdf5/serial 
```
but `H5public.h` fails to be included:
```
cd ~/src/github_jm/netcdf4-python
python3 setup.py build
## snipped
##creating build/temp.linux-x86_64-3.4/netCDF4
##x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.4m -c netCDF4/_netCDF4.c -o build/temp.linux-x86_64-3.4/netCDF4/_netCDF4.o
netCDF4/_netCDF4.c:237:22: fatal error: H5public.h: No such file or directory
## #include "H5public.h"
##                      ^
## compilation terminated.
```

Further information below on the environment.
Happy to submit a pull request if I find a proper fix, but am unfamiliar with python package build, so may not find my way around it.
May be a shortcoming of `nc-config` rather than netcdf4-python. 

Debian 3.16.7-ckt4-1 (2015-01-16) x86_64 GNU/Linux  
(Debian "unstable")

```
$ aptitude show libnetcdf-dev
# State: installed
# Version: 1:4.1.3-7.2
```
```
$ aptitude show libhdf5-dev
# Version: 1.8.13+docs-15
# Replaces: libhdf5-serial-dev (< 1.8.12-9~), libhdf5-serial-dev (< 1.8.12-9~)
# Provides: libhdf5-serial-dev
```

**Comment by jswhit** [comment]
You can edit setup.cfg and specify the locations of the hdf5 headers and libs (and turn off nc-config by setting use_ncconfig=False).

**Comment by jmp75** [comment]
I will use it as a workaround on my machine, but I wonder whether this is unusual. I don't think my setup is very unusual. Then again, if it was not reported...

**Comment by jswhit** [comment]
What does nc-config ``nc-config --cflags`` report?

**Comment by jswhit** [comment]
Is this still a problem?
