### ISSUE TITLE
ArcMap unable to read netcdf created by python 2.7.10/netcdf4-python 1.1.8 combination

### ISSUE THREAD

**Issue by havenerk** [Unidata/netcdf4-python#431]
I realize this is probably an ESRI ArcGIS problem but I need to be able to describe it to them and thought maybe you would understand what may have changed between python 2.7.6/1.1.x where x < 8.  Unsure at the moment what python-netcdf4 version we were running before.

Problem:  We created a netcdf4 file with a python script   After updating python a couple of days ago (and probably our python-netcdf4 module as well) ArcMap cannot read the new files.  Creating the same file with the same script on a 2.7.6/1.1.1 system results in a readable file.  Using ncdump or ncl_filedump on both files shows no difference in the seemingly valid files.

Can anyone propose a likely theory as to what is different?  A python 2.7.10 change? A python-netcdf4 change?  Anything you want me to try?

**Comment by jswhit** [comment]
Can you post the working and non-working file somewhere?  

Did the netcdf-c library version change between the two systems?

**Comment by havenerk** [comment]
Jeff,

Easy question first.  Netcdf 4.3.1.1 has not changed.  Posting outside our network is tough but I think I know a way.  It is called "AMRDEC Safe".  You can google that phrase to see what it is about.  Basically after I post them, you will get an email with a password and a link.  I will probably need standard email address rather than this github address, so if you can shoot me one, I'd appreciate it.  You can send it to kevin(DOT)havener(AT)us(DOT)af(DOT)mil.

**Comment by jswhit** [comment]
Before we try that, how about posting the result of 'ncdump -hs' on the files here. 

Also, the error message the ArcGIS spits out may be helpful.

**Comment by havenerk** [comment]
Here is the output, bad first then good.  The ArcMap error is strange.  If you browse to the problem file, ArcMap does nothing.  No error at all.  No response of any kind.  If you type the file's name and location into the proper dialog, it closes ArcMap.  ArcGIS is version 10.2.2

<<havenerk@metappdev:~/temp>>$ ncdump -hs bad_file.nc
netcdf bad_file {
dimensions:
        latitude = 361 ;
        longitude = 721 ;
        time = 1 ;
variables:
        double latitude(latitude) ;
                string latitude:units = "degrees_north" ;
                string latitude:long_name = "latitude" ;
                latitude:_Storage = "contiguous" ;
        double longitude(longitude) ;
                string longitude:units = "degrees_east" ;
                string longitude:long_name = "longitude" ;
                longitude:_Storage = "contiguous" ;
        double time(time) ;
                string time:units = "seconds since 1970-01-01 00:00:00.0 0:00" ;
                string time:long_name = "verification time generated by wgrib2 function verftime()" ;
                time:reference_time = 1425168000. ;
                time:reference_time_type = 0 ;
                string time:reference_date = "2015.03.01 00:00:00 UTC" ;
                string time:reference_time_description = "kind of product unclear, reference date is variable, min found reference date is given" ;
                string time:time_step_setting = "auto" ;
                time:time_step = 21600. ;
                time:_Storage = "contiguous" ;
        float TMP_2maboveground(time, latitude, longitude) ;
                TMP_2maboveground:_FillValue = 9.999e+20f ;
                string TMP_2maboveground:short_name = "TMP_2maboveground" ;
                string TMP_2maboveground:long_name = "Temperature" ;
                string TMP_2maboveground:level = "2 m above ground" ;
                TMP_2maboveground:units = "degrees_celsius converted from Kelvin using T - 273.15" ;
                TMP_2maboveground:_Storage = "contiguous" ;

// global attributes:
                :_Format = "netCDF-4" ;
}


<<havenerk@metappdev:~/temp>>$ ncdump -hs good_file.nc
netcdf good_file {
dimensions:
        latitude = 361 ;
        longitude = 721 ;
        time = 1 ;
variables:
        double latitude(latitude) ;
                latitude:units = "degrees_north" ;
                latitude:long_name = "latitude" ;
                latitude:_Storage = "contiguous" ;
        double longitude(longitude) ;
                longitude:units = "degrees_east" ;
                longitude:long_name = "longitude" ;
                longitude:_Storage = "contiguous" ;
        double time(time) ;
                time:units = "seconds since 1970-01-01 00:00:00.0 0:00" ;
                time:long_name = "verification time generated by wgrib2 function verftime()" ;
                time:reference_time = 1425168000. ;
                time:reference_time_type = 0 ;
                time:reference_date = "2015.03.01 00:00:00 UTC" ;
                time:reference_time_description = "kind of product unclear, reference date is variable, min found reference date is given" ;
                time:time_step_setting = "auto" ;
                time:time_step = 21600. ;
                time:_Storage = "contiguous" ;
        float TMP_2maboveground(time, latitude, longitude) ;
                TMP_2maboveground:_FillValue = 9.999e+20f ;
                TMP_2maboveground:short_name = "TMP_2maboveground" ;
                TMP_2maboveground:long_name = "Temperature" ;
                TMP_2maboveground:level = "2 m above ground" ;
                TMP_2maboveground:units = "degrees_celsius converted from Kelvin using T - 273.15" ;
                TMP_2maboveground:_Storage = "contiguous" ;

// global attributes:
                :_Format = "netCDF-4" ;
}

**Comment by havenerk** [comment]
I see I accidentally clicked a wrong box.

**Comment by jswhit** [comment]
OK, the metadata from the two files look identical.  I don't really think posting the files will help - I'm sure they will be perfectly readable in python (you probably already checked that).  Unless you can get ArcGIS to display some sort of error message to help us track this down, I think we are stuck.

**Comment by jswhit** [comment]
Do all the tests pass for netcdf4-python on the machine that produced the "bad" file?

(to run the tests, go to the 'test' directory inside the netcdf4-python tarball, and run 'python run_all.py')

**Comment by jswhit** [comment]
Any new information?

**Comment by havenerk** [comment]
Sorry, I pasted the output from tests here earlier.  Wonder what happened to them?  Maybe I wasn't logged in or something.  Anyhow...

<<havenerk@metappdev:~/python-netcdf-tests/netcdf4-python-master/test>>$ python run_all.py
not running tst_unicode3.py ...

netcdf4-python version: 1.1.8
HDF5 lib version:       1.8.12
netcdf lib version:     4.3.1.1
numpy version           1.9.2
..E...........................................................F......
======================================================================
ERROR: runTest (tst_dap.DapTestCase)
testing access of data over http using opendap
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/havenerk/python-netcdf-tests/netcdf4-python-master/test/tst_dap.py", line 22, in runTest
    ncfile = netCDF4.Dataset(URL)
  File "netCDF4/_netCDF4.pyx", line 1547, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:9831)
RuntimeError: NetCDF: Unknown file format

======================================================================
FAIL: runTest (tst_netcdftime.netcdftimeTestCase)
testing netcdftime
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/havenerk/python-netcdf-tests/netcdf4-python-master/test/tst_netcdftime.py", line 418, in runTest
    self.assertEqual(t, copy.deepcopy(t))
AssertionError: 2001-12-01 02:03:04 !=    0-01-01 00:00:00

----------------------------------------------------------------------
Ran 69 tests in 31.368s

FAILED (failures=1, errors=1)


DAP failure expected because this machine can't reach out of our network.  The netcdf time error may be important.  When opening both the good and bad files, the most recent version of Panoply will not work, citing a problem with the time coordinate in the files  An older version of Panoply will open both, however.  The original data was in grib2 format.  I am looking into what we used to convert to netcdf.  That may have been where things started to go wrong, but we do manipulate the data with python-netcdf and write it back out, too.

**Comment by jswhit** [comment]
I don't think either of those errors are significant.  The first one is because of the lack of a network connection (as you mentioned), the second one indicates that deepcopy is failing for netcdf time objects.  You must be using github master, because this was added after the 1.1.8 release.  I can't explain why deepcopy is failing, but it shouldn't affect what you are trying to do.

**Comment by havenerk** [comment]
For now, I will assume that the problem occurred during the grib2 to netcdf conversion and that python-netcdf is tolerant of whatever error was made and just brings it along when we import into python for our manipulation and writes it back out just like it read it in.  If you don't mind leaving this open for a couple more weeks while I run some of that to ground.  If you don't hear anything from me in those two weeks just close it and I'll re-open with more useful info next time if I need to.

**Comment by havenerk** [comment]
Here is the script that we use to write the faulty files.  It basically reads in three netcdfs, does some averaging/anomaly calculation and writes the result back out as a netcdf.  It was modified here to take 3 particular input files (months) for testing, Older versions of the python/netcdf/numpy combo seem to work OK.  Can you see where we are making a bad choice in writing out the netcdf that might cause it to break when it didn't before.  We aren't particularly skilled in the ins and outs of netcdf yet.

    #!/usr/bin/env python
    #-*- coding: utf-8 -*-
    
    #------------------------------------------------------------------------------
    #   Imports
    #------------------------------------------------------------------------------
    
    from netCDF4 import Dataset
    from datetime import datetime
    import numpy as np
    import glob
    import os
    
    
    #------------------------------------------------------------------------------
    #   Functions
    #------------------------------------------------------------------------------

    def _outputVariables(inputFile, outputFile):
        """Empty doc string... for now."""
        print inputFile
        dataset = Dataset(inputFile)
    
        for dim in dataset.dimensions:
            if dim == 'time':
                outputFile.createDimension(dim,size=1)
            elif dim =='longitude':
                outputFile.createDimension(dim,size=dataset.variables[dim].size + 1)
            else:
                outputFile.createDimension(dim,size=dataset.variables[dim].size)
    
        for var in dataset.variables:
            outputFile.createVariable(var,dataset.variables[var][:].dtype,dataset.variables[var].dimensions)
    
        for var in dataset.variables:
            for ncattr in dataset.variables[var].ncattrs():
                outputFile.variables[var].setncattr(ncattr,dataset.variables[var].getncattr(ncattr))
    
        outputFile.variables['latitude'][:] = np.arange(-90.,90.5,0.5)
        outputFile.variables['longitude'][:] = np.arange(-180.,180.5,0.5)
    
        return outputFile

    ##def netCDFWriter(season, fcst_year, valid_year, fileList=['201501','201502','201503']):
    season = 'JFM'
    fcst_year = 2014
    valid_year = 2015
    fileList = ['201501','201502','201503']
    
    """Empty doc string... for now."""

    for parm in ('temp',):
        print './data/%s_%sA_%s.nc' % (fcst_year, parm[0].upper(),season)
        with Dataset('./data/%s_%sA_%s.nc' % (fcst_year,
                                              parm[0].upper(),
                                              season
                                              ),
                     mode='w',
                     ) as out:
            temp = np.zeros((1,361,720))
            output = _outputVariables(
                                    './data/%s_%s.nc' % (fileList[0],parm),
                                    out
                                    )
            for file_ in fileList:
                print file_
                print './data/%s_%s.nc' % (file_, parm)
                dataset = Dataset('./data/%s_%s.nc' % (file_, parm))
                if parm == 'prcp':
                     v = 'APCP_surface'
                     data = np.sum(dataset.variables['APCP_surface'][:],axis=0,keepdims=True)
                    print data.shape
                else:
                    v = 'TMP_2maboveground'
                    data = np.subtract(np.mean(dataset.variables['TMP_2maboveground'][:],axis=0,keepdims=True),273.15)
                    print data.shape
                    output.variables['TMP_2maboveground'].setncattr('units','degrees_celsius converted from Kelvin using T - 273.15')
                print temp.shape
                temp = np.concatenate((temp,data),axis=0)
                print temp.shape

            # Add cyclic longitude
            temp = np.append(temp,temp[...,0,None],axis=2)
            print temp.shape
            
            # Remove the array of zeroes that was used to initialize this composite array
            #if parm == 'temp':
            temp = np.mean(np.delete(temp,0,axis=0),axis=0)
            #else:
                #temp = np.sum(np.delete(temp,0,axis=0),axis=0)
            print temp.shape
            
            output.variables[v][:] = temp[:]
    #os.chmod(glob.glob('./data/*%s.nc' % season), 0o664)

**Comment by jswhit** [comment]
Looks fine to me.  If you provide the input data, I'll run it and take a look at the output file.

**Comment by havenerk** [comment]
OK, I will post the input files to a .mil site after which you will receive an email with a link and password to use to download the files.  I've just recreated the problem on my laptop with these same input files using python 2.7.9/python-netcdf4 1.1.7 and python 2.7.10/python-netcdf4 1.1.8.  In both cases numpy was at version 1.9.2.  It does look like the 2.7.10/1.1.8 combo is the culprit.  Posting the same information to an ESRI technician as well.

**Comment by havenerk** [comment]
I did just confirm the error condition occurs under Python 3.4.3/python-netcdf 1.1.8

**Comment by jswhit** [comment]
I ran your script and generated my own version of the file.

    [mac28:/tmp/Esri/Data] jwhitaker% python
    Python 2.7.10 (default, May 25 2015, 13:06:17)
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from netCDF4 import Dataset
    >>> nc = Dataset('2014_TA_JFM.nc')
    >>> v = nc.variables['TMP_2maboveground'][:]
    >>> v.shape
    (1, 361, 721)
    >>> v.min()
    -44.997192
    >>> v.max()
    33.226185
    >>>

I can read the file just fine, as can ncdump.  I've put the file at

ftp://ftp.cdc.noaa.gov/Public/jwhitaker/2014_TA_JFM.nc

You can try it with ArcGIS, though I suspect you will see the same error.  If so, we're back at square one.  I really don't think there is anything wrong with the file though.

UPDATE:  I took at look at the 'working' and 'non-working' files (117*nc and 118*nc) you included in the zip file.  The only difference is that some of the attributes in the non-working file are encoded in netcdf as strings, not bytes.  I see this was changed in 1.1.8 - here's the entry in the Changelog:

 * unicode attributes now written as strings, not bytes (using
   nc_put_att_string instead of nc_put_att_text, issue #388).

I bet ArcGIS just doesn't know how to deal with unicode string attributes.  One potential workaround would be to create the file in NETCDF3_64BIT format (since the attributes will then be saved as bytes, since unicode strings are not supported in NETCDF3).

**Comment by jswhit** [comment]
Another workaround would be make sure the attributes in question are not unicode (but plain ascii instead).

**Comment by havenerk** [comment]
Thanks Jeff.  That is probably a relevant clue.  I will relay that to the Esri folks.  How did you figure out how the attributes were encoded differently?  Was ncdump or ncl_filedump telling me something I wasn't seeing?  I feel like I should have figured this out on my own.  We are just passing the attributes from whatever the wgrib2 netcdf converter gives us.  Then we read/manipulate/write them back out with python-netcdf4.  Not sure where the unicode is coming from.

**Comment by jswhit** [comment]
If you look at the output from ncdump, for the 1.1.8 generated file you see:

     string time:units = "seconds since 1970-01-01 00:00:00.0 0:00" ;

which indicates the attribute is a unicode string.  For the 1.1.7 file you get instead:

     time:units = "seconds since 1970-01-01 00:00:00.0 0:00" ;

**Comment by jswhit** [comment]
To make sure the attributes are encoded as bytes instead of strings, you can do

    nc.foo = b'xyz'

instead of

    nc.fool = 'xyz'

In fact, I believe you have to do this in Python 3, or else attributes will always end up as strings.

**Comment by havenerk** [comment]
Esri will have to deal with this sooner or later if that is, in fact, what is crashing it.  And it seems very likely.  I'll just close this problem report here.  Don't think there is much to be done about it on your end.

**Comment by shoyer** [comment]
Note that on Python 2, `'xyz'` and `b'xyz'` are equivalent. In this case, it looks like you're trying to save unicode data to a netcdf file, so netcdf4-python takes the reasonable approach of saving it as unicode instead of coercing it blindly to bytes.
