### ISSUE TITLE
Units in date2num / num2date

### ISSUE THREAD

**Issue by dpl** [Unidata/netcdf4-python#434]
In the documentation for num2date and date2num, it says that "units" in the arguments list should be: "a string of the form 'time units since reference time' describing the time units. time units can be days, hours, minutes, seconds, milliseconds or microseconds." Now I on several occasions encountered data where the time unit is set as, e.g., "months since yyyy-mm-dd hh:mm:ss". Is there any way or planned implementation to deal with such longer-timestep units as well?

**Comment by mdecker** [comment]
The problem with time units such as "months" is that they are not well defined. In contrast to days, hours, etc. the length of a month depends on the calendar used and even varies between different months. 
The alternative is to define a month exactly as 1/12th of a year as udunits does. This "solution" is not very intuitive to the user will will likely lead to misunderstandings.

A few words about this issue can be found in the CF conventions: http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#time-coordinate

    We recommend that the unit year be used with caution. The Udunits package defines a year to be exactly 365.242198781 days (the interval between 2 successive passages of the sun through vernal equinox). It is not a calendar year. Udunits includes the following definitions for years: a common_year is 365 days, a leap_year is 366 days, a Julian_year is 365.25 days, and a Gregorian_year is 365.2425 days.

    For similar reasons the unit month , which is defined in udunits.dat to be exactly year/12 , should also be used with caution.

**Comment by jswhit** [comment]
We could convert "months since" to "seconds since" using 1 month = year/12 = 2629743.831225 seconds.  Same for "weeks since"  and "years since".  This is how netcdf-java does it (http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/CDM/CalendarDateTime.html).  It may lead to confusion though, and cause more problems than it solves.

**Comment by shoyer** [comment]
My two cents is that it's better to give an error and force users to convert such ill-defined units explicitly.

**Comment by davidhassell** [comment]
I would agree. The Udunits definition of "month" is practically never what is meant by encoders of "months since ...", so giving an error would be safe and clear.

**Comment by jswhit** [comment]
We already do throw an error, so it seems like no change in the current behavior is needed.  Closing now...

**Comment by dpl** [comment]
Thanks for all replies - by the way, is there something like a users mailing list?

**Comment by jswhit** [comment]
There's no mailing list right now.  Wish github had a better mechanism for discussions.

**Comment by bennoblumenthal** [comment]
While the udunits definition of month is not what is ever meant, that is a udunits flaw, not a flaw in the standard.

units of months since   with a calendar of 360_day  is perfectly well defined and there is no reason why this cannot be properly coded.

**Comment by jswhit** [comment]
A pull request allowing ``months since`` when calendar is ``360_day`` would be welcome.

**Comment by rabernat** [comment]
:+1: to @bennoblumenthal's comment.
