### ISSUE TITLE
Incompatible with numpy.nditer

### ISSUE THREAD

**Issue by aidanheerdegen** [Unidata/netcdf4-python#443]
I am reading a large variable (21600x43200) from a netCDF file, transforming it and writing it out to a copy of the original file.

The variable is too large to fit in memory, so I'm trying to iterate over it using numpy.nditer. If I try this directly with the netCDF variable I get this:

"TypeError: Iterator operand is flagged as writeable, but is an object which cannot be written back to via UPDATEIFCOPY"

I have to make a copy to a temporary variable using np.array(var, copy=True), operate on the copy and then assign it back to the netCDF variable.

Is there another approach I should use for iterating over netCDF variables?

**Comment by zerothi** [comment]
Slice and take 1 row at a time, this will take some time but can be done.

**Comment by jswhit** [comment]
Something like this might be useful

https://bitbucket.org/robertodealmeida/arrayterator/

**Comment by shoyer** [comment]
I would suggest using dask, with or without xray. Some useful references:
http://eng.climate.com/2015/06/11/xray-dask-out-of-core-labeled-arrays-in-python/
http://matthewrocklin.com/blog/work/2015/02/13/Towards-OOC-Slicing-and-Stacking/
http://earthpy.org/dask.html

**Comment by jswhit** [comment]
+1 @shoyer's suggestion is the way to go (if you don't want to simply slice the variable into chunks manually).
