### ISSUE TITLE
Expected performance for traversing all cells in a file / Row vs column order?

### ISSUE THREAD

**Issue by dpl** [Unidata/netcdf4-python#446]
Hi, sorry to post again what might turn out to be more a candidate for a mailing-list style question, but I'm still wondering:

I need to do some verification calculations on every single grid cell of a 1deg x 1deg gridded dataset over a longer time series. The crawling through all cells appears a bit slow to me (right now it's about 90s per timestep, i.e. for touching each cell of the full grid - however the dataset is quite sparse; so on most cells I only see missing values and immediately leave again) One possible cause could be that I'm traversing the dimensions in the wrong order. Is there any way I can find out what storage order the data has in the file? So, (using your example from the online docs) if I issue:

INPUT: print rootgrp.variables['temp']
OUTPUT: type 'netCDF4.Variable'
OUTPUT: float32 temp(time, level, lat, lon)

will then the arguments be always given in the order that is most effiecient to traverse by? I.e., should my outermost loop be over the time steps and the innermost over lon? If not, how do I find out the "correct" storage order? (Also, I assume each different variable likely resides in its separate block in storage?)

If on the other hand I already got my dimension loops right, is there any open dataset you have benchmark data on with your own setup so I could compare if I'm unusually slow for some other reason?  In particular, while I unfortunately don't have much experience with netCDF files, the other two tools I use, cdo and ncap2,  seem to be 1-3 orders of magnitude faster for grid-wide value manipulations, and I'd assume they're touching each cell as well (i.e., they don't know the missingness pattern, or access some other information compression, correct?). Thanks for any pointers and for the library in general!

**Comment by jswhit** [comment]
Explicity looping over all the dimensions in python will be slow, and should be avoided if at all possible.  Ideally, you would loop over the time dimension, pull out an entire (level, lat, lon) chunk from the netcdf file, and operate on the entire (masked) array all at once.  The nice thing about masked arrays is that missing values are automatically skipped in the computation.  Is there a particular reason you're not doing it this way?

**Comment by dpl** [comment]
Thank you, Jeff, this helps a lot. No, no reason other than ignorance about the masked array aspect (if it popped up in the docs I must have missed it). 

As a quick follow-up question: how and when are the masks generated by netcdf4-python? Are they copied from a mask already present in the opened netcdf file, or generated by iterating through it  (e.g., upon load or access) and comparing each value to the "missing_value" attribute? The unidata netcdf docs [which are for the _library_, technically - but I found even less in "Appendix C File Format Specification" for the _file format_] state that: "The netCDF library itself does not handle these values in any special way, except that the value of a _FillValue attribute, if any, is used in pre-filling unwritten data." So I assume a standard netCDF file does not contain a mask..? But then it seems also that loading one into netcdf4-python is a bit fast for one to be generated on the fly..?

The reason I'm digressing in this direction is that I'm actually trying to debug some errors in my missing values having appeared in my processing chain (most likely before working with python4-netcdf). So it may help me in hunting that down to hear how python4-netcdf generates the masks. Thank you again

**Comment by jswhit** [comment]
If the variable has a ``missing_value`` attribute, all the values in the array that are equal to that value are masked.  Same for ``_FillValue``.  You are correct that there is no mask in the netcdf file - the python wrapper creates one when you read the data.  You can turn this feature off if you would rather have the raw data (including the missing values).

**Comment by jswhit** [comment]
See http://unidata.github.io/netcdf4-python/#netCDF4.Dataset.set_auto_maskandscale

**Comment by dpl** [comment]
Thanks again Jeff, very useful!
