### ISSUE TITLE
Add date2num back into the netcdftime module?

### ISSUE THREAD

**Issue by shoyer** [Unidata/netcdf4-python#449]
It appears that `date2num` is no longer in the `netcdftime` module. This has broken Iris, an external library that depends on netCDF4:
https://groups.google.com/forum/#!topic/scitools-iris/C5LnnMDaO7k

cc @ajdawson

**Comment by ajdawson** [comment]
@shoyer - this has been worked-around in iris (by @ocefpaf I believe), it just hasn't been released yet which should be addressed by the iris team. I don't know the history of the decision to remove `date2num` so I don't know if adding it back is a good idea or not.

**Comment by jswhit** [comment]
Before the change, date2num existing in both netCDF4 and netcdftime, which resulted in some code duplication and confusion.  I decided to remove it from netcdftime and leave it in netCDF4 - sorry for any pain this may have caused.

**Comment by shoyer** [comment]
I can understand why you wanted to clean this up. But in the future, let's try to be more intentional about maintaining backwards compatibility. Tools like [semantic versioning](http://semver.org/) can help communicate this with users.
