### ISSUE TITLE
Variables with a enum data type are unsupported

### ISSUE THREAD

**Issue by joaquinrgu** [Unidata/netcdf4-python#452]
Variables with a enum data type are not recognized.

The test file cloud2.nc (https://drive.google.com/folderview?id=0B6RTzwJWtu6zOFpDQjFSd2U0clU&usp=sharing) was created with ncgen using the following CDL file (based on http://www.unidata.ucar.edu/software/netcdf/workshops/2011/groups-types/EnumCDL.html) : 

netcdf cloud2 {
types:
  byte enum cloud_t {Clear = 0, Cumulonimbus = 1, Stratus = 2, 
      Stratocumulus = 3, Cumulus = 4, Altostratus = 5, Nimbostratus = 6, 
      Altocumulus = 7, Missing = 127} ;
dimensions:
	time = UNLIMITED ; // (5 currently)
variables:
	cloud_t primary_cloud(time) ;
		cloud_t primary_cloud:_FillValue = Missing ;
        float temperature(time) ;
data:

 primary_cloud = Clear, Stratus, Cumulus, _, Cumulonimbus ;
 temperature = 11,12,13,14,15;
}

It contains two variables: one float and one enum. The float variable works fine, but the enum var returns the following error:
KeyError: 'primary_cloud'

import netCDF4
rootgrp = netCDF4.Dataset('C:\\Users\\rodriguezgu\\NetCDF4\\cloud2.nc', 'r', format='NETCDF4')
print (rootgrp.variables["temperature"])
print (rootgrp.variables["primary_cloud"])
rootgrp.close()

**Comment by jswhit** [comment]
we could support enums the same way h5py does - by mapping to an integer numpy array restricted to certain named values.  See http://docs.h5py.org/en/latest/special.html#enumerated-types.

Would that be useful?

**Comment by jswhit** [comment]
started working on this in the enum branch

**Comment by joaquinrgu** [comment]
Thanks Jeff, that would be useful, in fact the ToolsUI and Panoply viewers are only showing the integer value as far as I know.

**Comment by jswhit** [comment]
enum support appears to be working (pull request #457).  Still need to add docs and a test. Please try it out with your data and report back here.

**Comment by jswhit** [comment]
test/tst_enum.py added.

**Comment by joaquinrgu** [comment]
I confirm I can read now the enum variables in my datasets :)
Thanks also for the test, it shows how to create enum variables.

Maybe now the intro section in http://unidata.github.io/netcdf4-python/ can be updated where it says enums are not supported :)

**Comment by jswhit** [comment]
Docs have been updated, so I think this is ready for a merge.  I'll wait a few days to see if any issues pop up.

**Comment by jswhit** [comment]
merged into master, closing..
