### ISSUE TITLE
date2index broken

### ISSUE THREAD

**Issue by FrancescAlted** [Unidata/netcdf4-python#453]
I am experiencing a strange error when using date2index in latest netCDF4 1.1.9 (via Anaconda on Ubuntu 15.04).  Here it is:

```
In [44]: nc = netCDF4.Dataset("/home/faltet/uio/shyft-data/netcdf/arome-testdata/arome_metcoop_red_default2_5km_20150823_06.nc")

In [45]: tvar = nc.variables['time']

In [46]: tvar[:3]
Out[46]: array([  1.44030960e+09,   1.44031320e+09,   1.44031680e+09])

In [47]: dt = datetime.datetime.utcfromtimestamp(int(1.44031320e+09))

In [48]: netCDF4.date2index(dt, tvar)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-48-e2a14096dc8f> in <module>()
----> 1 netCDF4.date2index(dt, tvar)

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.date2index (netCDF4/_netCDF4.c:51152)()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Variable.__getattr__ (netCDF4/_netCDF4.c:30655)()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Variable.getncattr (netCDF4/_netCDF4.c:28214)()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4._get_att (netCDF4/_netCDF4.c:3548)()

AttributeError: NetCDF: Attribute not found

In [49]: netCDF4.__version__
Out[49]: '1.1.9'
```

I'd expect getting just a 1.

**Comment by jswhit** [comment]
date2index is trying to access the calendar attribute of the time variable, since the calendar kwarg was not given.   If the calendar is one that python datetime supports, then python datetime is used, otherwise the netcdftime module is used.  It should either fail with a more informative error message, or just use netcdftime if it can't decide whether python datetime will work.  The only advantage of using python datetime is greater accuracy (millseconds or less, netcdftime has only 1 second accuracy).

**Comment by jswhit** [comment]
Actually, it's the 'units' attribute that it is choking on, not 'calendar'.

**Comment by FrancescAlted** [comment]
Well, the user's guide is saying this (http://netcdf4-python.googlecode.com/svn/trunk/docs/netCDF4-module.html#date2index):

```
If calendar is None, its value is given by nctime.calendar or standard if no such attribute exists.
```

So, if the calendar is not passed and `nctime.calendar` is not fond, date2index should default to 'standard'.  Also, the manual makes a reference to `nctime.calendar`, not `nctime.units`. This should be clarified too. Thanks for looking into this!

**Comment by jswhit** [comment]
pull request #456 adds a more informative error message if date2index called using a netcdf time variable that is missing a ``units`` attribute.

**Comment by jswhit** [comment]
Why?  I believe the
