### ISSUE TITLE
It should be possible to use Ellipsis (...) to index scalar variables with vlen dtype

### ISSUE THREAD

**Issue by shoyer** [Unidata/netcdf4-python#458]
If I try to use Ellipsis to write a scalar variable's data, I get an error:
```
In [6]: v = nc.variables['foo']

In [7]: v[...] = u'foo'
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-7-945a3fc83722> in <module>()
----> 1 v[...] = u'foo'

netCDF4.pyx in netCDF4.Variable.__setitem__ (netCDF4.c:45949)()

netCDF4.pyx in netCDF4.Variable._assign_vlen (netCDF4.c:45445)()

IndexError: single element VLEN slices must be specified by integers only
```

This (`...`) is generally the preferred syntax for copying to a variable because it works with both scalars and multi-dimensional arrays (unlike `:`), so it would be nice if it worked for vlen dtypes.

**Comment by jswhit** [comment]
A workaround for this is included in pull request #471.  In the process, I discovered that slicing scalar VLEN (non-str) variables was broken, so a workaround for that is added also.  

The code for slicing VLEN arrays needs to be overhauled though - it's kludgy at best right now.

**Comment by jswhit** [comment]
pull request #471 merged, closing now...

**Comment by shoyer** [comment]
Thanks Jeff!
