### ISSUE TITLE
netCDF4-Python uses "str" as an alias for the ASCII (even on Python 3) and doesn't support Unicode strings

### ISSUE THREAD

**Issue by shoyer** [Unidata/netcdf4-python#459]
This is confusing:
```
In [1]: import netCDF4

In [2]: nc = netCDF4.Dataset('foo.nc', 'w')

In [3]: v = nc.createVariable('foo', str, ())

In [4]: v[0] = u'foo'

In [5]: nc.close()

In [6]: !h5dump foo.nc
HDF5 "foo.nc" {
GROUP "/" {
   DATASET "foo" {
      DATATYPE  H5T_STRING {
         STRSIZE H5T_VARIABLE;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "foo"
      }
   }
}
}

In [7]: import sys

In [8]: sys.version_info
Out[8]: sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0)
```

Given that I'm running Python 3, I expected to be creating a unicode VLEN array, not a bytes VLEN array.

This leads to particularly strange behavior if passing in data without actual ASCII equivalents. The data is roundtripped faithfully by netCDF4-python, but it's not properly self-described -- the HDF5 file still claims it's holding ASCII: 
```
In [11]: v[0] = '∫ßå'

In [16]: v[0]
Out[16]: '∫ßå'

In [17]: nc.close()

In [18]: !h5dump foo.nc
HDF5 "foo.nc" {
GROUP "/" {
   DATASET "foo" {
      DATATYPE  H5T_STRING {
         STRSIZE H5T_VARIABLE;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "\37777777742\37777777610\37777777653\37777777703\37777777637\37777777703\37777777645"
      }
   }
}
}
```

To be fair, it's not even clear to me that netCDF4-C even supports a unicode dtype for arrays. But if not, it really should (and I'll file a feature request there). HDF5 certainly does support unicode dtypes.

**Comment by jswhit** [comment]
VLEN str arrays are of type NC_STRING.  I'm not entirely sure what NC_STRING means.

**Comment by jswhit** [comment]
There does not appear to be any way to tell the C lib to store NC_STRING as unicode, not ascii.

**Comment by rsignell-usgs** [comment]
@wardf, any comment here?

**Comment by WardF** [comment]
The C library does support the use of unicode characters, and I'm surprised by the bug report by @shoyer (although the python stuff is largely opaque to me); let me take a look into this and follow up once I have something more useful to say.

**Comment by jswhit** [comment]
This behaviour was also noted in issue #448.  Should be easy to reproduce in a C program - just write a string attribute and then examine the file with ncdump.  You will see  ``CSET H5T_CSET_ASCII``, not utf8.

**Comment by jswhit** [comment]
This appears to be fixed in netcdf-c master.  Thanks @wardf!
