### ISSUE TITLE
Allow indexing with unsorted integer arrays

### ISSUE THREAD

**Issue by jhamman** [Unidata/netcdf4-python#467]
https://github.com/xray/xray/issues/593 has brought indexing with integer arrays back.  There were a few long discussions about this back in #300 and #308 resulting in the integer arrays being required to be sorted and unique. Ultimately, `netCDF4` converts integer arrays to boolean areas for indexing.

In the xray issue above, I have found a reason to support indexing with integer arrays and would like to relax the requirements discussed above.

**Comment by jswhit** [comment]
Can you explain the use case for unsorted integer indices?  Seems like netcdf coordinate variables are almost always going to be monotonic.

**Comment by jhamman** [comment]
@jswhit -

My use case is shown in xray/xray#593 where I was basically sorting a `xray.DataArray` before loading the data from disk.  Since the xray `isel` method returns a view into the data, it was not triggering the loading of the data and eventually, I ended up trying to index into the netCDF4 variable with a unsorted integer array.

This all happened because someone gave me a MERRA Reanalysis dataset that had been poorly concatenated and there were a few scrambled time periods (e.g. [1979, 1980, 1982, 1981]).  Rather than rearranging the time dimension, I tried to sort the dataset using xray.

**Comment by jswhit** [comment]
So the ultimate cause was a malformed dataset.   Is it worth re-introducing un-sorted integer indexing just to work around those cases?

**Comment by shoyer** [comment]
Integer indexing is more general than boolean indexing, so I would argue that it makes more sense to standardize indexers to integers than booleans. If we took that approach, I don't think it would be any more difficult to support unsorted indexing.

**Comment by jhamman** [comment]
@jswhit - Supporting integer indexing would allow for other lazy operations in more cases than the one I explained above.  I can image other sorting operations that are not performed because of a malformed dataset.

**Comment by jswhit** [comment]
@shoyer, you may be right - but I think the counterargument is that boolean indexing is more common so standardizing around boolean indexing is preferred.

**Comment by shoyer** [comment]
To be a little more explicit, any boolean indexer can be converted into an integer indexer by calling `np.flatnonzero` on it. That's exactly how NumPy handles boolean indexers internally.

For user code, boolean indexing may indeed be more common, but for applications, I suspect integer indexing is more common, because it's more general. For example, xray will always convert boolean indexers into integer indexers before indexing on a netCDF4 variable.

**Comment by jswhit** [comment]
created a new branch`` unsorted_indices`` to work on this

**Comment by jswhit** [comment]
See pull request #469.  

Still need to add a test for unsorted integer array slice, and integer array slice with duplicates.

Also need to change docs.

**Comment by jswhit** [comment]
test added, docs updated.

**Comment by jswhit** [comment]
pull request #469 merged
