### ISSUE TITLE
Dimension does not have a "size" property

### ISSUE THREAD

**Issue by benoistlaurent** [Unidata/netcdf4-python#477]
Hi,

I noticed that netCDF4._netCDF4.Dimension has no *size* property.
This is a bit confusing since when one prints a *Dimension*, this is what he gets

```python
>>> root.dimensions['Natoms']
<type 'netCDF4._netCDF4.Dimension'>: name = 'Natoms', size = 2938
```

Note that *Dimension* has a *name* property.
So currently, this is the method to get the name on one side and the size on the other

```python
>>> name = root.dimensions['Natoms'].name
>>> size = len(root.dimensions['Natoms'])
```

which I humbly think is confusing.
What would be more logical in my opinion would be

```python
>>> name = root.dimensions['Natoms'].name
>>> size = root.dimensions['Natoms'].size
```

Note that I do not mean that *Dimension* should not implement  the *len* function but just that it should have two ways to access the data.

**Comment by jswhit** [comment]
See pull request #478.

**Comment by jswhit** [comment]
merge pull request #478, closing now...
