### ISSUE TITLE
Upcoming netcdf-c changes in 4.4.0

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf4-python#479]
The upcoming `4.4.0` release of the `netcdf-c` library is going to incorporate support for CDF-5 files.   This support has required some changes to the `C++` and `Fortran` interfaces, and I suspect it may require some changes to the `Python` interface as well. 

> There will be *at least* one release candidate with this functionality before the full 4.4.0 release.

CDF-5 support was added manually by @DennisHeimbigner, and is based on work by @wkliao.  The original work is viewable here:

* https://github.com/wkliao/netcdf-c/tree/CDF-5

I am still collating the documentation for the update; documentation, as is so frequently, has come last.  The changes are potentially wide-reaching, so I want to make sure I haven't missed anything.  For sure I can say that there are new data types, and a few format flags have been renamed, with aliases from the extant flag marked deprecated; this should prevent anything using these flags from breaking right away, but they are clearly marked deprecated in the documentation.

The current branch containing the cdf-5 work may be found on the `cdf-5` branch of the `netcdf-c` library.  

* https://github.com/Unidata/netcdf-c/tree/cdf-5

I have incorporated `netcdf4-python` tests into the netcdf regression tests.  These tests, which use docker, are described here:  

* https://hub.docker.com/r/unidata/nctests/

I've been using these tests to ensure that I don't break `netcdf4-python` with the 4.4.0 release; however, it will not do anything about adding new functionality.

**Comment by jswhit** [comment]
if you could update this issue with a link to the docs for the new features (when that is ready), I'd appreciate it.  At that point we can start working on adding the new capabilities to the python interface.

Sounds like most of the work will be in teaching the python interface to read and write the new format (by passing the right flags to the C lib calls).

**Comment by jswhit** [comment]
created a cdf-5 branch with initial support for NC_FORMAT_64BIT_DATA format.

**Comment by shoyer** [comment]
Is there documentation somewhere on what CDF-5 is?

**Comment by WardF** [comment]
CDF-5 is the file format used by parallel-netcdf; it adds a few new data types (unsigned, 64-bit native data) on top of the netcdf classic file format/data model.

The file format specification for CDF-5 can be found at http://cucis.ece.northwestern.edu/projects/PnetCDF/CDF-5.html.  

Sorry for the lack of a detailed response; the Unidata/netcdf documentation is forthcoming, and is the last thing holding up the next release candidate at this point.

**Comment by jswhit** [comment]
pull request #482 implements cdf-5 support.  Right now, the cdf-5 netcdf-c branch is needed to test this, but hopefully this will be merged into netcdf-c master soon.

**Comment by jswhit** [comment]
pull request #482 merged, now that the cdf-5 netcdf-c branch has been merged into netcdf-c master.
