### ISSUE TITLE
Error on variable creation when chunk size > dimension size

### ISSUE THREAD

**Issue by benj-pml** [Unidata/netcdf4-python#480]
Attempting to add (and then access) a variable to a netCDF file when the variable you're adding has a dimension smaller than the chunk size results in an unhelpful "HDF error":

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netCDF4/_netCDF4.pyx", line 3342, in netCDF4._netCDF4.Variable.__getitem__ (netCDF4/_netCDF4.c:32244)
  File "netCDF4/_netCDF4.pyx", line 3999, in netCDF4._netCDF4.Variable._get (netCDF4/_netCDF4.c:40661)
RuntimeError: NetCDF: HDF error
```

Doing this on a machine with a debug-enabled HDF build gives a more helpful error:

```
[snipped]
#009: ../../src/H5Dint.c line 1049 in H5D__create(): unable to construct layout information
    major: Dataset
    minor: Unable to initialize object
#010: ../../src/H5Dchunk.c line 546 in H5D__chunk_construct(): chunk size must be <= maximum dimension size for fixed-sized dimensions
    major: Dataset
    minor: Unable to initialize object
```

I would expect the python lib to pass through the helpful error (because debugging "HDF error" is really quite hard!). I guess in a perfect world you could automatically reduce the chunk size when this would happen, but re-chunking an existing large netCDF would take ages, so I guess not!

**Steps to reproduce (every time):**
1. Create a netCDF file with a chunk size of eg. 256x256 and open it in a Dataset
2. Add a variable with fixed dimensions of eg. 128x128
3. Attempt to access the variable
(Note below example slightly tweaked, as I couldn't upload my example netCDF file - should break)
```
import netCDF4
import numpy
height_dim = 128
width_dim  = 128
work_file = "test.nc"
dataset = netCDF4.Dataset(work_file, "a")
granule_indices_var = dataset.createVariable('granule_indices', numpy.int16, (height_dim, width_dim), zlib=True, chunksizes=(256,256), fill_value=None)
granule_indices_var[:]
```
**Expected results:**
Error saying that the chunk size > than the dimension size
**Actual results**
RuntimeError: NetCDF: HDF error

**Comment by jswhit** [comment]
The python lib is simply passing the error propogated by the netcdf C library - it doesn't have access to the HDF error messages unless the netcdf C library forwards them through nc_strerror.

 I suppose the python interface could (should?) check to make sure the chunksizes don't exceed time dimension sizes.

**Comment by DennisHeimbigner** [comment]
We should probably be catching this in the c library.

**Comment by jswhit** [comment]
pull request #481.

**Comment by jswhit** [comment]
pull request #481 has been merged.
