### ISSUE TITLE
Unicode variable attribute fill_value

### ISSUE THREAD

**Issue by aluhamaa** [Unidata/netcdf4-python#483]
This code fails when writing FillValue to Unicode variable.

    from netCDF4 import Dataset
    f1=Dataset('test','w')
    d1=f1.createDimension('t',10)
    v1=f1.createVariable('v1','S1','t')
    v2=f1.createVariable('v2','S1','t',fill_value='N')
    v3=f1.createVariable('v3','U1','t')
    print(v1.datatype,v1._isprimitive)
    print(v3.datatype,v3._isprimitive)
    v4=f1.createVariable('v4','U1','t',fill_value='N')

Possibly related to https://github.com/Unidata/netcdf4-python/issues/448

**Comment by jswhit** [comment]
This is a consequence of pull requests #224 and #238.  If a unicode string datatype is requested, it is actually saved as a vlen string in the file, since HDF5 and netcdf-4 do not support a fixed length unicode data type.  The error message happens because you can't use a fill_value for vlen strings.

**Comment by aluhamaa** [comment]
Thanks for quick responce. Does this mean that no solution is expected for this controversy due to HDF5 dependency? Then it would be nice to remove the 'U1' from netCDF4.defaultfillvals attribute, as one cannot use it anyway?

**Comment by jswhit** [comment]
Yes, 'U1' should be removed from defaultfillvals.  The reason it is converted a vlen str is this:

    >>> import numpy
    >>> a  = numpy.empty(1,dtype='U1')
    >>> a.itemsize
    4

So, 'U1' cannot be stored as NC_CHAR (but 'S1' can).  There is no other primitive data type available in netcdf that can be used to store unicode strings (that I am aware of anyway).
