### ISSUE TITLE
error: no such file or directory: 'netCDF4/_netCDF4.c'

### ISSUE THREAD

**Issue by ForTozs** [Unidata/netcdf4-python#488]
Hello. I am having trouble getting netcdf4-python to compile for me on my system. I use a MacPorts distribution of Python and have compiled hdf5 and netcdf4 from source into my /opt/local directory using gcc5. NetCDF is working for me (both netcdf-c and netcdf-fortran).  However, when I try to compile I get the following:

    building 'netCDF4._netCDF4' extension
    clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG \
    -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/include -I/opt/local/include \ 
    -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include \ 
    -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 \ 
    -c netCDF4/_netCDF4.c -o build/temp.macosx-10.11-x86_64-2.7/netCDF4/_netCDF4.o
    clang: error: no such file or directory: 'netCDF4/_netCDF4.c'
    clang: error: no input files
    error: command 'clang' failed with exit status 1

Any ideas what's going on? Could it be numpy is compiled using gfortran in macports by default? I also tried `CC='gcc' python setup.py build`, but that didn't work either. Any help would be greatly appreciated.

**Comment by jswhit** [comment]
I would guess that you have cython installed, and setup.py is invoking cython to compile _netCDF4.pyx into _netCDF4.c, but the compilation step is failing.  It would help to see the entire output of ``python setup.py build``.

If the cython step is failing, you would need to track down what's wrong with your cython installation.  If you want to bypass the compilation step, you can use setup.cfg to turn it off (use_cython=False).

**Comment by ForTozs** [comment]
Thanks for the help. Disabling Cython does allow it to build and install, but I get an import error in Python:

    >>> from netCDF4 import Dataset
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "netCDF4/__init__.py", line 3, in <module>
        from ._netCDF4 import *
    ImportError: No module named _netCDF4

I can also reproduce the same import error if I go into 'setup.py' and commenting out lines 391 and 392:

       #if len(sys.argv) >= 2 and os.path.exists(netcdf4_src_c):
            #os.remove(netcdf4_src_c)

I also tried manually specifying my library and header locations. If I reenable Cython and try to build, here is my full output (I don't know the markdown to put this all in a frame).

    cython version 0.23.4 found ...
    reading from setup.cfg...
    using nc-config ...
    using netcdf library version 4.4.0-development
    using Cython to compile netCDF4.pyx...
    netcdf lib has group rename capability
    netcdf lib has nc_inq_path function
    netcdf lib has nc_inq_format_extended function
    netcdf lib does not have cdf-5 format capability
    running build
    running build_py
    running build_ext
    building 'netCDF4._netCDF4' extension
    creating build/temp.macosx-10.11-x86_64-2.7
    creating build/temp.macosx-10.11-x86_64-2.7/netCDF4
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG \
    -g -fwrapv -O3 - Wall -Wstrict-prototypes -I/opt/local/include -I/opt/local/include \
    -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include \
    -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 \
    -c netCDF4/_netCDF4.c -o build/temp.macosx-10.11-x86_64-2.7/netCDF4/_netCDF4.o
    clang: error: no such file or directory: 'netCDF4/_netCDF4.c'
    clang: error: no input files
    error: command '/usr/bin/clang' failed with exit status 1

Jpeg is not required right?

**Comment by jswhit** [comment]
Don't run the test in the netcdf4-python directory, go up one level and it will work fine.  I think your only issue is that your cython installation is not working correctly.

**Comment by ForTozs** [comment]
Lol. It works just fine! Lesson learned. Thanks so much. I've been trying to get this working all day. I guess I should have changed directories at some point.
