### ISSUE TITLE
Construct Datasets from pathlib objects

### ISSUE THREAD

**Issue by gnurser** [Unidata/netcdf4-python#489]
I've just been starting to use Python 3 & the nice pathlib library.

Would it be possible to permit the Dataset constructor to use a pathlib object directly, instead of requiring the user to pass its string representation?

**Comment by jswhit** [comment]
Seems quite doable, should be a matter of just invoking str on the input.  This will convert the pathlib object to a string, and do nothing if it's already a string.

**Comment by gnurser** [comment]
On 18 Nov 2015, at 18:32, Jeff Whitaker <notifications@github.com<mailto:notifications@github.com>> wrote:


Seems quite doable, should be a matter of just invoking str on the input. This will convert the pathlib object to a string, and do nothing if it's already a string.



Glad it might be possible.

And, again, thanks for a really nice package; it’s encouraged some of my sceptical colleagues to convert to python.

George Nurser.

—
Reply to this email directly or view it on GitHub<https://github.com/Unidata/netcdf4-python/issues/489#issuecomment-157812486>.

________________________________
This message (and any attachments) is for the recipient only. NERC is subject to the Freedom of Information Act 2000 and the contents of this email and any reply you make may be disclosed by NERC unless it is exempt from release under the Act. Any material supplied to NERC may be stored in an electronic records management system.
________________________________

**Comment by jswhit** [comment]
Can you give pull request #490 a try?

**Comment by gnurser** [comment]
Looks good; will try tomorrow. Thanks George.
On 19 Nov 2015, at 13:41, Jeff Whitaker <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you give pull request #490<https://github.com/Unidata/netcdf4-python/pull/490> a try?

—
Reply to this email directly or view it on GitHub<https://github.com/Unidata/netcdf4-python/issues/489#issuecomment-158059485>.

________________________________
This message (and any attachments) is for the recipient only. NERC is subject to the Freedom of Information Act 2000 and the contents of this email and any reply you make may be disclosed by NERC unless it is exempt from release under the Act. Any material supplied to NERC may be stored in an electronic records management system.
________________________________

**Comment by gnurser** [comment]
On 19 Nov 2015, at 13:41, Jeff Whitaker <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you give pull request #490<https://github.com/Unidata/netcdf4-python/pull/490> a try?


Jeff; Tried it, it works for me. Many thanks. G

—
Reply to this email directly or view it on GitHub<https://github.com/Unidata/netcdf4-python/issues/489#issuecomment-158059485>.

________________________________
This message (and any attachments) is for the recipient only. NERC is subject to the Freedom of Information Act 2000 and the contents of this email and any reply you make may be disclosed by NERC unless it is exempt from release under the Act. Any material supplied to NERC may be stored in an electronic records management system.
________________________________
