### ISSUE TITLE
size atttribute in netcdf4.Dimension object

### ISSUE THREAD

**Issue by ocehugo** [Unidata/netcdf4-python#499]
Hi,

it's just me thinking that dimension objects are missing the  attribute "size" ? I know you can get the size by calling `len`, but i think it's very handy to have this thing in an attribute.

PS: I think I already requested that or saw some discussion here...not sure if duplicate/already discussed.

**Comment by jswhit** [comment]
https://github.com/Unidata/netcdf4-python/pull/478

it will be in the 1.2.2 release
