### ISSUE TITLE
Cannot create netCDF4 file

### ISSUE THREAD

**Issue by nicolaisi** [Unidata/netcdf4-python#500]
Hi guys,

I'd installed dependencies according to the installations guide. Then I started with the first guide (http://unidata.github.io/netcdf4-python/#section1) to create a netCDF4 file as shown in the tutorial. But instead of getting a netCDF4 file, I got a HDF file. 

I cannot even do a ncdump because it's not a valid netCDF file.

When I do cat, I get this:
�HDF

���������0�3EOHDR
                  �"������������������������
~c(�

I check my python-netcdf installation and ran test:

$ python run_all.py 
not running tst_unicode3.py ...

netcdf4-python version: 1.2.2
HDF5 lib version:       1.8.16
netcdf lib version:     4.3.3.1
numpy version           1.10.2
..............................................................................
----------------------------------------------------------------------
Ran 78 tests in 34.623s

OK

I assume the installation is fine. By the way, I'm building this on OpenSuse 13.1

Any idea what did I do wrong?

#update: I manage to create the netCDF4 file using the example code, but I must be root. If I'm not root, I can only manage to create HDF file. Seems like a permission problem, but which file is causing this?

**Comment by dopplershift** [comment]
netCDF files are valid HDF files, so the fact that you see an HDF problem is a red herring. To me, I think the problem might actually be in running `ncdump`.

You can get some netcdf files here: http://thredds.ucar.edu/thredds/catalog/nws/metar/ncdecoded/files/catalog.html

What happens if you run `ncdump` on one of those files as a non-root user?

**Comment by nicolaisi** [comment]
I just ncdump on one of the file in the catalog and I can read them.

**Comment by nicolaisi** [comment]
Just now i rerun my script from yesterday and I got a different error message. I cannot even reproduce the HDF file now. Instead I got this:

```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    fh = Dataset(my_example_nc_file, mode='w')
  File "netCDF4/_netCDF4.pyx", line 1781, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:12270)
RuntimeError: Permission denied
```

**Comment by jswhit** [comment]
That latest error is a filesystem permission issue.

Your original ncdump error is probably because it was built without netcdf-4 support.  Try the ncdump that goes with the netcdf-4 installation you linked when compiling netcdf4-python.

**Comment by jswhit** [comment]
any update on this issue?  Unless I hear otherwise, I'll assume it was an ncdump version mismatch - and close the issue in a couple of days.

**Comment by nicolaisi** [comment]
Hi,

The ncdump now works. You are right with the mismatch.

Thanks.
