### ISSUE TITLE
Should netcdftime.__version__ be defined?

### ISSUE THREAD

**Issue by tfeb** [Unidata/netcdf4-python#504]
Before e39a665eb9106c4cc2af703cebbf8d7bd7d8116b, I think that someone doing `import netcdftime` would be then able to check the version by looking at `netcdftime.__version__`.  Now they can't, because `__init__.py` does not import that name from the implementation file.

I think this is probably a bug, but I'm not sure.  Certainly we have code which relies on being able to check versions this way.

**Comment by jswhit** [comment]
Fixed now in master (pull request #505)
