### ISSUE TITLE
problem with packed data

### ISSUE THREAD

**Issue by sbiner** [Unidata/netcdf4-python#508]
Hi, 
I have an issue with netCDF4 when I read packed netCDF files on some machines. To demonstrate I attached a sample of the netcdf file (the file is zipped to be enable the upload). Here is some code showing the problem : 
```python
import netCDF4 as nc 
print nc.Dataset('ncks_154_109.nc').variables['tas'][:10]
````
this prints 10 values and normally the last one should be around 287.8226. Notice that this is very close to the "offset value" in the netcdf file. In fact the unpacked value is 0 when I use ncdump to show it. 

On one machine running netCDF4 v0.9.7 I get the right result. On other machines using v1.0.2 
and v1.1.3 I get a masked value at that same point. I also used the "climate data operators" and matlab with the nctoolbox and on the machine using v1.0.2 and got the expected value.

Any idea of why this is happening?

Cheers.

Seb

[ncks_154_109.nc.zip](https://github.com/Unidata/netcdf4-python/files/86382/ncks_154_109.nc.zip)

**Comment by jswhit** [comment]
The short variable 'tas' has a _FillValue of 1.e20, which is the wrong type.  Somehow this is being cast to a short integer and ending up as zero - hence the unexpected masked element.  I am investigating further....

**Comment by jswhit** [comment]
I have confirmed that the _FillValue of 1.e20 is being cast to a short integer of zero.  I guess that question is whether this is the right thing to do - or should an error be raised if the _FillValue is the wrong type.

**Comment by sbiner** [comment]
Hi,

 Thanks a lot for your input.

 just to be sure that I understand, are you saying that the _FillValue of 1.e20 is translated to 0 when it is read so any short integer value of zero is then flagged as masked?

 Is this dependent of the netcdf library or the netcdf4-python module? I do not understand why this problem does not appear on some machines.

Also if the problem is only that the short integer value of zero are masked, I could put the mask to False everywhere and get the right value right? But if do that or do something like

```python
print nc.Dataset('ncks_154_109.nc').variables['tas'][:10].data
````
I get an unpacked value of zero.

Again, any help is appreciated, and thank you again.

**Comment by jswhit** [comment]
Yes, that's right.  The _FillValue is cast to the type of the variable by the python interface, so 1.e20 becomes 0.  If you want to turn this off, use the ``var.set_auto_maskandscale(False)``, where ``var`` is the variable object.  Then the python interface won't return a masked array, or apply scale_factor/offset.  You'll just get the raw short integer data back.

**Comment by jswhit** [comment]
BTW - setting the _FillValue to a number that can't be represented by the variable type is certainly a bug in the netcdf file.  It will be set by the library to the largest short integer by default.

**Comment by sbiner** [comment]
I confirm that removing the _FillValue attributes ( I do not expect to have any of those in that case) takes care of that problem. The use of ```var.set_auto_maskandscale(False)``` also works. Again, thanks a lot for the help.

**Comment by jswhit** [comment]
OK, closing now then.
