### ISSUE TITLE
NOAA unknown file format

### ISSUE THREAD

**Issue by thomashrabe** [Unidata/netcdf4-python#509]
My issue with my code is that it runs on my Mac (Macport install) but fails on Ubuntu (apt). The Ubuntu code fails with RuntimeError: NetCDF: Unknown file format . Is it an installation / library version issue? Here's what I have as code: 

import netCDF4
import datetime

now = datetime.datetime.now()

mydate="{:%Y%m%d}".format(now)
print mydate
url = "http://nomads.ncep.noaa.gov:9090/dods/wave/mww3/"+mydate+"/multi_1.glo_30mext"+mydate+"_00z"
print url
data = netCDF4.Dataset(url)

**Comment by jswhit** [comment]
What version of netcdf4-python are you using on Ubuntu?  What version of the netcdf-c lib was the Ubuntu install linked against?

I suspect that the version of the netcdf c library that the Ubuntu install  uses lacks support for accessing OPENDAP datasets.

**Comment by thomashrabe** [comment]
ncdump -h http://nomads.ncep.noaa.gov:9090/dods/wave/mww3/20160119/multi_1.glo_30mext20160118_00z
ncdump: http://nomads.ncep.noaa.gov:9090/dods/wave/mww3/20160119/multi_1.glo_30mext20160118_00z: NetCDF: Unknown file format

The apt install gave the same issues, on Ubuntu, hence I ran a custom install of with the standard commands

netcdf-cxx4-4.2/
LDFLAGS=-L/usr/local/lib CPPFLAGS=-I/usr/local/include 
./configure --enable-netcdf-4 --enable-dap --enable-shared --prefix=/usr/local


netCDF4-1.2.2/

**Comment by rsignell-usgs** [comment]
You could install the free [miniconda](http://conda.pydata.org/miniconda.html), and then install netcdf4 by doing:
```
conda install -c ioos netcdf4
```

**Comment by jswhit** [comment]
Looks like the C lib was compiled without --enable-dap.  Your custom install is only building the c++ interface, you need to rebuild the c library (version 4.4.0 is now the latest version).

**Comment by thomashrabe** [comment]
I downloaded the newest version and ran 
./configure --enable-netcdf-4 --enable-dap --enable-shared --prefix=/usr/local
, which gave me the configuration below. Do I need another library to really enable OpenDAP?

# General
-------
NetCDF Version:		4.4.0
Configured On:		Tue Jan 19 23:53:20 CET 2016
Host System:		x86_64-unknown-linux-gnu
Build Directory: 	/home/thomas/usr/src/netcdf-4.4.0
Install Prefix:         /usr/local

# Compiling Options
-----------------
C Compiler:		/usr/bin/gcc
CFLAGS:			-g -O2
CPPFLAGS:		
LDFLAGS:		
AM_CFLAGS:		
AM_CPPFLAGS:		
AM_LDFLAGS:		
Shared Library:		yes
Static Library:		yes
Extra libraries:	-lhdf5_hl -lhdf5 -ldl -lm -lz 

# Features
--------
NetCDF-2 API:		yes
HDF4 Support:		no
NetCDF-4 API:		yes
NC-4 Parallel Support:	no
PNetCDF Support:	no
DAP Support:		no
Diskless Support:	yes
MMap Support:		no
JNA Support:		no

I'm sorry I'm posting here, it seems rather installation help than bug report for the python module.

**Comment by jswhit** [comment]
I guess you're missing one of the dependencies (the curl lib?) that netcdf needs for opendap support.

**Comment by WardF** [comment]
@jswhit is correct, you'll need `libcurl` to enable DAP support. Under ubuntu I use `libcurl4-openssl-dev` but any of the `libcurl4` options should work.

**Comment by thomashrabe** [comment]
This is getting weird: 

sudo apt-get install libcurl3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libcurl3 is already the newest version.

apt-file list libcurl3
libcurl3: /usr/lib/x86_64-linux-gnu/libcurl.so.3

I set 
export LDFLAGS=-L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/
export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu/"
before I run configure, but still a NO for DAP? Seems like it's not finding the libraries. What other environment var would configure use?

**Comment by jswhit** [comment]
Maybe you need to set CPPFLAGS too?

**Comment by thomashrabe** [comment]
It works! I finally could install the `libnetcdfc` so that `ncdump` would process without error. I had to rename / link to the `libcurl.so` library differently. I am building *netCDF* for *python* now, and I realize it comes with *netCDF* release that is built when I run `python setup.py build`, but it apparently links against the previously installed and renamed netCDFc library. Thanks a lot for your support!

**Comment by jswhit** [comment]
good - glad it's sorted.  closing now...
