### ISSUE TITLE
TypeError: expected bytes, list found

### ISSUE THREAD

**Issue by ihategribfiles** [Unidata/netcdf4-python#514]
I am having trouble loading some netcdf4 files. These are converted grb2 files from:
https://www.ncdc.noaa.gov/data-access/model-data/model-datasets/rapid-refresh-rap

They are converted by NCL from grb2 to netcdf4. These files open using matlab ncgeodataset. I'm having trouble googling this issue and did not get far troubleshooting myself. Github prevented me from attaching the files because it is too big.

thanks for any help!

error:

File ".\load_noaa_fn.py", line 42, in load_noaa
    rootcdf                                 = Dataset(filename,'r', format='NETCDF4')          # read in cdf
  File "netCDF4\_netCDF4.pyx", line 1557, in netCDF4._netCDF4.Dataset.__init__ (netCDF4\_netCDF4.c:9352)
TypeError: expected bytes, list found

**Comment by jswhit** [comment]
Need more information.  Posting the actual file that triggers the error would help.

**Comment by ihategribfiles** [comment]
My error was I passed my filename as a list with one item. I couldn't find where to delete this thread. Thanks for the reply anyway!
