### ISSUE TITLE
Unable to set a value to numpy.ma.masked, fails with "IndexError: too many indices for array"

### ISSUE THREAD

**Issue by dpl** [Unidata/netcdf4-python#517]
On http://docs.scipy.org/doc/numpy/reference/maskedarray.generic.html#masking-an-entry , it says that the preferred method to mask an entry when working with masked arrays with python is to assign numpy.ma.masked to it. They give as example:

import numpy as np
y = np.ma.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y[(0, 1, 2), (1, 2, 0)] = np.ma.masked
y

and this works as expected. When I try to reproduce a similar behaviour with a minimal netcdf4-python example (see code below), this fails with "IndexError: too many indices for array"

So my question is, is this expected behaviour? Am I not supposed to mask entries in this way with masked arrays that live within netcdf4 datasets? Different ways of indexing also seem to not help.. Thanks in advance..

from netCDF4 import Dataset
import numpy as np
from numpy.random import uniform
rootgrp = Dataset("test.nc", "w", format="NETCDF4")
time = rootgrp.createDimension("time", None)
lat = rootgrp.createDimension("lat", 3)
lon = rootgrp.createDimension("lon", 4)
times = rootgrp.createVariable("time","f8",("time",))
latitudes = rootgrp.createVariable("latitude","f4",("lat",))
longitudes = rootgrp.createVariable("longitude","f4",("lon",))
temp = rootgrp.createVariable("temp","f4",("time","lat","lon",), fill_value = -99)
latitudes[:] = np.arange(3)
longitudes[:] = np.arange(4)
temp[0:2,:,:] = uniform(size=(2,3,4))
temp.missing_value = -99
temp[0,0,0] = -99 #works
temp[1,0,0] = np.ma.masked #doesn't work

**Comment by jswhit** [comment]
temp is a netcdf variable, not a masked array.  You can create a masked array, then assign it to the netcdf variable, and the masked values will be handled automatically (by either converting them to missing values of fill values).  You can't however treat a netcdf variable as if it were a masked array directly.

**Comment by dpl** [comment]
Thanks, Jeff! I thought because of 
In [9]: type(temp[0])
Out[9]: numpy.ma.core.MaskedArray
One could perhaps also do
temp[0][0,1] = np.ma.masked
or similar. But thanks for clarifying. 

So, to summarize: to mask a numpy masked array one modifies its mask, but to mask an entry of a netcdf variable, one assigns the current missing_value, and that's the only way. Also, if one changes the missing_value, the mask changes as well, except for when values are the same as _FillValue, then they stay masked even if the missing_value changes. Is that summarizing the usage patterns about correctly? Thanks again!

**Comment by dpl** [comment]
Hm, and a related issue: if I continue with the above example, and I set one value to the current _FillValue, another to the current missing_value, leave all others as valid values, then close the file, and dump it externally via, say, ncks -- then what I see in the ncks dump is that the _FillValue value gets dumped with the _FillValue value, and the missing_value value with the missing_value value. But from the netcdf4-python docs ("When data is written to a variable, the masked array is converted back to a regular numpy array by replacing all the masked values by the fill_value of the masked array."), I would have expected both (because both were equally masked) to contain, in the ncks dump, the missing_value value, because the fill_value of the masked array is taken from the missing_value (also from the docs: "The fill_value of the masked array is set to the missing_value attribute "). So it seems more to me that the first quote is a bit misleading, and when writing to file, the contents of temp[i].data seem to be written to file as-is?

**Comment by jswhit** [comment]
Here's how it works.  If you the netcdf variable has a ``missing_value`` attribute set, and you assign a masked array to a slice, the mask array is converted to a numpy array with the masked values replaced with the ``missing_value``, and that numpy array is written to the netcdf file.  If you don't have a ``missing_value`` attribute set, the ``_FillValue`` is used instead.  If the documentation is not clear on this point I will fix it.
