### ISSUE TITLE
nc4tonc3 broken because bad indenting

### ISSUE THREAD

**Issue by jdemaria** [Unidata/netcdf4-python#519]
Hi, it seems that nc4tonc3 is broken because bad indenting in file netCDF4/utils.py from line 536:
`attdict = ncvar.__dict__`
to line 559 included:
`ncfile3.sync() # flush data to disk`
these lines must be in the loop line 522 too:
`for varname,ncvar in ncfile4.variables.items():`
I checked in an old version 1.0.5 and there was no bug

**Comment by jswhit** [comment]
Thanks for catching this.  Fix in pull request #520

**Comment by jswhit** [comment]
pull request #520 merged, closing now...
