### ISSUE TITLE
IndexError: in the future, 0-d boolean arrays will be interpreted as a valid boolean index

### ISSUE THREAD

**Issue by opoplawski** [Unidata/netcdf4-python#521]
I'm seeing the following trying to build on Fedora Rawhide:
~~~~~
+ python run_all.py
...................E.........................................................
======================================================================
ERROR: runTest (tst_masked.PrimitiveTypesTestCase)
testing auto-conversion of masked arrays and packed integers
----------------------------------------------------------------------
not running tst_unicode3.py ...

netcdf4-python version: 1.2.2
HDF5 lib version:       1.8.16
netcdf lib version:     4.4.0
numpy version           1.11.0b2
Traceback (most recent call last):
  File "/builddir/build/BUILD/netcdf4-python-1.2.2rel/test/tst_masked.py", line 56, in setUp
    foo2[:] = maskedarr2
  File "netCDF4/_netCDF4.pyx", line 3966, in netCDF4._netCDF4.Variable.__setitem__ (netCDF4/_netCDF4.c:42895)
IndexError: in the future, 0-d boolean arrays will be interpreted as a valid boolean index
~~~~~

**Comment by shoyer** [comment]
We should fix this -- the final release of numpy 1.11 will be out shortly.

@opoplawski for now, use numpy 1.10, not the 1.11 beta.

**Comment by jswhit** [comment]
@shoyer, do you understand what the issue is (and how to fix it)?

**Comment by shoyer** [comment]
Nope, I haven't encountered this one before

**Comment by jswhit** [comment]
Pull request #522 has a workaround for this. The error is triggered when we create a numpy array with np.nan values in it, convert that to a masked array, and then attempt to write that masked array to a netcdf variable that has a missing_value attribute set to 'nan'.  Apparently with numpy 1.11 you can't create a masked array from a numpy array with nans using

    maskedarr2 = ma.masked_values(ranarr2,np.nan)

My workaround was to use

   maskedarr2 = ma.masked_invalid(ranarr2)

instead, which seems to work.

**Comment by opoplawski** [comment]
Thanks that did the trick.
