### ISSUE TITLE
tst_cdf5.test_cdf5 fails on 32-bit Ubuntu

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf4-python#524]
> This error is manifesting in the python interface, but if the root problem is determined to exist in the C library I will move the issue over there.

netCDF-C is using Docker-based regression tests; these tests validate netCDF-C, Fortran, C++, Python and Charlie Zender's NCO.  

The Python tests are failing in the `unidata/nctests:serial32` environment, but are passing in the `unidata/nctests:serial` (64-bit) environment.  I haven't tested the `openmpi(32)` or `mpich(32)` environments yet. 

This failure does not occur when using netcdf4-python version `v1.2.2rel`.  

You can observe this behavior with docker by running the following commands:

## Success:

     $ docker run -it -e PBRANCH=v1.2.2rel -e RUNC=OFF -e RUNCXX=OFF -e RUNF=OFF -e RUNNCO=OFF unidata/nctests:serial32

## Failure:

    $ docker run -it -e RUNC=OFF -e RUNCXX=OFF -e RUNF=OFF -e RUNNCO=OFF unidata/nctests:serial32

The failure is as follows:

`````
(...)
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/netCDF4-1.2.3.egg-info
not running tst_unicode3.py ...

netcdf4-python version: 1.2.3
HDF5 lib version:       1.8.16
netcdf lib version:     4.4.1-development
numpy version           1.8.2
...............................................................................E
======================================================================
ERROR: runTest (tst_cdf5.test_cdf5)
testing NETCDF3_64BIT_DATA format (CDF-5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/netcdf4-python/test/tst_cdf5.py", line 17, in setUp
    d = nc.createDimension('dim',dimsize) # 64-bit dimension
  File "_netCDF4.pyx", line 1999, in netCDF4._netCDF4.Dataset.createDimension (netCDF4/_netCDF4.c:13721)
  File "_netCDF4.pyx", line 2673, in netCDF4._netCDF4.Dimension.__init__ (netCDF4/_netCDF4.c:21342)
OverflowError: long int too large to convert

----------------------------------------------------------------------
Ran 80 tests in 26.517s

FAILED (errors=1)
`````

**Comment by jswhit** [comment]
Seems like that test should be skipped on 32 bit systems.  I'll create a pull request for that.

**Comment by jswhit** [comment]
see pull request #525

**Comment by WardF** [comment]
Sounds good, although I'm curious; the C library CDF5 functionality is the same on 32 and 64 bit systems, so I'm surprised it wouldn't also work in the Python interface on either 32/64.  I guess I'm also not surprised it doesn't, so thanks for fixing this, I'll close the issue since you've got the pull request addressing it :).

**Comment by jswhit** [comment]
I wonder what happens in the C lib if you try to create a dimension with a length that overflows a 32 bit integer on a 32-bit system.  This is the situation that was triggered in the failing test.
