### ISSUE TITLE
slicing over VLEN variable with same length input returns error

### ISSUE THREAD

**Issue by jhprinz** [Unidata/netcdf4-python#526]
I have created a VLEN variable `test` of type `numpy.float64`. Now I can set values by

``` py
var = ncfile.variables['test']
data0 = np.array([1.0, 2.0, 3.0])
data1 = np.array([0.1, 0.2]) 

var[0] = data0
var[1] = data1
```

what also works is

``` py
var[0:2] = np.array([data0, data1])
```

this fails however when using two datasets of the same length

``` py
var[0:2] = np.array([data0, data0])

>>> IndexError: single element VLEN slices must be specified by integers only
```

one reason is that in the latter case `np.array` will create a single array, while in the first it create a `np.array(dtype=object)` that contains both arrays. If I mimic this by

``` py
data = np.empty((2, ), dtype=object)
data[:] = [data1, data2]

var[0:2] = data

>>> IndexError: single element VLEN slices must be specified by integers only

```

I get the same error.

I presume this happens in some detection of the shape of the input.

**Comment by jswhit** [comment]
Right now you can only assign data to a VLEN variable one element at a time, with integer indices (not slices).  The error message should be a little more clear about that.

**Comment by SpghttCd** [comment]
> Right now you can only assign data to a VLEN variable one element at a time, with integer indices 

Ok this is understood and just needs to be kept in mind - but it took me some time to find out that "integer" here means exclusively the pure python-int, no `np.intXY` or `np.uintXY` allowed.

Could that be updated so that numpy-ints work, too? Or at least mention this very strict requirement also in the error msg, because up to now the error complains about requiring an integer index while already getting one...
And the code needs such an additional line like
`idx_arr = [int(idx) for idx in idx_arr]`
which is not really nice

**Comment by jswhit** [comment]
how would you check for a numpy scalar integer?

**Comment by jswhit** [comment]
Please try pull request #757.  

It would be helpful if you could provide an example that failed before (and hopefully works now) so I can add it to the tests.

**Comment by SpghttCd** [comment]
```
strtest = nc.Dataset('X:/strtest.nc', 'w')
strtest.createDimension('tenstrings', 10)
strtest.createVariable('tenstrings', 'str', ['tenstrings'])
strtest['tenstrings'][np.int32(5)] = 'asdf'
strtest.close()
```

**Comment by SpghttCd** [comment]
The following code - more precisely line 4 - fails up to now:
```
strtest = nc.Dataset('X:/strtest.nc', 'w')
strtest.createDimension('tenstrings', 10)
strtest.createVariable('tenstrings', 'str', ['tenstrings'])
strtest['tenstrings'][np.int32(5)] = 'asdf'
strtest.close()
```

Replacing `np.int32(5)` by `int(np.int32(5))`  - or directly by `5` of course - makes it work.

**Comment by jswhit** [comment]
pull request #757 merged, with your example added as a test
