### ISSUE TITLE
HDF error

### ISSUE THREAD

**Issue by lisapalathingal** [Unidata/netcdf4-python#534]
Hi,

I have a script with 2 functions: 1st function creates a json file from a netcdf file. 2nd function updates the netcdf file based on a new json file. When I run the script with 1 function, the code works fine. But, when I run the script with these 2 fucntions, its showing the following error:

Traceback (most recent call last):
  File "newWork.py", line 114, in <module>
    add_values_into_netcdf()
  File "newWork.py", line 108, in add_values_into_netcdf
    fileHandle = netCDF4.Dataset('parameter.nc', mode='a')
  File "netCDF4.pyx", line 1466, in netCDF4.Dataset.__init__ (netCDF4.c:19673)
RuntimeError: NetCDF: HDF error

Please let me know if you have any suggestions on how to fix this.

**Comment by jswhit** [comment]
If the file parameter.nc is relatively small, please gzip it and attach it to this issue.

**Comment by jswhit** [comment]
Are you sure you have write permissions in the directory that parameter.nc lives in?

**Comment by lisapalathingal** [comment]
Hey, 

I fixed the issue. I forgot to close the netcdf file in both functions. My bad..Thanks!!
