### ISSUE TITLE
Generating file with Parallel I/O Support

### ISSUE THREAD

**Issue by rowanwins** [Unidata/netcdf4-python#536]
Gday,

I've just been reading up on enabling parallel I/O support for NetCDF files. I see a related issue #132 about Parallel I/O which says it's been fixed however no other details are provided.

So is it theoretically possible to use nercdf4-python to generate a file with parallel I/O support?Alternatively if it isn't possible with netcdf4-python can it be done with ncgen and a cdl file? I guess I'm after the simplest way possible :) 

Thanks in advance,
Rowan

**Comment by jswhit** [comment]
You can do read operations (or simultaneous write operations on different files) in parallel threads, or using the multiprocessing module in the standard library.  You can't do write operations to the same file from multiple threads or processes though, and there is currently no MPI support.

**Comment by rowanwins** [comment]
Thanks for the information @jswhit
