### ISSUE TITLE
No package 'hdf5' found

### ISSUE THREAD

**Issue by vinodrajkonda** [Unidata/netcdf4-python#562]
I'm getting below error while installing netCDF python module (netCDF4-1.2.4) on RHEL 64-bit machine. hdf5 is installed with share-enabled and I have mentioned the installation path in setup.cfg as below. Could you please suggest why is it not picking hdf5 libraries?

Error:
=====
user@server:/local/tools/downloads/netCDF4-1.2.4                                                                                               44 % python setup.py build
reading from setup.cfg...
Package hdf5 was not found in the pkg-config search path.
Perhaps you should add the directory containing `hdf5.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hdf5' found
using nc-config ...
using netcdf library version 4.3.2
running build
running build_py
creating build

setup.cfg:
=======
[options]
use_ncconfig=false
use_cython=True
ncconfig=/local/tools/misc/netcdf-4.3.2/bin/nc-config
[directories]
HDF5_dir = /local/tools/misc/hdf5-1.8.8

**Comment by jswhit** [comment]
That error is usually harmless - since you didn't post the rest of the output it's hard to tell what went wrong.  I would suggest setting use_ncconfig to True in setup.cfg, and commenting out the HDF5_dir entry.  If that fails, please include the full output of 'setup.py build'.

**Comment by vinodrajkonda** [comment]
I did run with use_ncconfig as true and commented out the HDF5 directory path entry and it still gives me the same error, PFA file for complete error. Please advice.
[netCDF_install_error.txt](https://github.com/Unidata/netcdf4-python/files/248973/netCDF_install_error.txt)

**Comment by dopplershift** [comment]
I don't see any errors in that log--what *problem* are you actually having using the library? Have you tried doing a:
```sh
python setup.py install
```
If so, what happens when you try:
```sh
python -c "import netCDF4"
```

**Comment by vinodrajkonda** [comment]
I didn't proceed with the install as it was saying hdf5 not found. I will go ahead now and let you know how it goes.

**Comment by vinodrajkonda** [comment]
Install did go through fine except that it says, hdf 5 not found, PFA logs.
[netCDF_install_log.txt](https://github.com/Unidata/netcdf4-python/files/249252/netCDF_install_log.txt)

But import fails with below error. I wonder how does it can use hdf5 libraries if build and install say hdf5 not found.

18 % python -c "import netCDF4"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: No module named _netCDF4

**Comment by dopplershift** [comment]
I bet you ran the import check from the source directory. Try changing to a different directory and see what happens...

**Comment by vinodrajkonda** [comment]
yeah, that helped. But I still can't see how will it work when we want to create files for hdf5 as it says it didn't find it?

**Comment by jswhit** [comment]
Red herring - the error message comes from pkg_config, the correct path to the library was provided by nc_config. You're fine.

**Comment by vinodrajkonda** [comment]
Thanks all.
