### ISSUE TITLE
using `_` in dimension names can cause Dataset to corrupt (somehow)

### ISSUE THREAD

**Issue by jhprinz** [Unidata/netcdf4-python#569]
This is somewhat hard to explain, because I was not able to reproduce the error with a simple example. This appeared in a larger project and I could track the error down to this:

``` py

nc = Dataset()
...
# this works fine
nc.variables['stores_name'][:]
nc.create_dimension('snapshot0kinetics')
nc.variables['stores_name'][:]

# this causes an error
nc.variables['stores_name'][:]
nc.create_dimension('snapshot0_kinetics')
nc.variables['stores_name'][:]  # after the creation this line fails with

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Variable.__getitem__ (netCDF4/_netCDF4.c:37912)()
netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Variable._get (netCDF4/_netCDF4.c:47437)()
RuntimeError: NetCDF: HDF error

nc.variables['stores_name'][:]  # trying again works! But
nc.sync() # always fails after the creation
```

So, when using an `_` (underscore) in the dimension name something strange happens. I guess I was lucky to just tried to run it without it. I might never have found this. It is (obviously) easy to get around this, but I was wondering if there are restrictions in the dimension name

A few notes. 
1. In both cases it might happen, that the state of the nc file is not the same, so it might have to do with other interference with content. 
2. I was also not able to make a simple example to reproduce this. 
3. the error appears when trying to access any variable, does not matter which one (at least the ones I have tried)
4. I am using the this versions installed from conda
   
   ```
   h5py                      2.6.0               np110py27_0  
   hdf5                      1.8.16                        0  
   libnetcdf                 4.4.0                         1  
   netcdf4                   1.2.4               np111py27_0  
   numpy                     1.11.1                   py27_0  
   python                    2.7.11                        0  
   ```

I will post again, if I manage to find an easy example.

**Comment by jswhit** [comment]
from http://www.unidata.ucar.edu/software/netcdf/docs/file_format_specifications.html

" The first character of a name must be alphanumeric, a multi-byte UTF-8 character, or '_' (reserved for special names with meaning to implementations, such as the “_FillValue” attribute). Subsequent characters may also include printing special characters, except for '/' which is not allowed in names. Names that have trailing space characters are also not permitted. "

Nothing about underscores in the middle of names.  

Probably a library bug, but we need to be able to reproduce it with a simpler example.

**Comment by jhprinz** [comment]
Thanks. I had another idea that I will look into. Can it be that it has to do with constructing a `unicode` vs `str` object. I will look into this some more.

**Comment by jswhit** [comment]
any update on this?

**Comment by DennisHeimbigner** [comment]
Without an example, this is going to be hard to solve. We use underscores in many of our
.cdl test case files, so there has to be something else going one.

**Comment by jhprinz** [comment]
No update here. I did not encounter this problem again, but I also found a way to circumvent the problem. Since this is so long ago and I cannot really give an example I consider this solved from my part. If the problem reappears I can open another issue and point to this discussion. Thanks for the help.
