### ISSUE TITLE
ImportError: libcom_err.so.3 after installing NetCDF4 in Anaconda

### ISSUE THREAD

**Issue by Omer80** [Unidata/netcdf4-python#572]
Hello, I am running Python 2.7.10 |Anaconda custom (64-bit) on Ubuntu 16.04 LTS

On the previous version of Ubuntu that I had, I didn't encounter any problem with importing NetCDF4, but after the installation of Ubuntu 16.04 and Anaconda 2, I received this error message:
`>>> import netCDF4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ohm/anaconda2/lib/python2.7/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: libcom_err.so.3: cannot open shared object file: No such file or directory`

What might be the problem?

**Comment by jswhit** [comment]
A quick google suggests that libcom_err is a "Common error description library".  Certainly nothing to do with netcdf.  Are you using the netcdf4-python that came with anaconda?  If so, maybe it's not compatible with Ubuntu 16?  Really just guessing here.

**Comment by Omer80** [comment]
I tried again to reinstall everything (Anaconda 2 and the NetCDF4 package through `conda install`) and it seems to work..
