### ISSUE TITLE
Variable objects don't have an available "name" attribute

### ISSUE THREAD

**Issue by edupenabad** [Unidata/netcdf4-python#578]
I'm trying to do the following:

```python
import netCDF4 as nc

ds = nc.Dataset('file.nc','r')
vv = ds.variables['some_var_name']

print vv.name
```

and I get an `AttributeError: NetCDF: Attribute not found`

Shouldn't I be able to access a netCDF4.Variable object's name in that way?

**Comment by jswhit** [comment]
Works for me
```python
>>> from netCDF4 import Dataset
>>> nc = Dataset('http://test.opendap.org/opendap/data/nc/bears.nc')
>>> v = nc['bears']
>>> v.name
u'bears'
```

This was added in version 1.1.2

**Comment by edupenabad** [comment]
Thanks a lot!

that was my problem, as I was using 1.1.1
