### ISSUE TITLE
read data from hdfs

### ISSUE THREAD

**Issue by wsf1990** [Unidata/netcdf4-python#580]
I want to use netcdf4 read the data from hdfs.Dose it has some method?

**Comment by jswhit** [comment]
what is hdfs?

**Comment by wsf1990** [comment]
hadoop fs

**Comment by jswhit** [comment]
OK, did a bit of googling on that and I'm pretty sure the answer is no.

**Comment by wsf1990** [comment]
all right，Thanks！
