### ISSUE TITLE
Reading a grib format file into a netcdf dataset 

### ISSUE THREAD

**Issue by dwSun** [Unidata/netcdf4-python#587]
I am using netcdf4-python to handle my grib2 format data(reading and writing). I have to
convert my data to netcdf format by using wgrib2 from:

http://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/
But some global attributes are missing and this is not acceptable. I have
written some mails with the author of wgrib2. Then I realized that
netcdf-java from:
http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/
can read grib2 format data and handle it as netcdf format file directly.

According to the reply from support-netcdf@unidata.ucar.edu, topic:[2netCDF #CQX-737246]

> Currently, netcdf4-python cannot read grib2 files directly.

I know scitools-iris can handle this kind of task but it is to heavy for my case.
pyrib is another solution, but it involves extra data handling.

So will netcdf4-python add grib format support in the future?

**Comment by jswhit** [comment]
No.  There are python grib readers out there ([pygrib](https://github.com/jswhit/pygrib).  I think it's the domain of a third party app to translate the grib variables and metadata to netcdf-like data structures, and then write out to netcdf.  In fact, this is what iris does (it uses the grib_api python interface and netcdf4-python).  I don't think this really belongs in netcdf4-python.

It would be great if someone would translate the netcdf-java code for doing this into python.  It's not an easy or quick task though.

**Comment by shoyer** [comment]
Also consider using PyNIO for GRIB reading, either on its own or as wrapped by xarray.
