### ISSUE TITLE
Error in running python setup.py: ['help-commands', 'help']) or sys.argv[1] == 'egg_info' IndexError: list index out of range

### ISSUE THREAD

**Issue by ArashMehraban** [Unidata/netcdf4-python#600]
I get the following error when I run python setup.py 

cython version 0.25.1 found ...
reading from setup.cfg...
Package hdf5 was not found in the pkg-config search path.
Perhaps you should add the directory containing `hdf5.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hdf5' found
using nc-config ...
Traceback (most recent call last):
  File "setup.py", line 379, in <module>
    ['help-commands', 'help']) or sys.argv[1] == 'egg_info':
IndexError: list index out of range

This is 14.04 Ubuntu machine. HDF5 and netCDF are installed. Hdf5 is also installed in /usr/local. Could you help?

**Comment by jswhit** [comment]
Sorry, but I've got nothing.  Hopefully someone else will have run across this.  As a workaround, you could modify setup.cfg to stop using nc-config, and set netCDF4_dir and HDF5_dir directly.

**Comment by ckhroulev** [comment]
@ArashMehraban If the command you ran is indeed "`python setup.py`", then `setup.py` got no arguments and `sys.argv` is empty. In that case it's not surprising that `sys.argv[1]` failed with the `IndexError` exception. If you are trying to install `netcdf4-python`, run "`python setup.py install`" instead.

**Comment by ArashMehraban** [comment]
Yes, I did run  "python setup.py" and it throws that IndexError exception but I am not sure why the sys.argv[1] is empty. At any rate,  "python setup.py install worked" Thnx :)

**Comment by ArashMehraban** [comment]
I am also leaving this comment in case anybody else runs to this issue:
After the suggested command by **ckhroulev** above, I got my netcdf4-python working, but I was getting a warning that said:

UserWarning: /home/cnetworks-admin/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
warnings.warn(msg, UserWarning)

So, that has something to do with a problem with my Python environment configuration on my Linux distribution. So that can be fixed by:

chmod g-wx,o-wx ~/.python-eggs

**Comment by dopplershift** [comment]
if you run `python setup.py`, you haven't given it any arguments. Therefore, the contents of `sys.argv` are `['setup.py']`. `sys.argv` isn't empty, it just doesn't contain a second argument (remember, python indexing starts at 0).

**Comment by ckhroulev** [comment]
@dopplershift Thanks for pointing this out! (I keep forgetting that the name of the executable is included in `sys.argv` -- probably because I never process arguments "by hand".)
