### ISSUE TITLE
split netcdf4time into standalone package

### ISSUE THREAD

**Issue by jhamman** [Unidata/netcdf4-python#601]
I'd like to propose splitting `netcdf4time` into a standalone package. The motivation for this request is coming from ongoing xarray development (https://github.com/pydata/xarray/issues/1084) where we would like to use `netcdftime` without the complete netCDF dependency. This would not require any change to user code as netcdf-python would still be able to provide users the netcdftime module. I'd be happy to perform this task, including setting up TravisCI, Pypi, etc...

cc @shoyer @spencerahill @spencerkclark @darothen

xref: https://github.com/pydata/xarray/issues/1084, https://github.com/pydata/xarray/issues/789

**Comment by shoyer** [comment]
To give a clearer motivation: netCDF-C can be hard to install. But `netcdftime` (a name I would prefer to `netcdf4time`) is still useful even if you only have `scipy`, `pydap` or `h5netcdf` for reading netCDF-like data. It's also useful even if you never read or write a netCDF files, because it contains all the necessary logic for working with custom datetime types (now including arithmetic).

**Comment by jswhit** [comment]
This is fine with me, as long as installing netcdf4-python installs netcdftime as well.   I can ask the Unidata folks to create a netcdf4time project.

**Comment by shoyer** [comment]
Let's call it netcdftime, which matches the existing name of the Python
module.

**Comment by dopplershift** [comment]
So do we have consensus on `netcdftime` ? I can create the repo as soon as I know what to call it.

**Comment by jhamman** [comment]
netcdftime is fine.  I would actually prefer cftime since that's what it is
but I understand the namespace confusion is an issue.

Joe Hamman
Post-Doctoral Researcher
Research Applications Laboratory
Hydrometeorological Applications Program
National Center for Atmospheric Research
Phone: 206-498-5497
Email:  jhamman@ucar.edu
Web:  joehamman.com

**Comment by dopplershift** [comment]
Repository is up at: https://github.com/Unidata/netcdftime

Jeff, you should have everything you need to give people permission as necessary--though I'm happy to do more if you want.

**Comment by jswhit** [comment]
Thanks Ryan - I don't have a "Settings" button on the main project page (as I do for netcdf4-python) so I can't add @jhamman as a contributor.

**Comment by dopplershift** [comment]
Accept my invite to the repo. 😁

**Comment by jswhit** [comment]
OK, done. I invited @jhamman to be a collaborator.

**Comment by jhamman** [comment]
A first swing at the stand-alone netcdftime package is up: https://github.com/Unidata/netcdftime

For that package, there are a bunch of issues I need to work through including documentation, testing, and pypi/conda distributions.

Once I have that all done, I'll issue a PR here removing the `netcdftime` module.

**Comment by jswhit** [comment]
Sounds like I should go ahead with a 1.2.6 release with netcdfime, and target removal for the 1.2.7 release?

**Comment by pelson** [comment]
```netcdftime``` was created. It is now called ```cftime```. https://github.com/Unidata/cftime

I think this can now be closed! 🎉
