### ISSUE TITLE
Raise a more informative error when pickling

### ISSUE THREAD

**Issue by shoyer** [Unidata/netcdf4-python#602]
pickle is Python's default serialization method, so lots of libraries use it.

netCDF4 does not support pickle, which is actually pretty reasonable -- it's not obvious how to (de)serialize a netCDF file (e.g., just with the filename, or with a complete image of the file?).

But, we should raise more informative errors when pickling Dataset/Variable objects. For example, netCDF4 currently produces hard to interpret error messages (`RuntimeError: NetCDF: Not a valid ID`) only after attempted access to data from a pickled/unpickled `netCDF4.Variable`:  https://github.com/dask/distributed/issues/629

CC @mrocklin @pwolfram

**Comment by jswhit** [comment]
How about adding a `__reduce__` method with:

    def __reduce__(self):         
        raise NotImplementedError('Dataset is not picklable')

**Comment by shoyer** [comment]
Yes, that would be great!

**Comment by jswhit** [comment]
see pull request #604

**Comment by jswhit** [comment]
pull request #604 merged

**Comment by shoyer** [comment]
Thanks Jeff!
