### ISSUE TITLE
Test failures on ppc64

### ISSUE THREAD

**Issue by opoplawski** [Unidata/netcdf4-python#608]
Trying to build netcdf4-python 1.2.5 for Fedora and getting:
```
+ /usr/bin/python2 run_all.py
..F.F............................................................................E.......
======================================================================not running tst_unicode3.py ...
netcdf4-python version: 1.2.5
HDF5 lib version:       1.8.17
netcdf lib version:     4.4.1
numpy version           1.11.2
ERROR: runTest (tst_enum.EnumTestCase)
testing enum data type
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/netcdf4-python-1.2.5rel/test/tst_enum.py", line 36, in setUp
    cloud_var[:] = datain_masked
  File "netCDF4/_netCDF4.pyx", line 4135, in netCDF4._netCDF4.Variable.__setitem__ (netCDF4/_netCDF4.c:45610)
  File "netCDF4/_netCDF4.pyx", line 4344, in netCDF4._netCDF4.Variable._put (netCDF4/_netCDF4.c:47131)
RuntimeError: NetCDF: HDF error
======================================================================
FAIL: runTest (tst_endian.EndianTestCase)
testing endian conversion capability
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/netcdf4-python-1.2.5rel/test/tst_endian.py", line 142, in runTest
    issue310(self.file)
  File "/builddir/build/BUILD/netcdf4-python-1.2.5rel/test/tst_endian.py", line 101, in issue310
    var_big_endian2[:].filled())
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 918, in assert_array_almost_equal
    precision=decimal)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 739, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 6 decimals
(mismatch 80.0%)
 x: array([  1.831347e-317,   1.831347e-317,  -9.990000e+002,  -9.990000e+002,
        -9.990000e+002,  -9.990000e+002,  -9.990000e+002,  -9.990000e+002,
        -9.990000e+002,  -9.990000e+002])
 y: array([  3.207376e-192,   1.831347e-317,   2.001905e-319,   2.001905e-319,
         2.001905e-319,   2.001905e-319,   2.001905e-319,   2.001905e-319,
         2.001905e-319,   2.001905e-319])
======================================================================
FAIL: runTest (tst_compound_alignment.CompoundAlignTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/netcdf4-python-1.2.5rel/test/tst_compound_alignment.py", line 104, in runTest
    assert cells[name].dtype == new_cells[name].dtype
AssertionError
----------------------------------------------------------------------
Ran 89 tests in 36.858s
FAILED (failures=2, errors=1)
``
Working on x86_64 and i386.

**Comment by jswhit** [comment]
Did the tests pass with 1.2.4?

**Comment by opoplawski** [comment]
No.  Looks like 1.1.0 was the last successful build on pcc64 we had - see http://ppc.koji.fedoraproject.org/koji/packageinfo?packageID=14557

**Comment by jswhit** [comment]
Hmmm.  Works on x86_64 though, AFAICT.

**Comment by jswhit** [comment]
May be related to pull request #311

**Comment by opoplawski** [comment]
I have access if there is anything I can run for you let me know.

**Comment by jswhit** [comment]
Could you try running this on PPC64?

    >>> import numpy=
    >>> is_native_little = numpy.dtype('<f4').byteorder == '='
    >>> is_native_big = numpy.dtype('>f4').byteorder == '='
    >>> print is_native_little, is_native_big

(to see if numpy is correctly identifying PPC as big endian - you should get `False, True`.

**Comment by jswhit** [comment]
Even simpler, you can just do
    
    >>> import netCDF4
    >>> print netCDF4.is_native_little, netCDF4.is_native_big

**Comment by opoplawski** [comment]
Yep, I get False True

**Comment by jswhit** [comment]
How about applying this patch to `tst_endian.py`

```
[mac28:python/netcdf4-python.git/test] jwhitaker% git diff tst_endian.py
diff --git a/test/tst_endian.py b/test/tst_endian.py
index 6856704..1e0574f 100644
--- a/test/tst_endian.py
+++ b/test/tst_endian.py
@@ -4,9 +4,12 @@ import unittest, os, tempfile
 from numpy.testing import assert_array_equal, assert_array_almost_equal

 data = np.arange(12,dtype='f4').reshape(3,4)
-FILE_NAME = tempfile.NamedTemporaryFile(suffix='.nc', delete=False).name
-FILE_NAME2 = tempfile.NamedTemporaryFile(suffix='.nc', delete=False).name
-FILE_NAME3 = tempfile.NamedTemporaryFile(suffix='.nc', delete=False).name
+#FILE_NAME = tempfile.NamedTemporaryFile(suffix='.nc', delete=False).name
+#FILE_NAME2 = tempfile.NamedTemporaryFile(suffix='.nc', delete=False).name
+#FILE_NAME3 = tempfile.NamedTemporaryFile(suffix='.nc', delete=False).name
+FILE_NAME = 'test1.nc'
+FILE_NAME2 = 'test2.nc'
+FILE_NAME3 = 'test3.nc'

 def create_file(file,format,data):
     import warnings
@@ -130,9 +133,10 @@ class EndianTestCase(unittest.TestCase):

     def tearDown(self):
         # Remove the temporary files
-        os.remove(self.file)
-        os.remove(self.file2)
-        os.remove(self.file3)
+        pass
+        #os.remove(self.file)
+        #os.remove(self.file2)
+        #os.remove(self.file3)

     def runTest(self):
         """testing endian conversion capability"""
```
and then attaching the resulting `test1.nc` file to this ticket?  (I think you have to gzip it first)

**Comment by opoplawski** [comment]
[test1.nc.gz](https://github.com/Unidata/netcdf4-python/files/632499/test1.nc.gz)

here you go.

**Comment by jswhit** [comment]
The missing_value and _FillValue attributes are apparently not being byte-swapped correctly.  When you get a chance, please try applying this patch to _netCDF4.pyx

``
diff --git a/netCDF4/_netCDF4.pyx b/netCDF4/_netCDF4.pyx
index 5176f3b..1c270d9 100644
--- a/netCDF4/_netCDF4.pyx
+++ b/netCDF4/_netCDF4.pyx
@@ -3257,7 +3257,9 @@ behavior is similar to Fortran or Matlab, but different than numpy.
                         fillval = numpy.array(fill_value, self.dtype)
                         if (is_native_little and self.endian() == 'big') or\
                            (is_native_big and self.endian() == 'little'):
+                            print 'byte-swapping fillval: before ',fillval
                             fillval = fillval.byteswap(True)
+                            print 'byte-swapping fillval: after ',fillval
                         _set_att(self._grp, self._varid, '_FillValue',\
                                  fillval, xtype=xtype)
                     else:
@@ -3662,7 +3664,9 @@ details."""
             elif name in ['valid_min','valid_max','valid_range','missing_value'] and self._isprimitive:
                 if (is_native_little and self.endian() == 'big') or\
                    (is_native_big and self.endian() == 'little'):
+                    print 'byte-swapping missing_value: before ',value
                     value = numpy.array(value, self.dtype).byteswap(True)
+                    print 'byte-swapping missing_value: after ',value
                 else:
                     value = numpy.array(value, self.dtype)
             self.setncattr(name, value)
``

and then (after building and installing), post the output of tst_endian.py.

**Comment by opoplawski** [comment]
I think this is what you're after:
```
byte-swapping fillval: before  -999.0
byte-swapping fillval: after  1.83141044105e-317
byte-swapping missing_value: before  999.0
byte-swapping missing_value: after  1.83134720065e-317
byte-swapping missing_value: before  999.0
byte-swapping missing_value: after  1.83134720065e-317
```

**Comment by jswhit** [comment]
OK, thanks - it's doing what it's supposed to do.  I guess my assumptions about how the C library deals with endian-ness are wrong.  The docs say that the data should be converted back to the native endian type when read back in.  This is what happens on little endian platforms, but apparently not on big endian platforms.   Any chance you could give me temporary ssh access to a PPC64 machine so I can debug this further?

**Comment by jswhit** [comment]
The endian-related test failures are fixed in pull request #615.  However, tst_enum.py is still failing - probably because of a library bug for enum data types on PPC platforms.  Will try to create a C program to trigger the error and create an issue on netcdf-c.

**Comment by jswhit** [comment]
Is the tst_enum.c netcdf-c test passing?

**Comment by jswhit** [comment]
Never mind - it is a bug in the netcdf4-python enum code.  Fix is forthcoming.

**Comment by jswhit** [comment]
OK, all tests pass now on PPC64 using pull request #615

**Comment by jswhit** [comment]
Pull request #615 merged.  I'll create a new release after the holidays.  Thanks for the bug report.

**Comment by opoplawski** [comment]
Works here.  Thanks!
