### ISSUE TITLE
Errors from netcdf creation, thanks.

### ISSUE THREAD

**Issue by duan2008** [Unidata/netcdf4-python#609]
Hello, everyone,

      I just have some problems when I run a R package to create nedcdf files. The error are as follows:

[root@pc090-056 netcdf]# cd
[root@pc090-056 ~]# R

R version 3.0.2 (2013-09-25) -- "Frisbee Sailing"
Copyright (C) 2013 The R Foundation for Statistical Computing
Platform: x86_64-unknown-linux-gnu (64-bit)

R は、自由なソフトウェアであり、「完全に無保証」です。
一定の条件に従えば、自由にこれを再配布することができます。
配布条件の詳細に関しては、'license()' あるいは 'licence()' と入力してください。

R は多くの貢献者による共同プロジェクトです。
詳しくは 'contributors()' と入力してください。
また、R や R のパッケージを出版物で引用する際の形式については
'citation()' と入力してください。

'demo()' と入力すればデモをみることができます。
'help()' とすればオンラインヘルプが出ます。
'help.start()' で HTML ブラウザによるヘルプがみられます。
'q()' と入力すれば R を終了します。

> library(climdex.pcic.ncdf)
 要求されたパッケージ PCICt をロード中です
> input.files=c("/data1/wlduan/d4PDF/sample/4.apdaba.pag1j0.05216.nc","/data1/wlduan/d4PDF/sample/4.apdaba.pag1j0.3236X.nc","/data1/wlduan/d4PDF/sample/4.apdaba.pag1j0.3236N.nc")
> vars=c(prec="precipitation_flux",tmax="Tmax", tmin="Tmin"
+ )
> outdir="/data1/wlduan/d4PDF/sample/output/"
> file.template="var_daily_DECCMA_historical_precis_1961-1990.nc"
> author.data=list(institution="Met Office", institution_id="UKMO")
> base.range=c(1961,1990)
>  create.indices.from.files(input.files,outdir,file.template,author.data,variable.name=vars,base.range=base.range,parallel=24,max.vals.million=70)Error in R_nc4_create: NetCDF: Can't add HDF5 file metadata (creation mode was 4096)
 以下にエラー ncdf4::nc_create(paste(out.dir, cdx.dat$filename[x], sep = "/"),  :
  Error in nc_create!
>
 It shows Error in R_nc4_create: NetCDF: Can't add HDF5 file metadata (creation mode was 4096).

 
so I checked the netcdf installation.
[root@pc090-056 ~]# nc-config --all

This netCDF 4.2.1.1 has been built with the following features:

  --cc        -> gcc
  --cflags    ->  -I/usr/local/include -I/usr/local/hdf5-1.8.18/include -I/usr/local/include
  --libs      -> -L/usr/local/lib -lnetcdf

  --has-c++   -> no
  --cxx       ->
  --has-c++4  -> no
  --cxx4      ->

  --fc        -> gfortran
  --fflags    -> -g -O2 -I/usr/local/include
  --flibs     -> -L/usr/local/lib -lnetcdff -lnetcdf -lnetcdf
  --has-f90   -> yes

  --has-dap   -> yes
  --has-nc2   -> yes
  --has-nc4   -> yes
  --has-hdf5  -> yes
  --has-hdf4  -> no
  --has-pnetcdf-> no
  --has-szlib ->

  --prefix    -> /usr/local
  --includedir-> /usr/local/include
  --version   -> netCDF 4.2.1.1

  It seems I already installed the hdf5 under netCDF 4.2.1.1

  Also, I used the Root user, suggesting I have the all permissions.

  So anyone can help me to solve this problem? 

  Thanks you very much!

Best regards,

**Comment by jswhit** [comment]
I think you are in the wrong place - this is the netcdf python interface, you are looking for the R interface.
