### ISSUE TITLE
Setting variables with array-like objects

### ISSUE THREAD

**Issue by skinny121** [Unidata/netcdf4-python#613]
We have an array-like object which acts like a multidimensional array but internally ravels some of the dimensions to save on memory for intermediate operations. These object defines the 'ndim' attribute which is causing netCDF4 to think this object itself is a numpy array and will fail as it isn't a numpy array. These objects define the \_\_array\_\_ method which mean numpy.array()/numpyy.asarray() methods work. The current workaround is to call np.asarray() when ever setting netCDF variables. 

I think the check([source](https://github.com/Unidata/netcdf4-python/blob/4d1cb6293d9f098c5051aa96bbf0f8f5823cbdbb/netCDF4/_netCDF4.pyx#L4046)) if the data is a numpy array is insufficient as non numpy objects may define a 'ndim' attribute and probably should instead call numpy.asarray() to possibly convert the data to a numpy array. Does anyone else agree?

Thanks
Ben Lewis

**Comment by jswhit** [comment]
How about using ``if isinstance(data, np.ndarray)``?  I don't know how much overhead would be incurred by calling ``np.asarray`` on everything, but I'd like to avoid it if possible.

**Comment by skinny121** [comment]
Yes that would be good. I think that would achieve the same purpose.

**Comment by dopplershift** [comment]
So long as the code (I'm not sure where it is) *absolutely* needs a numpy array, and only that.

**Comment by jswhit** [comment]
It really only needs the [numpy array interface](https://docs.scipy.org/doc/numpy/reference/arrays.interface.html), specifically the  PyArrayInterface C interface.

**Comment by jswhit** [comment]
see pull request #613

**Comment by jswhit** [comment]
pull request #614 has been merged, and is included in the 1.2.6 release
