### ISSUE TITLE
Error upgrading to version 1.2.5 on Ubuntu 14.04

### ISSUE THREAD

**Issue by stoiver** [Unidata/netcdf4-python#616]
Just obtained the following error when upgrading to the new version 1.2.5 from 1.2.4 using pip. The error is pasted below

The error looks exactly like the one I reported in issue #374 when upgrading to version 1.1.7

Cheers
Steve

sudo pip install --upgrade netCDF4
Downloading/unpacking netCDF4 from https://pypi.python.org/packages/bd/e7/6f562e868ff5c51a4ac5729b21314342bb02510cab10088c7447864d0ea2/netCDF4-1.2.5.tar.gz#md5=e306f3b659755663b60e5aed0dce4de3
  Downloading netCDF4-1.2.5.tar.gz (827kB): 827kB downloaded
  Running setup.py (path:/tmp/pip_build_root/netCDF4/setup.py) egg_info for package netCDF4
    Package hdf5 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `hdf5.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'hdf5' found
    using nc-config ...
    using netcdf library version 4.1.3
    
    warning: manifest_maker: MANIFEST.in, line 4: 'recursive-include' expects <dir> <pattern1> <pattern2> ...
    
Downloading/unpacking numpy>=1.7 from https://pypi.python.org/packages/16/f5/b432f028134dd30cfbf6f21b8264a9938e5e0f75204e72453af08d67eb0b/numpy-1.11.2.tar.gz#md5=03bd7927c314c43780271bf1ab795ebc (from netCDF4)
  Downloading numpy-1.11.2.tar.gz (4.2MB): 4.2MB downloaded
  Running setup.py (path:/tmp/pip_build_root/numpy/setup.py) egg_info for package numpy
    Running from numpy source directory.
    
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
Installing collected packages: netCDF4, numpy
  Found existing installation: netCDF4 1.2.4
    Uninstalling netCDF4:
      Successfully uninstalled netCDF4
  Running setup.py install for netCDF4
    Package hdf5 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `hdf5.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'hdf5' found
    using nc-config ...
    using netcdf library version 4.1.3
    building 'netCDF4._netCDF4' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c netCDF4/_netCDF4.c -o build/temp.linux-x86_64-2.7/netCDF4/_netCDF4.o
    In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
                     from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                     from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from netCDF4/_netCDF4.c:298:
    /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    netCDF4/_netCDF4.c: In function ‘__pyx_f_7netCDF4_8_netCDF4__get_full_format’:
    netCDF4/_netCDF4.c:6068:9: warning: implicit declaration of function ‘nc_inq_format_extended’ [-Wimplicit-function-declaration]
             __pyx_v_ierr = nc_inq_format_extended(__pyx_v_grpid, (&__pyx_v_formatp), (&__pyx_v_modep));
             ^
    netCDF4/_netCDF4.c:6139:10: error: ‘NC_FORMAT_NC3’ undeclared (first use in this function)
         case NC_FORMAT_NC3:
              ^
    netCDF4/_netCDF4.c:6139:10: note: each undeclared identifier is reported only once for each function it appears in
    netCDF4/_netCDF4.c:6169:10: error: ‘NC_FORMAT_NC_HDF5’ undeclared (first use in this function)
         case NC_FORMAT_NC_HDF5:
              ^
    netCDF4/_netCDF4.c:6199:10: error: ‘NC_FORMAT_NC_HDF4’ undeclared (first use in this function)
         case NC_FORMAT_NC_HDF4:
              ^
    netCDF4/_netCDF4.c:6229:10: error: ‘NC_FORMAT_PNETCDF’ undeclared (first use in this function)
         case NC_FORMAT_PNETCDF:
              ^
    netCDF4/_netCDF4.c:6259:10: error: ‘NC_FORMAT_DAP2’ undeclared (first use in this function)
         case NC_FORMAT_DAP2:
              ^
    netCDF4/_netCDF4.c:6289:10: error: ‘NC_FORMAT_DAP4’ undeclared (first use in this function)
         case NC_FORMAT_DAP4:
              ^
    netCDF4/_netCDF4.c:6319:10: error: ‘NC_FORMAT_UNDEFINED’ undeclared (first use in this function)
         case NC_FORMAT_UNDEFINED:
              ^
    netCDF4/_netCDF4.c: In function ‘__pyx_f_7netCDF4_8_netCDF4__set_att’:
    netCDF4/_netCDF4.c:7111:9: warning: passing argument 5 of ‘nc_put_att_string’ from incompatible pointer type [enabled by default]
             __pyx_v_ierr = nc_put_att_string(__pyx_t_6, __pyx_v_varid, __pyx_v_attname, __pyx_t_10, __pyx_v_string_ptrs);
             ^
    In file included from netCDF4/_netCDF4.c:297:0:
    /usr/include/netcdf.h:956:1: note: expected ‘const char **’ but argument is of type ‘char **’
     nc_put_att_string(int ncid, int varid, const char *name,
     ^
    netCDF4/_netCDF4.c:7521:13: warning: passing argument 5 of ‘nc_put_att_string’ from incompatible pointer type [enabled by default]
                 __pyx_v_ierr = nc_put_att_string(__pyx_t_14, __pyx_v_varid, __pyx_v_attname, 1, (&__pyx_v_datstring));
                 ^
    In file included from netCDF4/_netCDF4.c:297:0:
    /usr/include/netcdf.h:956:1: note: expected ‘const char **’ but argument is of type ‘char **’
     nc_put_att_string(int ncid, int varid, const char *name,
     ^
    netCDF4/_netCDF4.c: In function ‘__pyx_pf_7netCDF4_8_netCDF4_7Dataset_68renameGroup’:
    netCDF4/_netCDF4.c:20770:3: warning: implicit declaration of function ‘nc_rename_grp’ [-Wimplicit-function-declaration]
       __pyx_v_ierr = nc_rename_grp(__pyx_t_6, __pyx_v_newnamec);
       ^
    netCDF4/_netCDF4.c: In function ‘init_netCDF4’:
    netCDF4/_netCDF4.c:80685:36: error: ‘NC_FORMAT_64BIT_OFFSET’ undeclared (first use in this function)
       __pyx_t_1 = __Pyx_PyInt_From_int(NC_FORMAT_64BIT_OFFSET); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 1028, __pyx_L1_error)
                                        ^
    netCDF4/_netCDF4.c:80700:36: error: ‘NC_FORMAT_64BIT_DATA’ undeclared (first use in this function)
       __pyx_t_1 = __Pyx_PyInt_From_int(NC_FORMAT_64BIT_DATA); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 1029, __pyx_L1_error)
                                        ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/netCDF4/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-6akBej-record/install-record.txt --single-version-externally-managed --compile:
    Package hdf5 was not found in the pkg-config search path.

Perhaps you should add the directory containing `hdf5.pc'

to the PKG_CONFIG_PATH environment variable

No package 'hdf5' found

reading from setup.cfg...

using nc-config ...

using netcdf library version 4.1.3

running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/netcdftime

copying netcdftime/__init__.py -> build/lib.linux-x86_64-2.7/netcdftime

creating build/lib.linux-x86_64-2.7/netCDF4

copying netCDF4/__init__.py -> build/lib.linux-x86_64-2.7/netCDF4

copying netCDF4/utils.py -> build/lib.linux-x86_64-2.7/netCDF4

running build_ext

building 'netCDF4._netCDF4' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/netCDF4

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c netCDF4/_netCDF4.c -o build/temp.linux-x86_64-2.7/netCDF4/_netCDF4.o

In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,

                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,

                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,

                 from netCDF4/_netCDF4.c:298:

/usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]

 #warning "Using deprecated NumPy API, disable it by " \

  ^

netCDF4/_netCDF4.c: In function ‘__pyx_f_7netCDF4_8_netCDF4__get_full_format’:

netCDF4/_netCDF4.c:6068:9: warning: implicit declaration of function ‘nc_inq_format_extended’ [-Wimplicit-function-declaration]

         __pyx_v_ierr = nc_inq_format_extended(__pyx_v_grpid, (&__pyx_v_formatp), (&__pyx_v_modep));

         ^

netCDF4/_netCDF4.c:6139:10: error: ‘NC_FORMAT_NC3’ undeclared (first use in this function)

     case NC_FORMAT_NC3:

          ^

netCDF4/_netCDF4.c:6139:10: note: each undeclared identifier is reported only once for each function it appears in

netCDF4/_netCDF4.c:6169:10: error: ‘NC_FORMAT_NC_HDF5’ undeclared (first use in this function)

     case NC_FORMAT_NC_HDF5:

          ^

netCDF4/_netCDF4.c:6199:10: error: ‘NC_FORMAT_NC_HDF4’ undeclared (first use in this function)

     case NC_FORMAT_NC_HDF4:

          ^

netCDF4/_netCDF4.c:6229:10: error: ‘NC_FORMAT_PNETCDF’ undeclared (first use in this function)

     case NC_FORMAT_PNETCDF:

          ^

netCDF4/_netCDF4.c:6259:10: error: ‘NC_FORMAT_DAP2’ undeclared (first use in this function)

     case NC_FORMAT_DAP2:

          ^

netCDF4/_netCDF4.c:6289:10: error: ‘NC_FORMAT_DAP4’ undeclared (first use in this function)

     case NC_FORMAT_DAP4:

          ^

netCDF4/_netCDF4.c:6319:10: error: ‘NC_FORMAT_UNDEFINED’ undeclared (first use in this function)

     case NC_FORMAT_UNDEFINED:

          ^

netCDF4/_netCDF4.c: In function ‘__pyx_f_7netCDF4_8_netCDF4__set_att’:

netCDF4/_netCDF4.c:7111:9: warning: passing argument 5 of ‘nc_put_att_string’ from incompatible pointer type [enabled by default]

         __pyx_v_ierr = nc_put_att_string(__pyx_t_6, __pyx_v_varid, __pyx_v_attname, __pyx_t_10, __pyx_v_string_ptrs);

         ^

In file included from netCDF4/_netCDF4.c:297:0:

/usr/include/netcdf.h:956:1: note: expected ‘const char **’ but argument is of type ‘char **’

 nc_put_att_string(int ncid, int varid, const char *name,

 ^

netCDF4/_netCDF4.c:7521:13: warning: passing argument 5 of ‘nc_put_att_string’ from incompatible pointer type [enabled by default]

             __pyx_v_ierr = nc_put_att_string(__pyx_t_14, __pyx_v_varid, __pyx_v_attname, 1, (&__pyx_v_datstring));

             ^

In file included from netCDF4/_netCDF4.c:297:0:

/usr/include/netcdf.h:956:1: note: expected ‘const char **’ but argument is of type ‘char **’

 nc_put_att_string(int ncid, int varid, const char *name,

 ^

netCDF4/_netCDF4.c: In function ‘__pyx_pf_7netCDF4_8_netCDF4_7Dataset_68renameGroup’:

netCDF4/_netCDF4.c:20770:3: warning: implicit declaration of function ‘nc_rename_grp’ [-Wimplicit-function-declaration]

   __pyx_v_ierr = nc_rename_grp(__pyx_t_6, __pyx_v_newnamec);

   ^

netCDF4/_netCDF4.c: In function ‘init_netCDF4’:

netCDF4/_netCDF4.c:80685:36: error: ‘NC_FORMAT_64BIT_OFFSET’ undeclared (first use in this function)

   __pyx_t_1 = __Pyx_PyInt_From_int(NC_FORMAT_64BIT_OFFSET); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 1028, __pyx_L1_error)

                                    ^

netCDF4/_netCDF4.c:80700:36: error: ‘NC_FORMAT_64BIT_DATA’ undeclared (first use in this function)

   __pyx_t_1 = __Pyx_PyInt_From_int(NC_FORMAT_64BIT_DATA); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 1029, __pyx_L1_error)

                                    ^

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
  Rolling back uninstall of netCDF4
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/netCDF4/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-6akBej-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/netCDF4
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 36: ordinal not in range(128)

**Comment by jswhit** [comment]
Indeed - sorry about that.  I've uploaded a new source tarball to pypi with all the entries in ``constants.pyx`` set to zero (version 1.2.5.1).
