### ISSUE TITLE
Extracting mean rainfall data from netcdf file inside shapefile using python

### ISSUE THREAD

**Issue by John277** [Unidata/netcdf4-python#634]
I have netcdf file and I want to extract mean rainfall data within shapefile boundary. The shapefile contains 3 features, I have started as follows:

```
from netCDF4 import Dataset
import numpy as np
import geopandas as gpd
from osgeo import ogr
```

then I can access or slice variables from netcdf

```
dataset = Dataset('mynetcdf.nc')
long = dataset.variables['lon'][:]
lati = dataset.variables['lat'][:]
rainfall = dataset.variables['pr'][:]
```
Until this it is fine and working, I can see the data
Now the next step is to read shapefile and extract the above variables (long, lati, rainfall) for inside the shapefile. I know I can read shapefile using ogr or geopandas but I don't know how to continue afterwards
```
shapfile 1 = gpd.read_file('myshapefile.shp'), or using ogr
shapefile 2 = ogr.open('myshapefile.shp',0)
```
Another issue is there is a lot of netcdf files and the extraction has to go through each file (loop) and the process will get slow at some stage and I am looking solution that will extract for each 3 features as fast as possible and I thought Python could be possible solution.
Thanks for your help!

**Comment by jswhit** [comment]
Never done this myself, but it looks like you can use [shapely](http://toblerity.org/shapely/manual.html)  and use the [within](http://toblerity.org/shapely/manual.html#object.within) method to check if a point is inside a polygon object.  

It still might be slow, but you could ask on the shapely list how to optimize once you have some working code.

**Comment by John277** [comment]
@jswhit thanks for your comment, 
both lati and long are "numpy.ndarray" and I don't know how I can related with the shapefile.

**Comment by jhamman** [comment]
@shoyer has an [example](https://github.com/pydata/xarray/issues/501#issuecomment-126461466) of how this can be done with `xarray`. If you don't want to use xarray, it wouldn't be all that hard to adapt this approach.

**Comment by ckhroulev** [comment]
Regarding optimization: it might be a good idea to rasterize features in the shape file and use resulting raster masks to extract data. This should be much faster than repeatedly checking if a point is inside a polygon.

**Comment by John277** [comment]
is there a way to convert longitude and latitude type of "numpy.ndarray" in to raster?

**Comment by John277** [comment]
@ckhroulev if I convert features into raster, then how can I check each long and lati "numpy.ndarray" are within the raster or not? any suggestions?

**Comment by ckhroulev** [comment]
> is there a way to convert longitude and latitude type of "numpy.ndarray" in to raster?

In my understanding NumPy arrays *are* a form of raster data and shape files contain *vector* data.

I just realized that the example @jhamman mentioned shows how to create a raster mask. I think you should take a look at that.

Regarding using the mask: you did not specify what you mean by "extracting" rainfall data. What is the desired output? Is it an array? Or is it an average over the area specified in the shape file? Or?...

Assuming that you need to produce an array with rainfall data within a feature and zeros elsewhere, you can do something like this:

``` python
rows, cols = rainfall.shape
result = numpy.zeros_like(rainfall)
for r in range(rows):
    for c in range(cols):
        if point_in_feature(lon[r,c], lat[r,c]):
            result[r,c] = rainfall[r,c]
```

If you use a mask (1 within a feature, 0 elsewhere) you can achieve the same with

``` python
result = numpy.zeros_like(rainfall)
result[mask == 1] = rainfall[mask == 1]
```

Note that this is really about Python GIS programming and is not an issue with `netcdf4-python`. I would consider taking this discussion to http://gis.stackexchange.com/ instead.

**Comment by John277** [comment]
> Regarding using the mask: you did not specify what you mean by "extracting" rainfall data. What is the desired output? Is it an array? Or is it an average over the area specified in the shape file? Or?...
  -> average over the area specified in shapefile for each feature

Some info about the variables:

In[6]: rainfall.shape
Out[6]: (365, 1550, 1195)
In[8]: long.shape
Out[8]: (1195,)
In[4]: lati.shape
Out[4]: (1550,)

Thus, I want to extract rainfall within the shapefile (average over the area specified in shapefile for each feature) because the rainfall is for big domain or larger than the shapefile.
