### ISSUE TITLE
Incorrect timestamp format in netCDF4 API Documentation

### ISSUE THREAD

**Issue by djgagne** [Unidata/netcdf4-python#637]
In the [netCDF4 API docs Section 7](http://unidata.github.io/netcdf4-python/#section7), the text currently reads "Time coordinate values pose a special challenge to netCDF users. Most metadata standards (such as CF) specify that time should be measure relative to a fixed date using a certain calendar, with units specified like hours since **YY:MM:DD hh-mm-ss**." The dashes and colons on the example timestamp should be reversed and should read "YY-MM-DD hh:mm:ss". The time formats in the example code below this paragraph look correct.

**Comment by jswhit** [comment]
fixed in pull request #638 - thanks for catching this!
