### ISSUE TITLE
netcdf4 and python3.6 seem incompatible in jupyter

### ISSUE THREAD

**Issue by morganeoneill** [Unidata/netcdf4-python#641]
I just downloaded the anaconda package today on a linux machine, and tried to read a netcdf file in a jupyter notebook. The netcdf4 version that came with the package is 1.2.4, which doesn't seem to work with the new python version (my language will not be precise because I'm a brand new user).

In the jupyter notebook, 'import netCDF4' yields:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-f731da2de255> in <module>()
----> 1 import netCDF4

/home/moneill/anaconda3/lib/python3.6/site-packages/netCDF4/__init__.py in <module>()
      1 # init for netCDF4. package
      2 # Docstring comes from extension module _netCDF4.
----> 3 from ._netCDF4 import *
      4 # Need explicit imports for names beginning with underscores
      5 from ._netCDF4 import __doc__, __pdoc__

ImportError: libmfhdf.so.0: cannot open shared object file: No such file or directory
##########################################################################

and indeed, in the site-package directory, the contents of the netCDF4 folder mostly start with '__' (and one .so item).

A friend suggested that I update to netcdf4-1.2.7, which I did via 'conda upgrade -c conda-forge netcdf4'. The terminal printout said that netcdf4 would be updated from 1.2.4-np111py36_0 to 1.2.7-np111py36_0 conda-forge.

This added a new folder to the site-package directory, 'netCDF4-1.2.7-py3.6.egg-info', with *different* contents than the original netCDF4 folder (the new one has text files). 

But when I go back to the notebook (or if I shut it down and open back up again), the input 'import netCDF4' still leads to the error above, including the path /site-packages/netCDF4/, which I think remains the old problematic version.

Please help! How can I get to the point where 'from netCDF4 import Dataset' works?

**Comment by rabernat** [comment]
To reproduce this issue:

```bash
conda create -y -n py36netcdf4 python=3.6 netcdf4
source activate py36netcdf4
python -c 'import netCDF4'
```

gives:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/rpa/anaconda/envs/py36netcdf4/lib/python3.6/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: dlopen(/Users/rpa/anaconda/envs/py36netcdf4/lib/python3.6/site-packages/netCDF4/_netCDF4.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libmfhdf.0.dylib
  Referenced from: /Users/rpa/anaconda/envs/py36netcdf4/lib/libnetcdf.11.dylib
  Reason: image not found
```

works with `python=3.5`

**Comment by dopplershift** [comment]
I'm pretty sure it's an Anaconda problem. Try installing a different version of the hdf4 package.

**Comment by Bluno** [comment]
I had a similar problem and in my case was because of packages that weren't updated. My main example was numpy and its depedencies. By the command:

conda update numpy

I resolve my issues.
