### ISSUE TITLE
Different results on another PC

### ISSUE THREAD

**Issue by csango** [Unidata/netcdf4-python#644]
Hi,

I tried to read data on different computers, however I noticed that there are discrepancy in the read data
This is my code:
```
palm_data = Dataset(my_example_nc_file, mode='r')
u = palm_data.variables['u']
print  (u[1028, 36:40, 108, 153 ])
palm_data.close()
```
On one PC this produces the following result:

> [ 15.145  15.217  15.284  15.351]

While on another PC the result is
> [ 15.14531898   0.          15.28441048  15.35093212]

I tried to run with python version of 2.7.5 and 3.4. Both gives me the same result. There should not be any zeros in the data. What could be the problem?

I check the version of the packages
```
print( netCDF4.__version__)
print( np.__version__)
print( tables.__version__)
```
and it is the same:
```
1.2.7
1.12.1
3.4.1
```

Regards,
Robert

**Comment by jswhit** [comment]
Not enough information to say.  Does the netcdf file use compression?  Are there missing values?  Please post the file somewhere so we can take a look.

**Comment by csango** [comment]
It is not compressed and there are no missing values. It is a ~200GB of data, hence it is hard to upload anywhere.

**Comment by jswhit** [comment]
Is the variable data stored in short integers using scale/offset?  How about posting an ncdump -h of the file?

**Comment by csango** [comment]
I found the problem. I used multiple processes but I opened the file in the main process. After moving the file reading operation into the function which is run parallel. Thanks for your quick replay.
