### ISSUE TITLE
Problems installing with conda on Mac, Python 3.6

### ISSUE THREAD

**Issue by mbakker7** [Unidata/netcdf4-python#647]
Just tried to install netCDF4 version 1.2.7 with `conda install netcdf4` for Python 3.6 on a Mac. This installs version 1.2.4, which doesn't run as it complains that libnetcdf libraries are not matching. Trying to upgrade to 1.2.7 with conda gives an error message that 1.2.7 doesn't exist. Upgrading afterwards with pip works fine, which upgraded to 1.2.7, and works great. But it is odd, as conda install should have done the trick out of the box. @dopplershift. (previously posted on netcdf-c, but was send here).

**Comment by dopplershift** [comment]
Sorry to hear you're having problems. I hate to continue to pass the buck, but unfortunately that sounds like a problem with Anaconda's build, which is controlled by ContinuumIO: https://github.com/ContinuumIO/anaconda-recipes

The good news is that there's the conda-forge channel for conda, which consists of community packages managed entirely on GitHub (and which we have some control over). You can install netcdf4-python 1.2.7 from there as:
```
conda install -c conda-forge netcdf4
```
You can also add conda-forge to your default set of channels by:
```
conda config --add channels conda-forge
```
If you run into any problems with the netcdf4-python package there, you can report them at the [netcdf4 feedstock](https://github.com/conda-forge/netcdf4-feedstock)
