### ISSUE TITLE
least_significant_digit named incorrectly

### ISSUE THREAD

**Issue by gerritholl** [Unidata/netcdf4-python#651]
The attribute `least_significant_digit` is named incorrectly.  By rounding the value to n digits after the decimal point, it is determining the `number_of_decimal_points` rather than the `least_significant_digit`.  For example, the examples below all have 3 decimal places:

```
1.234   4 significant digits
0.123   3 significant digits
0.012   2 significant digits
0.001   1 significant digit
```

whereas the examples below all have 3 significant digits:

```
123     0 decimal places
12.3    1 decimal place
1.23    2 decimal places
0.123  3 decimal places
```

Unfortunately, this means using the `least_significant_digit` feature in NetCDF4-Python means there will be an incorrect variable attribute set in published data, which is embarrassing.

**Comment by jswhit** [comment]
From https://www.esrl.noaa.gov/psd/data/gridded/conventions/cdc_netcdf_standard.shtml

 least_significant_digit -- power of ten of the smallest decimal place in unpacked data that is a reliable value. 

That's the convention I followed - though I agree it may be misnamed.

**Comment by gerritholl** [comment]
I see.  I thought it was something from Python NetCDF.
