### ISSUE TITLE
Error During Installation - Mac OS Sierra

### ISSUE THREAD

**Issue by virendraghate** [Unidata/netcdf4-python#657]
Hi, 
I am fairly new to Python, just switching to Python from Matlab. I saw it coming over the years, but was lazy to make the switch. So I installed the latest version of Anaconda and then used "Conda install netcdf4" and same for hdf5, cython etc. Still when I say "import netcdf4" it gives me the "ModuleNotFoundError". I then went on to install the full netcdf4-python from this version and after the build I get the following message. 

6 warnings generated.
gcc -bundle -undefined dynamic_lookup -L/Users/vghate/anaconda/lib -L/Users/vghate/anaconda/lib -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/netCDF4/_netCDF4.o -L/usr/local/lib -L/usr/local/lib -L/Users/vghate/anaconda/lib -L/usr/local/lib -L/usr/local/lib -lnetcdf -lhdf5_hl -lhdf5 -lz -o build/lib.macosx-10.7-x86_64-3.6/netCDF4/_netCDF4.cpython-36m-darwin.so

Please help. 
-Virendra

**Comment by dopplershift** [comment]
Try this:

```
conda install -c conda-forge netcdf4
```

This will install the netcdf4 library from the conda-forge (community driven) channel of packages. The default Anaconda package has, unfortunately, been broken for a bit and is out of our control.

**Comment by virendraghate** [comment]
Hi Ryan,
Thanks for the reply. After using the command you suggested, the conda installation went smoothly. 

Unfortunately after that "import netcdf4" still gives the following message 
"ModuleNotFoundError: No module named 'netcdf4' " On top of that when I tried to do help("modules") to get the list of modules, anaconda gave me a long output and at the end "segmentation fault: 11" and quit.

**Comment by dopplershift** [comment]
Can you attach the output of `conda list`?

**Comment by virendraghate** [comment]
It is fairly long, and I do see netcdf4 there. The output is attached. 
[package_list.txt](https://github.com/Unidata/netcdf4-python/files/983974/package_list.txt)

**Comment by virendraghate** [comment]
One small update `which python` does point me to the correct anaconda installation of 
> /Users/vghate/anaconda/bin/python

**Comment by dopplershift** [comment]
Ah, I only just spotted it now. The proper import is:
```python
import netCDF4
```
(note the change in case)

**Comment by virendraghate** [comment]
Thanks "dopplershift" ... I knew I was doing something silly, and not everything is working fine! 
Cheers and have a great day!
Virendra

**Comment by virendraghate** [comment]
Thanks "dopplershift" ... I knew I was doing something silly, and not everything is working fine! 
Cheers and have a great day!
Virendra
