### ISSUE TITLE
Gdal with netcdf in AWS lambda function

### ISSUE THREAD

**Issue by ramotswa** [Unidata/netcdf4-python#688]
Hello,

I was wondering if anyone had managed to get an AWS Lambda function up and running using GDAL with netCDF (and HDF5) support? I have managed to get gdal working with it's python bindings following this [here](https://github.com/vincentsarago/lambda_gdal-python). 
As far as I can tell I would have to do something along the lines of the following;
configure and make netcdf (?)
configure and make gdal- pointing the netcdf flat to the location where I put netcdf?

Something like that?

Any pointers would be very useful.

Many thanks,
Toby

**Comment by jswhit** [comment]
this is really a question gdal question.
