### ISSUE TITLE
HDF error in the presence of h5py

### ISSUE THREAD

**Issue by Funkensieper** [Unidata/netcdf4-python#694]
If h5py is imported before netCDF4 on my system, reading a netCDF4 file fails with the following error:

    >>> import h5py
    >>> import netCDF4
    >>> nc = netCDF4.Dataset('test.nc', 'r')
    Traceback (most recent call last):
        File "<stdin>", line 1, in <module>
        File "netCDF4/_netCDF4.pyx", line 1873, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:13842)
        File "netCDF4/_netCDF4.pyx", line 1579, in netCDF4._netCDF4._ensure_nc_success (netCDF4/_netCDF4.c:12628)
    IOError: NetCDF: HDF error

If you swap the imports or omit the h5py import, everything works fine. Maybe this is related to #653 ? I'm using netCDF4-1.2.8 and h5py-2.7.0 linked against netCDF-4.4.1.1 with hdf5 support (hdf5-1.8.18). The modules were installed using pip, the Python version is 2.7.13, system is CentOS-7.3.

**Comment by jswhit** [comment]
This must depend on how the modules are built and installed, since I cannot reproduce this on macos x with git master h5py and netcdf4-python, and HDF5 1.10.0.

**Comment by Funkensieper** [comment]
Thanks for the hint! As it turned out, the modules were not linked against the local netCDF4/hdf5 libraries, but the wheels installed by pip come with their own version of the libraries which seem to be incompatible. Building the modules from source and linking against the local netCDF4/hdf5 libraries solves the problem.
