### ISSUE TITLE
Ellipsis don't always work

### ISSUE THREAD

**Issue by fredrik-1** [Unidata/netcdf4-python#701]
I just found out that the issue was fixed and that I had mixed up different versions of the code....
The error message is wrong when several ellipses where used though, so I made a pull request with my code anyway. The variable i was never used and I believe that it is clearer with the updating at the end of the loop. 

https://github.com/Unidata/netcdf4-python/pull/702

**Comment by jswhit** [comment]
Pull request #702 merged - thanks!
