### ISSUE TITLE
Entire variable is erroneously masked

### ISSUE THREAD

**Issue by mdklatt** [Unidata/netcdf4-python#707]
The attached file contains `int8` data (variable `Band1`)  with a `_FillValue` of 0. When reading the file using a `netCDF4.Dataset`, auto mask masks the entire array even though it contains non-zero values.

```python
from netCDF4 import Dataset

ds = Dataset("AQUA.QUAL.20170101.nc", "r")

ds.set_auto_mask(False)
qual = ds.variables["Band1"]
assert (qual[:] != qual._FillValue).any()

ds.set_auto_mask(True)
qual = ds.variables["Band1"]
assert not qual[:].mask.all()  # fails
```

This fails for **netCDF4 1.2.9** running with **Python 2.7.5** on platform **Linux-3.10.0-514.el7.x86_64-x86_64-with-centos-7.3.1611-Core**.

[AQUA.QUAL.20170101.nc.zip](https://github.com/Unidata/netcdf4-python/files/1283254/AQUA.QUAL.20170101.nc.zip)

**Comment by jswhit** [comment]
The data in variable `Band1` is all zeros - and the `_FillValue` is set to zero - hence it is all masked.

**Comment by jswhit** [comment]
Sorry, you are right- there are some nonzero values in `Band1`.

**Comment by jswhit** [comment]
The problem is with the `valid_range`, specifically the 255 upper bound.  The data is stored as `int8`, and 255 is not a valid signed 8 byte integer.  I think it wraps around to a value of zero, so the valid_range being applied is (0,0).  

Perhaps we should raise an error if the `valid_range` or `_FillValue` is not consistent with the variable's data type, instead of just casting it to the correct data type.

**Comment by mdklatt** [comment]
As a workaround, Is there a way to disable the `valid_range` check in netCDF4, or does that attribute need to be fixed/removed in the netCDF file?

**Comment by jswhit** [comment]
You can use `set_auto_mask(False)` or fix the attribute.  There is no way to just turn off the `valid_range` check (and still mask `_FillValue` and `missing_value`)

**Comment by jswhit** [comment]
Pull request #708 ignores attributes that cannot be safely cast to the variable's data type, and issues a warning.

**Comment by jswhit** [comment]
Please let me know if the pull request addresses your original problem  - if so, I'll go ahead and merge.  Instead of getting a masked array that is completely masked, you should get a regular (unmasked) numpy array (same as if you used `ds.set_auto_mask(False)`).

**Comment by mdklatt** [comment]
That pull request does resolve the issue. The `valid_range` is ignored, a warning is issued, and the variable is masked as expected.

**Comment by jswhit** [comment]
OK - thanks. Merging now..

**Comment by MRossol** [comment]
Hi I'm having the opposite issue. I have some WRF output that does not have any masked values:
with nc.Dataset(wrf_path, 'r') as f:
    U = f.variables['U'][...]
    print(U.mask.any())
False

But I still get a masked array.  In previous versions I would get a normal ndarray in this case...

**Comment by akrherz** [comment]
@MRossol this is the new behavior, that all variables are masked arrays by default.
