### ISSUE TITLE
Silent Failure when Opening netCDF File

### ISSUE THREAD

**Issue by piratepheasant** [Unidata/netcdf4-python#709]
For a very small number of my netCDF files, a fatal error occurs when I use the command nc = Dataset(line,'r') within a loop reading the filename "line" in from a file. I attempted to put it in a try block (see below), and it catches a number of bad files but not the ones causing the process to crash.

            try:
                # Open the netCDF file and read it.
                nc = Dataset(line,'r')
            except OSError:
                print('{} failed in process {}'.format(line,i))
                continue 

I have implemented a workaround in which I have an earlier try block testing if ncdump (pynco module) can be used on the file before it even gets to the try block shown above. This makes my script take much longer to run, and I'm just disappointed that this fails without throwing an exception (as far as I can tell, because it crashes). The message I've seen when using the IPython console in Spyder (Python 3.6) has been:

An error occurred while starting the kernel
python: v1hpg.c:234: v1h_get_nc_type: Assertion `type == 1 || type == 2 || ... (through 12)'

I want to say that the second line of that message is printed to screen when running my script (serially) from the command line. If you need any further information about the problem, please let me know. I appreciate any help.

**Comment by jswhit** [comment]
Perhaps it is not catching the error because it doesn't trigger an `OSError`?  What if you use a bare `except`?

**Comment by piratepheasant** [comment]
Thank you for your quick reply, jswhit. I just tried that to no avail. Without the try block containing the "ncdump test," processes still fail, and I still get the python: v1hpg.c:234: v1h_get_nc_type: Assertion `type == 1 || ...' message.

**Comment by piratepheasant** [comment]
This is what my two try blocks look like:

            try:
                ncdump_string = nco.ncdump(line, options=['-h'])
            except:
                sys.stderr.write('{} has an issue. Skipping file.\n'.format(line))
                continue
            
            try:
                # Open the netCDF file and read it.
                nc = Dataset(line,'r')
            except OSError:
                print('{} failed in process {}'.format(line,i))
                continue

**Comment by jswhit** [comment]
The ncdump test is actually reading data from the file.  What you have in the try/except block just opens the file.  Perhaps the error is only triggered when you try to read data from the file.

Unless you can provide a file and a script that triggers the error, there's not much I can do to help.

**Comment by piratepheasant** [comment]
I've included a simple script with the two try blocks I listed in my most recent comment and a netCDF file that fails. The first try block (the ncdump test) will catch it. The second try block does not catch it whether I use the "except OSError:" or the bare "except:". As a matter of fact, Python crashes. Since I don't believe I can attach .nc or .py files, I zipped both the simple script and the netCDF file. Thanks again.

[ncFile.zip](https://github.com/Unidata/netcdf4-python/files/1286347/ncFile.zip)
[test_ncFiles.zip](https://github.com/Unidata/netcdf4-python/files/1286351/test_ncFiles.zip)

**Comment by jswhit** [comment]
Just opening that file throws an error for me:

```python
>>> from netCDF4 import Dataset
>>> nc = Dataset('s1a-wv2-ocn-vv-20151204t000217-20151204t000219-008884-00cb47-044.nc')
Assertion failed: (type == NC_BYTE || type == NC_CHAR || type == NC_SHORT || type == NC_INT || type == NC_FLOAT || type == NC_DOUBLE || type == NC_UBYTE || type == NC_USHORT || type == NC_UINT || type == NC_INT64 || type == NC_UINT64 || type == NC_STRING), function v1h_get_nc_type, file v1hpg.c, line 234.
Abort
```python

Don't know why it doesn't for you.

**Comment by piratepheasant** [comment]
Though I get a different error, it crashes Python for me as well. That's why I put the command to open the file in the try block to begin with, and as I explained, it crashes Python even when it's in the try block. The command that does not crash Python is the ncdump command. My hope for bringing this problem to light is that someone can perhaps fix this so it throws an error rather than crashing.

**Comment by jswhit** [comment]
It's an issue with the C library, not the python interface.  I suggest opening an issue on the netcdf-c issue tracker, attaching the netcdf file.  Simply running ncdump on the file will trigger the crash in the C library.

**Comment by piratepheasant** [comment]
Thank you for figuring out where the problem lies. I will open an issue on the netcdf-c issue tracker and attach the file.

**Comment by jswhit** [comment]
I went ahead an created a netcdf-c issue (https://github.com/Unidata/netcdf-c/issues/481)

**Comment by piratepheasant** [comment]
Thank you for taking care of it. I had not yet because I was trying to determine how to best explain the problem.

**Comment by WardF** [comment]
What type of netCDF file should this be? Can you tell us a little bit about the provenance of the file, how it was created, etc?

**Comment by WardF** [comment]
For what it is worth, netcdf-java (which does not use the C library) also fails to open the file, which suggests there may be a problem with the file itself (either how it was created, or corruption after-the-fact).  The more you can tell us about the file, the quicker I can hopefully figure out what's going on! :)

**Comment by piratepheasant** [comment]
This is a netCDF file from the Sentinel-1 satellite mission containing Synthetic Aperture Radar (SAR) data. Out of the ~1.2 million files I tested for years 2015-2016, it appears that less than a half dozen files have this problem. Why it is a concern is that attempting to open this file silently crashes my processes. I was hoping an exception would be thrown so that A) it could be caught and my process wouldn't crash, and B) I could be aware of what was causing problems.

**Comment by WardF** [comment]
I'm very glad that it is only a handful of files out of so many, although that is still concerning.  I can evaluate having the assertion in v1hpg.c return an error code instead, but I will first need to investigate why it is using an assertion in the first place.   I am not super familiar with python, but can it be caught at that level for the time being?  @jswhit I see your comment that it crashes the python interpreter; is there a python-based workaround for this you can suggest?

**Comment by jswhit** [comment]
I can't catch the error in python, since the C-library crashes (taking the python interpreter with it) instead of throwing an exception.

**Comment by dopplershift** [comment]
To be clear @WardF , there's nothing to be done in Python since the failed assertion results in netCDF-c calling `abort()`--do not pass go, do not collect $200.

**Comment by piratepheasant** [comment]
@WardF, unless you mean something different by finding a python-based workaround, I found that using the pynco module ncdump command in a try-block gave me an error message and did not crash my process. I implemented this just ahead of the try-block containing the command to read the file using the netcdf4 command. Unfortunately, this makes my routine take about five times longer. At least it doesn't crash.

**Comment by jswhit** [comment]
that only works because the subprocess that is running nco crashes, returning an error code but not crashing python.

**Comment by piratepheasant** [comment]
Thank you, @jswhit, for explaining that to me.

**Comment by WardF** [comment]
The root issue appears to be that the underlying netcdf files are corrupt.  However, there should be a way to catch that other than an assert statement.  Assuming there's no historic technical debt that requires this ASSERT be an ASSERT, I can fix this for the next release, but that does not help you in the short term unfortunately.  I'm at a bit of a loss as to what we can do about this (thanks @jswhit for explaining the python part) immediately.

**Comment by WardF** [comment]
The fix for this will be in the next release candidate for 4.5.0.

**Comment by piratepheasant** [comment]
Thank you, @WardF.

**Comment by piratepheasant** [comment]
I am happy to report that my Python netDCF4 library was built using the netcdf4.6.0 C-library, and I can now run my code without the try-block that calls ncdump. My routine runs ~5x faster, and no processes fail. I am very grateful for your help.

**Comment by jswhit** [comment]
Excellent!  Thanks for reporting back.
