### ISSUE TITLE
Cannot build using python 2.7.9

### ISSUE THREAD

**Issue by pagecp** [Unidata/netcdf4-python#710]
% python2 --version
Python 2.7.9

%  cython --version
Cython version 0.26.1

% pyrexc --version
Pyrex version 0.9.9

Trying to build with python 2.7.9 (everything works fine if I use python 3.6 from anaconda):

% python2 setup.py build
reading from setup.cfg...
Package hdf5 was not found in the pkg-config search path.
Perhaps you should add the directory containing `hdf5.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hdf5' found
using nc-config ...
HDF5 library version: 1.8.15-patch1 found in /data/softs/local/hdf5/1.8.15p1
using netcdf library version 4.3.3.1
using Cython to compile netCDF4.pyx...
netcdf lib has group rename capability
netcdf lib has nc_inq_path function
netcdf lib has nc_inq_format_extended function
netcdf lib does not have nc_open_mem function
netcdf lib does not have cdf-5 format capability
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/netcdftime
copying netcdftime/__init__.py -> build/lib.linux-x86_64-2.7/netcdftime
creating build/lib.linux-x86_64-2.7/netCDF4
copying netCDF4/__init__.py -> build/lib.linux-x86_64-2.7/netCDF4
copying netCDF4/utils.py -> build/lib.linux-x86_64-2.7/netCDF4
running build_ext
pyrexc netCDF4/_netCDF4.pyx --> netCDF4/_netCDF4.c
/data/home/globc/page/src/netcdf4-python/netCDF4/_netCDF4.pyx:923:5: Expected an identifier
building 'netCDF4._netCDF4' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/netCDF4
gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/data/softs/local/netcdf/4.3.3.1/include -I/data/softs/local/hdf5/1.8.15p1/include -I/data/softs/local/hdf5/1.8.15p1/include -I/data/softs/local/python2.7-shared/lib/python2.7/site-packages/numpy/core/include -Iinclude -I/data/softs/local/python2.7-shared/include/python2.7 -c netCDF4/_netCDF4.c -o build/temp.linux-x86_64-2.7/netCDF4/_netCDF4.o
gcc: error: netCDF4/_netCDF4.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
error: command 'gcc' failed with exit status 1

If we fix the problem in netCDF4/_netCDF4.pyx:923:5: Expected an identifier
by removing () and the ., we have a new problem:

python2 setup.py build
reading from setup.cfg...
Package hdf5 was not found in the pkg-config search path.
Perhaps you should add the directory containing `hdf5.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hdf5' found
using nc-config ...
HDF5 library version: 1.8.15-patch1 found in /data/softs/local/hdf5/1.8.15p1
using netcdf library version 4.3.3.1
using Cython to compile netCDF4.pyx...
netcdf lib has group rename capability
netcdf lib has nc_inq_path function
netcdf lib has nc_inq_format_extended function
netcdf lib does not have nc_open_mem function
netcdf lib does not have cdf-5 format capability
running build
running build_py
running build_ext
pyrexc netCDF4/_netCDF4.pyx --> netCDF4/_netCDF4.c
include/netCDF4.pxi:697:30: Expected ')'
building 'netCDF4._netCDF4' extension
gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/data/softs/local/netcdf/4.3.3.1/include -I/data/softs/local/hdf5/1.8.15p1/include -I/data/softs/local/hdf5/1.8.15p1/include -I/data/softs/local/python2.7-shared/lib/python2.7/site-packages/numpy/core/include -Iinclude -I/data/softs/local/python2.7-shared/include/python2.7 -c netCDF4/_netCDF4.c -o build/temp.linux-x86_64-2.7/netCDF4/_netCDF4.o
gcc: error: netCDF4/_netCDF4.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
error: command 'gcc' failed with exit status 1

Fixing this problem by patching a const declaration as in the python FAQ, we end up with another problem I could not fix:
netCDF4/_netCDF4.pyx:1030:35: Expected ')'

% python2 setup.py build
reading from setup.cfg...
Package hdf5 was not found in the pkg-config search path.
Perhaps you should add the directory containing `hdf5.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hdf5' found
using nc-config ...
HDF5 library version: 1.8.15-patch1 found in /data/softs/local/hdf5/1.8.15p1
using netcdf library version 4.3.3.1
using Cython to compile netCDF4.pyx...
netcdf lib has group rename capability
netcdf lib has nc_inq_path function
netcdf lib has nc_inq_format_extended function
netcdf lib does not have nc_open_mem function
netcdf lib does not have cdf-5 format capability
running build
running build_py
running build_ext
pyrexc netCDF4/_netCDF4.pyx --> netCDF4/_netCDF4.c
/data/home/globc/page/src/netcdf4-python/netCDF4/_netCDF4.pyx:1030:35: Expected ')'
building 'netCDF4._netCDF4' extension
gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/data/softs/local/netcdf/4.3.3.1/include -I/data/softs/local/hdf5/1.8.15p1/include -I/data/softs/local/hdf5/1.8.15p1/include -I/data/softs/local/python2.7-shared/lib/python2.7/site-packages/numpy/core/include -Iinclude -I/data/softs/local/python2.7-shared/include/python2.7 -c netCDF4/_netCDF4.c -o build/temp.linux-x86_64-2.7/netCDF4/_netCDF4.o
gcc: error: netCDF4/_netCDF4.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by jswhit** [comment]
Looks like your cython is not working properly and fails to create `_netCDF.c` from `_netCDF4.pyx`.  Try running cython manually on _netCDF4.pyx - what error message does it produce?

**Comment by pagecp** [comment]
Weird, because if I compile directly there is no error and it compiles perfectly...

**Comment by jswhit** [comment]
I noticed this in the output of setup.py:

    pyrexc netCDF4/_netCDF4.pyx

Is it using the old pyrex compiler instead of cython?

**Comment by pagecp** [comment]
Yes, you are right, removing pyrex make it work. 
So the issue can be closed.
Thanks!!
