### ISSUE TITLE
Add support for parallel IO with mpi4py

### ISSUE THREAD

**Issue by jswhit** [Unidata/netcdf4-python#717]
add parallel IO capabilities.  netcdf-c and hdf5 must be compiled with MPI support, and mpi4py must be installed.  To open a file for parallel access, use `parallel=True` in `Dataset.__init__` and optionally pass the mpi4py Comm instance using the `comm` kwarg and the mpi4py Info instance using the `info` kwarg.  If neither are specified, `MPI_COMM_WORLD` and `MPI_INFO_NULL` are used.  IO can be toggled between collective and independent using `Variable.set_collective`.  See `examples/mpi_example.py` and pull request #716.

**Comment by jswhit** [comment]
There are no tests yet, but for some reason `tst_diskless.py` fails when the an mpi-enabled netcdf-c library is linked.

**Comment by jswhit** [comment]
Added a simple parallel IO test.  Failures are allowed for now while this support is experimental.

**Comment by jswhit** [comment]
Seems ready to go, will merge tomorrow if there are no comments.

**Comment by jswhit** [comment]
pull request #716 merged

**Comment by ArchangeGabriel** [comment]
@jswhit Where you able to pin/fix the tst_diskless.py failure? I had reported it a while ago https://github.com/Unidata/netcdf4-python/issues/669 so that some tests had already been done around it.

**Comment by jswhit** [comment]
No - someone should probably create at netcdf-c issue for this.
