### ISSUE TITLE
Can you provide a build with hdf5-1.10?

### ISSUE THREAD

**Issue by mjbrodzik** [Unidata/netcdf4-python#719]
Hello, I am working on a package that depends on netcdf4.  I am installing it on the CU summit supercomputer, which has recently rebuilt a bunch of their slurm packages, and they have built their slurm netcdf4 with hdf5-1.10 with an explanation about older versions.  Following is the explanation they sent me:

"Regarding NetCDF, there is an issue between the latest hdf5 (version 1.10.x) and versions of NetCDF up through 4.4.0 (which includes your 4.3.3).  The issue stems from some changes in HDF5 when they moved from 1.8.x to 1.10.x and the result is that files written with these older NetCDF versions + the new hdf5 are not readable by older versions of NetCDF due to files being written out with the wrong superblock version.  NetCDF 4.4.1.1 fixes this issue, creating files that are appropriately backwards compatible, and so that's what we are standardizing on at Summit moving forward."

I see that the current netcdf4-1.3.0 is pinned to hdf5-1.8.18, which is throwing these errors when I try to run my utilities on summit:

```The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.10.1, library is 1.8.18
```

Would it be possible to build netcdf4 with hdf5-1.10 on conda-forge?  The sys admin told me he could teach me how to do a custom slurm build with netcdf4 and hdf5-1.8, but that seems like only a mend and not a real fix.

Thank you.

**Comment by jswhit** [comment]
How did you install netcdf4-python?  Did you built from source or install a binary wheel from pypi using 'pip install'?

**Comment by jswhit** [comment]
Sorry, I see you say it was installed with slurm.  You try installing a binary wheel  from pypi, see https://pip.pypa.io/en/latest/user_guide/#installing-from-wheels

**Comment by mjbrodzik** [comment]
I am really sorry to have bothered you with this problem.  It turned out that I was loading the system netcdf libraries using the slurm "module load" command, after I activated my conda env with my own package.  At this point, all of the nco utilities that my package was trying to call were then pointing at the system netcdf library, instead of the one in my conda env.  The solution was to stop using slurm to load netcdf.
