### ISSUE TITLE
Add "calendar" overload to MFTime?

### ISSUE THREAD

**Issue by bekozi** [Unidata/netcdf4-python#720]
When using `MFTime` on time bounds variables, it is often the case that the variable does not have a `calendar` attribute which triggers: https://github.com/Unidata/netcdf4-python/blob/16b376340769a05628022a8318cc8963f85a3ae1/netCDF4/_netCDF4.pyx#L6309
Is there a reason the interface for `MFTime` could not accommodate a calendar overload similar to units?

**Comment by jswhit** [comment]
Seems like a default value `calendar='standard'` should work.  

Pull request is welcome.

**Comment by bekozi** [comment]
Thanks @jswhit. And, yes, I'll do a PR.

**Comment by bekozi** [comment]
Added in PR https://github.com/Unidata/netcdf4-python/pull/721.
