### ISSUE TITLE
paralle I/O failed

### ISSUE THREAD

**Issue by sunchaoatmo** [Unidata/netcdf4-python#723]
I am trying the latest version of netCDF4 (from GitHub:0164769c34b814da2515f57781110230e37bdcb2)

and the example:  examples/mpi_example.py.

However the results I got is incorrect: the script can run without error, but the data is incompleted:
#######################
ncdump -v var parallel_tst.nc 
netcdf parallel_tst {
dimensions:
	dim = 4 ;
variables:
	int64 var(dim) ;
data:

 var = 0, _, _, _ ;
}
#######################

Here is my nc-config's output:
This netCDF 4.4.1.1 has been built with the following features: 

  --cc        -> icc
  --cflags    -> -I/glade/u/home/sunchao/local/ch/include -I//glade/u/home/sunchao/local/ch/include
  --libs      -> -L/glade/u/home/sunchao/local/ch/lib -lnetcdf

  --has-c++   -> no
  --cxx       -> 

  --has-c++4  -> yes
  --cxx4      -> mpicxx
  --cxx4flags -> -I/glade/u/apps/ch/opt/netcdf-mpi/4.4.1.1/mpt/2.15f/intel/17.0.1/include -I/glade/u/apps/ch/opt/netcdf-mpi/4.4.1.1/mpt/2.15f/intel/17.0.1//include
  --cxx4libs  -> -L/glade/u/apps/ch/opt/netcdf-mpi/4.4.1.1/mpt/2.15f/intel/17.0.1/lib -lnetcdf_c++4 -lnetcdf

  --has-fortran-> yes
  --fc        -> ifort
  --fflags    -> -I/glade/u/home/sunchao/local/ch/include
  --flibs     -> -L/glade/u/home/sunchao/local/ch/lib -lnetcdff -L//glade/u/home/sunchao/local/ch/lib -lnetcdf -lnetcdf -lmpi
  --has-f90   -> no
  --has-f03   -> yes

  --has-dap   -> yes
  --has-nc2   -> yes
  --has-nc4   -> yes
  --has-hdf5  -> yes
  --has-hdf4  -> no
  --has-logging-> no
  --has-pnetcdf-> yes
  --has-szlib -> 

  --prefix    -> /glade/u/home/sunchao/local/ch
  --includedir-> /glade/u/home/sunchao/local/ch/include
  --libdir    -> /glade/u/home/sunchao/local/ch/lib
  --version   -> netCDF 4.4.1.1

As following is part of the output from the building:

reading from setup.cfg...
Package hdf5 was not found in the pkg-config search path.
Perhaps you should add the directory containing `hdf5.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hdf5' found
using nc-config ...
HDF5 library version: 1.8.18 found in /glade/u/apps/ch/opt/netcdf-mpi/4.4.1.1/mpt/2.15f/intel/17.0.1/
using netcdf library version 4.4.1.1
using Cython to compile netCDF4.pyx...
netcdf lib has group rename capability
netcdf lib has nc_inq_path function
netcdf lib has nc_inq_format_extended function
netcdf lib has nc_open_mem function
netcdf lib has cdf-5 format capability
netcdf lib has netcdf4 parallel functions
running build
running build_py
running build_ext
cythoning netCDF4/_netCDF4.pyx to netCDF4/_netCDF4.c
building 'netCDF4._netCDF4' extension
icc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/glade/u/apps/ch/opt/netcdf-mpi/4.4.1.1/mpt/2.15f/intel/17.0.1/include -I/glade/u/apps/ch/opt/netcdf-mpi/4.4.1.1/mpt/2.15f/intel/17.0.1//include -I/glade/u/apps/ch/opt/netcdf-mpi/4.4.1.1/mpt/2.15f/intel/17.0.1/include -I/glade/u/apps/ch/opt/pythonpkgs/2.7/numpy/1.13.3/intel/17.0.1/lib/python2.7/site-packages/numpy/core/include -I/glade/u/apps/ch/opt/pythonpkgs/2.7/mpi4py/2.0.0/mpt/2.15f/gnu/6.2.0/lib/python2.7/site-packages/mpi4py/include -I/opt/sgi/mpt/mpt-2.15/include -Iinclude -I/glade/u/apps/ch/opt/python/2.7.13/gnu/6.2.0/include/python2.7 -c netCDF4/_netCDF4.c -o build/temp.linux-x86_64-2.7/netCDF4/_netCDF4.o
In file included from /glade/u/apps/ch/opt/pythonpkgs/2.7/numpy/1.13.3/intel/17.0.1/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h(1809),
                 from /glade/u/apps/ch/opt/pythonpkgs/2.7/numpy/1.13.3/intel/17.0.1/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h(18),
                 from /glade/u/apps/ch/opt/pythonpkgs/2.7/numpy/1.13.3/intel/17.0.1/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h(4),
                 from netCDF4/_netCDF4.c(440):
/glade/u/apps/ch/opt/pythonpkgs/2.7/numpy/1.13.3/intel/17.0.1/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h(15): warning #1224: #warning directive: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
  #warning "Using deprecated NumPy API, disable it by " \
   ^

netCDF4/_netCDF4.c(7469): warning #167: argument of type "char **" is incompatible with parameter of type "const char **"
          __pyx_v_ierr = nc_put_att_string(__pyx_t_6, __pyx_v_varid, __pyx_v_attname, __pyx_t_10, __pyx_v_string_ptrs);
                                                                                                  ^

netCDF4/_netCDF4.c(7897): warning #167: argument of type "char **" is incompatible with parameter of type "const char **"
              __pyx_v_ierr = nc_put_att_string(__pyx_t_14, __pyx_v_varid, __pyx_v_attname, 1, (&__pyx_v_datstring));
                                                                                              ^

gcc -pthread -shared build/temp.linux-x86_64-2.7/netCDF4/_netCDF4.o -L/glade/u/apps/ch/opt/netcdf-mpi/4.4.1.1/mpt/2.15f/intel/17.0.1/lib -L/glade/u/apps/ch/opt/netcdf-mpi/4.4.1.1/mpt/2.15f/intel/17.0.1/lib -Wl,-R/glade/u/apps/ch/opt/netcdf-mpi/4.4.1.1/mpt/2.15f/intel/17.0.1/lib -Wl,-R/glade/u/apps/ch/opt/netcdf-mpi/4.4.1.1/mpt/2.15f/intel/17.0.1/lib -lnetcdf -lhdf5_hl -lhdf5 -lmpi -o build/lib.linux-x86_64-2.7/netCDF4/_netCDF4.so
/glade/u/apps/ch/opt/python/2.7.13/gnu/6.2.0/lib/libpython2.7.a(posixmodule.o): In function `posix_tmpnam':
/glade/p/work/csgteam/ch/BUILD/python/source-Python-2.7.13/./Modules/posixmodule.c:7614: warning: the use of `tmpnam_r' is dangerous, better use `mkstemp'
/glade/u/apps/ch/opt/python/2.7.13/gnu/6.2.0/lib/libpython2.7.a(posixmodule.o): In function `posix_tempnam':
/glade/p/work/csgteam/ch/BUILD/python/source-Python-2.7.13/./Modules/posixmodule.c:7561: warning: the use of `tempnam' is dangerous, better use `mkstemp'
skipping 'netcdftime/_netcdftime.c' Cython extension (up-to-date)

**Comment by jswhit** [comment]
I see you're netcdf lib is built with icc, but the python module is being built with gcc - that could be a problem.  Could you post the results of the test suite (`cd test; python run_all.py`) as well as the output from running `mpI_example.py`?

**Comment by sunchaoatmo** [comment]
Thanks again, I hit the bummer as soon as I tried the run_all.py:
Traceback (most recent call last):
  File "run_all.py", line 3, in <module>
    from netCDF4 import __has_cdf5_format__, __has_nc_inq_path__, __has_nc_par__
ImportError: cannot import name __has_cdf5_format__
sunchao@cheyenne3:~/sourcecode/netcdf4-python/test> ls
Any idea what happened please?
Did I install it incorrectly?

**Comment by jswhit** [comment]
Apparently not.  Did you run `setup.py install`?

What happens when you try to `import netCDF`? (do this outside the netcdf4-python source directory)

**Comment by sunchaoatmo** [comment]
Well, that's wired, I can import the netCDF4 without error:
sunchao@cheyenne3:~> python
Python 2.7.13 (default, Jan 11 2017, 15:53:57) 
[GCC 6.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import netCDF4
>>> netCDF4.__path__
['/glade/u/home/sunchao/.local/lib/python2.7/site-packages/netCDF4']

**Comment by jswhit** [comment]
OK, so how about trying `from netCDF4 import __has_cdf5_format__`

**Comment by jswhit** [comment]
I think you will find that the `netCDF4.so` you are importing from `/glade/u/home/sunchao/.local/lib/python2.7/site-packages/netCDF4` is an older version, not the one you just built.

**Comment by sunchaoatmo** [comment]
You are correct! That's an old version. I install the netCDF4 for myself:
python setup.py install --user
and after I changed the sys.path, and put the latest path into the first then reimport the netcdf4:
>>> sys.path=['/glade/u/home/sunchao/.local/lib/python2.7/site-packages/netCDF4-1.3.1-py2.7-linux-x86_64.egg','', '/glade/u/apps/ch/opt/pythonpkgs/2.7/mpi4py/2.0.0/mpt/2.15f/gnu/6.2.0/lib/python2.7/site-packages', '/glade/u/apps/ch/opt/pythonpkgs/2.7/matplotlib/2.0.2/gnu/6.3.0/lib/python2.7/site-packages', '/glade/u/apps/ch/opt/pythonpkgs/2.7/scipy/0.19.1/intel/17.0.1/lib/python2.7/site-packages', '/glade/u/apps/ch/opt/pythonpkgs/2.7/numpy/1.13.3/intel/17.0.1/lib/python2.7/site-packages', '/glade/u/apps/ch/opt/python/2.7.13/gnu/6.2.0/lib/python27.zip', '/glade/u/apps/ch/opt/python/2.7.13/gnu/6.2.0/lib/python2.7', '/glade/u/apps/ch/opt/python/2.7.13/gnu/6.2.0/lib/python2.7/plat-linux2', '/glade/u/apps/ch/opt/python/2.7.13/gnu/6.2.0/lib/python2.7/lib-tk', '/glade/u/apps/ch/opt/python/2.7.13/gnu/6.2.0/lib/python2.7/lib-old', '/glade/u/apps/ch/opt/python/2.7.13/gnu/6.2.0/lib/python2.7/lib-dynload', '/glade/u/home/sunchao/.local/lib/python2.7/site-packages', '/glade/u/home/sunchao/.local/lib/python2.7/site-packages/netCDF4-1.3.1-py2.7-linux-x86_64.egg', '/glade/u/apps/ch/opt/python/2.7.13/gnu/6.2.0/lib/python2.7/site-packages']
>>> import netCDF4
MPT ERROR: mpiexec_mpt must be used to launch all MPI applications

**Comment by sunchaoatmo** [comment]
I adjusted the path, and it seems work now, I will test it with large array and report to this issue later on.
Thanks for your help!

**Comment by sunchaoatmo** [comment]
Here is a quick summary of this issue"

Error reason: I used an incorrect sys path, the python actually imported an old version.
Solution: clean up the path.

Test result: the netcdf4py(7a02397ae6e3794598f0fd4c32ef4f9c6106618f) parallel I/O can work properlly on cheyenne with python 2.7.13 netCDF 4.4.1.1 and MPT.

Problem scale: 13545*138*195 array, parallel over the first dimension using 648 procs.

Thanks for Jswhit's help!

**Comment by jswhit** [comment]
Very glad to hear it's working on Cheyenne.  Please re-open this ticket if you run into any issues.
