### ISSUE TITLE
Import error centos 7

### ISSUE THREAD

**Issue by vgensini** [Unidata/netcdf4-python#731]
Using anaconda version 5.0.0, I've created a new environment:
**conda create --name netcdf_test python=2.7**
--------------------------------------------------------------------------------------
Fetching package metadata ...........
Solving package specifications: .
Package plan for installation in environment /home/vgensini/Programs/anaconda2/envs/netcdf_test:

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-h1d4fec5_0
    certifi:         2017.7.27.1-py27h9ceb091_0
    libedit:         3.1-heed3624_0
    libffi:          3.2.1-h4deb6c0_3
    libgcc-ng:       7.2.0-h7cc24e2_2
    libstdcxx-ng:    7.2.0-h7a57d05_2
    ncurses:         6.0-h06874d7_1
    openssl:         1.0.2l-h077ae2c_5
    pip:             9.0.1-py27hbf658b2_3
    python:          2.7.14-hc2b0042_21
    readline:        7.0-hac23ff0_3
    setuptools:      36.5.0-py27h68b189e_0
    sqlite:          3.20.1-h6d8b0f3_1
    tk:              8.6.7-h5979e9b_1
    wheel:           0.29.0-py27h411dd7b_1
    zlib:            1.2.11-hfbfcf68_1

----------------------------------------------------------------------------------------

I've then tried to install netcdf4:

source activate netcdf_test

(netcdf_test) [vgensini@vortex vargen]$ **conda install netcdf4**
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/vgensini/Programs/anaconda2/envs/netcdf_test:

The following NEW packages will be INSTALLED:

    curl:         7.49.0-1
    hdf4:         4.2.12-1
    hdf5:         1.8.17-2
    intel-openmp: 2018.0.0-h15fc484_7
    jpeg:         9b-habf39ab_1
    libnetcdf:    4.4.1-1
    mkl:          2018.0.0-hb491cac_4
    netcdf4:      1.2.4-np113py27_0
    numpy:        1.13.3-py27hbcc08e0_0

Proceed ([y]/n)? y

---------------------------------------------------------------------------------

..but from python prompt in the netcdf_test environment, I am getting an import error. 

>>> from netCDF4 import Dataset
RuntimeError: module compiled against API version 0xb but this version of numpy is 0x7
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vgensini/Programs/anaconda2/envs/narr/lib/python2.7/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: numpy.core.multiarray failed to import

**Comment by vgensini** [comment]
resolved issue by removing deprecated version of numpy (1.7.1 from base epel repo install; /usr/lib64/python2.7/site-packages/numpy) that was being superceded by conda env.

**Comment by dopplershift** [comment]
Glad you managed to track it down! I was just about to respond. 😁

**Comment by akrherz** [comment]
@vgensini It would have been nice to see your `PYTHONPATH` variable. Perhaps it was including RHEL system python libs, which is done by GEMPAK's Gemenviron file (naughty and corrected by some recent PRs against GEMPAK :))

**Comment by vgensini** [comment]
@akrherz I ran into a similar issue today and tracked it down to GEMPAK's Gemenviron setting of the PYTHONPATH variable. Naughty indeed!
