### ISSUE TITLE
Indexing a size 0 string variable fails

### ISSUE THREAD

**Issue by shoyer** [Unidata/netcdf4-python#743]
This was reported over in https://github.com/pydata/xarray/issues/1732.

The problematic netCDF file can be downloaded here: https://storage.googleapis.com/myargo/sample/4902076_prof.nc

Any attempt to index this string variable results in an `IndexError` from netCDF4-python:
```
In [12]: import netCDF4

In [13]: f = netCDF4.Dataset('4902076_prof.nc')

In [14]: f.variables['HISTORY_INSTITUTION']
Out[14]:
<class 'netCDF4._netCDF4.Variable'>
|S1 HISTORY_INSTITUTION(N_HISTORY, N_PROF, STRING4)
    long_name: Institution which performed action
    conventions: Argo reference table 4
    _FillValue: b' '
unlimited dimensions: N_HISTORY
current shape = (0, 33, 4)
filling off

In [15]: f.variables['HISTORY_INSTITUTION'][...]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-15-672749ef1fb0> in <module>()
----> 1 f.variables['HISTORY_INSTITUTION'][...]

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Variable.__getitem__ (netCDF4/_netCDF4.c:39734)()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Variable._get (netCDF4/_netCDF4.c:49784)()

IndexError:

In [16]: f.variables['HISTORY_INSTITUTION'][:, :, :]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-16-c8aa01a52be7> in <module>()
----> 1 f.variables['HISTORY_INSTITUTION'][:, :, :]

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Variable.__getitem__ (netCDF4/_netCDF4.c:39734)()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Variable._get (netCDF4/_netCDF4.c:49784)()

IndexError:
```

The desired behavior would be a string array with shape `(0, 33, 4)`.

**Comment by jswhit** [comment]
I think this might be a bug in `nc_get_vara`.  The [docs](https://www.unidata.ucar.edu/software/netcdf/netcdf-4/newdocs/netcdf-c/nc_005fget_005fvara_005f-type.html) say

`Note: setting any element of the count array to zero causes the function to exit without error, and without doing anything.`

but instead, the error code `NC_EINVALCOORDS` is being returned (which means 'index exceeds dimension bounds').

A workaround would be to check if no data is being requested, and just return an empty array.

**Comment by jswhit** [comment]
Note - the error only occurs with NETCDF3_CLASSIC format files.

**Comment by dopplershift** [comment]
@WardF you may want to look at `nc_get_vara`...

**Comment by jswhit** [comment]
pull request #744 merged, closing now.
