### ISSUE TITLE
Wrong data when retrieving an OpenDAP slice

### ISSUE THREAD

**Issue by RutgerK** [Unidata/netcdf4-python#745]
I'm getting some strange results when trying to retrieve data from an OpenDAP service. Its a spatial dataset (x,y) with a time dimension. If i query for a specific time step, everything looks fine, but when i query a slice over time, the data i get back changes.

I'm not sure if this is related to the netCDF4 client, or whether its related to the OpenDAP server (GrADS Data Server (GDS)). I don't know how I, as an end user, can make the distinction, so maybe this issue doesn't belong here. 

I'm using netCDF4 version: 1.3.1

Here is a snippet reproducing the behavior:

Setting up the Dataset:

```python
import netCDF4
print(netCDF4.__version__)

url = r'http://opendap.nccs.nasa.gov:9090/dods/GEOS-5/fp/0.25_deg/assim/tavg1_2d_slv_Nx'
f = netCDF4.Dataset(url)

# time layers
lyrs = [4344, 4367] # # 2014-08-20 till 2014-08-21

# spatial point (changing the location has no influence)
px, py = (672, 340)
```

Retrieving each time step individually seems to work fine. 
```python
for lyr in range(lyrs[0], lyrs[1]+1):    
    print(lyr, f.variables['ps'][lyr, py, px])
```
```
4344 89590.7
4345 89625.9
4346 89681.0
4347 89769.1
4348 89844.6
4349 89890.8
4350 89933.8
4351 89892.6
4352 89824.8
4353 89723.4
4354 89626.7
4355 89534.5
4356 89448.9
4357 89420.2
4358 89449.0
4359 89510.3
4360 89577.4
4361 89627.6
4362 89692.8
4363 89725.6
4364 89702.9
4365 89658.8
4366 89599.8
4367 89557.8
```

Retrieving all time steps at once changes the results, and looks wrong. 
```python
print(f.variables['ps'][lyrs[0]:lyrs[1]+1, py, px])
```
```
array([ 89590.734375  ,  89625.90625   ,  89681.        ,    276.59707642,
          276.59747314,    218.75848389,    216.04185486,    216.07647705,
          216.07681274,    216.08854675,    216.14804077,    218.81274414,
          238.08773804,    266.54556274,    266.35198975,    266.8302002 ,
          269.02648926,    269.08581543,    269.2666626 ,    269.28094482,
          269.25271606,    269.30371094,    271.02593994,    274.77075195], dtype=float32)
```

Retrieving a slice but skipping the first five time steps, seems to work again. 
```python
print(f.variables['ps'][lyrs[0]+5:lyrs[1]+1, py, px])
```

Results in:
```
array([ 89890.796875 ,  89933.8046875,  89892.59375  ,  89824.765625 ,
        89723.4140625,  89626.7421875,  89534.5      ,  89448.8671875,
        89420.21875  ,  89448.9765625,  89510.25     ,  89577.4453125,
        89627.609375 ,  89692.8046875,  89725.6484375,  89702.8671875,
        89658.8203125,  89599.7734375,  89557.765625 ], dtype=float32)
```

Here is a Jupyter notebook, which also shows the output i'm getting:
https://gist.github.com/RutgerK/ed6089ff369590ec3a26863645c06e67

**Comment by jswhit** [comment]
Confirmed.  Don't know yet if this is a python issue or not - will have to either write a simple C program or use nco to extract the same slice to see whether it's really a C lib issue.

**Comment by jswhit** [comment]
Not a python issue.  Using nco

    url='http://opendap.nccs.nasa.gov:9090/dods/GEOS-5/fp/0.25_deg/assim/tavg1_2d_slv_Nx'
    ncks -v 'ps' -d time,735466.10,735466.15 -d lat,78,78 -d lon,-73.75,-73.75 $url out.nc
    ncdump out.nc

    netcdf out {
    dimensions:
	lat = 1 ;
	lon = 1 ;
	time = 2 ;
    variables:
	double lat(lat) ;
		lat:grads_dim = "y" ;
		lat:grads_mapping = "linear" ;
		lat:grads_size = "721" ;
		lat:units = "degrees_north" ;
		lat:long_name = "latitude" ;
		lat:minimum = -90. ;
		lat:maximum = 90. ;
		lat:resolution = 0.25f ;
	double lon(lon) ;
		lon:grads_dim = "x" ;
		lon:grads_mapping = "linear" ;
		lon:grads_size = "1152" ;
		lon:units = "degrees_east" ;
		lon:long_name = "longitude" ;
		lon:minimum = -180. ;
		lon:maximum = 179.6875 ;
		lon:resolution = 0.3125f ;
	float ps(time, lat, lon) ;
		ps:_FillValue = 1.e+15f ;
		ps:missing_value = 1.e+15f ;
		ps:long_name = "surface_pressure " ;
	double time(time) ;
		time:grads_dim = "t" ;
		time:grads_mapping = "linear" ;
		time:grads_size = "33075" ;
		time:grads_min = "00:30z20feb2014" ;
		time:grads_step = "60mn" ;
		time:units = "days since 1-1-1 00:00:0.0" ;
		time:long_name = "time" ;
		time:minimum = "00:30z20feb2014" ;
		time:maximum = "02:30z29nov2017" ;
		time:resolution = 0.04166667f ;

    // global attributes:
	  	:title = "GEOS5 FP 2d time-averaged single level diagnostics" ;
		:Conventions = "COARDS\n",
			"GrADS" ;
    		:dataType = "Grid" ;
    		:history = "Wed Nov 29 10:46:32 2017: ncks -v ps -d time,735466.10,735466.15 -d 
    lat,78,78 -d lon,-73.75,-73.75 http://opendap.nccs.nasa.gov:9090/dods/GEOS-
    5/fp/0.25_deg/assim/tavg1_2d_slv_Nx out.nc\n",
	    		"Wed Nov 29 07:01:40 EST 2017 : imported by GrADS Data Server 2.0" ;
    		:extra_das_attribute = "This is an example of metadata added using a supplementary 
    DAS file. See testdata/extra.das for the source." ;
		:NCO = "4.6.6" ;
        data:

     lat = -70.5 ;

     lon = -73.75 ;

     ps =
      98961,
      241.0229 ;

     time = 735466.104166667, 735466.145833333 ;
    }

**Comment by RutgerK** [comment]
Thanks for confirming this, I will reach out to the maintainer of the OpenDAP server.

**Comment by jswhit** [comment]
OK - we'd appreciate it if you could report back here what happens next.

**Comment by RutgerK** [comment]
So far i haven't got any response, but i will let you know if i find out more. I guess this can be closed for now, it can always be reopened if it does turn out to be something client related after all.
