### ISSUE TITLE
erratic behavior when writing to string arrays

### ISSUE THREAD

**Issue by nschloe** [Unidata/netcdf4-python#746]
When creating a variable of type 'S1', assigning this variable is buggy. `fill_value` doesn't work, and filling the array manually also doesn't. Most of the time, that it.

MWE:
```python
import netCDF4

print(netCDF4.__version__)
# 1.3.1

rootgrp = netCDF4.Dataset('test.nc', 'w')

rootgrp.createDimension('num_strings', 1)
rootgrp.createDimension('max_len', 10)

strings = rootgrp.createVariable(
          'strings', 'S1', ('num_strings', 'max_len'),
          fill_value=b'x'
          )
print(strings[:])
# nothing despite fill value
# [[-- -- -- -- -- -- -- -- -- --]]

strings[:] = b'x'
print(strings[:])
# still nothing
# [[-- -- -- -- -- -- -- -- -- --]]

strings[:] = b'y'
print(strings[:])
# okay
# [['y' 'y' 'y' 'y' 'y' 'y' 'y' 'y' 'y' 'y']]
```
Other odd cases can be constructed when `fill_value` is omitted, but the cause is probably the same.

**Comment by jswhit** [comment]
A masked array is being returned with values equal to the `_FillValue` masked (the masked values are shown as `--` when you print the array).  You can disable this if you want using the `set_auto_mask` variable method.

Bottom line - I think this is expected behavior, unless I'm missing something.

**Comment by nschloe** [comment]
If `fill_value=b'x'` is specified, why is everything masked?
Note that overriding the data with `b'x'` fails, but succeeds with `b'y'`. Is this really expected?

**Comment by jswhit** [comment]
You haven't written any data to the variable, so all the values are equal to the `_FillValue` and show up as masked. You only 'see' the data if you write data that is not equal to the `_FillValue`.

From the netcdf users guide

"Generic applications often need to write a value to represent undefined or missing values. The fill value provides an appropriate value for this purpose because it is normally outside the valid range and therefore treated as missing when read by generic applications. It is legal (but not recommended) for the fill value to be within the valid range."

**Comment by dopplershift** [comment]
The fill value specifies what bytes are used to initialize the array, and subsequently written to disk if they are not overridden by other values. By default, netcdf4-python treats the fill value as a value that should be masked. If you call `set_auto_mask(False)`, when you run `strings[:]`, you should see the fill values.

**Comment by nschloe** [comment]
I think I understand now: `fill_value` not only fills the array, but also sets a "mask character". Every entry with that gets set with this character in the future will get masked. Fair enough.

Thanks for the explanation!

**Comment by jswhit** [comment]
Note that the mask is  also set if the data values are equal to the `missing_value` attribute, or outside `valid_min`, `valid_max` or `valid_range`.
