### ISSUE TITLE
How are Windows wheels created?

### ISSUE THREAD

**Issue by letmaik** [Unidata/netcdf4-python#750]
I found the bits that build [conda](https://github.com/Unidata/netcdf4-python/blob/master/appveyor.yml) [packages](https://github.com/Unidata/netcdf4-python/tree/master/conda.recipe) and [Linux/macOS wheels](https://github.com/MacPython/netcdf4-python-wheels), but couldn't find anything for Windows wheels. Since they exist on PyPI, how are they created? This is mostly for having some reference for other developers who want to do the same and also to have more transparency which I always find quite important for binary packages.

**Comment by matthew-brett** [comment]
Machinery here : https://github.com/MacPython/netcdf4-python-wheels

This machinery triggers builds on Travis-CI - builds here: https://travis-ci.org/MacPython/netcdf4-python-wheels

See the repo README for more detail.

**Comment by letmaik** [comment]
Please read my message again :)

**Comment by matthew-brett** [comment]
Oops!

**Comment by jswhit** [comment]
Christoph Gohlke (@cgohlke) creates the windows wheels, and I grab them from his [site](https://www.lfd.uci.edu/~gohlke/pythonlibs/#netcdf4).
