### ISSUE TITLE
appveyor windows tests failing

### ISSUE THREAD

**Issue by jswhit** [Unidata/netcdf4-python#758]
Error message is 'The batch file cannot be found.'

Sounds like [this](https://github.com/conda/conda/issues/6527), but I don't know what the fix is.  

@ocefpaf, do you have any ideas?

**Comment by jswhit** [comment]
Fixed it using the hack suggested in the conda-forge issue (in pull request #757)

**Comment by ocefpaf** [comment]
Sorry, just saw this and you already fixed it.
