### ISSUE TITLE
Different HDF5 library and header version

### ISSUE THREAD

**Issue by AgilentGCMS** [Unidata/netcdf4-python#760]
I'm trying to install netcdf4-python on a system that has two versions of HDF5 installed, version 1.8.17 in /usr/local, and 1.10.1 in /opt/intel/intelpython3. No matter what I do, netCDF4.so seems to be building with headers from 1.8.17 and linking to 1.10.1. This is a problem, because it then barfs when I try to use it.

I've tried the following:
```
$ export HDF5_DIR=/usr/local
$ /opt/intel/intelpython3/bin/python3 setup.py build
reading from setup.cfg...
Package hdf5 was not found in the pkg-config search path.
Perhaps you should add the directory containing `hdf5.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hdf5' found
using nc-config ...
HDF5 library version: 1.8.17 found in /usr/local
using netcdf library version b'4.4.1'
using Cython to compile netCDF4.pyx...
netcdf lib has group rename capability
netcdf lib has nc_inq_path function
netcdf lib has nc_inq_format_extended function
netcdf lib has nc_open_mem function
netcdf lib has cdf-5 format capability
netcdf lib does not have netcdf4 parallel functions
running build
running build_py
creating build
```
This makes it seem like it is finding the 1.8.17 library, and indeed during the install stage,
```
$ /opt/intel/intelpython3/bin/python3 setup.py install --prefix=/opt/intel/intelpython3
reading from setup.cfg...
Package hdf5 was not found in the pkg-config search path.
Perhaps you should add the directory containing `hdf5.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hdf5' found
using nc-config ...
HDF5 library version: 1.8.17 found in /usr/local
using netcdf library version b'4.4.1'
using Cython to compile netCDF4.pyx...
netcdf lib has group rename capability
```
My LD_LIBRARY_PATH has /usr/local/lib as the first element. However, at run time, when I try to open a netcdf file with Dataset, it barfs saying
```
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.8.17, library is 1.10.1
```
Indeed, when I check which library the .so is linked to, I get
```
$ ldd /opt/intel/intelpython3/lib/python3.6/site-packages/netCDF4-1.3.1-py3.6-linux-x86_64.egg/netCDF4/_netCDF4.cpython-36m-x86_64-linux-gnu.so  | grep hdf
        libhdf5_hl.so.100 => /opt/intel/intelpython3/lib/libhdf5_hl.so.100 (0x00007ff1d71c2000)
        libhdf5.so.101 => /opt/intel/intelpython3/lib/libhdf5.so.101 (0x00007ff1d6c0b000)
        libhdf5_hl.so.10 => /usr/local/lib/libhdf5_hl.so.10 (0x00007ff1d5ec1000)
        libhdf5.so.10 => /usr/local/lib/libhdf5.so.10 (0x00007ff1d590e000)
$ ldd /opt/intel/intelpython3/lib/python3.6/site-packages/netCDF4-1.3.1-py3.6-linux-x86_64.egg/netCDF4/_netCDF4.cpython-36m-x86_64-linux-gnu.so  | grep cdf
        libnetcdf.so.11 => /usr/local/lib/libnetcdf.so.11 (0x00007f1e36cad000)
```
What I can't figure out is why it's linking at all to version 1.10.1 in /opt/intel/intelpython3, when it has clearly found 1.8.17 in /usr/local, and the netcdf library it's linked to was also compiled with 1.8.17.

**Comment by jswhit** [comment]
Difficult to say, could be a lot of things.  Maybe nc-config is telling it to use the library in /opt/intel/intelpython3?

**Comment by AgilentGCMS** [comment]
I don't think so:
```
$ nc-config --all

This netCDF 4.4.1 has been built with the following features: 

  --cc        -> icc
  --cflags    ->  -I/usr/local/include 
  --libs      -> 

  --has-c++   -> no
  --cxx       -> 
  --has-c++4  -> no
  --cxx4      -> 

  --fc        -> 
  --fflags    -> 
  --flibs     -> 
  --has-f90   -> no
  --has-f03   -> no

  --has-dap   -> yes
  --has-nc2   -> yes
  --has-nc4   -> yes
  --has-hdf5  -> yes
  --has-hdf4  -> no
  --has-logging-> no
  --has-pnetcdf-> no
  --has-szlib -> 

  --prefix    -> /usr/local
  --includedir-> /usr/local/include
  --version   -> netCDF 4.4.1
```
I would be happy to have python-netcdf exclusively use the library and headers in /opt/intel/intelpython3 as well, but when I try that by exporting HDF5_DIR and putting /opt/intel/intelpython3/lib first in LD_LIBRARY_PATH, it still uses headers from one and libraries from another location.

**Comment by AgilentGCMS** [comment]
By the way, I don't know why ```nc-config --all``` omitted the libraries, but it does know about them:
```
$ nc-config --libs
-L/usr/local/lib -lnetcdf
```

**Comment by jswhit** [comment]
Have you tried using setup.cfg to explicit set all the include and library paths, and disable the use of nc-config?

**Comment by AgilentGCMS** [comment]
No, but I can try that. The setup.cfg I have does not have skeleton lines for paths, but am I correct in thinking that the structure should be as follows?
```
[directories]
HDF5_dir = /usr/local
netCDF4_dir = /usr/local
szip_dir = /usr/local
hdf4_dir = /usr/local
```
If I specify all the root folders as above, do I also need to define HDF5_incdir etc, or are those going to be derived from HDF5_dir?

**Comment by AgilentGCMS** [comment]
Update: even with the above settings in my setup.cfg, I can see that ``python3 setup.py build`` is trying to execute
```
gcc -pthread -shared -L/opt/intel/intelpython3/lib -Wl,-rpath=/opt/intel/intelpython3/lib,--no-as-needed -z noexecstack -z relro -z now -fstack-protector build/temp.linux-x86_64-3.6/netCDF4/_netCDF4.o -L/usr/local/lib -L/usr/local/lib -L/usr/local/lib -L/usr/local/lib -L/opt/intel/intelpython3/lib -Wl,--enable-new-dtags,-R/usr/local/lib -Wl,--enable-new-dtags,-R/usr/local/lib -Wl,--enable-new-dtags,-R/usr/local/lib -Wl,--enable-new-dtags,-R/usr/local/lib -lhdf5_hl -lhdf5 -lnetcdf -lz -lsz -lmfhdf -ldf -lpython3.6m -o build/lib.linux-x86_64-3.6/netCDF4/_netCDF4.cpython-36m-x86_64-linux-gnu.so
```
No idea where it's getting the ``-L/opt/intel/intelpython3/lib`` from. It's definitely *not* in my LD_LIBRARY_PATH.

**Comment by AgilentGCMS** [comment]
OK, I figured out why it keeps taking /opt/intel/intelpython3. That's because the python3.6 headers and libraries are there, along with HDF5 that came along with intelpython3. So it includes /opt/intel/intelpython3/lib for the '-lpython3.6m', but then finds HDF5 there as well. Now how do I tell it *not* to use HDF5 from there?

**Comment by jswhit** [comment]
Maybe set the LDSHARED environment variable to be 'gcc -pthread -shared' (leaving out the -L/opt/intel/intelpython3/lib)?

**Comment by AgilentGCMS** [comment]
That didn't work either, but I've given up. Having two versions of HDF on one system is not advisable any way, I'll just forego intel's python for now. I'll get back to it when they stop bundling a whole bunch of libraries with it.
