### ISSUE TITLE
Auto-masking broken since version 1.2.8

### ISSUE THREAD

**Issue by kwilcox** [Unidata/netcdf4-python#761]
I was banging my head against the wall for a good few hours until I boiled the code I was working on into something reproducible. The automasking feature of `netCDF4-python` may be broken in all versions since 1.2.8. Thanks to @yosoyjay for finding a version that worked!

Using this little code block: https://gist.github.com/kwilcox/999a8154f913fc6c0873e2302c17a3c0

`netcdf4-python==1.2.8` correctly produces:
```
NETCDF4
            xarray: [  0.   1.  nan   3.   4.   5.   6.   7.   8.   9.]
  automask netcdf4: [0.0 1.0 -- 3.0 4.0 5.0 6.0 7.0 8.0 9.0]
manualmask netcdf4: [0.0 1.0 -- 3.0 4.0 5.0 6.0 7.0 8.0 9.0]

NETCDF4_CLASSIC
            xarray: [  0.   1.  nan   3.   4.   5.   6.   7.   8.   9.]
  automask netcdf4: [0.0 1.0 -- 3.0 4.0 5.0 6.0 7.0 8.0 9.0]
manualmask netcdf4: [0.0 1.0 -- 3.0 4.0 5.0 6.0 7.0 8.0 9.0]

NETCDF3_CLASSIC
            xarray: [  0.   1.  nan   3.   4.   5.   6.   7.   8.   9.]
  automask netcdf4: [0.0 1.0 -- 3.0 4.0 5.0 6.0 7.0 8.0 9.0]
manualmask netcdf4: [0.0 1.0 -- 3.0 4.0 5.0 6.0 7.0 8.0 9.0]

NETCDF3_64BIT_OFFSET
            xarray: [  0.   1.  nan   3.   4.   5.   6.   7.   8.   9.]
  automask netcdf4: [0.0 1.0 -- 3.0 4.0 5.0 6.0 7.0 8.0 9.0]
manualmask netcdf4: [0.0 1.0 -- 3.0 4.0 5.0 6.0 7.0 8.0 9.0]

NETCDF3_64BIT_DATA
            xarray: [  0.   1.  nan   3.   4.   5.   6.   7.   8.   9.]
  automask netcdf4: [0.0 1.0 -- 3.0 4.0 5.0 6.0 7.0 8.0 9.0]
manualmask netcdf4: [0.0 1.0 -- 3.0 4.0 5.0 6.0 7.0 8.0 9.0]
```

Anything after `1.2.8` incorrectly produces:
```
NETCDF4
            xarray: [  0.   1.  nan   3.   4.   5.   6.   7.   8.   9.]
  automask netcdf4: [0.0 1.0 -- -- -- -- -- -- -- --]
manualmask netcdf4: [0.0 1.0 -- 3.0 4.0 5.0 6.0 7.0 8.0 9.0]

NETCDF4_CLASSIC
            xarray: [  0.   1.  nan   3.   4.   5.   6.   7.   8.   9.]
  automask netcdf4: [0.0 1.0 -- -- -- -- -- -- -- --]
manualmask netcdf4: [0.0 1.0 -- 3.0 4.0 5.0 6.0 7.0 8.0 9.0]

NETCDF3_CLASSIC
            xarray: [  0.   1.  nan   3.   4.   5.   6.   7.   8.   9.]
  automask netcdf4: [0.0 1.0 -- -- -- -- -- -- -- --]
manualmask netcdf4: [0.0 1.0 -- 3.0 4.0 5.0 6.0 7.0 8.0 9.0]

NETCDF3_64BIT_OFFSET
            xarray: [  0.   1.  nan   3.   4.   5.   6.   7.   8.   9.]
  automask netcdf4: [0.0 1.0 -- -- -- -- -- -- -- --]
manualmask netcdf4: [0.0 1.0 -- 3.0 4.0 5.0 6.0 7.0 8.0 9.0]

NETCDF3_64BIT_DATA
            xarray: [  0.   1.  nan   3.   4.   5.   6.   7.   8.   9.]
  automask netcdf4: [0.0 1.0 -- -- -- -- -- -- -- --]
manualmask netcdf4: [0.0 1.0 -- 3.0 4.0 5.0 6.0 7.0 8.0 9.0]
```

I believe this is the culprit: https://github.com/Unidata/netcdf4-python/blob/949d6366688c86db17108c71d88c1d910a57b513/netCDF4/_netCDF4.pyx#L4007-L4010

I can't think of a situation where someone would want to set the `valid_min` or `valid_max` to the `_FillValue` if they don't exist... this is essentially masking anything ABOVE the `_FillValue` if it is greater than `0` and masking everything BELOW the `_FillValue` if it is equal to or below `0`. I can confirm by running the linked code with a fillvalue of `5`:

```
NETCDF4
            xarray: [  0.   1.   2.   3.   4.  nan   6.   7.   8.   9.]
  automask netcdf4: [0.0 1.0 2.0 3.0 4.0 -- -- -- -- --]
manualmask netcdf4: [0.0 1.0 2.0 3.0 4.0 -- 6.0 7.0 8.0 9.0]

NETCDF4_CLASSIC
            xarray: [  0.   1.   2.   3.   4.  nan   6.   7.   8.   9.]
  automask netcdf4: [0.0 1.0 2.0 3.0 4.0 -- -- -- -- --]
manualmask netcdf4: [0.0 1.0 2.0 3.0 4.0 -- 6.0 7.0 8.0 9.0]

NETCDF3_CLASSIC
            xarray: [  0.   1.   2.   3.   4.  nan   6.   7.   8.   9.]
  automask netcdf4: [0.0 1.0 2.0 3.0 4.0 -- -- -- -- --]
manualmask netcdf4: [0.0 1.0 2.0 3.0 4.0 -- 6.0 7.0 8.0 9.0]

NETCDF3_64BIT_OFFSET
            xarray: [  0.   1.   2.   3.   4.  nan   6.   7.   8.   9.]
  automask netcdf4: [0.0 1.0 2.0 3.0 4.0 -- -- -- -- --]
manualmask netcdf4: [0.0 1.0 2.0 3.0 4.0 -- 6.0 7.0 8.0 9.0]

NETCDF3_64BIT_DATA
            xarray: [  0.   1.   2.   3.   4.  nan   6.   7.   8.   9.]
  automask netcdf4: [0.0 1.0 2.0 3.0 4.0 -- -- -- -- --]
manualmask netcdf4: [0.0 1.0 2.0 3.0 4.0 -- 6.0 7.0 8.0 9.0]
```

I'm going to go back to banging my head against the wall.

**Comment by jswhit** [comment]
Sorry this change has caused you so much grief.  For what it's worth, here's why I did it

From the netcdf users guide under valid_range:

"If neither valid_min, valid_max nor valid_range is defined then generic applications should define a valid range as follows. If the data type is byte and _FillValue is not explicitly defined, then the valid range should include all possible values. Otherwise, the valid range should exclude the _FillValue (whether defined explicitly or by default) as follows. If the _FillValue is positive then it defines a valid maximum, otherwise it defines a valid minimum. For integer types, there should be a difference of 1 between the _FillValue and this valid minimum or maximum. For floating point types, the difference should be twice the minimum possible (1 in the least significant bit) to allow for rounding error."

So, the code is now interpreting the_FillValue as a valid_min/valid_max.  This has caused enough trouble for some people that I'm willing to revert to the old behaviour.

**Comment by kwilcox** [comment]
Thanks for the explanation and I agree that the behavior I am seeing is consistent with the best practices document. Unfortunately we have ourselves in a situation where other client libraries have ignored (maybe for good reason)  that "best practice" and used `_FillValue` as a single-value-fill for as long as I can remember. 

I think the change you commit above is the right way to go. It brings `netcdf4-python` in line with every other netcdf client library I could find.

There is probably a larger discussion to be had here between the authors of the NUG, CF, and netcdf client libraries to make sure everyone is on the same page.

For example, this leads me to believe that CF is expecting the single-value-fill and not the NUG "best practice"

> http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#missing-data.
If only one missing value is needed for a variable then we recommend that this value be specified using the _FillValue attribute. Doing this guarantees that the missing value will be recognized by generic applications that follow either the before or after version 2.4 conventions."

**Comment by jswhit** [comment]
I'll go ahead and merge that pull request tomorrow if no one objects.

**Comment by jswhit** [comment]
pull request #763 merged, closing now...
