### ISSUE TITLE
“RuntimeWarning: invalid value encountered in greater/less” with NaN slices

### ISSUE THREAD

**Issue by equaeghe** [Unidata/netcdf4-python#766]
While creating a netCDF file using netCDF4-python 1.3.1 (in combination with netCDF 4.6.0, HDF5 1.10.1, and Numpy 1.10.4), I got the messages `RuntimeWarning: invalid value encountered in greater` and `RuntimeWarning: invalid value encountered in less`.

I managed to create a simple minimal example:
```python
>>> f = nc.Dataset('test.nc', 'w')

>>> f.createDimension('dimension', 2)
<class 'netCDF4._netCDF4.Dimension'>: name = 'dimension', size = 2

>>> f.createVariable('variable', np.float32, dimensions=('dimension',))
<class 'netCDF4._netCDF4.Variable'>
float32 variable(dimension)
unlimited dimensions: 
current shape = (2,)
filling on, default _FillValue of 9.969209968386869e+36 used

>>> f['variable'][:] = np.nan

>>> f['variable'][:]
__main__:1: RuntimeWarning: invalid value encountered in greater
array([ nan,  nan], dtype=float32)
```

My feeling is that that warning should not be output and may indicate an underlying bug in netCDF4-Python or the libraries it is built upon. When opening the file and requesting `f['variable'][:]` with h5py, I do not get any warning, so that points towards netCDF4-Python or netCDF-C.

**Comment by jswhit** [comment]
With github master I get

```python
from netCDF4 import Dataset
import numpy as np
f = Dataset('test.nc', 'w')
f.createDimension('dimension', 2)
f.createVariable('variable', np.float32, dimensions=('dimension',))
f['variable'][:] = np.nan
print f['variable'][:]

[nan nan]
``python

**Comment by jswhit** [comment]
That warning is coming from numpy and is triggered by the presence of NaNs in the output array.  You can turn it off with `np.warnings.filterwarnings('ignore')`

**Comment by equaeghe** [comment]
`np.warnings.filterwarnings('ignore')` does not work for me. Silencing with `np.warnings.filterwarnings('ignore')` does work, but then I may miss this message when it is something that needs my attention. Is it possible to only check for missing values for non-NaN values?

**Comment by jswhit** [comment]
It's possible, but cumbersome.  The question I have is why do you have NaNs in your output?

**Comment by equaeghe** [comment]
NaN values indicate missing data and is perfectly normal. The dataset does not need to be all-NaN for the warning to appear; I think all-NaN along one axis for a single index-tuple for the other axes is enough. I have had a data-processing situation where this warning was useful, as it prompted me to special-case the NaN values.

One reason why this warning was worrying is that I couldn't figure out why I got it. It was only after your explanation that I understood it isn't some error in my data processing code. Perhaps a solution would be to catch that warning and rethrow it with information for the user about why it is triggered.

**Comment by jswhit** [comment]
If you upgrade to github master you won't see this warning ([this](https://github.com/Unidata/netcdf4-python/commit/97d581539dc3ee3e0e246d413f454c910730fd9f) commit removes it).

I could argue with the 'NaN values indicate missing data' - according the the netcdf users guide missing data should be flagged with the `missing_value` attribute.  The point is moot though - you can just update and it will go away.

**Comment by jswhit** [comment]
Disregard my last comment.  I see in [netcdf best practices](https://www.unidata.ucar.edu/software/netcdf/docs/BestPractices.html) that it does mention using NaNs to indicate missing values.

**Comment by jswhit** [comment]
Added a test for this in pull request #768 to prevent this behavior from being accidentally re-introduced.
