### ISSUE TITLE
CompilerCrash during build since fe293c84

### ISSUE THREAD

**Issue by jsolbrig** [Unidata/netcdf4-python#767]
I hadn't intended to build from the tip of the master, but when I made a mistake and did, I found that I get a ComplierCrash during `setup.py build`.  If, however, do a hard reset to revision #756 (a few days ago) the build completes with no errors.

The two builds shown below are done in a CentOS 7 docker build using Python 2.7.14.  Nothing has been changed except which revision I have cloned.

The output of the two builds are linked below.  Please let me know if there is any additional information I can provide or if there appears to be something that I did wrong.

[good_build.txt](https://github.com/Unidata/netcdf4-python/files/1772502/good_build.txt)
[bad_build.txt](https://github.com/Unidata/netcdf4-python/files/1772499/bad_build.txt)

**Comment by jswhit** [comment]
Don't see why the 'Unreachable code' cython warning actually resulting in a cython crash in your case, but removing that warning is probably a good idea anyway (pull request #769)

**Comment by jswhit** [comment]
Actually I see that your Cython crash is a result of setup.py trying to compile _netcdftime.pyx, which is no longer in the repo.  You must be using an old version of setup.py -  revision #756 removes all references to _netcdftime.pyx in setup.py.

**Comment by jsolbrig** [comment]
I actually get this issue with a fresh clone of the repo, so setup.py is what I am getting from the repo.  Here I fired up a Docker container, then cloned from this repo with `git clone https://github.com/Unidata/netcdf4-python.git`.  `git log` shows the most recent commit as:

```
commit a4f208175cef4dc804e5a02bc8ac18f4881e1a05
Merge: 351ceca 3c8345d
Author: Jeff Whitaker <jswhit@fastmail.fm>
Date:   Thu Mar 1 20:45:57 2018 -0500

    Merge pull request #769 from Unidata/issue767
    
    fix 'Unreachable code' cython warning (issue #767)
```

Here are the build and install logs (I thought this was in build, but it's in the install step):
[build.txt](https://github.com/Unidata/netcdf4-python/files/1776272/build.txt)
[install.txt](https://github.com/Unidata/netcdf4-python/files/1776273/install.txt)

Here is the setup.py that I get when cloning:
[setup.py](https://github.com/Unidata/netcdf4-python/files/1776275/setup.py.txt)

Now, if I reset to revision b5aa84ee396c6257f260d93e3d18744857b04307 everything works fine until I attempt to import:
```
$ git clone https://github.com/Unidata/netcdf4-python.git
$ cd netcdf4-python
$ git reset --hard b5aa84ee396c6257f260d93e3d18744857b04307
$ python setup.py build
$ python setup.py install --user
$ python
Python 2.7.14 (default, Feb 22 2018, 20:28:27) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import netCDF4
>>>
```

If I do a hard reset to:

- b5aa84ee396c6257f260d93e3d18744857b04307: Last working revision for me
- e1c0adc90c5bb29949b7e00b76bef7a4395af6aa: CompilerCrash (earliest broken revision for me)
- a4f208175cef4dc804e5a02bc8ac18f4881e1a05: CompilerCrash (HEAD)

**Comment by jswhit** [comment]
It's crashing when building netcdftime, which is now a dependency.

**Comment by jsolbrig** [comment]
It looks like setup.py in netcdftime requires Cython to be installed prior to calling setup.py, so setup.py is crashing when Cython hasn't been installed yet.  It tries to run `from Cython.Build import cythonize` before it has attempted to check for Cython.

Should I submit this as an issue on netceftime?

**Comment by jswhit** [comment]
yes, please do
