### ISSUE TITLE
Inconsistent storage of ASCII/Unicode/float scalars/arrays

### ISSUE THREAD

**Issue by equaeghe** [Unidata/netcdf4-python#770]
When storing arrays of strings, the behavior is not at all like for floats (and probably other numeric types). Namely, for ASCII strings, everything is concatenated together in one fixed-length string. For Unicode strings, everything is concatenated together in one string and then stored as a singleton array!

Minimal example:
```python
f = nc.Dataset('test.nc', 'w')
f.setncattr('ascii', "boring")
f.setncattr('útf8', "èxítïng")
f.setncattr('ascii-singleton', np.array(["boring"], dtype=str))
f.setncattr('útf8-singleton', np.array(["èxítïng"], dtype=str))
f.setncattr('ascii-array', np.array(["boring", "boring"], dtype=str))
f.setncattr('útf8-array', np.array(["èxítïng", "èxítïng"], dtype=str))
f.setncattr('float-array', [.1, .2])
f.setncattr('float', .3)
f.close()
```

```
$ ncdump test.nc 
netcdf test {

// global attributes:
                :ascii = "boring" ;
                string :útf8 = "èxítïng" ;
                :ascii-array = "boringboring" ;
                string :útf8-array = "èxítïngèxítïng" ;
                :ascii-singleton = "boring" ;
                string :útf8-singleton = "èxítïng" ;
                :float-array = 0.1, 0.2 ;
                :float = 0.3 ;
}
```

```
$ h5dump test.nc 
HDF5 "test.nc" {
GROUP "/" {
   ATTRIBUTE "_NCProperties" {
      DATATYPE  H5T_STRING {
         STRSIZE 55;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "version=1|netcdflibversion=4.6.0|hdf5libversion=1.10.1"
      }
   }
   ATTRIBUTE "ascii" {
      DATATYPE  H5T_STRING {
         STRSIZE 6;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "boring"
      }
   }
   ATTRIBUTE "ascii-array" {
      DATATYPE  H5T_STRING {
         STRSIZE 12;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "boringboring"
      }
   }
   ATTRIBUTE "ascii-singleton" {
      DATATYPE  H5T_STRING {
         STRSIZE 6;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "boring"
      }
   }
   ATTRIBUTE "float" {
      DATATYPE  H5T_IEEE_F64LE
      DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
      DATA {
      (0): 0.3
      }
   }
   ATTRIBUTE "float-array" {
      DATATYPE  H5T_IEEE_F64LE
      DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
      DATA {
      (0): 0.1, 0.2
      }
   }
   ATTRIBUTE "útf8" {
      DATATYPE  H5T_STRING {
         STRSIZE H5T_VARIABLE;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
      DATA {
      (0): "\37777777703\37777777650x\37777777703\37777777655t\37777777703\37777777657ng"
      }
   }
   ATTRIBUTE "útf8-array" {
      DATATYPE  H5T_STRING {
         STRSIZE H5T_VARIABLE;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
      DATA {
      (0): "\37777777703\37777777650x\37777777703\37777777655t\37777777703\37777777657ng\37777777703\37777777650x\37777777703\37777777655t\37777777703\37777777657ng"
      }
   }
   ATTRIBUTE "útf8-singleton" {
      DATATYPE  H5T_STRING {
         STRSIZE H5T_VARIABLE;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
      DATA {
      (0): "\37777777703\37777777650x\37777777703\37777777655t\37777777703\37777777657ng"
      }
   }
}
}
```

I'm using netCDF4-Python 1.3.1, netCDF-C 4.6.0 and HDF5 1.10.1.

The current treatment of text arrays (concatenation) seems wrong. The different treatment between ASCII and Unicode also seems wrong. I would have expected the same treatment as for numeric data.
(Is there any way to create arrays of text as attribute values?)

**Comment by jswhit** [comment]
the only way to treat ascii text similar to numeric arrays is to store in single byte arrays (there is no fixed length ascii string datatype in the netcdf data model).  I thought this would be even more surprising than munging arrays of ascii strings into a single string. You can force the attributes to be saved as arrays of vlen strings with `setncattr_str` (https://github.com/Unidata/netcdf4-python/pull/597).

**Comment by jswhit** [comment]
An example

```python
from netCDF4 import Dataset
import numpy as np
f = Dataset('test.nc','w')
f.setncattr('útf8-string', np.array(["èxítïng", "èxítïng"], dtype=str))
f.setncattr_string('útf8-array', np.array(["èxítïng", "èxítïng"], dtype=str))
f.close()
```

produces

```
netcdf test {

// global attributes:
		string :útf8-string = "èxítïngèxítïng" ;
		string :útf8-array = "èxítïng", "èxítïng" ;
}
```

**Comment by jswhit** [comment]
It would be easy to implement automatically storing attributes as strings if the size of the array is greater than 1.  However, this would only work with NETCDF4 files, since NETCDF3 has no vlen string data type.  The reason I did not implement this is that the same code would produce different results using NETCDF3 and NETCDF4, i.e. 

    f.setncattr('útf8-array', np.array(["èxítïng", "èxítïng"], dtype=str))

would produce

    string :útf8-array = "èxítïng", "èxítïng" ;

in NETCDF4, but 

    string :útf8-array = "èxítïngèxítïng" ;

in NETCDF3*, NETCDF4_CLASSIC formats.  To avoid this, I decided to require the user to explicitly request arrays using `setncattr_string`, but I'm open to changing this.

**Comment by jswhit** [comment]
for the sake of discussion, I implemented this in pull request #771

**Comment by jswhit** [comment]
Regarding the issue of why ascii text attributes are stored differently in the underlying HDF5 file than unicode attributes, this is due to differences in the way `nc_put_att_text` and `nc_put_att_string` work in the C library, not netcdf4-python.

**Comment by equaeghe** [comment]
Thanks for the explanation. To be honest, I do not understand why you would even go through the effort of accepting an array, concatenating it and storing the concatenation. If users try to store arrays of strings in netCDF3|4_classic, just raise an exception, I would say, and inform them of why. They can always do the concatenation themselves. With the current code, the operation seems to have succeeded, but actually with a result that is unexpected, violating the principle of least surprise.

So I fully accept the netCDF4 part of pull request #771, but for the netCDF3|4_classic part, I would just raise an exception and allow users to only write scalar strings. But of course you are the boss and may have to consider other aspects as well.

Regarding `nc_put_att_text` vs. `nc_put_att_string`, I've found #448 and netcdf-c issue [#127](https://github.com/Unidata/netcdf-c/issues/127). That is just crazy: there's a semantic difference between a scalar and a singleton array! I'll provide feedback there even if it seems that they have made up their mind that the inconsistency is as it should be.

**Comment by jswhit** [comment]
I think you are right, an error should be raised for arrays of strings in NETCDF3/NETCDF4_CLASSIC.  Updated the pull request to do this.

**Comment by shoyer** [comment]
I just stumbled across this issue and agree with the resolution to raise an error when attempting to write lists of strings to netCDF3 files.

@equaeghe I agree with you that the semantic difference between scalars and singleton arrays in netCDF4 is crazy! Maybe we can revisit issue in netCDF-C?
