### ISSUE TITLE
can't rename a variable to 'level'

### ISSUE THREAD

**Issue by moisespr123** [Unidata/netcdf4-python#772]
Hi,

When a dimension is already named 'level' and I attempt to rename a variable into `level`, I get the following traceback:

```
Traceback (most recent call last):
    f.renameVariable(var, 'level')
  File "netCDF4/_netCDF4.pyx", line 2460, in netCDF4._netCDF4.Dataset.renameVariable
  File "netCDF4/_netCDF4.pyx", line 1638, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: HDF error
```

The same happens for the inverse, if I already have `level` as a variable and I rename a dimension to `level`, I get the following:

```
python3: nc4internal.c:1340: nc4_reform_coord_var: Assertion `dim_datasetid > 0' failed.
Aborted (core dumped)
```

Any help is really appreciated.

**Comment by jswhit** [comment]
Please provide actual code that we can run to trigger the error.

From the [netcdf-c docs](https://www.unidata.ucar.edu/software/netcdf/docs/group__variables.html#gaca781f9f72b189d1eeb2a949c300324e)

"You cannot rename a variable to have the name of any existing variable."

Doesn't say anything about dimensions though - but I suspect you also have a coordinate variable named 'level' that goes with the dimension.

**Comment by jswhit** [comment]
May be related to https://github.com/Unidata/netcdf-c/issues/865

**Comment by moisesmcardona** [comment]
ncrename tool gives me the same issue. I guess my solution here is to create a brand-new file with the correct dimension and variable names.

**Comment by jswhit** [comment]
Still would be nice to have a simple script to trigger the problem (esp for netcdf-c devs, since it's likely an issue in the C lib)

**Comment by evomassiny** [comment]
Hi,

First of all, thank for your work on this project !

I can confirm that this bug persists, at least on those 2 environments:
* python netCDF4 == 1.4.2, debian netcdf-bin == 1.3.1-1
* python netCDF4 == 1.5.5.1, debian netcdf-bin == 1:4.7.3-1

Here is a simple script that triggers the bug:
```python3

#!/usr/bin/env python3
import netCDF4

file_path = "./level.nc"

# create a dataset with one variable named "Z" expressed on one dimension named "level"
with netCDF4.Dataset(file_path, "w") as dataset:
    dataset.createDimension("level", 1)
    z_var = dataset.createVariable("Z", float, ("level",))
    z_var[:] = 0

# attempt to rename the variable from "Z" to "level"
with netCDF4.Dataset(file_path, "r+") as dataset:
    dataset.renameVariable("Z", "level") # RunTimeError
```

Running the above snippet triggers the following RuntimeError:
```
Traceback (most recent call last):
  File "fails.py", line 15, in <module>
    dataset.renameVariable("Z", "level")
  File "netCDF4/_netCDF4.pyx", line 2580, in netCDF4._netCDF4.Dataset.renameVariable
  File "netCDF4/_netCDF4.pyx", line 1754, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: HDF error
```

I've tried a couple of variable and dimension names and I was only able to reproduce the bug when renaming a variable
to "level" while a "level" dimension exists. It does not matter if the renamed variable is expressed on the "level" dimension
or not.

Best regards,

evomassiny
