### ISSUE TITLE
Issue with missing_value

### ISSUE THREAD

**Issue by thomascoquet** [Unidata/netcdf4-python#777]
From what I understood, missing_value / valid_min / valid_max always apply to packed data.
However, I have troubles understanding why 105 is masked in this case.
```

import netCDF4 as nc
f = nc.Dataset('test_nc2.nc', 'w')
f.createDimension('d', None)

v = f.createVariable('var', 'u2', 'd')
v.missing_value = 105
v.scale_factor = 0.1
v.set_auto_scale(True)

v[:] = [65535/10, 105, 10.5]
v[:]
```

returns 

```
masked_array(data = [-- -- --],
             mask = [ True  True  True],
       fill_value = 105)
```

**Comment by jswhit** [comment]
65535/10 is masked because when scaled, it is equal to the default fill_value.
10.5 is masked because when scaled, it is equal to the missing_value.
105 is masked, because it is equal to the missing value before scaling.

I agree that the last one is surprising.  It happens because a masked array is created before the scale and offset is applied.  This probably should be considered a bug.

**Comment by jswhit** [comment]
fix for this in pull request #779

**Comment by thomascoquet** [comment]
Yes, I understand why 65535/10 and 10.5 are masked :) But either missing_value is applied before or after scaling. Else, it keeps this feature quite confusing (are those masks applied before or after auto_scale, should we cast them as the packed type or unpacked type, + minimum and maximum valid values, etc.). 

I agree with your analysis: the masked array is created before scaling operations and values are masked afterwards as a numpy consequence.

For example, the numpy mask fill_value is missing_value and not add_offset + scale_factor*missing_value.

Maybe the mask should be copied between the np packed array and the np unpacked array with a new scaled fill_value.
Thomas

**Comment by thomascoquet** [comment]
Sorry I hadn't seen your PR. Thanks !!!

**Comment by jswhit** [comment]
Merged pull request, thanks for the report
