### ISSUE TITLE
data is masked if fill value is set even when the data is not equal to fill value

### ISSUE THREAD

**Issue by cpaulik** [Unidata/netcdf4-python#784]
I see this behavior starting with version 1.2.9

The following script:

```
import netCDF4
import numpy as np

print netCDF4.__version__

with netCDF4.Dataset('test.nc', 'w') as nc4:
    dim = 'test'
    nc4.createDimension(dim, size=10)

    var = nc4.createVariable('test-var', np.int,
                             dim, fill_value=5)
    var[:] = np.arange(10)
    print var[:]
    var.set_auto_maskandscale(False)
    print var[:]
```

Give the following output:

```
1.2.9
[0 1 2 3 4 -- -- -- -- --]
[0 1 2 3 4 5 6 7 8 9]
```

So it seems that everything that is `>=` the `FillValue` is masked.

**Comment by MeraX** [comment]
Hi cpaulik,

I stumbled upon a similar problem and found another very related issue:
https://github.com/Unidata/netcdf4-python/issues/748#issuecomment-352082362

**Comment by cpaulik** [comment]
Ok, I understand. I was checking the netcdf attibute conventions but only checked the entry for FillValue for any clues on why it is implemented that way.

**Comment by jswhit** [comment]
This was changed (see issue #777) so starting with version 1.3.2 it will revert to the old behavior (_FillValue will not act as valid_min/valid_max).
