### ISSUE TITLE
Error while using mpi4py

### ISSUE THREAD

**Issue by kurkutesa** [Unidata/netcdf4-python#786]
I am trying to use netcdf with Python MPI. But, when I tried to use mpi4py or python for MPI; I am getting following error.

`from mpi4py import MPI`
`import numpy as np`
`from netCDF4 import Dataset`
`rank = MPI.COMM_WORLD.rank `
`nc = Dataset('parallel_test.nc', 'w', parallel=True, comm=MPI.COMM_WORLD,info=MPI.Info())`

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-17576a75765e> in <module>()
      1 nc = Dataset('parallel_test.nc', 'w', parallel=True, comm=MPI.COMM_WORLD,
----> 2         info=MPI.Info())
 
_netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:12226)() 
**ValueError: parallel mode requires MPI enabled netcdf-c**_
 
While, running above code I have following modules loaded on the HPC.

> 
>  (1) nixpkgs/16.09     (3) gcccore/.5.4.0    (5) intel/2016.4  (7) StdEnv/2016.4   (9) netcdf-mpi/4.1.3    (11) python/3.5.2   ( 13) python35-mpi4py/2.0.0 
>   (2) icc/.2016.4.258   (4) ifort/.2016.4.258  (6) openmpi/2.1.1 (m)  ( 8) hdf5/1.8.18 (10) imkl/11.3.4.258  (12) python35-scipy-stack/2017a
>

**Comment by jswhit** [comment]
I suspect that when you built the netcdf4-python module, you did not actually link the MPI enabled netcdf and hdf5 libs.  Can you post the output of 'setup.py build'?

**Comment by kurkutesa** [comment]
Thank you @jswhit .. When I had tried `setup.py`. I get following messages
>netcdf lib does not have group rename capability
netcdf lib has nc_inq_path function
netcdf lib does not have nc_inq_format_extended function
netcdf lib does not have nc_open_mem function
netcdf lib does not have cdf-5 format capability
netcdf lib does not have netcdf4 parallel functions

With reference to previous message,  I have above mentioned `12 modules` loaded on HPC .

**Comment by kurkutesa** [comment]
Hi @jswhit  ... The HPC sys admin have installed NetCDF4 with Mpi4py for all the slave nodes. Now, It is working as expected. Thank You for your help. I think you can close the ticket.

Thank You,
Sopan
