### ISSUE TITLE
Installing netcdf4 using conda forge channel causes gdal to fail

### ISSUE THREAD

**Issue by rutgerhofste** [Unidata/netcdf4-python#790]
Some compatibility issues with GDAL using anaconda:

 conda install netcdf4
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /opt/anaconda3/envs/python35:

The following NEW packages will be INSTALLED:

    netcdf4:   1.3.1-py35_2 conda-forge

The following packages will be UPDATED:

    libnetcdf: 4.4.1.1-10   conda-forge --> 4.5.0-3      conda-forge

`The following packages will be DOWNGRADED:

    gdal:      2.2.4-py35_0 conda-forge --> 2.0.0-py35_1
    libgdal:   2.2.4-0      conda-forge --> 2.0.0-1

Proceed ([y]/n)? y

libnetcdf-4.5. 100% |######################################################################| Time: 0:00:03 642.84 kB/s
libgdal-2.0.0- 100% |######################################################################| Time: 0:00:00  51.29 MB/s
gdal-2.0.0-py3 100% |######################################################################| Time: 0:00:00  53.71 MB/s
netcdf4-1.3.1- 100% |######################################################################| Time: 0:00:01   1.50 MB/s
(python35) root@5c2a36d4d9a3:/# gdalinfo --version
gdalinfo: error while loading shared libraries: libgeos-3.4.2.so: cannot open shared object file: No such file or directory`

**Comment by dopplershift** [comment]
This is probably best reported to conda-forge: https://github.com/conda-forge/netcdf4-feedstock/issues

**Comment by ocefpaf** [comment]
Even though this is an issue for the feedstock here is the gist of it.

Conda is not good at updating. If you try a new env with:

```
conda create --name TEMP --channel conda-forge python=3.6 netcdf4 gdal
```

Everything should be consistent. However, if I force the latest `libnetcdf` like you have there, v4.5.0, with:

```
conda create --name TEMP --channel conda-forge python=3.6 libnetcdf=4.5.0 netcdf4 gdal
```

We will get the right error message (that conda should've give to you in that update):

```
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - gdal
  - libnetcdf=4.5.0
  - python=3.6
Use "conda info <package>" to see the dependencies for each package.
```

The reason is because we don't have `gdal` builds with `libnetcdf 4.5.0`. I'm working on them now.

**Comment by rutgerhofste** [comment]
Much appreciated!
