### ISSUE TITLE
NC_CHAR vs NC_STRING

### ISSUE THREAD

**Issue by sukye** [Unidata/netcdf4-python#806]
I am using netcdf4-python v1.2.2 and wont be able to upgrade in the near future.

How to set an attribute of NC_CHAR? I tried
f.variables[var].setncattr(attr, u"testing")
or
"testing".encode("ascii")
but the data type was still string.

Thanks,
sukye

**Comment by sukye** [comment]
@jswhit

**Comment by jswhit** [comment]
If the attribute is not unicode, v1.2.2 should write it as NC_CHAR.
