### ISSUE TITLE
Empty mask being returned as full mask array 

### ISSUE THREAD

**Issue by davidhassell** [Unidata/netcdf4-python#808]
Hello,

Since `v1.4`, the code at https://github.com/Unidata/netcdf4-python/blob/master/netCDF4/_netCDF4.pyx#L4293-L4298 suggests that when there are no masked elements, the mask of the variable's numpy array should be of type `numpy.bool_`, via the setting of `mask=False`. 

This is not what I'm seeing, though:

```
import netCDF4, numpy

print netCDF4.__version__, numpy.__version__

n = netCDF4.Dataset('test1.nc', 'w')

x = n.createDimension('x', 4)
y = n.createDimension('y', 3)

var = n.createVariable('var', 'f8', ('y', 'x'))
var.units = "metre"
var[...] = numpy.arange(12)

n.close()

n2 = netCDF4.Dataset('test1.nc', 'r')
print repr(n2.variables['var'][...])
```
Outputs:
```
1.4.0 1.13.3
masked_array(data =
 [[0.0 1.0 2.0 3.0]
 [4.0 5.0 6.0 7.0]
 [8.0 9.0 10.0 11.0]],
             mask =
 [[False False False False]
 [False False False False]
 [False False False False]],
       fill_value = 9.96920996839e+36)
```
i.e. a full mask of type `numpy.ndarray` full of Falses.

Compared with:
```
In [2]: numpy.ma.arange(12).reshape(3, 4)
Out[2]: 
masked_array(data =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]],
             mask =
 False,
       fill_value = 999999)
```
Am I expecting correctly? and if so, am I doing something wrong, or is the code not behaving?

Many thanks for you help,

David

**Comment by jswhit** [comment]
I would have expected the array to have a boolean False mask, not a ndarray mask full of Falses.

However, it looks like if I leave out ``mask=False``, the mask will be type `np.bool_`.  Is there a particular reason to prefer this behavior?  If so, I'll go ahead and make a pull request.

**Comment by davidhassell** [comment]
The reason is to save on memory - a float32 array with a full mask of `False`s is 25% larger than it needs to be. Also performance - on my laptop it is 40x faster to test for any masked points if the mask is `numpy.bool_`:

**Comment by davidhassell** [comment]
```
In [20]: z = numpy.ones((1000000,))

In [21]: a = numpy.ma.array(z, mask=False)

In [22]: b = numpy.ma.array(z)

In [23]: %timeit a.mask.any()
The slowest run took 6.72 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 41.4 µs per loop

In [24]: %timeit b.mask.any()
The slowest run took 46.96 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.77 µs per loop
```

**Comment by jswhit** [comment]
pull request #818 fixes this, but introduces a cftime-related test failure.  cftime pull request #55 fixes this test failure.
