### ISSUE TITLE
Use of masked arrays comes with huge performance drop

### ISSUE THREAD

**Issue by fmaussion** [Unidata/netcdf4-python#809]
The change included in https://github.com/Unidata/netcdf4-python/pull/787 made our test suite run in two hours instead of a couple of minutes.

I am not well placed to judge whether this was a good change or not, but I spent several hours in finding out what was going on. <s>It would be great if these changes were documented somewhere, i.e. in a "what's new section" or similar.</s> EDIT: just discovered the ``Changelog``. Still, a link to it in the html documentation would be of great help.

Right now this makes v1.4 unusable for us: is there a way to ``set_auto_mask`` to False globally?

**Comment by fmaussion** [comment]
An example with indexing:

```python
import numpy as np
import time

a = np.linspace(0, 100, 2000)
ma = np.ma.array(a)

ids = np.arange(1000, 1500)

%timeit a[ids]
631 ns ± 13.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

%timeit ma[ids]
14.3 µs ± 188 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

**Comment by davidhassell** [comment]
I, too, have been anecdotally concerned about this aspect of performance, but haven't got round to properly testing it in my code; so thanks for raising this.

An option to produce the pre-1.4 behaviour- i.e. return non-masked numpy arrays when there are no elements of fillValue, and masked numpy arrays when there are - would be great for me.

Something like `set_dynamic_mask`, perhaps? This would default to `False`, meaning the default 1.4 behaviour, or could be set to `True` for the pre-1.4 behaviour.

Thanks, David

**Comment by davidhassell** [comment]
... if this is of interest, I'd be happy to create pull request with some new code ....

**Comment by fmaussion** [comment]
I can't imagine that the majority of users will be happy with the current 1.4 behavior. Masked arrays are a not well understood part of numpy, beginners have troubles with them, and they come with a huge performance loss (factor 20 in the indexing example above). What's going to happen is that most users will set the masking to false per default, or wrap their own ``Dataset`` with this as default (this what we will probably do instead of enforcing netCDF v1.3).

I wonder if the path isn't to go through a painful (but rewarding on long term) deprecation of the pre 1.4 behavior: set ``auto_mask`` to ``False`` per default...

**Comment by jswhit** [comment]
You can turn auto-masking off globally using the set_auto_mask Dataset method.

I think there are only two choices that make sense - always return masked arrays or always return numpy arrays.

**Comment by jswhit** [comment]
There was a lot of discussion [here](https://github.com/Unidata/netcdf4-python/issues/785) about changing to the new behaviour (always returning masked arrays).  The basic problem was that users could not predict what they were going to get (a numpy.ma or a numpy.ndarray), and this is generally considered bad API design.

**Comment by davidhassell** [comment]
OK, but I don't think that we would be breaking anything if we gave users who don't mind what they get the option of specifying that behaviour.

**Comment by akrherz** [comment]
@davidhassell you are asking for an attribute set at the module level to define this behavior and not just at the `Dataset` object?  The latter already exists.

**Comment by davidhassell** [comment]
At the `Dataset` level is what I have in mind. How can you do it? `set_auto_mask` is not the right method, as setting that to `True` will never return masked arrays ....

**Comment by jswhit** [comment]
Re-enabling the old behavior with a Dataset method would be fine, please do submit a pull request.

**Comment by davidhassell** [comment]
Proposed fix in pull request #???

This pull request introduces a new method `set_auto_array_type` on both the `Dataset` and `Variable` classes with unit tests:

**Comment by davidhassell** [comment]
```

**Comment by davidhassell** [comment]
Pull request to optionally re-enable old behaviour: #816

This introduce a new method `set_auto_array_type` on both `Dataset` and `Variable`. The signature is:
```
  
    def set_auto_array_type(self,array_type):
        """
**`set_auto_array_type(self,array_type)`**

turn on or off conversion of data without missing values to regular
numpy arrays.

If `array_type` is set to `True` then a masked array with no missing
values is converted to a regular numpy array.

The default value of `array_type` is `False` (conversions are not
performed). 
        """
```

**Comment by jswhit** [comment]
Hopefully, a more efficient method for dealing with missing values will soon be implemented in numpy.  It's been under discussion for at least 7 years (https://docs.scipy.org/doc/numpy-1.14.5/neps/missing-data.html#missing-values-as-seen-in-python)

**Comment by jswhit** [comment]
We could also add an option for converting missing values to NaNs (I believe this is what Pandas and Xarray do).  Matplotlib knows to skip NaNs, and there is some support for NaNs in numpy (numpy.nanmean, numpy.nanvar etc)

**Comment by fmaussion** [comment]
> We could also add an option for converting missing values to NaNs (I believe this is what Pandas and Xarray do)

Yes, but only for floats of course. The question about what to do with missing values in non-float arrays is a frequent discussion point at xarray.

**Comment by jswhit** [comment]
`set_always_mask` method added by pull request #816  to enable previous behavior (thanks @davidhassell).  Closing now...

**Comment by bekozi** [comment]
`set_always_mask` does not seem to work with `MFDataset`:
```
File "netCDF4/_netCDF4.pyx", line 2884, in netCDF4._netCDF4.Dataset.set_always_mask
AttributeError: 'NoneType' object has no attribute 'values'
```
I didn't notice an open issue for this. Should this theoretically work and needs a patch?

**Comment by jswhit** [comment]
Yes, that needs to be added.  It's definitely a bug - I will create a PR.

**Comment by jswhit** [comment]
pull request #855

**Comment by bekozi** [comment]
Works! Thanks @jswhit.
