### ISSUE TITLE
bdist_msi error: "I don't know what to do with 'runtime_library_dirs': . . . . error:don't know how to set runtime library search path for MSVC++

### ISSUE THREAD

**Issue by dopplershift** [Unidata/netcdf4-python#81]
_From [philmore...@gmail.com](https://code.google.com/u/112145785508273726610/) on March 25, 2011 20:56:06_

What steps will reproduce the problem? 1. Try to build netCDF4-0.9.x on Python 2.6.x
2. On Windows XP 32-bit use 'python setup.py bdist_msi' 3. What is the expected output? What do you see instead? I expect to produce an msi installer. Instead, I get the error message:bdist_msi error: "I don't know what to do with 'runtime_library_dirs': [my library dirs here] error: don't know how to set runtime library search path for MSVC++ What version of the product are you using? On what operating system? Windows XP 32-bit
netcdf-4.1.1 (source and win32 binaries)
hdf5-1.8.5 patch 1
szip
zlib 1.2.5
Microsoft Visual Studio 2008
Python 2.6.6 (also tried with version 2.6.2) Please provide any additional information below. Ultimately, what I'm going for is a an msi installer built on Python 2.6.2 (it's a long story...mostly explained here: http://resources.arcgis.com/content/kbase?fa=articleShow&d=37767 )

The netCDF4 Windows installers > 0.9.1 hosted on code.google.com have never worked for me.

_Original issue: http://code.google.com/p/netcdf4-python/issues/detail?id=81_

**Comment by abhishekpandey07** [comment]
How did you fix it?
