### ISSUE TITLE
Error reading IDs for variable in new file

### ISSUE THREAD

**Issue by epennington** [Unidata/netcdf4-python#815]
Hi,
I'm trying to combine multiple netCDF files into a single netCDF file (using the attached script, edit_ncf.py), but they have different variables and dimensions. I want to put all variables in the new file, and if 2+ of the existing files have the same variable, then add the values together. All of the input files are on the same horizontal grid, but have different numbers of vertical layers. I want the output file to have the maximum number of layers, 18. If an input file has fewer than 18 layers, I create a new array with 18 layers and fill in the missing values with zeroes, so that I can add all the arrays together to put in the output file. The script works (the output netcdf file is attached, emis2012202.ncf) and the output file can be read, but when I try to use the file as an input to another program (CMAQ), I get the following error:

 *** ERROR ABORT in subroutine OPEMIS on PE 037
     Could not open EMIS_1           file
     Date and time 8:00:00   July 20, 2012  (2012202:080000)
 PM3EXIT:  DTBUF 8:00:00   July 20, 2012
ncvarid: ncid 1441792: NetCDF: Variable not found
     Error reading IDs for  variable TFLAG     CO
     netCDF error number  -49  processing file "EMIS_1"
     NetCDF: Variable not found

EMIS_1 is emis_2012202.ncf and it's start time is 08:00:00. TFLAG is the timeseries variable and CO is one of the other variables (out of 72 total). I'm using Python 2.7.

I know that variables have IDs and that they change each time the file is opened, so I
'm not sure how to deal with defining or extracting the IDs. Any help is appreciated.

[edit_ncf.txt](https://github.com/Unidata/netcdf4-python/files/2181773/edit_ncf.txt)

**Comment by jswhit** [comment]
Can CMAQ read NETCDF4 formatted files?

**Comment by jswhit** [comment]
any update on this?  I
