### ISSUE TITLE
Error renameDimension / renameVariable

### ISSUE THREAD

**Issue by pgamez** [Unidata/netcdf4-python#817]
Hello

When using `renameVariable` after `renameDimension` on a coordinate, all the values from the variable are removed.

Here is a code that could reproduce the problem (version 1.4.0):

```python
#!/usr/bin/env python3

import netCDF4 as nc

with nc.Dataset('test.nc', 'w') as fp:
    fp.createDimension('x', 3)
    ncvar = fp.createVariable('x', float, ('x',))
    ncvar[:] = [1.1, 2.2, 3.3]

with nc.Dataset('test.nc', 'r+') as fp:
    fp.renameDimension('x', 'lon')
    fp.renameVariable('x', 'lon')
```

I expect a variable `lon` with values `[1.1, 2.2, 3.3]`. However, the result is this:

```
$ ncdump test.nc
netcdf test {
dimensions:
	lon = 3 ;
variables:
	double lon(lon) ;
data:

 lon = _, _, _ ;
}
```

This problem doesn't happens when executing *first* `renameVariable` and *then* `renameDimension`

Greetings,

Pedro

**Comment by jswhit** [comment]
In your case, the variable is also a dimension - so I think it makes sense that you have to rename the variable before renaming the dimension.  This is because the dimension information is attached to the variable, if you change the the dimension name first you are breaking this connection.

**Comment by pgamez** [comment]
OK Jeff, thank you! I didn't have that information...
Pedro
