### ISSUE TITLE
Read data for certain days (datetime)

### ISSUE THREAD

**Issue by ameanijon** [Unidata/netcdf4-python#819]
Let's say I have a dataset composed of 4 readings per day, for every day of the month.

I have used num2date to turn these into understandable dates and times, but if I wanted to obtain data from 1 specific time of 1 day, how could I go about this?

For example, if I wanted to find the temperature for the first timestep, I could use `time[0]`, but it's not so easy when you want a specific value from the middle of the month.

Is there a way to get this data using datetime?

**Comment by jthielen** [comment]
Would the [`date2index`](http://unidata.github.io/netcdf4-python/#netCDF4.date2index) function get you what you would need? 

Another possibility, if you are willing to go with a higher-level package, is using [`xarray`](http://xarray.pydata.org/en/stable/), which makes this kind of label-based selection fairly straightforward.

**Comment by ameanijon** [comment]
@jthielen thank you! Solved using: `xarraydataset.variable.loc['1979-01-01':'1980-01-01']`
