### ISSUE TITLE
`enum_dict` not saved after updating

### ISSUE THREAD

**Issue by npow** [Unidata/netcdf4-python#821]
I noticed that `enum_dict` (either from `Variable` or `EnumType` isn't persisted after being updated. Is this a bug, or enum types aren't supposed to be changed? I'm able to add new enums to `enum_dict` and it does seem to work, except that the `enum_dict` isn't persisted (but the new values in the variable are).

```
>>> ds['item'].datatype
<class 'netCDF4._netCDF4.EnumType'>: name = '_', numpy dtype = uint32, fields/values ={'_': 0}
>>> ds['item'].datatype.enum_dict
{'_': 0}
>>> ds['item'][0]
0
>>> ds['item'][0]=1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netCDF4/_netCDF4.pyx", line 4188, in netCDF4._netCDF4.Variable.__setitem__
ValueError: trying to assign illegal value to Enum variable
>>> ds['item'].datatype.enum_dict['foo']=1
>>> ds['item'][0]=1
>>> ds['item'][0]
1
```

**Comment by jswhit** [comment]
The enum dict attribute s created when the EnumType is created.  Modifying it afterward has no effect - you have to create a new EnumType.
