### ISSUE TITLE
Error: attribute has unsupported datatype

### ISSUE THREAD

**Issue by PaulHuwe** [Unidata/netcdf4-python#822]
I have an issue using the NetCDF4 python library to read the variable attributes from the following file: https://oco2.gesdisc.eosdis.nasa.gov/data/s4pa/OCO2_DATA/OCO2_L2_Lite_FP.8r/2018/oco2_LtCO2_180117_B8100r_180221182228s.nc4

As an example, I am trying to read the attributes for the variable vertex_longitude. (It fails for the rest, as well.) When I use the latest netCDF4 python in conda (1.4.0), I get:

>>> print dataset.variables['vertex_longitude']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netCDF4.pyx", line 2302, in netCDF4.Variable.__str__ (netCDF4.c:25699)
  File "netCDF4.pyx", line 2307, in netCDF4.Variable.__unicode__ (netCDF4.c:25941)
  File "netCDF4.pyx", line 2426, in netCDF4.Variable.getncattr (netCDF4.c:27513)
  File "netCDF4.pyx", line 934, in netCDF4._get_att (netCDF4.c:12165)
KeyError: 'attribute units has unsupported datatype

This is surprising given that when I use the ncdump in conda, I see the attributes fine:

>/opt/anaconda/bin/ncdump -h copy.nc4 | grep vertex_longitude
        float vertex_longitude(sounding_id, vertices) ;
                string vertex_longitude:units = "degrees_east" ;
                string vertex_longitude:long_name = "vertex_longitude" ;
                vertex_longitude:missing_value = -999999.f ;
                string vertex_longitude:comment = "corner longitudes of the measurement FOV" ;

When I h5dump this variable, I see:

/opt/anaconda/bin/h5dump -A -d /vertex_longitude oco2_LtCO2_180117_B8100r_180221182228s.nc4
HDF5 "oco2_LtCO2_180117_B8100r_180221182228s.nc4" {
DATASET "/vertex_longitude" {
   DATATYPE  H5T_IEEE_F32LE
   DATASPACE  SIMPLE { ( 193218, 4 ) / ( 193218, 4 ) }
   ATTRIBUTE "DIMENSION_LIST" {
      DATATYPE  H5T_VLEN { H5T_REFERENCE { H5T_STD_REF_OBJECT }}
      DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
      DATA {
      (0): (DATASET 7216 /sounding_id ), (DATASET 8414 /vertices )
      }
   }
   ATTRIBUTE "comment" {
      DATATYPE  H5T_STRING {
         STRSIZE H5T_VARIABLE;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
      DATA {
      (0): "corner longitudes of the measurement FOV"
      }
   }
   ATTRIBUTE "long_name" {
      DATATYPE  H5T_STRING {
         STRSIZE H5T_VARIABLE;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
      DATA {
      (0): "vertex_longitude"
      }
   }
   ATTRIBUTE "missing_value" {
      DATATYPE  H5T_IEEE_F32LE
      DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
      DATA {
      (0): -999999
      }
   }
   ATTRIBUTE "units" {
      DATATYPE  H5T_STRING {
         STRSIZE H5T_VARIABLE;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
      DATA {
      (0): "degrees_east"
      }
   }
}
}

**Comment by jswhit** [comment]
After creating an account, I was able to access the dataset.  However, I can't reproduce the error with github master

```python
>>> print  dataset.variables['vertex_longitude']

<type 'netCDF4._netCDF4.Variable'>
float32 vertex_longitude(sounding_id, vertices)
    units: degrees_east
    long_name: vertex_longitude
    missing_value: -999999.0
    comment: corner longitudes of the measurement FOV
unlimited dimensions:
current shape = (193218, 4)
filling on, default _FillValue of 9.96920996839e+36 used
```

I'll see if I can narrow down which commit since the v1.4.0 release fixed it.

**Comment by jswhit** [comment]
Also works for me with version 1.4.0.

**Comment by PaulHuwe** [comment]
Strange - could it a problem with the release in conda? The info I see is:

>/opt/anaconda/bin/pip show NetCDF4
---
Metadata-Version: 1.1
Name: netCDF4
Version: 1.4.0
Summary: Provides an object-oriented python interface to the netCDF version 4 library.
Home-page: http://github.com/Unidata/netcdf4-python
Author: Jeff Whitaker
Author-email: jeffrey.s.whitaker@noaa.gov
License: OSI Approved
Location: /opt/anaconda-2.4.0-3/lib/python2.7/site-packages
Requires: numpy, cftime
Entry-points:
  [console_scripts]
  nc3tonc4 = netCDF4.utils:nc3tonc4
  nc4tonc3 = netCDF4.utils:nc4tonc3
  ncinfo = netCDF4.utils:ncinfo

**Comment by jswhit** [comment]
Are you sure you are actually getting that version when you run the test?  

It could be the versions of HDF5 and netcdf-c that are linked also.  Try running 'checkversion.py' in the netcdf4-python source directory (you'll have to copy that out of the source directory to run it).

**Comment by PaulHuwe** [comment]
Thank you for your help. I ran another pip upgrade, and the issue is now resolved! I am glad it was merely operator error. If you are curious, the results of checkversion.py are:

>/opt/anaconda/bin/python checkversion.py
netcdf4-python version: 1.4.0
HDF5 lib version:       1.8.15
netcdf lib version:     4.3.3.1
numpy version           1.15.0
