### ISSUE TITLE
How to obtain paths for dimensions linked to variables

### ISSUE THREAD

**Issue by PaulHuwe** [Unidata/netcdf4-python#824]
I have an nc4 file with groups (and subgroups) containing variables and dimensions at various levels within the group structure. When I try to obtain the dimensions that a specific variable maps, netcdf4-python only provides the pathless dimension name (and size in a tuple). Is there a way to obtain the dimension name with path, or a link to the dimension object (which I could then use the .group() method on)? 

An example:
netcdf file {
dimensions:
        airs_idx = 143 ;
...
group: AIRS {
  dimensions:
        Cloud = 2 ;
...
  group: RetStd{
    variables:
        float CldFrcStd(airs_idx, Cloud) ;
...
    }
  }
}

When I perform the following in python, I get:
>>> f['/AIRS/RetStd/CldFrcStd'].dimensions
(u'airs_idx', u'Cloud')

When I would like to know that the dimensions are:
(u'/airs_idx', u'/AIRS/Cloud')

Thanks

**Comment by jswhit** [comment]
From https://www.unidata.ucar.edu/software/netcdf/docs/netcdf_data_set_components.html

"Dimensions are scoped such that they can be seen in all descendant groups. That is, dimensions can be shared between variables in different groups, if they are defined in a parent group."

Given this, I'm not sure it makes sense to assign a path to a dimension.  Internally, `netCDF4.utils._find_dim` is used to find a dimension instance the the Group and name, by searching the current group and then traversing it's parents.  I suppose we could expose this function

**Comment by jswhit** [comment]
BTW, here is the code for _find_dim, which actually is accessible, just not documented.

```python
def _find_dim(grp, dimname):
    # find Dimension instance given group and name.
    # look in current group, and parents.
    group = grp
    dim = None
    while 1:
        try:
            dim = group.dimensions[dimname]
            break
        except:
            try:
                group = group.parent
            except:
                raise ValueError("cannot find dimension %s in this group or parent groups" % dimname)
    return dim
```

**Comment by jswhit** [comment]
Perhaps what is needed is a variable method to retrieve the actual dimension objects, not just their names?

**Comment by PaulHuwe** [comment]
I think such a method would both be useful and consistent with the rest of the package.

**Comment by jswhit** [comment]
Pull request #825  adds a `get_dims` Variable method that returns a tuple of dimension objects associated with the Variable.

**Comment by jswhit** [comment]
pull request #825 merged, closing now
