### ISSUE TITLE
NetCDF: file not found

### ISSUE THREAD

**Issue by DanielIAvila** [Unidata/netcdf4-python#826]
Hi, 

I have installed Anaconda3, from here I have installed the required packages for `netcdf4` to run. My code was working properly until yesterday. Today it appears this legend:

>   File "netCDF4\_netCDF4.pyx", line 1733, in netCDF4._netCDF4._ensure_nc_success

>   RuntimeError: NetCDF: file not found

What can I do? I have reinstalled Anaconda3 from scratch and the problem persists. 

Tha packages I have are:
```
cython=0.28.2
hdf4 = 4.2.13
hdf5=1.10.2
libcurl=7.60.00
libnetcdf=4.6.1
netcfd=1.4.0
numpy=1.14.3
```

**Comment by jswhit** [comment]
make sure the file path is correct, and you have permissions to access it

**Comment by DanielIAvila** [comment]
Yeap, I am running it as admin and I have only one path.

**Comment by jswhit** [comment]
That error comes from the C library, so for some reason it can't access the file.  If it's not a filesystem or permission issue I don't know what it could be.

**Comment by jswhit** [comment]
can you access the file with `ncdump`?

**Comment by DanielIAvila** [comment]
I think I solved the problem installing Visual Studio in C:  , I recovered it from here https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145

**Comment by dopplershift** [comment]
From the command line run `ncdump -h myfile.nc`.
