### ISSUE TITLE
FutureWarning when using slice.

### ISSUE THREAD

**Issue by brorfred** [Unidata/netcdf4-python#833]
Dear all,

Numpy recently turned on a deprecation warning for indexing with lists containing None (arr[[None, 0]], https://github.com/numpy/numpy/pull/9686). This seems to be biting netCDF4 when using the 'slice' command. The following code works fine.

    Aarr = np.zeros((100,100))
    aslice = (slice(5,7,-1), slice(5,7))
    Aarr[aslice]

result:

    Out[192]: 
    array([[0., 0.],
           [0., 0.]])

But an analogous case with netCDF4

    #curl -O https://oceandata.sci.gsfc.nasa.gov/cgi/getfile/A20021852018181.L3m_CU_PAR_par_9km.nc

    nc = netCDF4.Dataset("A20021852018181.L3m_CU_PAR_par_9km.nc")
    aslice = (slice(5,7,-1), slice(5,7))
    nc.variables["par"][aslice]

triggers the warning

    /Users/bror/anaconda3/bin/ipython3w:1: FutureWarning: Using a non-tuple sequence for     
    multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this   will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a        
    different result. 

/Bror Jonsson

**Comment by jswhit** [comment]
Confirmed.  Will take some digging to see where this warning is being emitted.
