### ISSUE TITLE
Add option to choose source of global attributes in MFDataset.

### ISSUE THREAD

**Issue by juseg** [Unidata/netcdf4-python#835]
Just a suggestion... Could we add a keyword argument on MFDataset to choose the index (or name) of the file to be used as a master file? Or, the file to pick global attributes from?

I typically use MFDatasets to combine model output from consecutive model runs. When creating an MFDataset instance history is taken from the first run and all subsequent history is lost.

https://github.com/Unidata/netcdf4-python/blob/151ccb357c964ae3512c13b74cc6a11609ff2872/netCDF4/_netCDF4.pyx#L5864

Thanks for considering!

**Comment by jswhit** [comment]
add `master_file` kwarg arg in pull request #837

**Comment by jswhit** [comment]
@juseg, could you please test the pull request and let me know if it works for your use case?

**Comment by juseg** [comment]
@jswhit Thanks very much! It works, but the time coordinate is reordered (starting with the master file, and then all other files in order). Potentially this could be solved by either re-ordering subdatasets by filenames, or adding a separate ``attr_file`` keyword argument or so.

PS. I've noticed that the current behaviour of netCDF4 (using global attributes from the first file) is similar to other tools such as `ncrcat` and `cdo cat`. I realize this is a pure metadata issue but at least in the context of model simulation chains, apparently concatenation systematically discards history.

**Comment by juseg** [comment]
@jswhit Sorry that was a mistake, things work exactly as they should. I think we can close this issue.

```python
import numpy as np
import netCDF4 as nc

# prepare fake data
time = np.arange(1000)
data = time**2

# write to multiple netcdf files
for i in range(10):
    filename = 'ds' + str(i) + '.nc'
    ds = nc.Dataset(filename, 'w', format='NETCDF4_CLASSIC')
    ds.createDimension('time', None)
    ds.createVariable('time', 'i4', ('time',))
    ds.createVariable('data', 'i4', ('time',))
    ds.variables['time'][:] = time[100*i:100*i+100]
    ds.variables['data'][:] = data[100*i:100*i+100]
    ds.history = 'Created ' + filename + '.'
    ds.close()

# open as mfdataset and assert time is increasing
ds = nc.MFDataset('ds?.nc', master_file='ds9.nc')
assert ds.history == 'Created ds9.nc.'
assert np.all(np.diff(ds.variables['time'][:]) > 0)
ds.close()
```

Many thanks!

**Comment by juseg** [comment]
@jswhit I mean after merging the `master_file` branch... Sorry for the mess.
