### ISSUE TITLE
Opendap strided slice is horribly inefficient

### ISSUE THREAD

**Issue by dopplershift** [Unidata/netcdf4-python#838]
So this example code:
```python
import netCDF4

url = ('http://thredds-test.unidata.ucar.edu/thredds/dodsC/'
       'satellite/goes16/GRB16/ABI/CONUS/Channel02/current/'
       'OR_ABI-L1b-RadC-M3C02_G16_s20182341637323_e20182341640096_c20182341640138.nc')

ds = netCDF4.Dataset(url)
values = ds.variables['Rad'][::4,::4]
```
was still chugging after 45 minutes and I restarted my kernel. Changing the `[::4, ::4]` to `[:,:]` resulted in completion after a minute. Based on the TDS logs, the code is making requests for individual grid points, which is just insane. Not sure what's going on here.

This is on 1.4.1 and libnetcdf 4.6.1 from conda-forge.

**Comment by jswhit** [comment]
Does setting `use_nc_get_vars(True)` on the variable before reading the data help at all?

**Comment by akrherz** [comment]
@jswhit Yes.  Setting `use_nc_get_vars(True)` makes the read reasonably fast. python3.5 linux64 netcdf4=1.4.1 libnetcdf=4.6.1 here.

**Comment by jswhit** [comment]
pull request issue #839
