### ISSUE TITLE
unexpected masking based on fill_value magnitude

### ISSUE THREAD

**Issue by barronh** [Unidata/netcdf4-python#840]
This may be a "feature", but I find that variables are masked when value is less/greater than negative/positive fill value. This can be confusing when creating variables from numpy arrays where the default fill value for a 32-bit integer (999999). Using the same fill_value in a Variable results in values being masked if they are greater (less) than or equal to the positive (negative) fill_value. The valid range for 32-bit ints are valid (-2147483648, 2147483647) and there is no valid_range set on the variable.

Code to reproduce:
```
import numpy
import netCDF4

print(numpy.version.version)
print(netCDF4.__version__)
f = netCDF4.Dataset('test.nc', format='NETCDF4_CLASSIC', mode='w')
f.createDimension('TSTEP', None)
tflag = f.createVariable('TFLAG', 'i', ('TSTEP',), fill_value=999999)
tflag[0:24] = 2018156
print(tflag[:])
```

Results
```
1.11.2
1.3.1
[-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --]
```

Thanks

**Comment by jswhit** [comment]
Try updating to 1.4.0 or 1.4.1.  From the Changelog:

* _FillValue is no longer treated as a valid_min/valid_max. This was too surprising, despite the fact the thet netcdf docs attribute best practices suggests that clients should to this if valid_min, valid_max and valid_range are not set.

**Comment by barronh** [comment]
Sorry, I missed the previous issues (e.g., #748) and now see that it was expected/intended from approach. And that it can be fixed by updating.

Thanks for the fast response!
