### ISSUE TITLE
netCDF4 should error when assigning multi-dimensional arrays as attributes

### ISSUE THREAD

**Issue by shoyer** [Unidata/netcdf4-python#841]
Right now, they are silently flattened:
```
In [13]: import netCDF4

In [14]: with netCDF4.Dataset('testing.nc', 'w') as nc:
    ...:     nc.foo = ['multi', 'dimensional']
    ...:     nc.bar = [[1, 2], [3, 4]]
    ...:

In [15]: with netCDF4.Dataset('testing.nc') as nc:
    ...:     print(nc.foo)
    ...:     print(nc.bar)
    ...:
multidimensional
[1 2 3 4]
```

This was reported downstream by an xarray user: https://github.com/pydata/xarray/issues/2251

**Comment by jswhit** [comment]
I hope no one is depending on this behavior.  Maybe we should issue a FutureWarning instead, and change it to ValueError in the next release.

**Comment by jswhit** [comment]
Note that `nc.foo = ['multi', 'dimensional']` produces `[u'multi', u'dimensional']` in master, so this PR will have no affect for this case.  However `nc.foo = [['multi'], ['dimensional']]` will now raise a `ValueError`.

**Comment by shoyer** [comment]
A FutureWarning sounds like a good choice for now.

**Comment by jswhit** [comment]
changed pull request #842  to FutureWarning

**Comment by jswhit** [comment]
pull request #824 merged.  FutureWarning will change to ValueError after 1.4.2/
