### ISSUE TITLE
python netcdf4 basemap scale/offset values and acces

### ISSUE THREAD

**Issue by aponivi** [Unidata/netcdf4-python#843]
Hello,
Sorry upfront, I am a bit of a newbee... i have following issue. 
I have an ERA20c file and try to visualize it with python. The netCDF4 library is reading the temperatur correctly, scaling and offsetting it! However the geopotential at 850hpa and 500hpa have approximately the same values (and wrong ones too). If I scale and offset the 500hPa it turns out correctly. But the 850hPa still is wrong... can anybody tell me: 
1. Is the scale factor and add_offset for every sub-variable different?
2. How can I acces these 2 factors, meaning, how can I automatically get the value and print use it with the netcdf4 library?

**Comment by jswhit** [comment]
the are variable attributes, so just print `z850.scale_factor` and `z500.add_offset`.

**Comment by jswhit** [comment]
I just downloaded some geopotential height data at 850 and 500 hPa from the ERA intertim web site at ECMWF.  Here's what I get

```python
>>> from netCDF4 import Dataset
nc = Dataset('Bm>>> nc = Dataset('_grib2netcdf-atls01-a562cefde8a29a7288fa0b8b7f9413f7-sBxSsn.nc')
>>> print nc
<type 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_64BIT_OFFSET data model, file format NETCDF3):
    Conventions: CF-1.6
    history: 2018-09-03 16:10:45 GMT by grib_to_netcdf-2.8.0: grib_to_netcdf /data/data03/scratch/a6/b2/_mars-atls01-98f536083ae965b31b0d04811be6f4c6-RTSUkB.grib -o /data/data04/scratch/a8/0b/_grib2netcdf-atls01-a562cefde8a29a7288fa0b8b7f9413f7-sBxSsn.nc -utime
    dimensions(sizes): longitude(480), latitude(241), level(2), time(31)
    variables(dimensions): float32 longitude(longitude), float32 latitude(latitude), int32 level(level), int32 time(time), int16 z(time,level,latitude,longitude), int16 t(time,level,latitude,longitude), int16 d(time,level,latitude,longitude)
    groups:

>>> zdata = nc['z'][:]
>>> levels = nc['level'][:]
>>> zdata.shape
(31, 2, 241, 480)
>>> levels
masked_array(data=[500, 850],
             mask=False,
       fill_value=999999,
            dtype=int32)
>>> z500 = zdata[:,0,...]
>>> z500.min(), z500.max()
(45519.836673770275, 58445.4921875)
>>> z850 = zdata[:,1,...]
>>> z850.min(), z850.max()
(8489.312500000004, 16979.87342898807)
>>> print nc['z'].scale_factor, nc['z'].add_offset
0.7623057038057162 33467.0211908981
```

which seems reasonable to me given that the data in geopotential (not geopotential height).

**Comment by aponivi** [comment]
Hi Jeff... It all works great now... Made the mistake with the arrays! But thanks for the tip, with the getattr() it works great!

Am 03.09.2018 6:18 nachm. schrieb Jeff Whitaker <notifications@github.com>:

I just downloaded some geopotential height data at 850 and 500 hPa from the ERA intertim web site at ECMWF. Here's what I get

>>> from netCDF4 import Dataset
nc = Dataset('Bm>>> nc = Dataset('_grib2netcdf-atls01-a562cefde8a29a7288fa0b8b7f9413f7-sBxSsn.nc')
>>> print nc
<type 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_64BIT_OFFSET data model, file format NETCDF3):
    Conventions: CF-1.6
    history: 2018-09-03 16:10:45 GMT by grib_to_netcdf-2.8.0: grib_to_netcdf /data/data03/scratch/a6/b2/_mars-atls01-98f536083ae965b31b0d04811be6f4c6-RTSUkB.grib -o /data/data04/scratch/a8/0b/_grib2netcdf-atls01-a562cefde8a29a7288fa0b8b7f9413f7-sBxSsn.nc -utime
    dimensions(sizes): longitude(480), latitude(241), level(2), time(31)
    variables(dimensions): float32 longitude(longitude), float32 latitude(latitude), int32 level(level), int32 time(time), int16 z(time,level,latitude,longitude), int16 t(time,level,latitude,longitude), int16 d(time,level,latitude,longitude)
    groups:

>>> zdata = nc['z'][:]
>>> levels = nc['level'][:]
>>> zdata.shape
(31, 2, 241, 480)
>>> levels
masked_array(data=[500, 850],
             mask=False,
       fill_value=999999,
            dtype=int32)
>>> z500 = zdata[:,0,...]
>>> z500.min(), z500.max()
(45519.836673770275, 58445.4921875)
>>> z850 = zdata[:,1,...]
>>> z850.min(), z850.max()
(8489.312500000004, 16979.87342898807)
>>> print nc['z'].scale_factor, nc['z'].add_offset
0.7623057038057162 33467.0211908981

which seems reasonable to me given that the data in geopotential (not geopotential height).
