### ISSUE TITLE
installing netcdf4 with conda in parallel mode

### ISSUE THREAD

**Issue by carlestena** [Unidata/netcdf4-python#845]
I'm having that error while trying to run my job when installing netcdf4 using conda:
ValueError: parallel mode requires MPI enabled netcdf-c

my yml file is using that (and more much libraries)
channels:
  - conda-forge

dependencies:
  - python = 2
  - numpy
  - netcdf4 >= 1.3.1

So, Have I to add --enable-parallel in somewhere? 
Will I have the same problem with HDF5?

**Comment by jswhit** [comment]
You have to build the netcdf-c and hdf5 libraries with MPI enabled (see https://www.unidata.ucar.edu/software/netcdf/docs/getting_and_building_netcdf.html#build_parallel).

**Comment by carlestena** [comment]
Thanks @jswhit. 
I know how to install HDF5 and NEtCDF4-C in bash, but not using conda. Is to make easier the installation of my future package

**Comment by jswhit** [comment]
I don't either.  There may already be a conda hdf5-parallel package already though (https://anaconda.org/spectralDNS/hdf5-parallel)

**Comment by carlestena** [comment]
I've already tried to use hdf5-parallel and libnetcdf-parallel.

But I cannot tested it because I have another dependency:
esmpy[version='>=7.1.0r'] -> esmf==7.1.0r -> hdf5[version='>=1.10.2,<1.10.3.0a0']

and the hdf5-parallel is <= 1.8.17

**Comment by lanougue** [comment]
As a temporary work around, using conda, I downgraded netcdf4 to version 1.2.4. which seems to be linked to parallel libraries. As a side-effect, this also downgrade numpy.
You can still check if it still match your dependencies.

**Comment by carlestena** [comment]
But i thought that parallel netcdf starts at 1.3.1 version

**Comment by jswhit** [comment]
hope you got this straightened out, closing now...
