### ISSUE TITLE
Problem with masked array logic in char variable types

### ISSUE THREAD

**Issue by kmpaul** [Unidata/netcdf4-python#850]
I just found a problem with some of my tools that can only be described as a problem seemingly stemming from the new masked array return value types for all variables.

In my test case, admittedly, I have a corner case.  I have a zero-length `char` variable (or a `char` constant), and I am trying to simply read the value from one file and then write it to another file.  I can detect that the variable has a shape of (), so it is a constant, but the read-value from the file is  `numpy.ma.masked`.  When I try to write this value to the second file directly, I get an error.  (See below)

```python
In [2]: import netCDF4 as nc

In [3]: f = nc.Dataset('test.nc', 'w')

In [4]: a = f.createVariable('a', 'c', ())

In [5]: a
Out[5]: 
<type 'netCDF4._netCDF4.Variable'>
|S1 a()
unlimited dimensions: 
current shape = ()
filling on, default _FillValue of  used

In [6]: a[:]
Out[6]: masked

In [7]: a[:] = ''

In [8]: a[:]
Out[8]: masked

In [9]: import numpy as np

In [10]: a[:] = np.ma.masked
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-b25f83f0055a> in <module>()
----> 1 a[:] = np.ma.masked

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Variable.__setitem__()

/Users/kpaul/Software/miniconda3/envs/conform/lib/python2.7/site-packages/numpy/ma/core.pyc in filled(self, fill_value)
   3705             fill_value = self.fill_value
   3706         else:
-> 3707             fill_value = _check_fill_value(fill_value, self.dtype)
   3708 
   3709         if self is masked_singleton:

/Users/kpaul/Software/miniconda3/envs/conform/lib/python2.7/site-packages/numpy/ma/core.pyc in _check_fill_value(fill_value, ndtype)
    470         if isinstance(fill_value, basestring) and (ndtype.char not in 'OSVU'):
    471             err_msg = "Cannot set fill value of string with array of dtype %s"
--> 472             raise TypeError(err_msg % ndtype)
    473         else:
    474             # In case we want to convert 1e20 to int.

TypeError: Cannot set fill value of string with array of dtype float64
```

It seems to me that you should be able to read the value from one file and write it directly to another file, as long as the shape and datatype are the same.

Is there a way to do this without error?  Or is this to be considered a bug?

**Comment by kmpaul** [comment]
Good to know!  How is the PR coming along?  Is there a timeline?

**Comment by jswhit** [comment]
I just created it.  If you can test it and verify that it works for you I will merge.

**Comment by jswhit** [comment]
Pull request #852 merged, closing now
