### ISSUE TITLE
Mysterious interaction with rasterio

### ISSUE THREAD

**Issue by howff** [Unidata/netcdf4-python#860]
Hi. When netcdf4 is installed alongside rasterio (latest versions via pip) I get the error below trying to open a netcdf4 file. I can't work out what's causing it, any suggestions?

```
File "/opr/pytroll/lib/python3.5/site-packages/xarray/backends/netCDF4_.py", line 247, in _open_netcdf4_group
    ds = nc4.Dataset(filename, mode=mode, **kwargs)
  File "netCDF4/_netCDF4.pyx", line 2135, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1752, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'OR_ABI-L1b-RadF-M3C11_G16_s20183170600346_e20183170611112_c20183170611167.nc'
Exception ignored in: <bound method NC_ABI_L1B.__del__ of <NC_ABI_L1B: 'OR_ABI-L1b-RadF-M3C11_G16_s20183170600346_e20183170611112_c20183170611167.nc'>>
Traceback (most recent call last):
  File "/opr/pytroll/lib/python3.5/site-packages/satpy/readers/abi_l1b.py", line 213, in __del__
    self.nc.close()
AttributeError: 'NC_ABI_L1B' object has no attribute 'nc'
```

**Comment by howff** [comment]
Hi, it's ubuntu 14.04.5, packages installed via pip. I have discovered that the order of the "import" statements seems to affect it so if netCDF4 is imported first the error disappears. Does the error message mean anything to you?

**Comment by jswhit** [comment]
Sorry, I have no idea.   Have you reported this to the rasterio team?  The  error is coming from that library.

**Comment by howff** [comment]
Sorry I must have misunderstood the error message and thought it came from the netcdf4 library.
