### ISSUE TITLE
More meaningful messages for beginners

### ISSUE THREAD

**Issue by mathiasbockwoldt** [Unidata/netcdf4-python#873]
When invoking `ncinfo` without any parameters, the following error message is emitted:

```
Traceback (most recent call last):
  File "/usr/local/bin/ncinfo", line 11, in <module>
    sys.exit(ncinfo())
  File "/usr/local/lib/python3.6/dist-packages/netCDF4/utils.py", line 517, in ncinfo
    filename = pargs[-1]
IndexError: list index out of range
```

It would be much more helpful if the help text would be printed instead. It would also be nice if not only `-h` but also `--help` would print the help text without error message.

**Comment by jswhit** [comment]
Fixed now, thanks for the suggestion
