### ISSUE TITLE
Issue with install not sure as to why

### ISSUE THREAD

**Issue by rachelglenn** [Unidata/netcdf4-python#876]
**Hi I am doing an offline installation. I followed the instructions online and used all recommended versions. I set the environmental variables for  hdf5, netCDF4, hdf4, szip, jpeg, curl, mpi, and zlib before doing pipinstall. I set USE_NCCONFIG=0 and USE_SETUPCFG=0. I worked for days trying to get the install to work correctly.

Instructions: http://unidata.github.io/netcdf4-python/**

>>> xarray.open_dataset('wind-global.nc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda3/lib/python3.6/site-packages/xarray/backends/api.py", line 320, in open_dataset
    **backend_kwargs)
  File "/home/anaconda3/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 332, in open
    ds = opener()
  File "/home/anaconda3/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 231, in _open_netcdf4_group
    ds = nc4.Dataset(filename, mode=mode, **kwargs)
  File "netCDF4/_netCDF4.pyx", line 2135, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1752, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -51] NetCDF: Unknown file format: b'/home/Desktop/Software2/examples/wind-global.nc'

Any ideas to help me understand why netCDF4 is not working?

**Comment by dopplershift** [comment]
Are you able to post your datafile (`wind-global.nc`) somewhere that we can try to replicate? That way we can verify that the file is not the problem.

**Comment by rachelglenn** [comment]
Thank you so much for the quick response.

Yes. I checked that everything works for an online install. I need to install it for an offline--Download the tar files and install them manually. 

Here is the URL for the file:
https://github.com/benbovy/xvelmap/raw/master/notebooks/wind-global.nc

**Comment by rachelglenn** [comment]
Hi I tried to import the file directly.
from netCDF4 import Dataset
Dataset('wind-global.nc')
This was the output: ( I have netcdf4-c 4.6.2 installed)


Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.10.3, library is 1.10.2
	    SUMMARY OF THE HDF5 CONFIGURATION
	    =================================

General Information:
-------------------
                   HDF5 Version: 1.10.2
                  Configured on: Wed May  9 23:24:59 UTC 2018
                  Configured by: root@19a5a2e5-30a4-45db-5607-0c407004981e
                    Host system: x86_64-conda_cos6-linux-gnu
              Uname information: Linux 19a5a2e5-30a4-45db-5607-0c407004981e 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
                       Byte sex: little-endian
             Installation point: /home/heart/anaconda3

Compiling Options:
------------------
                     Build Mode: production
              Debugging Symbols: no
                        Asserts: no
                      Profiling: no
             Optimization Level: high

Linking Options:
----------------
                      Libraries: static, shared
  Statically Linked Executables: 
                        LDFLAGS: -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/heart/anaconda3/lib -L/home/heart/anaconda3/lib
                     H5_LDFLAGS: 
                     AM_LDFLAGS:  -L/home/heart/anaconda3/lib
                Extra libraries: -lrt -lpthread -lz -ldl -lm 
                       Archiver: /tmp/build/80754af9/hdf5_1525908201964/_build_env/bin/x86_64-conda_cos6-linux-gnu-ar
                       AR_FLAGS: cr
                         Ranlib: /tmp/build/80754af9/hdf5_1525908201964/_build_env/bin/x86_64-conda_cos6-linux-gnu-ranlib

Languages:
----------
                              C: yes
                     C Compiler: /tmp/build/80754af9/hdf5_1525908201964/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc
                       CPPFLAGS: -DNDEBUG -D_FORTIFY_SOURCE=2 -O2
                    H5_CPPFLAGS: -D_GNU_SOURCE -D_POSIX_C_SOURCE=200112L   -DNDEBUG -UH5_DEBUG_API
                    AM_CPPFLAGS:  -I/home/heart/anaconda3/include
                        C Flags: -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/heart/anaconda3/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix
                     H5 C Flags:   -std=c99 -pedantic -Wall -Wextra -Wbad-function-cast -Wc++-compat -Wcast-align -Wcast-qual -Wconversion -Wdeclaration-after-statement -Wdisabled-optimization -Wfloat-equal -Wformat=2 -Winit-self -Winvalid-pch -Wmissing-declarations -Wmissing-include-dirs -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wunused-macros -Wunsafe-loop-optimizations -Wwrite-strings -finline-functions -s -Wno-inline -Wno-aggregate-return -Wno-missing-format-attribute -Wno-missing-noreturn -O
                     AM C Flags: 
               Shared C Library: yes
               Static C Library: yes


                        Fortran: yes
               Fortran Compiler: /tmp/build/80754af9/hdf5_1525908201964/_build_env/bin/x86_64-conda_cos6-linux-gnu-gfortran
                  Fortran Flags: 
               H5 Fortran Flags:  -pedantic -Wall -Wextra -Wunderflow -Wimplicit-interface -Wsurprising -Wno-c-binding-type  -s -O2
               AM Fortran Flags: 
         Shared Fortran Library: yes
         Static Fortran Library: yes

                            C++: yes
                   C++ Compiler: /tmp/build/80754af9/hdf5_1525908201964/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++
                      C++ Flags: -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/heart/anaconda3/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix
                   H5 C++ Flags:   -pedantic -Wall -W -Wundef -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Wredundant-decls -Winline -Wsign-promo -Woverloaded-virtual -Wold-style-cast -Weffc++ -Wreorder -Wnon-virtual-dtor -Wctor-dtor-privacy -Wabi -finline-functions -s -O
                   AM C++ Flags: 
             Shared C++ Library: yes
             Static C++ Library: yes

                           Java: no


Features:
---------
                  Parallel HDF5: no
             High-level library: yes
                   Threadsafety: yes
            Default API mapping: v110
 With deprecated public symbols: yes
         I/O filters (external): deflate(zlib)
                            MPE: no
                     Direct VFD: no
                        dmalloc: no
 Packages w/ extra debug output: none
                    API tracing: no
           Using memory checker: yes
Memory allocation sanity checks: no
            Metadata trace file: no
         Function stack tracing: no
      Strict file format checks: no
   Optimization instrumentation: no
Bye...
Aborted (core dumped)

**Comment by rachelglenn** [comment]
Hi I tried to import the file another way.
 from netCDF4 import Dataset
 Dataset('wind-global.nc')
 This was the output: ( I have netcdf4-c 4.6.2 installed)

Warning! HDF5 library version mismatched error
 The HDF5 header files used to compile this application do not match
 the version used by the HDF5 library to which this application is linked.
 Data corruption or segmentation faults may occur if the application continues.
 This can happen when an application was compiled by one version of HDF5 but
 linked with a different version of static or shared HDF5 library.
 You should recompile the application or check your shared library related
 settings such as 'LD_LIBRARY_PATH'.
 You can, at your own risk, disable this warning by setting the environment
 variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
 Setting it to 2 or higher will suppress the warning messages totally.
 Headers are 1.10.3, library is 1.10.2
 SUMMARY OF THE HDF5 CONFIGURATION
 =================================
General Information:
               HDF5 Version: 1.10.2
              Configured on: Wed May  9 23:24:59 UTC 2018
                Host system: x86_64-conda_cos6-linux-gnu

**Comment by jswhit** [comment]
This indicates you have two versions of HDF5 installed on your system, and the linker chose one while the header that was included when the netcdf4-python was built chose the other.

**Comment by rachelglenn** [comment]
I agree. I re-imaged my hard drive and started from scratch with the goal just to get netcdf4-python to work. I was unsuccessful. I am explaining everything that I installed prior. I am on Ubuntu with python 3.6 

Here is the command and the error:

from netCDF4 import Dataset
Dataset('wind-global.nc', 'r',format='NETCDF4')

Traceback (most recent call last):
  File "test", line 2, in <module>
    Dataset('wind-global.nc', 'r',format='NETCDF4')
  File "netCDF4/_netCDF4.pyx", line 2135, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1752, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -51] NetCDF: Unknown file format: b'wind-global.nc'

Here is what I installed and in what order. I included the configure options. 
szip-master.zip
zlib-1.2.10.tar.gz
curl-7.64.0.tar.gz
hdf5-1.10.3.tar.gz
./configure --enable-hl --enable-shared --prefix /usr/local/hdf5 --with-zlib=/usr/local/zlib

m4-1.4.1.tar.gz
jpegsrc.v9b.tar.gz
netcdf-c-4.6.2.tar.gz
CPPFLAGS="-I/usr/local/hdf5/include -I/usr/local/zlib/include" LDFLAGS="-L/usr/local/hdf5/lib -L/usr/local/zlib/lib"  ./configure --enable-netcdf4 --prefix=/usr/local/netcdf4  --enable-shared --disable-dap

cftime-1.0.3.4.tar.gz
netcdf4-python-1.4.2rel.tar.gz

I really appreciate the help.

**Comment by jswhit** [comment]
anaconda python is a much easier way to get started.

**Comment by jswhit** [comment]
Hope you got this straightened out - closing now...
