### ISSUE TITLE
Error: Library not loaded: @rpath/libssl.1.0.0.dylib

### ISSUE THREAD

**Issue by johnwoodill** [Unidata/netcdf4-python#877]
I am receiving the the following error when trying to load the package.

`import netCDF4 as nc`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/john/miniconda3/lib/python3.6/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: dlopen(/Users/john/miniconda3/lib/python3.6/site-packages/netCDF4/_netCDF4.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libssl.1.0.0.dylib
  Referenced from: /Users/john/miniconda3/lib/libssh2.1.dylib
  Reason: image not found
```

**Comment by ocefpaf** [comment]
This does not look like a problem with netcdf4-python. but rather a problem with the conda package you are using. If that package from conda-forge please open an issue at: https://github.com/conda-forge/netcdf4-feedstock/issues

If that is from `defaults` you can contact AnacondaInc.

**Comment by johnwoodill** [comment]
Ok, thanks.
