### ISSUE TITLE
Cannot set int64 attributes when format='NETCDF3_64BIT_DATA'

### ISSUE THREAD

**Issue by randallpittman** [Unidata/netcdf4-python#878]
## Version info:
Tested with netcdf4-python 1.4.2 on Windows 10 with Python 3.7.2

## Steps to reproduce
1. Create a dataset in the CDF-5 format:
```python
ds = netCDF4.Dataset('test.nc', 'w', 'format=NETCDF3_64BIT_DATA')
```
EDIT -- corrected:
```python
ds = netCDF4.Dataset('test.nc', 'w', format='NETCDF3_64BIT_DATA')
```

2. Set an int64 attribute:
```python
ds.setncattr('int64_attr', np.int64(-9223372036854775806))
````
3. Check value and type of attribute:
```python
print(type(ds.int64_attr), ds.int64_attr)
```
Result: `<class 'numpy.int32'> 2`

## Expected result
`ncgen` can create NETCDF3_64BIT_DATA netCDF files with int64 attributes (e.g. using the `LL` suffix in CDL). I did this and opened the created nc file with netcdf4-python and got:
`<class 'numpy.int64'> -9223372036854775806`

## Suspected cause:
`_set_att` only checks the format string for the prefix 'NETCDF3' to determine if int64 attributes are allowed. [Link to code line.](https://github.com/Unidata/netcdf4-python/blob/master/netCDF4/_netCDF4.pyx#L1521)

**Comment by jswhit** [comment]
The following works for me:

```python
from __future__ import print_function
import netCDF4
import numpy as np
ds = netCDF4.Dataset('test.nc', 'w', 'format=NETCDF3_64BIT_DATA')
ds.setncattr('int64_attr', np.int64(-9223372036854775806))
print(type(ds.int64_attr), ds.int64_attr)
```

there are several typos in your example.  I think the most relevant one may be the quotes you have around `format=NETCDF3_64bit_data`.

**Comment by randallpittman** [comment]
Yeah, I'm having a "sometimes works, sometimes doesn't" issue with this... I'll look into it more. The quotes in my example were a typo writing the issue.

**Comment by jswhit** [comment]
Scratch that - the example works if you include that typo but not if you fix it!  (with the quotes it effectively ignores the format kwarg and uses the NETCDF4 format).  Fix is in pull request #881.

**Comment by randallpittman** [comment]
Cool, thanks! I found the problem working on adding the CDF-5 types to [cdlparser](https://github.com/rockdoc/cdlparser).

**Comment by jswhit** [comment]
Fixed now in master, closing ....
