### ISSUE TITLE
NOAA NODC opendap error

### ISSUE THREAD

**Issue by rabernat** [Unidata/netcdf4-python#879]
I am getting an error from netcdf with the following opendap server

```python
import netCDF4
url = 'https://data.nodc.noaa.gov/thredds/dodsC/pathfinder/Version5.2/2004/20040101004519-NODC-L3C_GHRSST-SSTskin-AVHRR_Pathfinder-PFV5.2_NOAA17_G_2004001_night-v02.0-fv02.0.nc'
dset = netCDF4.Dataset(url)
```

```
--------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-4-eeb58969c818> in <module>()
      1 import netCDF4
      2 url = 'https://data.nodc.noaa.gov/thredds/dodsC/pathfinder/Version5.2/2004/20040101004519-NODC-L3C_GHRSST-SSTskin-AVHRR_Pathfinder-PFV5.2_NOAA17_G_2004001_night-v02.0-fv02.0.nc'
----> 3 dset = netCDF4.Dataset(url)
netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__()
netCDF4/_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()
OSError: [Errno -45] NetCDF: Not a valid data type or _FillValue type mismatch: b'https://data.nodc.noaa.gov/thredds/dodsC/pathfinder/Version5.2/2004/20040101004519-NODC-L3C_GHRSST-SSTskin-AVHRR_Pathfinder-PFV5.2_NOAA17_G_2004001_night-v02.0-fv02.0.nc'
```

The data provider (NOAA NODC) is pretty sure there is not problem with the server, and they can't reproduce. I'm using `netCDF4.__version__=='1.4.2'`.

Just opening an issue here to try to sort this out. Can others reproduce?

**Comment by ocefpaf** [comment]
BTW, the problem is in the `netcdf-c` library, see https://github.com/Unidata/netcdf-c/issues/1299

I also experienced this issue in many datasets where I failed to see the problem with the data :-/. For now the workaround is to append `#fillmismatch` to URL.

**Comment by rabernat** [comment]
Thanks @ocefpaf! As usual, you are on top of all the tricky problems! 

I have informed the data provider about this issue. I'm fine if you want to close this. However, as long as this situation persists, it might be worthwhile to figure out how to generate a more informative error.

**Comment by dopplershift** [comment]
Well, the error comes from NetCDF-c, so I don't think there's a lot the python library can do about this. Suggestions to netcdf C are welcome, but the problem is that the error message accurately describes the core problem. It's just not expected that things that used to work no longer do.

At any rate, netcdf-c 4.6.3 should be out shortly and fix this.
