### ISSUE TITLE
xarray/netcdf4/THREDDS extremely slow when using coordinate variable to subset

### ISSUE THREAD

**Issue by tsanah** [Unidata/netcdf4-python#880]
Here is my test code and result.  The problem seems to related the newest version 1.4.2
Instead of get a subset data via opendap,  it creates a new loop of the coordinate  variable (for example lat).   So it creates a lot http access of small data access. 

import xarray as xr
import time
URL ='https://esgf.nccs.nasa.gov/thredds/dodsC/CMIP6.CMIP.NASA-GISS.GISS-E2-1-G.historical.r2i1p1f1.SImon.sithick.gn.sithick.20180827.aggregation.1'
ds = xr.open_dataset(URL)
startc = time.process_time() 
da = ds['sithick'].sel(lat = ds.lat >45)  # seaIce only in the north (this method should be avoided and it is extreamly slow due to a new loop on variable lat)
dt  = da.groupby('time.month', squeeze = False).mean('time') # do the average of the each month over 164 years  
endc = time.process_time() 
print ("cpu time for variable position selection")
print (endc - startc)

xarray                    0.11.2                py37_1000    conda-forge

libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge

netcdf4                   1.4.2            py37h808af73_0  

----------   cpu time  539 seconds  ------------------

xarray                    0.11.3                   py37_0    anaconda

libnetcdf                 4.6.1                h5e45101_3    conda-forge

netcdf4                   1.4.1           py37ha292673_200    conda-forge

----------   cpu time  28 seconds  ------------------

xarray                    0.11.3                   py37_0    anaconda

libnetcdf                 4.6.1                h5e45101_3    conda-forge

netcdf4                   1.4.2            py37h4b4f87f_0  

----------   cpu time  562 seconds  ------------------

xarray                    0.11.2                py37_1000    conda-forge

libnetcdf                 4.6.1                h5e45101_3    conda-forge

netcdf4                   1.4.1           py37ha292673_200    conda-forge

----------   cpu time  31 seconds  ------------------

**Comment by jswhit** [comment]
Probably related to this item in the Changelog:

 * always use nc_get_vars for strided access over OpenDAP (issue #838 ).

I will try backing out this change in master and see how it affects your test.

**Comment by tsanah** [comment]
Hi thanks...  in our case with xarray, 1.4.1 works fine.

**Comment by jswhit** [comment]
There are two variable reads in your example, the one that selects data > 45 degrees latitude and the one that selects monthly averages.  Which one is causing the slowdown for you?

**Comment by jswhit** [comment]
Using your example with netcdf4-python and xarray master (and netcdf-c 4.6.2), I get timings of 1-2 seconds.  Not sure why - perhaps it was https://github.com/Unidata/netcdf4-python/pull/872.

**Comment by tsanah** [comment]
the problem is that using lat > 45 degree with netcdf4(4.6.2) is 30 times slower than using index like [68:90].  However, with netcdf4(4.6.1) these two methods are almost same fast.  I looked at the THREDDS logs and found lat >45 with 4.6.2 create a loop 
*****aggregation.1.dods?sithick.sithick[0][68][0:143] HTTP/1.1" 200 791
*****aggregation.1.dods?sithick.sithick[0][69][0:143] HTTP/1.1" 200 791
That is the reason so slow because it does loop in lat instead of like 
aggregation.1.dods?sithick.sithick[0][68:89][0:143] HTTP/1.1" 200 12888

**Comment by jswhit** [comment]
Can you try updating netcdf4-python to master?  It looks like this may have been fixed by #872.

**Comment by tsanah** [comment]
Wow, I just check the log, the access is a lot more efficient.  Did you use exact the same code that I posted here ?  Can you give me the detail of xarray version and its dependencies ? 
aggregation.1.dods?sithick.sithick[0:12:1979][68:89][0:143] HTTP/1.1" 200 2091098 "oc4.6.2"
aggregation.1.dods?sithick.sithick[1:12:1979][68:89][0:143] HTTP/1.1" 200 2091098 "oc4.6.2"
aggregation.1.dods?sithick.sithick[2:12:1979][68:89][0:143] HTTP/1.1" 200 2091098 "oc4.6.2"
aggregation.1.dods?sithick.sithick[3:12:1979][68:89][0:143] HTTP/1.1" 200 2091098 "oc4.6.2"
aggregation.1.dods?sithick.sithick[4:12:1979][68:89][0:143] HTTP/1.1" 200 2091098 "oc4.6.2"
aggregation.1.dods?sithick.sithick[5:12:1979][68:89][0:143] HTTP/1.1" 200 2091098 "oc4.6.2"
aggregation.1.dods?sithick.sithick[6:12:1979][68:89][0:143] HTTP/1.1" 200 2091098 "oc4.6.2"
aggregation.1.dods?sithick.sithick[7:12:1979][68:89][0:143] HTTP/1.1" 200 2091098 "oc4.6.2"
aggregation.1.dods?sithick.sithick[8:12:1979][68:89][0:143] HTTP/1.1" 200 2091098 "oc4.6.2"
aggregation.1.dods?sithick.sithick[9:12:1979][68:89][0:143] HTTP/1.1" 200 2091098 "oc4.6.2"
aggregation.1.dods?sithick.sithick[10:12:1979][68:89][0:143] HTTP/1.1" 200 2091098 "oc4.6.2"
aggregation.1.dods?sithick.sithick[11:12:1979][68:89][0:143] HTTP/1.1" 200 2091098 "oc4.6.2"

**Comment by tsanah** [comment]
How can I get it from master ?  I installed netcdf4 through anaconda

**Comment by tsanah** [comment]
Ok, I got through git clone, and I just installed the master.
The lat loop problem is resolved.  It takes about 29 seconds.  I checked the log and found it was not as good as the test you run.  The time loop is still there (that was not an issue that I initially complained).  But having seen your test, I would like to make sure that I should have the same result as you did.  Can you tell me what else is different from your test environment ?   Mine 
libnetcdf                 4.6.1                h5e45101_3    conda-forge
netcdf4                   1.4.3                    pypi_0    pypi
xarray                    0.11.2                py37_1000    conda-forge

**Comment by jswhit** [comment]
I used the same code you posted.  netcdf-c 4.6.2, netcdf4-python from github master, xarray from github master.

**Comment by tsanah** [comment]
okay, thanks !  great help !
