### ISSUE TITLE
netdcf4 ValueError: invalid literal for float(): -90.0 ... 90.0

### ISSUE THREAD

**Issue by thaizesb** [Unidata/netcdf4-python#887]
Hello
I'm trying to read a netcdf file using the following code but it's not working

filename = 'CAL_LID_L15_Exp-Beta-V3-30.2015-03-26T13-30-00ZD.nc'
data = Dataset(filename, 'r')
time = data.variables['Profile_UTC_Time'][:].squeeze()
latitude = data.variables['Latitude'][:]
longitude = data.variables['Longitude'][:]

I'm getting this error:

 File "netCDF4/_netCDF4.pyx", line 4098, in netCDF4._netCDF4.Variable.__getitem__
  File "netCDF4/_netCDF4.pyx", line 4244, in netCDF4._netCDF4.Variable._toma
  File "netCDF4/_netCDF4.pyx", line 4391, in netCDF4._netCDF4.Variable._check_safecast
ValueError: invalid literal for float(): -90.0 ... 90.0

I run this code in pc my and it works fine (python 2.7.15, netcdf4 1.4.2)
But when I try to run it on a remote server using anaconda (conda 4.6.4), this problem appears
Does anybody know why? And how I can fix it?

**Comment by jswhit** [comment]
How large is this file?  If it's reasonably small, you can zip or tar it and attach it to this ticket.  Otherwise, please post a link to it so we can have a look.

**Comment by thaizesb** [comment]
Its quite big...but I already solved
I just added: data.set_auto_mask(False) and now it's working!
Thank you very much!

**Comment by jswhit** [comment]
Can you post the output of 'ncdump -h' here?
