### ISSUE TITLE
[Doc] ValueError: parallel mode only works with format=NETCDF4

### ISSUE THREAD

**Issue by gihankarunarathne** [Unidata/netcdf4-python#890]
After going through[ lots of trouble](https://github.com/Unidata/netcdf4-python/issues/883#issuecomment-468947747), I manage to install NetCDF4-Python for Parallel I/O support. It's working fine now.

As document states in [section 8](http://unidata.github.io/netcdf4-python/#section8), reading data from multiple NetCDF files not possible with `NETCDF4` format, but with other formats. Thus, it's trade-off between choosing NETCDF4 for use a single file vs multiple files NETCDF4_CLASSIC format. Also storing data in multiple files become good for parallel access also. Thus my initial design was to use `NETCDF4_CLASSIC`, but need to have parallel access to the files (not only the search).

### Problem:
When I try to create a `NETCDF4_CLASSIC` file with `parallel=True` enabled, it gives me following [error](https://github.com/Unidata/netcdf4-python/blob/master/netCDF4/_netCDF4.pyx#L2111);
```
ValueError: parallel mode only works with format=NETCDF4
```

But this format issue is not mentioned in the document at any of critical places s.t. 
- [Parallel I/O](http://unidata.github.io/netcdf4-python/#section13) 
- [ Dataset.__init__ ](http://unidata.github.io/netcdf4-python/#netCDF4.Dataset.__init__)

#### Questions: 
- If netcdf4-python doesn't support parallel I/O for other formats, then update the above documents ?
- Does that NetCDF4-C library also not support parallel I/O for `NETCDF4_CLASSIC` format ?

I'm using;
```
hdf5-1.10.4
NETCDF_C_VERSION 4.6.1
netcdf4-python-1.4.2
```

Thank you!

**Comment by jswhit** [comment]
Apparently, NETCDF4_CLASSIC files do work with parallel IO.  I will enable this in the upcoming v1.4.3 release (pull request #889) and update the docs accordingly.

**Comment by gihankarunarathne** [comment]
Got it. Thanks a lot @jswhit !
Waiting for the v1.4.3 ... 😃

**Comment by jswhit** [comment]
v1.4.3 is available on pypi now
