### ISSUE TITLE
 netCDF4/_netCDF4.pyx:1203:0: 'membuf.pyx' not found

### ISSUE THREAD

**Issue by snowman2** [Unidata/netcdf4-python#893]
https://github.com/Unidata/netcdf4-python/blob/b22fb81ed511f48bb6fb7597c4e1b03707a8a7db/netCDF4/_netCDF4.pyx#L1203

```
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from numpy import ma
    from libc.string cimport memcpy, memset
    from libc.stdlib cimport malloc, free
    import_array()
    include "constants.pyx"
    include "membuf.pyx"
    ^
    ------------------------------------------------------------
    
    netCDF4/_netCDF4.pyx:1203:0: 'membuf.pyx' not found
```

**Comment by snowman2** [comment]
netCDF-1.4.3.1

**Comment by snowman2** [comment]
Looks like `constants.pyx` is missing from the directory as well.

**Comment by jswhit** [comment]
Thanks @snowman2, looks like I will have to make a 1.4.3.2 release to fix the missing membuf.pyx file in the source tarball.  constants.pyx is created be setup.py, so that should not be in the release.

**Comment by snowman2** [comment]
Sounds good. Thanks @jswhit!

**Comment by jswhit** [comment]
1.4.3.2 is out with this fix.
