### ISSUE TITLE
opening multiple netcdf files

### ISSUE THREAD

**Issue by kawtherOuenniche** [Unidata/netcdf4-python#895]
I'm trying to read data from multiple netcdf files. `import glob
from netCDF4 import MFDataset
dirData = '/homes/k19ouenn/Bureau/MEGATL6_N50_CFSR1h_on_full_tides'
os.chdir(dirData)
genfileDataSurf = 'megatl6_surf_ZoneOsmosis'
filename = dirData+genfileDataSurf+'*.nc'
filename = glob.glob(filename)
f = MFDataset(filename)`  but it raises an error netCDF4/_netCDF4.pyx in netCDF4._netCDF4.MFDataset.__init__()

IndexError: list index out of range
Does anyone know how to deal with it . thanks

**Comment by jswhit** [comment]
what does `glob.glob(filename)` actually produce in your case?

**Comment by kawtherOuenniche** [comment]
It doesn't produce anything actually !

**Comment by jswhit** [comment]
Well, that's your problem then.  Check the globbing in a terminal to make sure you don't have a type, and then pass the string directly to MFDataset (e.g. `MFDataset('/homes/k19ouenn/Bureau/MEGATL6_N50_CFSR1h_on_full_tides/megatl6_surf_ZoneOsmosis*nc')`).
