### ISSUE TITLE
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xigrug** [Unidata/netcdf4-python#898]
from ._netCDF4 import *
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory

python                    3.6.7                h0371630_0 
h5netcdf                  0.5.1                      py_0    conda-forge
libnetcdf                 4.6.1              h628ed10_200    conda-forge
netcdf4                   1.4.1           py36ha292673_200    conda-forge

**Comment by ocefpaf** [comment]
This is not a problem with `netcdf4`. It is a problem with the conda package. I recommend you to open an issue at https://github.com/conda-forge/netcdf4-feedstock
