### ISSUE TITLE
Error opening Dataset

### ISSUE THREAD

**Issue by kawtherOuenniche** [Unidata/netcdf4-python#900]
Hi , I am trying to open a netcdf file on colab using 

>data =  Dataset ('/content/gdrive/My Drive/Colab Notebooks/on_full_tide/normalized_with_tide.nc')
but it raises this error
OSError                                   Traceback (most recent call last)
<ipython-input-18-c2074ea7b17c> in <module>()
----> 1 data = Dataset('/content/gdrive/My Drive/Colab Notebooks/on_full_tide/normalized_with_tide.nc')

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()

OSError: [Errno -101] NetCDF: HDF error: b'/content/gdrive/My Drive/Colab Notebooks/on_full_tide/normalized_with_tide.nc'

**Comment by akrherz** [comment]
Hi @kawtherOuenniche, I was just showing off this functionality to a colleague on Friday, so it at least sometimes works!  Are you certain that your `/content/gdrive` folder is working?  Can you read other non-netcdf files from it in the same script?  Does the `normalized_with_tide.nc` file open regularly on a local filesystem?

**Comment by kawtherOuenniche** [comment]
The file works fine on a local filesystem but on colab it raises this error sometimes ( I was able to open it normally the last time ) .

**Comment by jswhit** [comment]
Seems unlikely that this is a netcdf4-python issue if the file opens normally on a local filesystem.

**Comment by jswhit** [comment]
Closing now, feel free to reopen if the issue recurs.
