### ISSUE TITLE
HDF5 headers error on install

### ISSUE THREAD

**Issue by BSchilperoort** [Unidata/netcdf4-python#901]
When installing netcdf4-python 1.5.0 on a windows system, the install fails with the following error:
```
Collecting netCDF4
  Downloading https://files.pythonhosted.org/packages/b5/45/3dd855840a6374a3bacf1129e612d8608d4dc7087ac5c9db233bc0622ad2/netCDF4-1.5.0.tar.gz (765kB)
    Complete output from command python setup.py egg_info:
    reading from setup.cfg...
    
        HDF5_DIR environment variable not set, checking some standard locations ..
    checking C:\Users\appveyor ...
    checking /usr/local ...
    checking /sw ...
    checking /opt ...
    checking /opt/local ...
    checking /usr ...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-install-8icmmrhi\netCDF4\setup.py", line 386, in <module>
        _populate_hdf5_info(dirstosearch, inc_dirs, libs, lib_dirs)
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-install-8icmmrhi\netCDF4\setup.py", line 334, in _populate_hdf5_info
        raise ValueError('did not find HDF5 headers')
    ValueError: did not find HDF5 headers
    
    ----------------------------------------
```

The install does not fail when using netcdf4-python version 1.4.3, or when installing the newest version on a linux system.

**Comment by BSchilperoort** [comment]
Additional info;
- Packages being installed are: pytest pytest-travis-fold pytest-cov numpy xarray dask toolz statsmodels patsy pandas matplotlib pyyaml xmltodict scipy jupyter_client ipykernel netCDF4
- Install fails on both py36 and py37.

**Comment by jswhit** [comment]
Windows binary wheels were just uploaded, please try again.

**Comment by BSchilperoort** [comment]
version 1.5.0 now installs properly on py36 and py37!

**Comment by veenstrajelmer** [comment]
This issue occurs again, but it is solved by updating to python=3.8

**Comment by jmckenna** [comment]
Google has brought me here as I am facing this same error with Python 3.11.4, netcdf4 1.6.4, on Windows

**Comment by jmckenna** [comment]
Workaround: use the whl instead, such as:
```
python -m pip install https://github.com/cgohlke/geospatial-wheels/releases/download/v2023.7.16/netCDF4-1.6.4-cp311-cp311-win32.whl
```
hope that helps someone else someday....

**Comment by aaron-kaijser** [comment]
Getting the same error with netCDF4-1.6.4.tar.gz on Windows 11 and Python 3.12.

**Comment by e22tracey** [comment]
> Getting the same error with netCDF4-1.6.4.tar.gz on Windows 11 and Python 3.12.

Also getting the same issue.
