### ISSUE TITLE
Getting OSError: [Errno -101] NetCDF: HDF error When opening a netcdf file

### ISSUE THREAD

**Issue by ArnoiZ** [Unidata/netcdf4-python#903]
Hi, when I tried `Dataset('bathymetry.nc')` and `dataset = Dataset('bathymetry.nc', 'r+', format='NETCDF4')`,  I got the following error:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-75a3afc7da8b>", line 1, in <module>
    dataset = Dataset('bathymetry.nc')
  File "netCDF4/_netCDF4.pyx", line 2285, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1855, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'bathymetry.nc'
```

But it didn't throw error when I tried `dataset = Dataset('bathymetry.nc', 'w', format='NETCDF4')`. 

However, although I opened the file, I don't think it was opened properly as you can see in the below screenshot, the length of dimensions is zero. I couldn't manipulate the file as you showed in the API document.
<img width="502" alt="スクリーンショット 2019-04-01 9 31 52" src="https://user-images.githubusercontent.com/25852180/55297511-9df2b280-5461-11e9-8a6b-d0df29e56e7a.png">

I could send you the netCDF file if you would like to take a look for me. Thank you.

**Comment by jswhit** [comment]
When you did `dataset = Dataset('bathymetry.nc', 'w', format='NETCDF4')` you clobbered the existing file.  Please do post the original file here (you can upload a zipped file to the ticket if it's not too large).

**Comment by ArnoiZ** [comment]
I see, is there a way to know which format should I open it with?
[bathymetry.nc.zip](https://github.com/Unidata/netcdf4-python/files/3031930/bathymetry.nc.zip)

**Comment by jswhit** [comment]
That's not a valid netcdf file.  When unzipped, it's only 636 bytes.

**Comment by jswhit** [comment]
> I see, is there a way to know which format should I open it with?
> [bathymetry.nc.zip](https://github.com/Unidata/netcdf4-python/files/3031930/bathymetry.nc.zip)

The format will be auto-detected - you only need to set the format if you are writing, not reading.  The 'w' argument means open a new file, clobbering the file if it exists (the argument clobber=False can be set to prevent this).

**Comment by ArnoiZ** [comment]
Thank you, I downloaded the data again. And it can be read properly now.
