### ISSUE TITLE
Support for nested attributes?

### ISSUE THREAD

**Issue by naught101** [Unidata/netcdf4-python#905]
See https://github.com/pydata/xarray/issues/2868

It would be nice if there was a way to use nested attributes with netcdf from python.

**Comment by jswhit** [comment]
You can - in the netCDF data model they are called "compound type" attributes.  They map to numpy structured arrays, not python dicts.  For example

```python
from netCDF4 import Dataset, CompoundType
import numpy as np
nc = Dataset('test.nc','w')
dtype=np.dtype([('bar', 'i4')])
att_type = nc.createCompoundType(dtype, 'simple compound type')
att_val = np.empty(1,dtype)
att_val['bar']=2
nc.foo = att_val
print nc.foo['bar']
```

**Comment by jswhit** [comment]
Does this solution work for  you @naught101 ?

**Comment by naught101** [comment]
Sorry, I don't usually use netcdf4 directly, I use it via xarray. I haven't had a chance to test that yet.

@shoyer might also be able to help.

**Comment by jswhit** [comment]
Going to close this for now, feel free to re-open if need be.
