### ISSUE TITLE
NetCDF: HDF error with connection to other packages

### ISSUE THREAD

**Issue by jajcayn** [Unidata/netcdf4-python#910]
Hello,

I am in a weird situation when I cannot open netCDF dataset, but only sometimes - depending on other packages imported to python. On MacOS (all system packages - python, hdflib, netcdf4 - installed through `homebrew`) everything works as expected, however on linux machine not.

Basic info:
* `python3 --version`: `Python 3.6.7`
* `lsb_release -a`: `Description:	Ubuntu 18.04.2 LTS`
* `netcdf library version 4.6.3` (manual install)
* `dpkg -s libhdf5-dev`: `Version: 1.10.0-patch1+docs-4` (`apt-get`)

### What works:
```python
In [1]: from netCDF4 import Dataset

In [2]: Dataset('/home/jajcayn/spaceknow/storage/spaceknow-testing/sentinel_5p/plotting_tools/2019041
   ...: 0/US_CH4_monthly.nc')
Out[2]:
<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    dimensions(sizes): time(2), lat(81), lon(81)
    variables(dimensions): float64 CH4_rnd_err(time,lat,lon), float64 viewing_azimuth_angle(time,lat,lon), float64 solar_azimuth_angle(time,lat,lon), float64 solar_zenith_angle(time,lat,lon), float64 CH4(time,lat,lon), float64 surface_pressure(time,lat,lon), float64 viewing_zenith_angle(time,lat,lon), int64 time(time), float64 lat(lat), float64 lon(lon)
    groups:

In [3]:
```

### What does not work:
```python
In [1]: import geopandas

In [2]: from netCDF4 import Dataset

In [3]: Dataset('/home/jajcayn/spaceknow/storage/spaceknow-testing/sentinel_5p/plotting_tools/2019041
   ...: 0/US_CH4_monthly.nc')
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-a7dc4ba2cd7e> in <module>
----> 1 Dataset('/home/jajcayn/spaceknow/storage/spaceknow-testing/sentinel_5p/plotting_tools/20190410/US_CH4_monthly.nc')

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()

OSError: [Errno -101] NetCDF: HDF error: b'/home/jajcayn/spaceknow/storage/spaceknow-testing/sentinel_5p/plotting_tools/20190410/US_CH4_monthly.nc'

In [4]:
```

or

```python
In [1]: import rasterio

In [2]: from netCDF4 import Dataset

In [3]: Dataset('/home/jajcayn/spaceknow/storage/spaceknow-testing/sentinel_5p/plotting_tools/2019041
   ...: 0/US_CH4_monthly.nc')
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-a7dc4ba2cd7e> in <module>
----> 1 Dataset('/home/jajcayn/spaceknow/storage/spaceknow-testing/sentinel_5p/plotting_tools/20190410/US_CH4_monthly.nc')

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()

OSError: [Errno -101] NetCDF: HDF error: b'/home/jajcayn/spaceknow/storage/spaceknow-testing/sentinel_5p/plotting_tools/20190410/US_CH4_monthly.nc'

In [4]:
```

in general, a couple of packages somehow interfere with netCDF4 / HDF5, I guess there are more, but which are definitely creating a problem:
* `geopandas==0.4.1`
* `rasterio==1.0.22`
* `cartopy==0.17.0` (but downgrading to 0.16.0 solved the problem)

there might be others (I also suspected e.g. `h5py` or `shapely` but these do not generate this bug)...

however - different order of importing (firstly importing `netCDF4`, then e.g. `geopandas`) solves the issue, however, this is not an option: code base in the company where I work is just too large for refactoring of all imports, moreover, the dependency graph between various files and modules would make this impossible.

Any help is appreciated!! Thanks

**Comment by jajcayn** [comment]
update: I was able to replicate this behaviour on fresh ubuntu inside a docker environment, so
`docker run -it ubuntu` and inside I just installed all my dependencies (both system and python modules),
btw, `pip3 freeze`:
<details>
affine==2.2.2
annoy==1.15.1
apipkg==1.5
asn1crypto==0.24.0
atomicwrites==1.3.0
attrs==19.1.0
beautifulsoup4==4.7.1
branca==0.3.1
bson==0.5.8
cachetools==3.1.0
Cartopy==0.17.0
certifi==2019.3.9
cffi==1.12.2
cftime==1.0.3.4
chardet==3.0.4
Click==7.0
click-plugins==1.1.1
cligj==0.5.0
configobj==5.0.6
cryptography==2.6.1
cycler==0.10.0
Cython==0.29.6
dataclasses==0.6
decorator==4.4.0
deepdiff==4.0.5
docopt==0.6.2
docutils==0.14
earthengine-api==0.1.173
execnet==1.6.0
Fiona==1.8.6
Flask==0.12.4
flexmock==0.10.4
folium==0.8.3
future==0.17.1
geographiclib==1.49
geojson==1.3.5
geojsoncontour==0.3.0
geomet==0.2.0.post2
geopandas==0.4.1
google-api-core==1.9.0
google-api-python-client==1.7.8
google-auth==1.6.3
google-auth-httplib2==0.0.3
google-cloud-bigquery==1.8.1
google-cloud-core==0.29.1
google-cloud-datastore==1.7.3
google-cloud-logging==1.10.0
google-cloud-storage==1.14.0
google-resumable-media==0.3.2
googleapis-common-protos==1.5.9
gpflow==1.3.0
graphviz==0.10.1
h5py==2.9.0
html2text==2018.1.9
httplib2==0.12.1
idna==2.8
imageio==2.5.0
itsdangerous==1.1.0
Jinja2==2.10.1
jsonpickle==1.1
kiwisolver==1.0.1
lockfile==0.12.2
lxml==4.2.1
mandrill==1.0.57
MarkupSafe==1.1.1
matplotlib==3.0.3
mock==2.0.0
more-itertools==7.0.0
multipledispatch==0.6.0
munch==2.3.2
ndg-httpsclient==0.5.1
netCDF4==1.5.0.1
networkx==2.2
numpy==1.16.2
oauth2client==4.1.3
ordered-set==3.1
OWSLib==0.17.1
pandas==0.22.0
patsy==0.5.1
pbr==5.1.3
pika==1.0.0
Pillow==5.4.1
pluggy==0.9.0
protobuf==3.7.1
py==1.8.0
py3nvml==0.2.3
Py6S==1.7.2
pyasn1==0.4.5
pyasn1-modules==0.2.4
pycparser==2.19
pycrypto==2.6.1
pydotplus==2.0.2
pygobject==3.26.1
pyGPs==1.3.5
PyJWT==1.7.1
pykdtree==1.3.1
pymongo==3.7.2
pyOpenSSL==19.0.0
pyparsing==2.4.0
pyproj==2.1.3
pyresample==1.12.0
pyshp==2.1.0
Pysolar==0.6
pytest==4.4.0
pytest-forked==1.0.2
pytest-xdist==1.28.0
python-apt==1.6.3+ubuntu1
python-daemon==2.2.3
python-dateutil==2.8.0
python-Levenshtein==0.12.0
pytz==2019.1
PyWavelets==1.0.3
PyYAML==5.1
rasterio==1.0.22
reportlab==3.5.17
requests==2.21.0
retrying==1.3.3
rsa==4.0
scikit-image==0.15.0
scikit-learn==0.20.3
scipy==1.2.1
sentinelsat==0.12.2
Shapely==1.6.4.post2
six==1.12.0
snuggs==1.4.3
soupsieve==1.9
statsmodels==0.9.0
tqdm==4.31.1
typeguard==2.3.0
uritemplate==3.0.0
urllib3==1.24.1
validate-email==1.3
voluptuous==0.11.5
Werkzeug==0.15.2
xarray==0.12.1
xmltodict==0.12.0
</details>

**Comment by dopplershift** [comment]
That feels like `geopandas` and `rasterio` are pulling in GDAL, which is in turn linked to one version of HDF5 (or maybe netcdf-c), while netcdf4-python is pulling in netcdf-c, which is linked to a different HDF5. I think `ldd` is going to be your friend here.

**Comment by jajcayn** [comment]
@dopplershift thanks for the response! I'll play with it and let you know any findings

**Comment by jajcayn** [comment]
ok, I found this:
```python
root@2263d9168b85:/# python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.getpid()
4196
>>> import geopandas
>>> import netCDF4 as nc4
>>> from subprocess import call
>>> call("lsof -p 4196 | grep 'netcdf\|hdf'", shell=True)
python3 4196 root  mem    REG    8,1  4116192 2232213 /usr/local/lib/python3.6/dist-packages/netCDF4/.libs/libhdf5-257e6423.so.101.1.0
python3 4196 root  mem    REG    8,1  1761168 2232212 /usr/local/lib/python3.6/dist-packages/netCDF4/.libs/libnetcdf-e3d50ece.so.15.0.0
python3 4196 root  mem    REG    8,1   182032 2228289 /usr/local/lib/python3.6/dist-packages/fiona/.libs/libhdf5_hl-d68fbc5b.so.100.1.0
python3 4196 root  mem    REG    8,1  4116192 2228286 /usr/local/lib/python3.6/dist-packages/fiona/.libs/libhdf5-9d222ec8.so.101.1.0
python3 4196 root  mem    REG    8,1  1843520 2228287 /usr/local/lib/python3.6/dist-packages/fiona/.libs/libnetcdf-5ca8eca1.so.11.0.4
0
```

so `fiona` loads hdflib 101, same as netCDF4 but they load different `libnetcdf`: 11.0.4 and 15.0.0 respectively. Do you think this could be the culprit? If so, is there anything I can do? Force link `fiona` or `netCDF4` to use the same shared lib?

**Comment by jajcayn** [comment]
solved! When I install ‘netcdf4-python’ from source it works. Should I close? Or keep it for the future reference?

**Comment by dopplershift** [comment]
Closing because there’s no action to take for us. The closed issue will remain for people to find.
