### ISSUE TITLE
Identity scale (offset:0,scale:1) ignores the auto_scale

### ISSUE THREAD

**Issue by FxIII** [Unidata/netcdf4-python#913]
in the line below,
https://github.com/Unidata/netcdf4-python/blob/8c94ad5848e6db1502e9472ec08e4a90a907cbc6/netCDF4/_netCDF4.pyx#L4401
we shortcut the transformation, which makes sense, but this will leave the variable as short, which is against the auto_scale meaning.

**Comment by jswhit** [comment]
Good point - fixed in pull request #914
