### ISSUE TITLE
nudump does not support NETCDF4 data model

### ISSUE THREAD

**Issue by ZHANGGU** [Unidata/netcdf4-python#921]
a test netcdf4 created by Python netCDF4
ncdump can not dump it into text
![2019-05-03_11-24-16](https://user-images.githubusercontent.com/8365180/57129281-38fae700-6d96-11e9-8dee-b25d2470e8b5.png)

**Comment by jswhit** [comment]
How was the file created?

**Comment by ZHANGGU** [comment]
Have reinstalled the library and then it works. strange but problem solved.
