### ISSUE TITLE
variable attributes: float32 vs float64, int32 vs int64

### ISSUE THREAD

**Issue by pacioos** [Unidata/netcdf4-python#926]
When I define my variables as data_type of "f" or "f4", these should be 32-bit floating-point decimals. However, when defining a variable attribute whose value is a floating-point via setncattr, the result is a 64-bit floating-point ("double"). (The result of ncdump shows "1." instead of "1.f", indicating a double instead of a float.) Since there is no way for me to specify the data type of the attribute when calling setncattr, I presume this is happening under the hood within netcdf4-python. Shouldn't the data type match the data type of the variable as defined in data_type?

Similarly, when my variable is data_type of "i" or "i4", these should be 32-bit integers. However, when defining a variable attribute whose value is an integer via setncattr, the result is a 64-bit integer. (The result of ncdump shows "1L" for an integer of 1, indicating a 64-bit integer.) Again, I don't believe I have any control over this, do I? Or are these data type conversions bugs in netcdf4-python?

Thanks in advance for your help.

**Comment by jswhit** [comment]
If you explictly set the dtype, it should work.  For example,

```python
>>> from netCDF4 import Dataset
>>> import numpy as np
>>> nc = Dataset('test.nc','w')
>>> nc.foo = np.array(1.0,'f4')
>>> print(nc.foo.dtype)
>>> nc.setncattr('bar',np.array(2.0,'f4'))
>>> print(nc.bar.dtype)
>>> nc.close()

float32
float32

netcdf test {

// global attributes:
		:foo = 1.f ;
		:bar = 2.f ;
}
```

If you just use a python float, you will get a double.

**Comment by pacioos** [comment]
THANKS! That solved it. Unfortunately, this means I always have to
explicitly cast my data values and attributes prior to writing out numeric
values to f4 and i4 (to avoid getting the defaults of f8 and i8), but at
least there is a workaround. I appreciate your reply.
Cheers,
John Maurer
Data Systems Engineer
Pacific Islands Ocean Observing System (PacIOOS)
University of Hawaii at Manoa
