### ISSUE TITLE
OS Error NetCDF : Unknown file format

### ISSUE THREAD

**Issue by blefouler** [Unidata/netcdf4-python#927]
Hi guys, I am actually stuck since a few days on this issue. I was looking everywhere to fix it but I didn't find a way out for it. Actually, I'm trying to read a file with netCDF4 but for unkwn reason, my module seems incomplete and I don't know how to solve it. I'm on Anaconda.
Here it's the code that I wrote :

from netCDF4 import Dataset
fid = Dataset('mix.nc4','r')

and what I got:

OSError: [Errno -51] NetCDF: Unknown file format: b'mix.nc4'

Thanks for your help

**Comment by jswhit** [comment]
Can you post the file somewhere?  (if it's small enough you can zip and attach it to this ticket).

**Comment by blefouler** [comment]
https://www.zipshare.com/download/eyJhcmNoaXZlSWQiOiIyMmJjMTk0YS0zNDU5LTRjZmItOGVhYS1iMGY5ZjMwMDUyOWQiLCJlbWFpbCI6ImJlbm9pdC5sZWZvdWxlckBnbWFpbC5jb20ifQ==

https://drive.google.com/file/d/10CpsUARtd41ELNmcOiQkwhzC_T_kAUHJ/view?usp=sharing

I stay available if you need something else. 

Furthermore, 
to install netcdf4 I used
`conda install netcdf4`

**Comment by jswhit** [comment]
Neither ncdump or h5dump can read that file - it's not valid netcdf or hdf5.

**Comment by blefouler** [comment]
Sorry is there any differences between netcdf4 and netcdf?

**Comment by jswhit** [comment]
See https://www.unidata.ucar.edu/software/netcdf/docs/netcdf_introduction.html (the section on netcdf file formats).

**Comment by jswhit** [comment]
How was that file created?

**Comment by blefouler** [comment]
To be honest, I am not quite sure on what you have inside but I think it's
a kind of sum of different nc files

**Comment by jswhit** [comment]
I'd suggest contacting the data provider, somehow the file has become corrupted.  Closing now.

**Comment by Ex-Origin** [comment]
Maybe you haven't pulled the `lfs` files from the source, try `git lfs pull` to solve this problem.
