### ISSUE TITLE
surprising results writing data to a 2d variable with both dimensions unlimited

### ISSUE THREAD

**Issue by 5tefan** [Unidata/netcdf4-python#933]
Here's a short test case that produces unexpected results when writing to a multi-unlimited-dimension VLEN type variable. 

```python
import netCDF4 as nc
import numpy as np


with nc.Dataset("test.nc", "w") as f:
    f.createDimension("t", None)
    f.createDimension("s", None)
    f.createVariable("x", np.float, dimensions=("t",))
    f.createVariable("y", str, dimensions=("t", "s"), fill_value="THISISFILL")

    f.variables["x"][:] = np.arange(10, dtype=np.float)
    for i in range(10):
        for j in range(5):
            if i==0:
                f.variables["y"][i, j] = "hello_{}-{}".format(i, j)
            if i == 2 and j > 1 and j < 4:
                f.variables["y"][i, j] = "wowow_{}-{}".format(i, j)

```

A ncdump of the resulting file:

```
netcdf test {
dimensions:
        t = UNLIMITED ; // (10 currently)
        s = UNLIMITED ; // (5 currently)
variables:
        double x(t) ;
                x:_Storage = "chunked" ;
                x:_ChunkSizes = 512 ;
                x:_Endianness = "little" ;
        string y(t, s) ;
                string y:_FillValue = "THISISFILL" ;
                y:_Storage = "chunked" ;
                y:_ChunkSizes = 724, 724 ;

// global attributes:
                :_NCProperties = "version=1|netcdflibversion=4.4.1.1|hdf5libversion=1.10.2" ;
                :_SuperblockVersion = 0 ;
                :_IsNetcdf4 = 1 ;
                :_Format = "netCDF-4" ;
data:

 x = 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ;

 y =
  {"hello_0-0", "hello_0-1", "hello_0-2", "hello_0-3", "hello_0-4"},
  {_, _, _, _, _},
  {_, _, "wowow_2-2", "wowow_2-3", _},
  {_, _, "wowow_2-2", "wowow_2-3", _},
  {_, _, "wowow_2-2", "wowow_2-3", _},
  {_, _, "wowow_2-2", "wowow_2-3", _},
  {_, _, "wowow_2-2", "wowow_2-3", _},
  {_, _, "wowow_2-2", "wowow_2-3", _},
  {_, _, "wowow_2-2", "wowow_2-3", _},
  {_, _, "wowow_2-2", "wowow_2-3", _} ;
}

```

For the wowow elements, the code above is supposed to write each one individually, so it is unexpected that they are repeated along the t dimension since only t==2 should have been assigned.

I have been able to reproduce this with both NetCDF-Python versions 1.4.2 and 1.5.1.2.

**Comment by jswhit** [comment]
interesting...  It seems that the correct information is being pass to the C library (via `nc_put_vara`), so this may be a C lib bug.  In order to create an issue there I will need to create a C program that reproduces this, and that may take a while...

**Comment by jswhit** [comment]
Definitely a C library issue.  See Unidata/netcdf-c/#1413

**Comment by 5tefan** [comment]
Wow thanks! That was impressively fast to get the C example together! Looking forward to the resolution.

**Comment by dopplershift** [comment]
Just wanted to hop in and clarify that VLEN is an entirely different thing than what's being used here. Multiple unlimited dimensions don't need pre-declared sizes, but for a given e.g row, all columns have a the same size. VLEN's have a different numbers of elements per row, but they are created completely differently.

**Comment by jswhit** [comment]
@dopplershift - yes that's very true.  I believe the issue here has nothing to do with VLEN datatypes per se.

**Comment by 5tefan** [comment]
@dopplershift thanks for making that explicit, I noticed jswhit's C example demonstrates with ints.

**Comment by jswhit** [comment]
Should be fixed in C lib how.
