### ISSUE TITLE
how to silence the warnings?

### ISSUE THREAD

**Issue by sukye** [Unidata/netcdf4-python#935]
"UserWarning: endian-ness of dtype and endian kwarg do not match, using endian kwarg"

Is there any way to mute the warnings? Thanks.

**Comment by akrherz** [comment]
Since I believe that `UserWarning` is coming from python code and not from c module code, it should be as simple as this at the top of your python script
```python
import warnings
warnings.simplefilter("ignore", UserWarning)
```

**Comment by sukye** [comment]
@akrherz

Yes, thank you so much.
