### ISSUE TITLE
Reading entire variable as missing

### ISSUE THREAD

**Issue by hahnd** [Unidata/netcdf4-python#936]
Greetings,

I have attached a sample file that I am reading with the following code:

```
from netCDF4 import Dataset
# using version 1.5.1.2

# open the data file
file = '/tmp/sample.nc'
data = Dataset(file)
# data.set_auto_mask(False)

# print the data
for row in data['kx']:
    for val in row:
        print('%0.2f, ' % float(val), end='')
    break  # print only the first row
```

This code prints all 'nan' values.  However, if I use ncdump or the Java libraries, the values are read in as expected.  I found a work around that fixes the problem: if I call set_auto_mask(False), then I get expected values.

[sample.nc.gz](https://github.com/Unidata/netcdf4-python/files/3262965/sample.nc.gz)

**Comment by jswhit** [comment]
data is outside `valid_range` (1-1000)

**Comment by hahnd** [comment]
Is the valid range checked before the offset is applied?  If so, then that would explain it.  If the valid range is checked after the offset is applied, then the values are all within that range.
        short kx(nbatches, batchlen) ;
                kx:name = "Data source index" ;
                kx:add_offset = 32768 ;
                kx:valid_range = 1, 1000 ;

**Comment by hahnd** [comment]
Just, got your edit.  Thanks!

**Comment by jswhit** [comment]
From https://www.unidata.ucar.edu/software/netcdf/docs/attribute_conventions.html:

If the variable is packed using scale_factor and add_offset attributes (see below), the _FillValue, missing_value, valid_range, valid_min, or valid_max attributes should have the data type of the packed data.

**Comment by hahnd** [comment]
Thanks for the quick response!  I updated the valid_range attribute and got the expected data back.
