### ISSUE TITLE
IOError: [Errno -36] NetCDF: Invalid argument

### ISSUE THREAD

**Issue by 1fatuheeva** [Unidata/netcdf4-python#938]
Hello,
I'm running Python 2.7.15, netCDF4 1.5.1.2 on Windows 10.

I can go to JPL's opendap page here (year = 2018):
https://opendap.jpl.nasa.gov/opendap/allData/modis/L3/aqua/11um/v2014.0/4km/8day/2018/contents.html

click on the first .nc file (A20180012018008.L3m_8D_NSST_sst_4km.nc), copy the full path from the Data URL box, and successfully open a netCDF4 Dataset instance.
If I try the same thing with 2019 (any of the files) instead of 2018 I get the invalid argument error.
I can manually download the 2019 files and open them locally.
Any ideas?
Thanks,

Mike

**Comment by jswhit** [comment]
This one works for me

```nc = netCDF4.Dataset('https://opendap.jpl.nasa.gov:443/opendap/allData/modis/L3/aqua/11um/v2014.0/4km/8day/2019/A20190012019008.L3m_8D_NSST_sst_4km.nc')```

Can you point me to a specific file that triggers the error?

**Comment by 1fatuheeva** [comment]
Very strange. I get the error running your exact command.

**Comment by jswhit** [comment]
Might be related to https://github.com/Unidata/netcdf-c/issues/657.

Do you have netcdf-c version 4.5.0?

**Comment by 1fatuheeva** [comment]
I uninstalled netCDF4 with pip, installed NetCDF-C 4.7.0 from the Unidata website (from the pre-built Windows binary netCDF4.7.0-NC4-DAP-32.exe), and then reinstalled netCDF4 with whl file netCDF4-1.5.1.2-cp27-cp27m-win32.whl.

netCDF4.__netcdf4libversion__ shows 4.4.1.1. I must be doing something wrong with the install...

**Comment by 1fatuheeva** [comment]
As far as I can tell the Windows install of netCDF4 (using pip with official whl file from pypi, or pip install netcdf4) does not care if netcdf-c is installed. The install succeeds, and I still have the same issue with 2018 vs 2019 files. And netCDF4.__netcdf4libversion__ shows 4.4.1.1.
This suggests to me that the netcdf-c version is baked into the whl file. Or is there something I'm missing?

**Comment by jswhit** [comment]
@cgohlke - can you confirm you windows wheels include netcdf-c 4.4.1.1?

**Comment by cgohlke** [comment]
Netcdf-c 4.4.1.1 is the last version that compiles with Visual Studio 2018 required for Python 2.7 on Windows. The Python 3 wheels use netcdf-c-4.6.3.

**Comment by jswhit** [comment]
Thanks @cgohlke - @1fatuheeva, would it be possible for you to try the python 3 wheel?

**Comment by 1fatuheeva** [comment]
That did it. Time to move to 3. Thanks for the help guys!
