### ISSUE TITLE
Set _FillValue attribute with its default value

### ISSUE THREAD

**Issue by dopplershift** [Unidata/netcdf4-python#94]
_From [bstde...@gmail.com](https://code.google.com/u/107327889122501351667/) on July 22, 2011 12:08:31_

If the 'fill_value' keyword is not used when creating a variable, the default NetCDF _FillValue is used, but the _FillValue attribute is not explicitely written to the NetCDF file (and it can't be written to afterwards). I would like to have the ability to make the _FillValue attribute appear with its default value.

Is there any way I can get the default NetCDF _FillValue for a given data type?

e.g.:
ncdtype = 'i2'
x = # some function that returns the default NetCDF _FillValue of ncdtype
nc.createVariable(...,dtype=ncdtype,fill_value=x)

I assume that would output the _FillValue attribute to the NetCDF file, even if it seems redundant... Perhaps there is some other way to achieve this?

_Original issue: http://code.google.com/p/netcdf4-python/issues/detail?id=94_

**Comment by lukemorrill** [comment]
Just another update on the url for Dataset.create_variable. It is now at: [https://unidata.github.io/netcdf4-python/#Dataset.createVariable](https://unidata.github.io/netcdf4-python/#Dataset.createVariable).
