### ISSUE TITLE
How to delete Dimensions and Variables from Dataset?

### ISSUE THREAD

**Issue by ElusiveTau** [Unidata/netcdf4-python#940]
I'm still learning the API so I apologize in advance if this the answer is obvious to you. 

```
import netCDF4 as nc
import numpy as np
new_ncd = nc.Dataset("Testdataset.nc', 'w')
new_ncd.createDimension('UTC_time',  10) 
new_ncd.close()

ncd = nc.Dataset('Testdataset.nc', 'r+')
del ncd.dimensions['UTC_time']   # Attempt to delete dimension. This runs without error.
ncd.dimensions  # Shows an empty OrderedDict() 
ncd.close()  # Save modifications and close file

ncd = nc.Dataset('Testdataset.nc', 'r+')
ncd.dimensions  # 'UTC_time' is back again
ncd.close()

ncd = nc.Dataset('Testdataset.nc', 'r+')
del ncd.dimensions['UTC_time']  # Attempt to delete dimension. This runs without error. 
ncd.dimensions # Shows empty OrderedDict()
ncd.createDimension('UTC_time', 100)  # Attempt recreate the dimension, with length = 100
                                      # RuntimeError: NetCDF: String match to name in use
```

The `del` statement doesn't seem to delete the dimension variable. It successfully removes the key-value pair in the dimensions OrderedDict but the name is still "registered" with the netCDF Dataset ...

What's the call order to delete Dataset dimensions and variables?

**Comment by jswhit** [comment]
You can't delete Dimension or Variable object (the netcdf-c API does not allow this).  del just removes the reference to the object.  The only way to achieve this is to make a copy of the Dataset.  nco provides tools for removing dimensions and variables by making a new copy.
