### ISSUE TITLE
Update docs for py3?

### ISSUE THREAD

**Issue by ibell** [Unidata/netcdf4-python#946]
I landed on the documentation page (https://unidata.github.io/netcdf4-python/netCDF4/index.html) and I saw print statements (rather than functions) and it made me cry a little bit.  Also, python 2.x is end of life as of Jan 1, 2020.  Perhaps it is time to update the Python docs?  A print statement replacement with print functions would go a long way towards python 3.x support in the docs.  I can make a PR if you can point me to where the upstream files are.

**Comment by jswhit** [comment]
The docs are generated from the comments in the source code (netCDF4/_netCDF4.pyx).

**Comment by jswhit** [comment]
Merged pull request #950. Will regenerate html docs in a separate PR.
