### ISSUE TITLE
Python versions in setup.py vs. .travis.yml

### ISSUE THREAD

**Issue by mwtoews** [Unidata/netcdf4-python#948]
The configuration file setup.py implies that the master branch supports a wide range of Python versions, including several that are no longer supported (namely Python 2.6, 3.3 and 3.4). However, only Python 2.7, 3.6 and 3.7 are tested with Travis CI.

I would advise either dropping some of these Python versions from setup.py, as they are not tested. Or add these Python versions to the Travis CI test suite to ensure they still work as advertized.

**Comment by jswhit** [comment]
I agree we should remove 2.6,3.3 and 3.4 from the setup.py configuration and make them consistent with the tests (we should test 2.7,3.5,3.6,3.7 and  drop 2.7 when numpy does in Jan 2020).
