### ISSUE TITLE
setup.py does not recognise parallel built netcdf in some versions on netcdf

### ISSUE THREAD

**Issue by mamueller** [Unidata/netcdf4-python#964]
I am building netcdf4-python with nix. The current version of netcdf in the nix store is 4.6.1.
In this version the includefile
` "netcdf_meta.h"`
 does contain the pattern `'#define NC_HAS_PARALLEL' ` but not `'#define NC_HAS_PARALLEL4' `
which is the pattern the setup.py is looking for.
I propose to remove the 4 from the search pattern and will make a pull request.
(The shortest in the history of github ?;-))

**Comment by jswhit** [comment]
Good catch.  When support for PnetCDF was added in the python interface, we forgot to change this.

**Comment by jswhit** [comment]
But wait, I see that we are also checking for 

#define NC_HAS_PNETCDF

so if you have PnetCDF support but not HDF5/MPI support it should still recognize that.  

Do you not have

#define NC_HAS_PNETCDF 1

in your netcdf_meta.h file?

**Comment by jswhit** [comment]
OK, I see now.  It's because the NC_HAS_PARALLEL4 was missing in netcdf-c 4.6.1

https://fossies.org/diffs/netcdf-c/4.6.1_vs_4.6.2/include/netcdf_meta.h-diff.html.

We still need a way to distinguish between PnetCDF support and parallel HDF5 support (one supports NETCDF3 files and not NETCDF4, and the other NETCDF4 but not NETCDF3).  It doesn't seem like this is possible with version 4.6.1.

**Comment by jswhit** [comment]
Can you try pull request #966?  It's an alternative to your fix that has special case logic for detecting parallel HDF5 support for netcdf-c version 4.6.1.

**Comment by jswhit** [comment]
@mamueller - can you test PR #966 (branch `issue964`) when you get a chance?  I'd like to merge and make a new release ASAP.

**Comment by jswhit** [comment]
I'm going to go ahead and merge PR #966.  Feel free to reopen this issue if the problem persists.

**Comment by mamueller** [comment]
Sorry for my late reply. I was on a business trip to China.
Thanks for the steps you took.
Cheers
Markus

Am Di., 3. Sept. 2019 um 15:55 Uhr schrieb Jeff Whitaker <
notifications@github.com>:
