### ISSUE TITLE
Process hangs when opening a corrupted file

### ISSUE THREAD

**Issue by rsmith013** [Unidata/netcdf4-python#967]
Version: netCDF4==1.5.1.2
HDF5 Version : 1.10.4 
OS: RHEL 6.10
Python Version: 3.7.3
Installed with conda.

I have a file which exists but is corrupted in some way. When I try to load it using `Datasets()`
the process freezes. After some time I kill the process and it produces the following.

```
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140244065056512:
  #000: H5F.c line 509 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1400 in H5F__open(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #002: H5Fint.c line 1615 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #003: H5FD.c line 1640 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #004: H5FDsec2.c line 941 in H5FD_sec2_lock(): unable to lock file, errno = 4, error message = 'Interrupted system call'
    major: File accessibilty
    minor: Bad file ID accessed

```

I would be good if it produced an exception instead of failing quietly. I have found the same behaviour using `ncdump -h <filename>`

**Comment by jswhit** [comment]
This is happening in the HDF5 C library.  The python interface can't raise an exception until the C library returns an error code.

**Comment by rsmith013** [comment]
OK. Have raised it with the HDF5 team
