### ISSUE TITLE
Spyder 'crashes' when importing data with NetCDF

### ISSUE THREAD

**Issue by estherroosenbrand** [Unidata/netcdf4-python#974]
When importing data (through netCDF's Dataset) my script periodically 'crashes'. This entails the variable explorer beging cleared and the red square in the python console being there for eternity. I've run import script before, with a larger amount of data to be imported, and it's worked fine. It periodically did this crashing behaviour at that time too.
Now however, I can't get it to run at all. I've updated my conda and my netCDF. No errors show up in the console when clicking on the red square.
Suggestions are very much welcome!
Thanks!

**Comment by jswhit** [comment]
We need more to go on.  A self-contained script that triggers the crash would be ideal.
