### ISSUE TITLE
Windows Wheels missing for 1.5.3 on PyPi

### ISSUE THREAD

**Issue by joernweissenborn** [Unidata/netcdf4-python#978]
Hi,

am getting alot of user complaints since you upgraded to 1.5.3. 

It seems there is no Windows wheel available for this release yet on PyPy do you plan to ship one?

**Comment by s-weigand** [comment]
It's PyPi and not PyPy 😋 
That the wheels for Windows are missing can be seen [here](https://pypi.org/project/netCDF4/#files)

**Comment by jswhit** [comment]
Takes me a bit longer to get windows wheels.  They are up now.

**Comment by s-weigand** [comment]
Thanks ❤️
