### ISSUE TITLE
Number precision with least_significant_digit

### ISSUE THREAD

**Issue by rocheseb** [Unidata/netcdf4-python#979]
I was trying to write data with a given precision using least_significant_digit

Using netCDF4 1.5.0.1 with python 3.7.3

Consider the example below

```
import netCDF4
import numpy as np

data = [20.5953,20.5955]
with netCDF4.Dataset('test.nc','w') as f:
    f.createDimension('x',None)
    f.createVariable('y',np.float32,('x',),least_significant_digit=3)
    f['y'][:] =data

with netCDF4.Dataset('test.nc','r') as f:
   print(f['y'][:]) # prints [20.595703,20.595703]
```

From there https://unidata.github.io/netcdf4-python/netCDF4/index.html#section9 if I understand correctly it does:
`np.float32(np.around(2**bits*data)/2**bits) = [20.595703, 20.595703]`

where bits is 9 or 10

But the text in the link also says least_significant_digit=1 means that we keep a precision of 0.1
which mean we should be able to do np.round(f['y'][:],f['y'].least_significant_digit) to get our numbers to the desired precision. 

But in this case rounding to the 3rd decimal will yield 20.596 for both numbers when the first number should round to 20.595 instead.
 
Am I misunderstanding least_significant_digit or is this an issue?

**Comment by jswhit** [comment]
Closing now, feel free to reopen if you have more questions
