### ISSUE TITLE
Issue with including netCDF4 package in Glue

### ISSUE THREAD

**Issue by Kenny-Gill** [Unidata/netcdf4-python#985]
Facing below errors while including netCDF4 package in glue. Has anyone been able to successfully utilize this package? and share the correct .egg file to be linked in glue.

1. "cannot import name 'Dataset'
2. "No module named netCDF4._netCDF4"

**Comment by jswhit2** [comment]
You will probably get more results posting to the glue issue tracker (which I assume is here https://github.com/glue-viz/glue/issues/new).
