### ISSUE TITLE
root group is missing '.name'

### ISSUE THREAD

**Issue by kmuehlbauer** [Unidata/netcdf4-python#988]
* the version of the software with which you are encountering an issue
    `netCDF4.__version__ '1.5.3'`
    `netCDF4.getlibversion() '4.7.3 of Nov 26 2019 11:01:47 $'`

* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
linux, conda-forge, Python3.8
* a description of the issue with the steps needed to reproduce it
The root-group of opened file does not have a `.name` associated and breaks with `KeyError`. 

```python
import netCDF4
root = netCDF4.Dataset("test1.nc", "w", format="NETCDF4")
test1 = root.createGroup("test1")
test1.createGroup("test2")
root.close()
ncn = netCDF4.Dataset('test1.nc')
print(ncn['test1/test2'].name)
print(ncn.name)
ncn.close()
```
Output:
```
test2

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-40-589f4ab29b0d> in <module>
      6 ncn = netCDF4.Dataset('test.nc')
      7 print(ncn['test1/test2'].name)
----> 8 print(ncn.name)
      9 ncn.close()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__getattr__()

KeyError: 'name'

```

**Comment by jswhit** [comment]
resolved by PR #988 - thanks for the report.
