### ISSUE TITLE
Inconsistency in importing the netCDF4 python package a second time

### ISSUE THREAD

**Issue by GingrasO** [Unidata/netcdf4-python#992]
I'm using netCDF4 version 1.5.3 with python 2.7.14 on a Linux 3.10.0-1062.9.1.el7.x86_64 cluster.

I am working on a fortran code which calls a python interpreter to run a python script externally. Once this script is done, the fortran code continues. This happens multiple times in the program. The executable and the python script are communicating data using netCDF. The first line of my python script is

`from netCDF4 import Dataset`

The first time the python script is called in the program, everything works perfectly. However, the second and subsequent times, I get the following error:

```
Traceback (most recent call last):
  File "python_script.py", line 1, in <module>
    from netCDF4 import Dataset
  File "[path_to_python]/lib/python2.7/site-packages/netCDF4/__init__.py", line 1, in <module>
    from ._netCDF4 import *
  File "include/membuf.pyx", line 16, in init netCDF4._netCDF4
AttributeError: type object 'netCDF4._netCDF4._MemBuf' has no attribute '__reduce_cython__'
```

the script crashes and the program continues.

From what I could find online, other people having such an error was due to a bad installation or something like that. In my case however, it works the first time, so I don't see how it could be badly installed. It seems like there is something going on in the environment it-self but I'm clueless.

I tried to check if any file used for the communication was left opened, but they are all closed when the second python invocation happens. I also try to unimport the netCDF4 package by ending my python script with

`del Dataset`

but it doesn't work.

Is this a problem with netCDF4? Any idea of what could cause such an error would be very helpful. Thanks!

**Comment by jswhit** [comment]
what version of cython do you have?  This could be related to [this](https://github.com/pynbody/pynbody/issues/503), which was fixed in cython recently.

Are you importing any other C extension modules in your python script?

**Comment by GingrasO** [comment]
After playing a bit more with the interpreter functions, I realized netCDF4 was not at fault.

What I do is that I initialize the python interpreter. Then I run the script. Then I close the python interpreter. Then I reinitialize it. Then I run the script again, but it doesn't work anymore.

If I do not close the interpreter and reinitialize it between the two runnings of the script, there is no problem. It seems that closing and reinitializing the interpreter breaks up something.

I will close this issue as it is not really related to netCDF4, but if you have any idea please tell me!
