### ISSUE TITLE
num2date returns cftime.datetime instead of datetime.datetime object

### ISSUE THREAD

**Issue by kdebrab** [Unidata/netcdf4-python#994]
Since the release of cftime 1.1.0, `num2date` by default returns a `cftime.datetime` object instead of a `datetime.datetime` object.

```python
from netCDF4 import num2date
num2date(1e6, 'seconds since 1970-01-01')
```
returns:
```
Out[2]: cftime.DatetimeGregorian(1970-01-12 13:46:40)
```

This is a breaking change and in contradiction with the [API documentation](https://unidata.github.io/netcdf4-python/netCDF4/index.html#netCDF4.num2date):

> **only_use_cftime_datetimes**: if False (default), datetime.datetime objects are returned from num2date where possible; if True dates which subclass cftime.datetime are returned for all calendars.

Clearly, the default is not longer False. Indeed:
```python
num2date(1e6, 'seconds since 1970-01-01', only_use_cftime_datetimes=False)
```
returns:
```
Out[3]: real_datetime(1970, 1, 12, 13, 46, 40)
```
Either the documentation should be updated, or alternatively (preferably) the old default behaviour `only_use_cftime_datetimes=False` should be restored.

**Comment by jswhit2** [comment]
cftime is it's own [project](https://github.com/Unidata/cftime)) now.  The API documentation [there](https://unidata.github.io/cftime/api.html) is correct - but you are right, the netcdf4-python docs need to be updated to be consistent.

The change in the default behavior was discussed [here](https://github.com/Unidata/cftime/issues/136).

**Comment by jswhit** [comment]
PR #995
