### ISSUE TITLE
attribute variable long(double) added as int

### ISSUE THREAD

**Issue by Corentingu** [Unidata/netcdf4-python#996]
If I create a variable and I try to add valid_min/valid_max attributes ( long/int64 type), there is a different behavior depending on how to add it.

Exemple:

f = netCDF4.Dataset(output_file, 'w', format='NETCDF4_CLASSIC')
...
time = f.createVariable('TIME', 'f8', 'TIME', fill_value=netCDF4.default_fillvals['f8'])
...

f.variables["TIME"].valid_min = 9000000000
**Result OK =>  :valid_min = 9.0E9; // double**
f.variables["TIME"].setncattr("valid_min", 9000000000)
**Result KO => :valid_min = 410065408; // int**

Edit : 
f.variables["TIME"].setncattr("valid_min", 9000000000.)
**Result OK**

My environnement:
python                    3.8.1            h0371630_1
netcdf4                   1.5.3            py38hbf33ddf_0

**Comment by jswhit2** [comment]
If you want an attribute  to have a certain type, it is best to explicitly cast it to a numpy scalar array with that type before the assignment

```python
f.variables["TIME"].valid_min = np.array(9000000000, dtype=f.variables["TIME"].dtype)
```
If you assign a python scalar to an attribute, it will get cast to a numpy scalar, and the type of the attribute will be whatever type numpy assigns to it.  The exception is that the attributes
'valid_min','valid_max','valid_range','missing_value' are supposed to have the same type as the variable, so __setattr__ enforces that.
