### ISSUE TITLE
OPeNDAP url results in: RuntimeError: NetCDF: Access failure

### ISSUE THREAD

**Issue by naomi-henderson** [Unidata/netcdf4-python#998]
Hi, I have been struggling to read an opendap URL using netcdf-python version '1.5.1.2'.  I can see the file with many other opendap-enabled tools: `ncview`,  plot with `panoply` and `ncdump` and the `ncotools` work, but am having trouble reading into python with netCDF4. 

The same (I think) file, downloaded to my machine works fine:
`wget http://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/AS-RCEC/TaiESM1/historical/r1i1p1f1/SImon/siconc/gn/v20200218/siconc_SImon_TaiESM1_historical_r1i1p1f1_gn_185001-201412.nc`

But the following produces an error:

```
import netCDF4

OPENDAP_url = 'http://esgf-data1.llnl.gov/thredds/dodsC/css03_data/CMIP6/CMIP/AS-RCEC/TaiESM1/historical/r1i1p1f1/SImon/siconc/gn/v20200218/siconc_SImon_TaiESM1_historical_r1i1p1f1_gn_185001-201412.nc'
ncds = netCDF4.Dataset(OPENDAP_url)
assert 'siconc' in ncds.variables
ncds['siconc'][:]

```

Anyone have an idea of what is causing this?  

Here is the error:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-22-b4d011463347> in <module>
      5 i = nc_fid.variables['i'][:]
      6 j = nc_fid.variables['j'][:]
----> 7 siconc = nc_fid.variables['siconc'][:,:,:]

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Variable.__getitem__()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Variable._get()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()

RuntimeError: NetCDF: Access failure
```

**Comment by jswhit** [comment]
Looks like the opendap server doesn't like to send the whole variable at once.  Reading it in smaller chunks (`ncds['siconc'][0:100]` works)

**Comment by naomi-henderson** [comment]
@jswhit - thanks! I should have checked this, but the netcdf file itself is <130M.  My guess is that it is something to do with the compression. This global seaice concentration data is mostly zeros and nans - it is mostly only in the Arctic Ocean and near Antarctica that is anything else.  

I would really like to know what is happening, since this is just one example of a persistent problem I have with these highly compressible datasets. Since I am accessing thousands of datasets (using `xarray` to concatenate in time and convert to `zarr` format), I really don't want to read them little chunk by little chunk.

**Comment by jswhit** [comment]
You might create a netcdf-c issue, since this is definitely happening in the C library.

**Comment by DennisHeimbigner** [comment]
The proximate problem is probably that the server
has a limit on the max size that can be downloaded via dap.
